### PR TITLE
core(gather-runner): use final document when reporting non-HTML error

### LINKED ISSUE #11585: Incorrect main document used when retrieving page load errors
#### Provide the steps to reproduce
1. Run LH programmatically on page that redirects a similarly matching URL (e.g. same `startsWith(request.url)`), where the redirect response does not return `text/html` as its mime type.

_More Information_

I'm not sure how common this for non-authenticated redirects, but in our case we are running LH on authenticated pages using cookie-based login (similar to [this doc](https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md#option-3-pass-custom-request-headers-with-lighthouse-cli), but with Node API). 

The redirect response when hitting the requestedUrl (prior to auth) does not return HTML, and so the content-type response header is empty. It then redirects to the authentication server, and finally back to the originally requested document this time with the correct mime type `text/html`.
  

#### What is the current behavior?

LH reports error `NOT_HTML` even though document loaded in the final URL after redirecting is `text/html`. 

I don't see any documentation on this, but according @brendankenny in #11430, it should be the final matching URL (that is an html document) when loading the page.

The error occurred starting in version 6.2.0 of LH from #11042.

I have a fix locally by using the _last_ matching HTML document (as opposed to the first) in [`findMainDocument(records, finalURL)`](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js#L443).

A naive one-line fix that works on my site in test is:

```js
// should probably search backwards using loop
const mainResource = records.slice().reverse().find(request => finalURL.startsWith(request.url) &&
        URL.equalWithExcludedFragments(request.url, finalURL));
```

As for the logic when `finalUrl` is not supplied, I think the comment on line 452 still applies. 

#### What is the expected behavior?

LH doesn't fail when valid redirect eventually responds with HTML on a matching `finalUrl`.

#### Environment Information
* Affected Channels: Node
* Lighthouse version: >=6.2.0
* Chrome version: N/A
* Node.js version: 12.9.2
* Operating System: MacOS (and Docker Linux Container)

**Related issues**
* #11042
* #11430

### PR DESCRIPTION
**Pull request by bradfrosty**
**Summary**

Fixes a bug where non-HTML page load error would be reported for sites that redirect and resolve to a valid HTML document. The main document's mime type would be checked instead of the "final" document resolved from the redirect.

This change is needed because previously, false positive errors may be reported for valid pages that ultimately respond with HTML via redirects.

**Related Issues/PRs**

Fixes #11585
Introduced in #11042

### CODE REVIEW

File: lighthouse-core/gather/gather-runner.js [hunk 1]
```diff
@@ -259,9 +259,14 @@ class GatherRunner {
       mainRecord = NetworkAnalyzer.findMainDocument(networkRecords, passContext.url);
     } catch (_) {}
 
+    let finalRecord;
+    try {
+      finalRecord = NetworkAnalyzer.findFinalDocument(mainRecord);
+    } catch (_) {}
+
```
Comment (patrickhulce) [inline lighthouse-core/gather/gather-runner.js:266]: I don't think we need `try/catch` around this if we end up going with the `resolveRedirects` option that can handle `undefined` :)

```suggestion
    // MIME Type is only set on the final redirected document request. Use this for the HTML check instead of root.
    const finalRecord = NetworkAnalyzer.resolveRedirects(mainRecord);

```

File: lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js [hunk 2]
```diff
@@ -385,4 +388,26 @@ describe('DependencyGraph/Simulator/NetworkAnalyzer', () => {
       assert.equal(mainDocument.url, 'https://www.example.com');
     });
   });
+
+  describe('#findFinalDocument', () => {
+    it('should find the final document without redirects', async () => {
```
Comment (patrickhulce) [inline lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js:393]: one extra one for the undefined case?

**Review by patrickhulce — CHANGES_REQUESTED** [review]
thanks very much @bfrost2893! 🎉  this is great navigating of core Lighthouse code, and excellent tests too 👍

File: lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js [hunk 3]
```diff
@@ -452,6 +452,26 @@ class NetworkAnalyzer {
...
   }
+
+  /**
+   * Finds the final document in a redirect chain given a main document.
+   * See: {@link NetworkAnalyzer.findMainDocument}) for how to retrieve main document.
+   *
+   * @param {LH.Artifacts.NetworkRequest|undefined} mainDocument
+   * @returns {LH.Artifacts.NetworkRequest}
+   */
+  static findFinalDocument(mainDocument) {
```
[the remark this answers is not in the document]
Comment (bradfrosty) [reply lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js:463]: Definitely agree, given it takes a single NetworkRequest.

**Comment by bradfrosty** [comment]
@patrickhulce thanks for the review! Addressed the changes and added the additional test.

File: lighthouse-core/gather/gather-runner.js [hunk 4]
```diff
@@ -225,20 +225,20 @@ class GatherRunner {
 
   /**
    * Returns an error if we try to load a non-HTML page.
```
Comment (patrickhulce) [inline lighthouse-core/gather/gather-runner.js:227]: come to think of it... any reason for not just moving the redirect resolution into here? :)

on the other hand, we might end up needing the resolved request elsewhere too and the visibility might be nice to have to future readers of the distinction. if we keep it outside of this fn, let's add an extra a little comment that it expects redirects resolved.
```suggestion
   * Returns an error if we try to load a non-HTML page.
   * Expects a network request with all redirects resolved, otherwise the MIME type may be incorrect.
```

**Review by patrickhulce — APPROVED** [review]
LGTM! over to @Beytoven for the final seal of 👍

File: lighthouse-core/gather/gather-runner.js (hunk 4 above)
Comment (bradfrosty) [reply lighthouse-core/gather/gather-runner.js:227]: I think the reasoning makes sense to keep it separate, but whichever you or @Beytoven prefer! I'll add a comment for now.

Comment (Beytoven) [reply lighthouse-core/gather/gather-runner.js:227]: I like them being separate as well so i think we're good here. Thanks for adding the comment.

**Review by Beytoven — APPROVED** [review]
Everything LGTM as well! Thanks.

**Comment by patrickhulce** [comment]
The test failure is a result of a Chrome change, we can land this once https://github.com/GoogleChrome/lighthouse/pull/11625/files lands 👍

**Comment by Beytoven** [comment]
> The test failure is a result of a Chrome change, we can land this once https://github.com/GoogleChrome/lighthouse/pull/11625/files lands 👍

It has landed now.

**Comment by patrickhulce** [comment]
Awesome, @bradfrosty if you can rebase we should be able to get this landed 👍

**Comment by bradfrosty** [comment]
@patrickhulce done! Although when I committed the suggestion through Github, it used my other email on the account. I amended author and pushed but it's still saying CLA is not signed now.

**Comment by bradfrosty** [comment]
@patrickhulce @Beytoven any idea about how to fix the CLA check?

**Comment by connorjclark** [comment]
CLA is blocked on "patrick.hulce@gmail.com" for some reason .... We can just override. Yours went through. Thanks!

File: lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js [hunk 5]
```diff
@@ -452,6 +452,19 @@ class NetworkAnalyzer {
...
   }
+
+  /**
+   * Resolves redirect chain given a main document.
+   * See: {@link NetworkAnalyzer.findMainDocument}) for how to retrieve main document.
+   *
+   * @param {LH.Artifacts.NetworkRequest|undefined} request
+   * @returns {LH.Artifacts.NetworkRequest|undefined}
+   */
+  static resolveRedirects(request) {
```
Comment (connorjclark) [inline lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js:463]: nit: @patrickhulce would this method be better on NetworkRequest?

File: lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js [hunk 6]
```diff
@@ -452,6 +452,19 @@ class NetworkAnalyzer {
...
+    if (!request) return undefined;
```
Comment (connorjclark) [inline lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js:464]: Can we handled the undefined case where this is called instead?

Comment (bradfrosty) [reply lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js:464]: I'm good with either, but this came from [this suggestion](https://github.com/GoogleChrome/lighthouse/pull/11620#discussion_r516281777)

cc @patrickhulce

Comment (patrickhulce) [reply lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js:464]: I suggested that so it would be drop-in replacement with the rest :)

I would also have a slight preference to handle the undefined at the caller, but I don't think it matters much honestly.

File: lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js (hunk 5 above)
Comment (patrickhulce) [reply lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js:463]: Marginally yes, but we have network analysis somewhat scattered at the moment, so I don't think it makes a large difference.

File: lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js (hunk 6 above)
Comment (connorjclark) [reply lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js:464]: Alrighty, I leave it to you @bradfrosty, we're good with w/e!

Comment (bradfrosty) [reply lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js]: Moved the undefined case to the caller -- let me know if that looks alright! Instead of handling the possible exception (like with the call to `findMainDocument()`), I type checked the `mainDocument` .

I also updated the undefined case test in `network-analyzer-test.js` to expect an exception to throw.

**Comment by patrickhulce** [comment]
@googlebot I consent.

File: lighthouse-core/gather/gather-runner.js [hunk 7]
```diff
@@ -259,9 +261,15 @@ class GatherRunner {
       mainRecord = NetworkAnalyzer.findMainDocument(networkRecords, passContext.url);
     } catch (_) {}
 
+    // MIME Type is only set on the final redirected document request. Use this for the HTML check instead of root.
+    let finalRecord;
+    if (mainRecord instanceof NetworkRequest) {
```
Comment (connorjclark) [inline lighthouse-core/gather/gather-runner.js:266]: A simple truthy check is good enough, other than that this LGTM.

Comment (connorjclark) [inline lighthouse-core/gather/gather-runner.js:266]:
```suggestion
    if (mainRecord) {
```

File: lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js [hunk 8]
```diff
@@ -385,4 +388,30 @@ describe('DependencyGraph/Simulator/NetworkAnalyzer', () => {
...
+        computedCache: new Map(),
+      });
+
+      const mainDocument = NetworkAnalyzer.findMainDocument(records, 'http://www.vkontakte.ru/');
+      const finalDocument = NetworkAnalyzer.resolveRedirects(mainDocument);
+      assert.notEqual(mainDocument.url, finalDocument.url);
+      assert.equal(finalDocument.url, 'https://m.vk.com/');
+    });
+
+    it('should throw if not given a request', () => {
```
Comment (connorjclark) [inline lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js:413]: Since the parameter is typechecked to not allow undefined, we can consider this case covered trivially by the typesystem, so let's delete this test case.

Comment (bradfrosty) [reply lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js]: Done!

**Comment by patrickhulce** [comment]
heads up @bradfrosty there's a lint error to fix based on one of the github applied suggestions :) (unused variable)

looks great though, can merge after that!
