### PR TITLE
core(devtools-model): fix missing `Runtime.experiments` object

### LINKED ISSUE #3509: Perform 'yarn test' abnormal
platform:  OSX 10.10.5
node version: v8.3.0
branch: master

My order is executed

1. yarn 
2. yarn install-all
3. yarn build-all
4. yarn test 

but it is abnormal

```shell
 ~/Open_Source/lighthouse:  yarn test
yarn run v1.1.0
$ yarn lint --quiet && yarn unit && yarn closure && yarn test-cli-formatting
lighthouse-core tests


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․!․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․!,!!!!․․․
  ․!․․․․․․․․․․․․․․․․,․․․․․․․․․․․․․․․․․․․․․․․․․․․․,,․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
error Command failed with exit code 7.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by paulirish**
1. The changes in web-inspector fix #3509 and the current `yarn test` breakage on master due to changes in #3497
2. The DTM changes handle the silent failure coming from mocha. One alternative to this fix is removing consoleQuieter entirely, which I'm open to. It was introduced to handle cases like https://github.com/paulirish/pwmetrics/issues/3. @brendankenny thoughts?

### CODE REVIEW

File: lighthouse-core/lib/traces/devtools-timeline-model.js [hunk 1]
```diff
@@ -36,11 +36,14 @@ class TimelineModel {
     // populate with events
     this._tracingModel.reset();
 
-    ConsoleQuieter.mute({prefix: 'timelineModel'});
-    this._tracingModel.addEvents(events);
-    this._tracingModel.tracingComplete();
-    this._timelineModel.setEvents(this._tracingModel);
-    ConsoleQuieter.unmuteAndFlush();
+    try {
+      ConsoleQuieter.mute({prefix: 'timelineModel'});
```
Comment (patrickhulce) [inline lighthouse-core/lib/traces/devtools-timeline-model.js]: what does this do?

**Comment by patrickhulce** [comment]
we should really make it a P0 to fix or disable appveyor so we can trust checks and require green before merging again

**Comment by brendankenny** [comment]
> One alternative to this fix is removing consoleQuieter entirely, which I'm open to

having all of Lighthouse follow `--quiet` is really nice. I don't think we should go back to that old world (though at least that particular case is to `stderr` like `lighthouse-logger`)

**Comment by brendankenny** [comment]
> we should really make it a P0 to fix or disable appveyor so we can trust checks and require green before merging again

isn't appveyor fixed with #3498 now? It would be nice if the appveyor badge in the readme linked to the latest master build, though...

File: lighthouse-core/lib/traces/devtools-timeline-model.js (hunk 1 above)
Comment (brendankenny) [reply lighthouse-core/lib/traces/devtools-timeline-model.js]: > what does this do?

any console messages that are absorbed are later logged with that as the logger prefix/title

Comment (patrickhulce) [reply lighthouse-core/lib/traces/devtools-timeline-model.js]: oh I didn't mean this particular line, just why is this try/finally necessary now?

Comment (paulirish) [reply lighthouse-core/lib/traces/devtools-timeline-model.js]: Previous to this patch landing, when you run `mocha lighthouse-core/test/lib/traces/devtools-timeline-model-test.js` it just exits silently. That's because console-quieter was also muting the logs from mocha. They never got flushed (the `finally`) because of an exception.

**Comment by patrickhulce** [comment]
> isn't appveyor fixed with #3498 now? It would be nice if the appveyor badge in the readme linked to the latest master build and not just the latest build, though...

it is, but I'm talking about appveyor breakages in general. I'm betting Paul fell into my similar camp of "since all the builds are always red anyhow, this red build telling me I shouldn't merge is meaningless, so I'm just gonna merge now"

if red builds weren't pretty regularly crying wolf, then we'd be more likely to investigate and postpone a merge because of a red build

**Comment by brendankenny** [comment]
> if red builds weren't pretty regularly crying wolf, then we'd be more likely to investigate and postpone a merge because of a red build

ah, got it, yes definitely agree

File: lighthouse-core/lib/traces/devtools-timeline-model.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-core/lib/traces/devtools-timeline-model.js]: oh gotchaaaa, mocha really just calls `console.log`? I see

Comment (paulirish) [reply lighthouse-core/lib/traces/devtools-timeline-model.js]: yah it does. found that this morning. was kinda surprised they aren't doing `process.std*.write()`, but yeah. :)
