### PR TITLE
report: fix wording when screenEmulation disabled

### LINKED ISSUE #14560: Report shows "Emulated Moto G4" when testing on a mobile device
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

Can not share

### What happened?

I followed the section on [Testing on a mobile device](https://github.com/GoogleChrome/lighthouse/blob/main/docs/readme.md#testing-on-a-mobile-device) to run Lighthouse on a URL on a Moto Power G.

The exact command I ran was

```
lighthouse \
  --port=9222 \
  --screenEmulation.disabled \
  --throttling-method=devtools \
  --throttling.cpuSlowdownMultiplier=1 \
  --no-emulatedUserAgent \
  --view \
  --print-config \
  SOME_URL
```

I see Lighthouse load the page in Chrome on the phone. However, in the report it says "Emulated Moto G4 with Lighthouse 9.6.8":

Screen Shot 2022-11-23 at 1 54 53 PM

### What did you expect?

The LH page would say "Testing on a real device with Lighthouse 9.6.8", or even "Testing on physical Moto Power G device with Lighthouse 9.6.8"

### What have you tried?

_No response_

### How were you running Lighthouse?

CLI

### Lighthouse Version

9.6.8

### Chrome Version

107

### Node Version

16.13.2

### OS

Mac OS

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by paulirish**
fixes #14560

### CODE REVIEW

File: report/renderer/util.js [hunk 1]
```diff
@@ -512,10 +512,12 @@ class Util {
...
     }
 
-    const deviceEmulation = {
-      mobile: Util.i18n.strings.runtimeMobileEmulation,
-      desktop: Util.i18n.strings.runtimeDesktopEmulation,
-    }[settings.formFactor] || Util.i18n.strings.runtimeNoEmulation;
+    let deviceEmulation = Util.i18n.strings.runtimeMobileEmulation;
+    if (settings.screenEmulation.disabled) {
+      deviceEmulation = Util.i18n.strings.runtimeNoEmulation;
+    } else if (settings.formFactor === 'desktop') {
```
Comment (adamraine) [inline report/renderer/util.js:518]: I still think we should use `settings.screenEmulation.mobile` here because the strings refer to the emulated device and not scoring methodology.

That should only matter when the `formFactor` and `screenEmulation.mobile` disagree for some reason so this is probably fine.

Comment (paulirish) [reply report/renderer/util.js:518]: Good idea.

File: report/test/renderer/util-test.js [hunk 2]
```diff
@@ -33,12 +33,13 @@ describe('util helpers', () => {
...
-    const get = opts => Util.getEmulationDescriptions({
-      ...opts,
-      screenEmulation: {disabled: true},
-    }).deviceEmulation;
-    assert.equal(get({formFactor: 'mobile'}), 'Emulated Moto G4');
-    assert.equal(get({formFactor: 'desktop'}), 'Emulated Desktop');
+    const get = settings => Util.getEmulationDescriptions(settings).deviceEmulation;
+    /* eslint-disable max-len */
+    assert.equal(get({formFactor: 'mobile', screenEmulation: {disabled: false, mobile: true}}), 'Emulated Moto G4');
+    assert.equal(get({formFactor: 'mobile', screenEmulation: {disabled: true, mobile: true}}), 'No emulation');
```
Comment (brendankenny) [inline report/test/renderer/util-test.js:39]: this does bring it back to @connorjclark's point that there's no indication this was a mobile report now

Comment (adamraine) [reply report/test/renderer/util-test.js:39]: Adding a separate indicator for that would be fine, I just don't think it makes sense here.

Comment (connorjclark) [reply report/test/renderer/util-test.js:39]: https://github.com/GoogleChrome/lighthouse/issues/8178
