### PR TITLE
Service worker test improvements.

### LINKED ISSUE #163: offline reload detection is broken :(

### PR DESCRIPTION
**Pull request by samccone**
Fixes #163 :arrow_right: depends on #165

See each commit for details.

-----

:warning: Please **do not** squash when merging, as each of these commits are atomic in nature and squashing will mash together two unrelated things.  :warning:

### CODE REVIEW

File: gatherers/offline.js [hunk 1]
```diff
@@ -20,12 +20,11 @@ const Gather = require('./gather');
 
 // Request the current page by issuing a sync request to ''.
```
Comment (samthor) [inline gatherers/offline.js]: this is no longer a sync request!

File: gatherers/offline.js [hunk 2]
```diff
@@ -49,9 +48,41 @@ class Offline extends Gather {
...
+    return driver.sendCommand('Runtime.evaluate', {
+      expression: 'window._offlineRequestStatus'
+    }).then(r => {
+      if (r.result.type !== 'undefined' || retryCount > 9) {
+        return r;
+      }
+
+      // Wait for 1.5 seconds and retry
+      return new Promise((res, _) => {
+        setTimeout(_ => {
```
Comment (samthor) [inline gatherers/offline.js]: `window.setTimeout` for Closure compiler

File: gatherers/offline.js (hunk 1 above)
Comment (samccone) [inline gatherers/offline.js]: Oops will update the comment 😋

File: gatherers/offline.js (hunk 2 above)
Comment (samccone) [inline gatherers/offline.js]: Hmm given this runs in a node and brower context the use of window will be problematic

Comment (samthor) [inline gatherers/offline.js]: Oh good point. I actually don't know what in Node defines this unless it's actually a true global (but it's not in HTML).

Comment (samthor) [inline gatherers/offline.js]: You can ignore this comment then, but I'd argue for it in browser-invoked JS.

File: gatherers/service-worker.js [hunk 3]
```diff
@@ -20,11 +20,15 @@ const Gather = require('./gather');
...
+    this.resolved = false;
+
     this.artifactsResolved = new Promise((res, _) => {
       options.driver.on(
           'ServiceWorker.workerVersionUpdated', data => {
-            if (ServiceWorker.getActivatedServiceWorker(data.versions) !== undefined) {
+            if (ServiceWorker.getActivatedServiceWorker(data.versions) !== undefined &&
+                !this.resolved) {
               this.artifact = {serviceWorkers: data};
+              this.resolved = true;
```
Comment (paullewis) [inline gatherers/service-worker.js]: Why the check here? I get that it stops you resolving multiple times, but it seems unnecessary given you can't resolve a Promise multiple times.

If it's to stop the artifact being overwritten then that's the only statement that should be inside the if clause.

File: gatherers/service-worker.js [hunk 4]
```diff
@@ -20,11 +20,15 @@ const Gather = require('./gather');
 
 class ServiceWorker extends Gather {
   setup(options) {
+    this.resolved = false;
+
     this.artifactsResolved = new Promise((res, _) => {
       options.driver.on(
```
Comment (paullewis) [inline gatherers/service-worker.js]: Not sure how I missed this, but in general we've been explicitly dropping driver out to its own variable. I'm definitely being pedantic here.

Comment (samccone) [inline gatherers/service-worker.js]: K

File: gatherers/service-worker.js (hunk 3 above)
Comment (samccone) [inline gatherers/service-worker.js]: Since artifacts is a object, when we override a prop on it, it propagates to all references of that object. So since we are not calling off on the event, we were resolving the promise and then changing the underlying prop on artifacts after. Which caused us problems.

Comment (paullewis) [inline gatherers/service-worker.js]: What's it being overwritten by?

Comment (samccone) [inline gatherers/service-worker.js]: The issue is,

we resolve the promise like all the work is done however 

`'ServiceWorker.workerVersionUpdated', data => {`

keeps firing over and over again... changing the value of this.artifact which is problematic as we do not interact with the this.artifact value until potentially a while after the promise was resolved. Thus opening the door for mutation before getting the state of the value.

This guard clause is to prevent that mutation from happening.

Comment (samccone) [inline gatherers/service-worker.js]: https://github.com/GoogleChrome/lighthouse/blob/sjs/test-sketch/gather-scheduler.js#L67

File: gatherers/service-worker.js (hunk 4 above)
Comment (samccone) [inline gatherers/service-worker.js]: :white_check_mark: resolved

**Comment by paullewis** [comment]
:boom:

**Comment by samccone** [comment]
(reverted the single commit and applied the series of commits)
