### PR TITLE
report(html): replace Typed OM getComputedStyle() with CSSOM equivalent

### LINKED ISSUE #5966: Report: "e.computedStyleMap is not a function" error when viewing in Safari
Using lighthouseVersion 3.0.3, when uploading or using gist to send a JSON file to the Lighthouse Report Viewer I receive the following errors in the console log of the browser:

```
[Error] Error: Error rendering report: e.computedStyleMap is not a function. (In 'e.computedStyleMap()', 'e.computedStyleMap' is undefined)
	(anonymous function) (viewer.js:16:169301) Line 770

[Error] Error: e.computedStyleMap is not a function. (In 'e.computedStyleMap()', 'e.computedStyleMap' is undefined)
	(anonymous function) (viewer.js:16:169301) Line 770
```

I've verified that the JSON file is valid JSON syntax, so I'm not sure what's happening. 

I'm using lighthouse from the command line on Ubuntu.

### PR DESCRIPTION
**Pull request by midzer**
**Summary**

Replace Typed OM's `element.getComputedStyle()` with CSSOM `window.getComputedStyle()`

Typed OM is not widely supported yet. Our delivered JS should work properly in all major browsers

https://developers.google.com/web/updates/2018/03/cssom#computed
**Related Issues/PRs**

fixes #5966

Yeah, this replacement looks a bit hacky. But I've not found a more elegant way

### CODE REVIEW

File: lighthouse-core/report/html/renderer/report-ui-features.js [hunk 1]
```diff
@@ -130,17 +130,21 @@ class ReportUIFeatures {
 
   _setupHeaderAnimation() {
     const scoresWrapper = this._dom.find('.lh-scores-wrapper', this._document);
-    this.headerOverlap = /** @type {number} */
-      (Number(window.getComputedStyle(scoresWrapper).marginTop.replace('px', '')));
+    const computedMarginTop = scoresWrapper.style.marginTop ?
+      window.getComputedStyle(scoresWrapper).marginTop : '0px';
+    this.headerOverlap = computedMarginTop ?
+      /** @type {number} */ (Number(computedMarginTop.replace('px', ''))) : 0;
```
Comment (paulirish) [inline lighthouse-core/report/html/renderer/report-ui-features.js]: I know you're copying what was here but `parseFloat(computedMarginTop)` should do the same. (unless there's some tsc thing i'm not thinking of).
   could even do `parseFloat(computedMarginTop|| 0)` to drop your ternary?

File: lighthouse-core/report/html/renderer/report-ui-features.js [hunk 2]
```diff
@@ -130,17 +130,21 @@ class ReportUIFeatures {
...
     this.headerBackground = this._dom.find('.lh-header-bg', this._document);
     this.lighthouseIcon = this._dom.find('.lh-lighthouse', this._document);
     this.scoresWrapperBg = this._dom.find('.lh-scores-wrapper__background', this._document);
     this.productInfo = this._dom.find('.lh-product-info', this._document);
     this.toolbar = this._dom.find('.lh-toolbar', this._document);
     this.toolbarMetadata = this._dom.find('.lh-toolbar__metadata', this._document);
-    this.headerHeight = /** @type {number} */
-      (Number(window.getComputedStyle(this.headerBackground).height.replace('px', '')));
+    const computedHeight = this.headerBackground.style.height ?
+      window.getComputedStyle(this.headerBackground).height : '0px';
```
Comment (paulirish) [inline lighthouse-core/report/html/renderer/report-ui-features.js]: 2 above comments apply here too.

**Comment by midzer** [comment]
I appreciate your feedback @paulirish 
Now patch shouldn't look like a workaround any more

File: lighthouse-core/report/html/renderer/report-ui-features.js [hunk 3]
```diff
@@ -130,20 +130,17 @@ class ReportUIFeatures {
 
   _setupHeaderAnimation() {
     const scoresWrapper = this._dom.find('.lh-scores-wrapper', this._document);
-    this.headerOverlap = /** @type {number} */
-      // @ts-ignore - TODO: move off CSSOM to support other browsers
-      (scoresWrapper.computedStyleMap().get('margin-top').value);
-
+    const computedMarginTop = window.getComputedStyle(scoresWrapper).marginTop;
+    this.headerOverlap = /** @type {number} */ (parseFloat(computedMarginTop || '0'));
```
Comment (brendankenny) [inline lighthouse-core/report/html/renderer/report-ui-features.js]: parseFloat returns a number, so no longer need to cast

File: lighthouse-core/report/html/renderer/report-ui-features.js [hunk 4]
```diff
@@ -130,20 +130,17 @@ class ReportUIFeatures {
...
     this.lighthouseIcon = this._dom.find('.lh-lighthouse', this._document);
     this.scoresWrapperBg = this._dom.find('.lh-scores-wrapper__background', this._document);
     this.productInfo = this._dom.find('.lh-product-info', this._document);
     this.toolbar = this._dom.find('.lh-toolbar', this._document);
     this.toolbarMetadata = this._dom.find('.lh-toolbar__metadata', this._document);
-
-    // @ts-ignore - TODO: move off CSSOM to support other browsers
-    this.headerHeight = this.headerBackground.computedStyleMap().get('height').value;
+    const computedHeight = window.getComputedStyle(this.headerBackground).height;
+    this.headerHeight = /** @type {number} */ (parseFloat(computedHeight || '0'));
```
Comment (brendankenny) [inline lighthouse-core/report/html/renderer/report-ui-features.js]: Same
