### PR TITLE
core(without-javascript): remove audit

### LINKED ISSUE #11459: remove without-javascript audit
My home page does not require JavaScript (except to start the service worker) and looks fine with it disabled.  I added a `<noscript>` element and can see its text display, but the test doesn't care (probably because it doesn't run).

#### Provide the steps to reproduce
1. Run LH on localhost - I'll upload the latest version to prod in the next few days and update this report.
  

#### What is the current behavior?
Test doesn't even run.

#### What is the expected behavior?
Test runs and passes

#### Environment Information
* Affected Channels: Extension
* Lighthouse version: 100.0.0.0
* Chrome version: Google Chrome	85.0.4183.102 (Official Build) (64-bit)
    * Revision	ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
    * OS	Linux
    * JavaScript	V8 8.5.210.20
    * Flash	32.0.0.433 /home/gpeterso/.config/google-chrome/PepperFlash/32.0.0.433/libpepflashplayer.so
    * User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
    * Command Line	/usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end
* Node.js version: NONE
* Operating System: Ubuntu 18.04

**Related issues**
#11455 Failing this previous test may break some subsequent ones, IDK.

### PR DESCRIPTION
**Pull request by Beytoven**
Fixes #11459.

### CODE REVIEW

**Comment by adamraine** [comment]
In addition to the CI failures, I found some files which still reference this audit:
- `lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-config.js` Related to smoke failures?
- `lighthouse-treemap/app/debug.json` @connorjclark should we update in this PR?

Additionally, the `HTMLWithoutJavascript` gatherer is only used for this audit, should we remove this too?

**Comment by connorjclark** [comment]
> lighthouse-treemap/app/debug.json @connorjclark should we update in this PR?

No need.

**Comment by patrickhulce** [comment]
New idea for a replacement: we could take a screenshot of the page without javascript and run the speed index algorithm on it, if it's more than ~20% different it fails? If there's interest I can file an issue with more details :)

**Review by patrickhulce — COMMENTED** [review]
one other note on the changes necessary here, we'll probably want to simplify the flow and remove the `disableJavaScript` handling in driver as well :)

**Comment by Beytoven** [comment]
> New idea for a replacement: we could take a screenshot of the page without javascript and run the speed index algorithm on it, if it's more than ~20% different it fails? If there's interest I can file an issue with more details :)

Just to be clear, you're proposing this as an alternative to removing the 'without-js' audit completely, right?

**Comment by patrickhulce** [comment]
> Just to be clear, you're proposing this as an alternative to removing the 'without-js' audit completely, right?

A long-term alternative yes, but my proposal shouldn't block the landing of this PR. I commented here to keep discussion about why it's OK to remove this in one logical place :)

File: lighthouse-core/gather/driver.js [hunk 1]
```diff
@@ -648,7 +648,6 @@ class Driver {
     const waitForNavigated = options.waitForNavigated || false;
     const waitForLoad = options.waitForLoad || false;
     const passContext = /** @type {Partial<LH.Gatherer.PassContext>} */ (options.passContext || {});
-    const disableJS = passContext.disableJavaScript || false;
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js:651]: 🎉 🎉 

should also delete in [`PassContext`](https://github.com/GoogleChrome/lighthouse/blob/f71cfc0ab431afbc2a2a4225c0222ba0fcda33e5/types/gatherer.d.ts#L39)

🎉 🎉

Comment (brendankenny) [reply lighthouse-core/gather/driver.js:651]: will not miss you `disableJavaScript` :)

**Comment by brendankenny** [comment]
smoke test failure for now-possible js redirects is an interesting new case :)

**Comment by brendankenny** [comment]
> smoke test failure for now-possible js redirects is an interesting new case :)

we should add this to Monday's eng sync because this is a pretty significant change

**Comment by brendankenny** [comment]
> we should add this to Monday's eng sync because this is a pretty significant change

conclusion was that this is a completely reasonable interpretation of `redirects-http`, one that folks have actually asked for in the past. See e.g. #2383 and #3417.

File: lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js [hunk 2]
```diff
@@ -82,6 +77,9 @@ module.exports = [
           scoreDisplayMode: 'manual',
         },
       },
+      runWarnings: {
+        length: 1,
+      },
```
Comment (brendankenny) [inline lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js:82]: This might be a problem. Is it a flakiness issue? The runWarning is "The page loaded too slowly to finish within the time limit. Results may be incomplete."  in [the (current) ToT smoke test](https://github.com/GoogleChrome/lighthouse/pull/11711/checks?check_run_id=1513775529#step:8:221), but there's no warning in the stable smoke test and [so the assertion fails](https://github.com/GoogleChrome/lighthouse/pull/11711/checks?check_run_id=1513775477#step:8:222). Presumably that's not a stable/ToT difference though and the page is just slow?

We could tweak the smoke config timeout, but any ideas why this is happening now?

Comment (patrickhulce) [reply lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js]: Yeah this is a flakiness issue, it shouldn't be added to expectations.

I'm inclined to ignore this particular warning completely in smokes honestly. I'm not sure it adds any value being notified of it.

**Comment by adamraine** [comment]
@Beytoven is next action on reviewer?

**Comment by Beytoven** [comment]
> @Beytoven is next action on reviewer?

Yeah, just updated the tags.

File: third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt.orig [hunk 3]
```diff
@@ -0,0 +1,22 @@
+Tests that exporting works.
```
Comment (adamraine) [inline third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt.orig:1]: Is this a temp file? I think we can remove.

File: third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt.orig [hunk 4]
```diff
@@ -0,0 +1,737 @@
+Tests that audits panel works.
```
Comment (adamraine) [inline third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt.orig:1]: Temp file?

File: third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt [hunk 5]
```diff
@@ -72,7 +72,6 @@ uses-text-compression
 uses-webp-images
 
 View Trace Button Text: "View Original Trace"
-View Trace Button Title: "The performance metrics above are simulated and won't match the timings found in this trace. Disable simulated throttling in "Lighthouse Settings" if you want the timings to match."
-
-Showing view: timeline
+PROMISE FAILURE: TypeError: UI.Tooltip.getContent is not a function
```
Comment (adamraine) [inline third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt:75]: I think this webtest was fixed recently. Either way, we shouldn't commit the error into our expectations.

**Review by adamraine — COMMENTED** [review]
One last remnant I noticed:
https://github.com/GoogleChrome/lighthouse/blob/80b9db0e84cb89fdc4a04357e0d80a9a9f0174f8/lighthouse-core/test/results/artifacts/artifacts.json#L3342-L3344

**Review by adamraine — APPROVED** [review]
LGTM
