### PR TITLE
core(rel=noopener-audit): Only test http/https links

### LINKED ISSUE #3714: rel="noopener" audit should ignore href="mailto:x@y.com" links
screen shot 2017-11-01 at 2 34 04 pm

Following this suggestion for these `mailto:` links causes the links to break on Chrome for Android and iOS Safari. Unfortunately, we only found this issue in production :(

screenshot_20171101-151030

Reproduction:
```
<ul>
        <li>
          <a href="mailto:sales@marketamplified.com" target="_blank">
            <mat-icon>mail_outline</mat-icon>Sales
          </a>
        </li>
        <li>
          <a href="mailto:support@marketamplified.com" target="_blank" rel="noopener">
            <mat-icon>mail_outline</mat-icon>Support
          </a>
        </li>
</ul>
```
The support link fails as seen above on Chrome for Android. The sales link works fine and launches Gmail from Chrome for Android.

### PR DESCRIPTION
**Pull request by sanjsanj**
Closes #3714 

Only filter anchor links that start with an http protocol for the `rel=noopener` audit.

### CODE REVIEW

File: lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js [hunk 1]
```diff
@@ -46,10 +46,7 @@ class ExternalAnchorsUseRelNoopenerAudit extends Audit {
           return true;
         }
       })
-      .filter(anchor => {
-        // Ignore href's that are not real links
-        return !anchor.href || !anchor.href.toLowerCase().startsWith('javascript:');
-      })
+      .filter(anchor => anchor.href.toLowerCase().startsWith('http'))
```
Comment (patrickhulce) [inline lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js]: probably need a `anchor.href &&` here to be safe

**Comment by sanjsanj** [comment]
Fixing the tests now...

**Comment by sanjsanj** [comment]
@patrickhulce Thanks for the fast feedback!  Yup sure, leave it with me I'll get that done asap.

File: lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js (hunk 1 above)
Comment (sanjsanj) [reply lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js]: @patrickhulce I meant to ask about that, it was previously checking for `!anchor.href`, and the unit tests seem to suggest that's what it's wanting to do, so I've put that back in.

https://github.com/GoogleChrome/lighthouse/blob/f49ef0602537de1a87e692960d8962974c566e1e/lighthouse-core/test/audits/dobetterweb/external-anchors-use-rel-noopener-test.js#L43-L49

Comment (sanjsanj) [reply lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js]: Unless there is an error with this unit test and this audit should ignore anchors without external links, and I presume you need an href to be an external link.

Comment (patrickhulce) [reply lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js]: oh whoops, yeah that's right you can ignore my comment then :) 

when glancing I assumed it was there as a `null` guard for the next case, but I remember now it was intentional

**Comment by sanjsanj** [comment]
Ok I've added a handful more tests.  While I was at it I couldn't resist tidying them up a bit; have grouped passes and fails together to make it a bit more organised, have added comments where there weren't any, and separated a couple of the unit tests out since they were testing for more than they say they were.

**Comment by sanjsanj** [comment]
Sorry again, fixing the tests... :)

**Comment by sanjsanj** [comment]
Sorry, forgot to update after fixing the failing tests but the PR is ready for more feedback when you have time, TY!

**Comment by sanjsanj** [comment]
Sweeeet, cheers @patrickhulce !
