### PR TITLE
Fixes #1282

### LINKED ISSUE #1282: Extension Error: Failed to construct 'URL': Invalid URL
**Lighthouse Version**: 1.3.1
**Chrome Version**: 55.0.2883.95
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
 ```TypeError: Failed to construct 'URL': Invalid URL
    at artifacts.DateNowUse.usage.filter.err (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1047:39)
    at Array.filter (native)
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1046:48)
    at Promise.resolve.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11388:20)```

### PR DESCRIPTION
**Pull request by ebidel**
R: @brendankenny

You can test against https://geda.nkenspen.de/ to trigger the `debugString` path. DBW tester won't surface it partly because of https://github.com/GoogleChrome/lighthouse/issues/1286.

### CODE REVIEW

File: lighthouse-core/audits/dobetterweb/no-datenow.js [hunk 1]
```diff
@@ -61,17 +61,26 @@ class NoDateNowAudit extends Audit {
...
-    // TODO: better extendedInfo for violations with no URL.
-    // https://github.com/GoogleChrome/lighthouse/issues/1263
     const results = artifacts.DateNowUse.usage.filter(err => {
       if (err.isEval) {
         return !!err.url;
       }
-      return err.url ? new URL(err.url).host === pageHost : true;
+
+      // If the violation doesn't have a valid url, don't filter it out, but
+      // warn the user that we don't know what the callsite is.
```
Comment (ebidel) [inline lighthouse-core/audits/dobetterweb/no-datenow.js]: one could argue this is ripe for a helper refactor, but we only have 2 atm. Don't think that warrants it just yet.

**Comment by wardpeet** [comment]
I like the idea of this fix. The try catch covers all our errors but might it be better to add this check inside the error capture as well? So we can mimic it as an eval but say extension?

**Comment by ebidel** [comment]
@wardpeet do you mean why isn't this inside of driver.js? One reason I kept it in the audits is because we have some `captureFunctionCallSites` audits that don't filter on page host and the `debugString`s for every audit will be different. [I don't think](https://github.com/GoogleChrome/lighthouse/pull/1288#discussion_r93809752) there will be much code saved atm.

**Comment by Janpot** [comment]
Looking through https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L740
For eval'ed code it seems there is [`getEvalOrigin`](https://github.com/v8/v8/wiki/Stack-Trace-API#customizing-stack-traces). Any reason this isn't used instead?

```js
if (callFrame.isEval()) {
  callFrame = callFrame.getEvalOrigin();
}
```
Seems like that would solve the `eval` special case. I think if you fix the `getEvalOrigin`, you can get a valid url for these cases as well.

regarding https://github.com/GoogleChrome/lighthouse/blob/39cc6a7a47746baa700b5db6161a8d22627efa1b/lighthouse-core/gather/driver.js#L751 url will only be empty then in case of content scripts, which produce stacks like `<anonymous>:1:1`. I guess you want those filtered out anyway.

**Comment by wardpeet** [comment]
@ebidel sorry should have been a bit more clear.

Whenever we write more and more audits that rely on the captureJSCallUsage, it might be ok to also add a check for "extensions" like we do with eval.

we could add an extra parameter but for now just mimic eval.
```
__nativeError.prepareStackTrace = function(error, structStackTrace) {
      // First frame is the function we injected (the one that just threw).
      // Second, is the actual callsite of the funcRef we're after.
      const callFrame = structStackTrace[1];
      let url = callFrame.getFileName();
      const line = callFrame.getLineNumber();
      const col = callFrame.getColumnNumber();
      let isEval = callFrame.isEval();
      const stackTrace = structStackTrace.slice(1).map(callsite => callsite.toString());

      // If we don't have an URL, (e.g. eval'd code), use the last entry in the
      // stack trace to give some context: eval(<context>):<line>:<col>
      // See https://crbug.com/646849.
      if (!url) {
        url = stackTrace[0];
      }

      try {
         new URL(url);
      } catch(ex) {
         isEval  = true;
      }

      // TODO: add back when we want stack traces.
      // Stack traces were removed from the return object in
      // https://github.com/GoogleChrome/lighthouse/issues/957 so callsites
      // would be unique.
      return {url, args, line, col, isEval }; // return value is e.stack
    };
```

**Comment by wardpeet** [comment]
@Janpot indeed getEvalOrigin looks like a good fit.

#1331 is somewhat related, this happens when scripts are evalled.

**Comment by patrickhulce** [comment]
+1 to seeing if there's a way to identify scripts originating from extensions. Ideally we should ignore those usages entirely and treat them as if they were disabled if we can't actually disable them temporarily? (which seems like a bad idea for extensions to have permission to do anyway)

**Comment by ebidel** [comment]
PTAL. We're now catching and filtering out crx usage. I've verified this PR works against dbw_tester.html and the original page posted in comment 1 (https://geda.nkenspen.de/), with and without the redux crx enabled.

**Comment by Janpot** [comment]
@ebidel `getEvalOrigin` returns a new `CallSite` instance. I think your code should look like:

```js
const callFrame = structStackTrace[1];
while (callFrame.isEval()) {
  callFrame = callFrame.getEvalOrigin();
}
let url = callFrame.getFileName();
const line = callFrame.getLineNumber();
const col = callFrame.getColumnNumber();
const stackTrace = structStackTrace.slice(1).map(callsite => callsite.toString());
```

After this you can drop the whole `isEval` logic completely. The special case will be extension scripts which you can't detect using the stacktrace API. (You can parse the stringified stacktrace though like what's currently happening for eval)

File: lighthouse-core/audits/dobetterweb/no-console-time.js [hunk 2]
```diff
@@ -61,10 +61,25 @@ class NoConsoleTimeAudit extends Audit {
...
+      // If the violation doesn't have a valid url, don't filter it out, but
+      // warn the user that we don't know what the callsite is.
+      try {
+        return new URL(err.url).host === pageHost;
+      } catch (e) {
+        debugString = 'Lighthouse was unable to determine if some API uses ' +
+                      'were made by this page. It\'s possible a Chrome extension' +
+                      'content script or other eval\'d code is calling this API.';
+      }
+      return true;
```
Comment (patrickhulce) [inline lighthouse-core/audits/dobetterweb/no-console-time.js]: nit: move to inside catch block? feels a bit like `if () { return cond } else { } return true` atm

**Comment by ebidel** [comment]
@Janpot that may be, but the `getEvalOrigin()` stringifies as expected to the last callframe on the stack. That's the one want went.

I tried your snippet, but it misses some of the eval'd lines in dbw_tester.html

```
eval('Date.now()'); // FAIL
new Function('Date.now()')() // FAIL
```

The approach in this PR produces the correct results for all cases:

screen shot 2016-12-29 at 10 43 14 am

File: lighthouse-core/gather/driver.js [hunk 3]
```diff
@@ -738,24 +739,36 @@ function captureJSCallUsage(funcRef, set) {
...
       const col = callFrame.getColumnNumber();
       const isEval = callFrame.isEval();
+      let isExtension = false;
       const stackTrace = structStackTrace.slice(1).map(callsite => callsite.toString());
 
-      // If we don't have an URL, (e.g. eval'd code), use the last entry in the
-      // stack trace to give some context: eval(<context>):<line>:<col>
+      // If we don't have an URL, (e.g. eval'd code), use the 2nd entry in the
+      // stack trace. First is eval context: eval(<context>):<line>:<col>.
+      // Second is the callsite where eval was called.
```
Comment (patrickhulce) [inline lighthouse-core/gather/driver.js]: nice I like this improvement

File: lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html [hunk 4]
```diff
@@ -108,6 +108,7 @@
     return Date.now();
   }
   helloDate();
+  const d = Date.now(); // FAIL
   eval('Date.now()'); // FAIL
```
Comment (patrickhulce) [inline lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html]: given our fail/no fail smoke tests right now, what benefit does this add? (seems like we'd be unable to catch `eval` not working here too actually)

File: lighthouse-core/audits/dobetterweb/no-console-time.js (hunk 2 above)
Comment (ebidel) [inline lighthouse-core/audits/dobetterweb/no-console-time.js]: done

File: lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html (hunk 4 above)
Comment (ebidel) [inline lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html]: Not much,  just wanted to check that `Date.now()` outside of an inner function was also producing results. Until smokehouse audits number of violations, this won't do much other than a manual verify.

**Comment by Janpot** [comment]
@ebidel You are right, I tried and it turns out `getEvalOrigin` just returns a `string` and not `CallSite`. The documentation is bogus. Maybe another options is to use some regex to get the url out of `'eval at dateNowTest (http://localhost:10200/dobetterweb/dbw_tester.html:13:3'`?

**Comment by Janpot** [comment]
Filed as https://bugs.chromium.org/p/chromium/issues/detail?id=677529

File: lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html (hunk 4 above)
Comment (patrickhulce) [inline lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html]: alright just checking, sg

**Comment by ebidel** [comment]
@Janpot going to keep the existing behavior as is. We were returning the first entry of eval'd stack traces before this PR (as opposed to regex'ing out URL patterns). It's been my experience that DevTools doesn't always give us a well defined URL.

**Comment by Janpot** [comment]
sure, you could always fall back on the first entry if a regex parse doesn't return a valid url
