### PR TITLE
properly filter extension audits to run by name

### LINKED ISSUE #921: Unchecked audits in Extension options leads to error
I unchecked "Best Practices" 
image

but at the end of the run, it failed with this message 
image

Pretty sure this is coming from the new https://github.com/GoogleChrome/lighthouse/pull/914 so we'll need to adjust things to allow this usecase.

@wardpeet can you look at this?

### PR DESCRIPTION
**Pull request by brendankenny**
fixes #921 

There was confusion between an audit's name (`myaudit.meta.name`) and the path name used in the config file. The extension was filtering path names by audit names, which happened to work with the core audits until the DBW tests were added to core. The assertion added in #914 caught this for us.

We now do a proper `Map` lookup from audit path names to audit names, then filter out audits that shouldn't run by name. The other changes are exposing the audit loader on `Config` and  a few other places that touch this code, clarifying the difference between variables representing names vs paths.

### CODE REVIEW

File: lighthouse-extension/app/src/lighthouse-background.js [hunk 1]
```diff
@@ -32,16 +32,25 @@ const _flatten = arr => [].concat.apply([], arr);
...
- * @param {!Array<string>} requestedAudits Names of audits to run.
+ * @param {!Array<string>} requestedAuditNames Names of audits to run.
  * @return {!Promise}
  */
-window.runLighthouseForConnection = function(connection, url, options, requestedAudits) {
+window.runLighthouseForConnection = function(connection, url, options, requestedAuditNames) {
   // Always start with a freshly parsed default config.
   const runConfig = JSON.parse(JSON.stringify(defaultConfig));
 
   // Filter out audits not requested.
```
Comment (ebidel) [inline lighthouse-extension/app/src/lighthouse-background.js]: Can you beef up the comment:
"Create a Map lookup from audit path names to audit names, then filter out audits that shouldn't run by name."

Comment (brendankenny) [inline lighthouse-extension/app/src/lighthouse-background.js]: done

**Comment by brendankenny** [comment]
I'll wait for travis to wake up to merge
