### PR TITLE
core(byte-efficiency): use more optimistic GZIP ratios

### LINKED ISSUE #7180: Default GZIP compression ratio is pessimistic for CSS
#### Provide the steps to reproduce
1. Run LH with Google Pagespeed on https://mopinion.com/test-pagespeed/
Note: the page is not otherwise optimized for speed.

#### What is the current behavior?
Our 3rd party javascript tool fetches it's styles via gzipped json and then appends it in a style tag to the DOM. 
Pagespeed is reporting a size of 80kb and a potential savings of +- 70kb under 'Defer unused CSS' when the total configuration fetched by our tool is only around 20kb gzipped. 
This regarding the following entry:
schermafbeelding 2019-02-07 om 15 56 41

#### What is the expected behavior?
Calculated scores and savings should be based on actually fetched resources, size in dom does not perse reflect actual data fetched.

#### Environment Information
* Affected Channels: Pagespeed
* Lighthouse version:-
* Node.js version:-
* Operating System:-

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/7141

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
Our assumed compression ratio for GZIP was pretty far off for CSS. This updates our compression ratios to be more realistic.

**Related Issues/PRs**
closes #7180

### CODE REVIEW

File: lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js [hunk 1]
```diff
@@ -66,15 +66,26 @@ class UnusedBytes extends Audit {
...
    */
-  static estimateTransferSize(networkRecord, totalBytes, resourceType, compressionRatio = 0.5) {
+  static estimateTransferSize(networkRecord, totalBytes, resourceType) {
     if (!networkRecord) {
       // We don't know how many bytes this asset used on the network, but we can guess it was
       // roughly the size of the content gzipped.
-      // See https://discuss.httparchive.org/t/file-size-and-compression-savings/145 for multipliers
-      return Math.round(totalBytes * compressionRatio);
+      // See https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer for specific CSS/Script examples
+      // See https://discuss.httparchive.org/t/file-size-and-compression-savings/145 for fallback multipliers
```
Comment (brendankenny) [inline lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js]: the second link doesn't entirely seem to back this up, but the methodology seems a bit weird

Comment (patrickhulce) [reply lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js]: The second link is where the 50% originally came from, I agree the methodology is odd and not really what we're after. That's also why I trust an Ilya proclamation over hand wavvy stats :) haha
