### PR TITLE
core(icons): Add PNG check to icon validation

### LINKED ISSUE #4876: Lighthouse PWA audits pass even with a JPG icon
Chrome "Improved A2HS" requires a PNG icon in the Web Manifest file, but Lighthouse doesn't mention this in its PWA audits.

To reproduce:
Create a PWA with a JPG icon in its `manifest.json`, like this:

```
{
  "name": "Example",
  "short_name": "Example",
  "icons": [
    {
      "src": "icon.jpg",
      "sizes": "1024x1024",
      "type": "image/jpg"
    }
  ],
  "scope": "https://www.example.com/my-url/",
  "start_url": "https://www.example.com/my-url/",
  "display": "standalone",
  "background_color": "#626160",
  "theme_color": "#626160"
}
```

Expected: Lighthouse PWA audit should flag this manifest as ineligible for Web App Install Banner, because there's no PNG icon in this manifest.

Actual: All audits pass

### PR DESCRIPTION
**Pull request by exterkamps**
fixes #4876 

**Summary**
Adds the additional check of validating if an icon is a PNG when validating that an icon is the correct size.

**Notes** 
Changed the way that artifacts are computed in audit tests so that they can take in a manifest.json as a param to use multiple different manifests for testing.

### CODE REVIEW

File: lighthouse-core/lib/icons.js [hunk 1]
```diff
@@ -31,7 +31,10 @@ function sizeAtLeast(sizeRequirement, manifest) {
   /** @type {Array<string>} */
   const flattenedSizes = [];
   iconValues.forEach(icon => {
-    if (icon.value.sizes.value) {
+    // check that the icon has a size, src, and is a png
+    if (icon.value.sizes.value &&
+        icon.value.src.value &&
+        icon.value.src.value.endsWith('.png')) {
```
[the remark this answers is not in the document]
Comment (exterkamps) [reply lighthouse-core/lib/icons.js]: Yup!  Modified to look at the typehint if exists, to only analyze 'image/png' typed files.

File: lighthouse-core/lib/icons.js [hunk 2]
```diff
@@ -24,17 +24,26 @@ function doExist(manifest) {
...
-    }
-  });
+  iconValues
+    // filter out icons with a typehint that is not 'image/png'
+    .filter(icon => !icon.value.type.value ||
+      (icon.value.type.value &&
+      icon.value.type.value === 'image/png'))
+    // filter out icons that are not png
+    .filter(icon => icon.value.src.value &&
+      icon.value.src.value.endsWith('.png'))
```
Comment (brendankenny) [inline lighthouse-core/lib/icons.js]: some people add query strings in their manifest (e.g. `https://example.com/img.png?utm_source=manifest` or whatever for analytics), and the spec [doesn't disallow it](https://www.w3.org/TR/appmanifest/#src-member), so I think we want to do `new URL(icon.value.src.value).pathname.endsWith('.png')` here.

(note that `URL` needs to come from `const URL = require('./url-shim.js')`, which gets a different version of the constructor based on if it's running in node or in the browser)

Comment (exterkamps) [reply lighthouse-core/lib/icons.js]: Good point, fixed!
