### PR TITLE
report: expand on "learn more" links 

### LINKED ISSUE #12241: Lighthouse shouldn't use "Learn more" links in its report
#### Provide the steps to reproduce

When running the SEO report in Lighthouse, it will flag uses of "Learn more" links as problematic. Ironically, the Lighthouse report itself uses "Learn more" links:

#### What is the current behavior?

The following screenshot is taken from the [Link Text](https://web.dev/link-text/) audit article on web.dev:

159564551_130438489000377_2939511278204770703_n

#### What is the expected behavior?

We shouldn't be breaking our own recommendations 🙃

### PR DESCRIPTION
**Pull request by alexnj**
Fixes #12241.

I've taken a stab at expanding "Learn more" links in LH reports to be more descriptive and accessible. Most of the expansions fall into one of the two formats:

1. "Learn more about foo" (majority)
2. "Learn how to bar" (if the link target is a guide, or is about avoiding something, or if I thought the first one doesn't fit well).

Feel free to suggest better expansions and I'll make the edits.

### CODE REVIEW

**Review by adamraine — COMMENTED** [review]
Quick comment dump for Accessibility. These are really just nit suggestions for consistency and specificity. Feel free to ignore them if you think the current stuff works better.

File: lighthouse-core/audits/accessibility/link-name.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ const UIStrings = {
   description: 'Link text (and alternate text for images, when used as links) that is ' +
       'discernible, unique, and focusable improves the navigation experience for ' +
       'screen reader users. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/link-name).',
+      '[Learn how to make links accessible](https://dequeuniversity.com/rules/axe/4.4/link-name).',
```
[the remark this answers is not in the document]
Comment (alexnj) [reply lighthouse-core/audits/accessibility/link-name.js:25]: The target article is more than just alt text, and is about making links more accessible in general. So may be this one we should keep as is. Thoughts?

[the remark this answers is not in the document]
Comment (adamraine) [reply lighthouse-core/audits/accessibility/link-name.js:25]: Yeah sounds good

File: lighthouse-core/audits/accessibility/aria-tooltip-name.js [hunk 2]
```diff
@@ -19,7 +19,7 @@ const UIStrings = {
   /** Title of an accessibility audit that evaluates if tooltip HTML elements do not have accessible names. This title is descriptive of the failing state and is shown to users when there is a failure that needs to be addressed. */
   failureTitle: 'ARIA `tooltip` elements do not have accessible names.',
   /** Description of a Lighthouse audit that tells the user *why* they should have accessible names for HTML elements. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
-  description: 'When an element doesn\'t have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn more](https://dequeuniversity.com/rules/axe/4.4/aria-tooltip-name).',
+  description: 'When an element doesn\'t have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn how to name `tooltip` elements](https://dequeuniversity.com/rules/axe/4.4/aria-tooltip-name).',
```
[the remark this answers is not in the document]
Comment (adamraine) [reply lighthouse-core/audits/accessibility/aria-tooltip-name.js:22]: That makes sense. What about "Learn how to name..." vs "Learn how to label...", would it be better to pick one of "name" or "label"?

File: lighthouse-core/audits/accessibility/tabindex.js [hunk 3]
```diff
@@ -21,7 +21,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user *why* they should try to pass. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'A value greater than 0 implies an explicit navigation ordering. ' +
       'Although technically valid, this often creates frustrating experiences ' +
-      'for users who rely on assistive technologies. [Learn more](https://dequeuniversity.com/rules/axe/4.4/tabindex).',
+      'for users who rely on assistive technologies. [Learn more about `tabindex` attribute](https://dequeuniversity.com/rules/axe/4.4/tabindex).',
```
Comment (adamraine) [inline lighthouse-core/audits/accessibility/tabindex.js:24]:
```suggestion
      'for users who rely on assistive technologies. [Learn more about the `tabindex` attribute](https://dequeuniversity.com/rules/axe/4.4/tabindex).',
```

File: lighthouse-core/audits/accessibility/td-headers-attr.js [hunk 4]
```diff
@@ -25,7 +25,7 @@ const UIStrings = {
   description: 'Screen readers have features to make navigating tables easier. Ensuring ' +
       '`<td>` cells using the `[headers]` attribute only refer to other cells in the same ' +
       'table may improve the experience for screen reader users. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/td-headers-attr).',
+      '[Learn more about headers attribute](https://dequeuniversity.com/rules/axe/4.4/td-headers-attr).',
```
Comment (adamraine) [inline lighthouse-core/audits/accessibility/td-headers-attr.js:28]:
```suggestion
      '[Learn more about the headers attribute](https://dequeuniversity.com/rules/axe/4.4/td-headers-attr).',
```

File: lighthouse-core/audits/accessibility/meta-viewport.js [hunk 5]
```diff
@@ -23,7 +23,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user *why* they should try to pass. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Disabling zooming is problematic for users with low vision who rely on ' +
       'screen magnification to properly see the contents of a web page. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/meta-viewport).',
+      '[Learn more about viewport meta tag](https://dequeuniversity.com/rules/axe/4.4/meta-viewport).',
```
Comment (adamraine) [inline lighthouse-core/audits/accessibility/meta-viewport.js:26]:
```suggestion
      '[Learn more about the viewport meta tag](https://dequeuniversity.com/rules/axe/4.4/meta-viewport).',
```

File: lighthouse-core/audits/accessibility/meta-refresh.js [hunk 6]
```diff
@@ -22,7 +22,7 @@ const UIStrings = {
   description: 'Users do not expect a page to refresh automatically, and doing so will move ' +
       'focus back to the top of the page. This may create a frustrating or ' +
       'confusing experience. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/meta-refresh).',
+      '[Learn more about refresh meta tag](https://dequeuniversity.com/rules/axe/4.4/meta-refresh).',
```
Comment (adamraine) [inline lighthouse-core/audits/accessibility/meta-refresh.js:25]:
```suggestion
      '[Learn more about the refresh meta tag](https://dequeuniversity.com/rules/axe/4.4/meta-refresh).',
```

File: lighthouse-core/audits/byte-efficiency/efficient-animated-content.js [hunk 7]
```diff
@@ -18,7 +18,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user *why* they should use video instead of GIF format for delivering animated content. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Large GIFs are inefficient for delivering animated content. Consider using ' +
     'MPEG4/WebM videos for animations and PNG/WebP for static images instead of GIF to save ' +
-    'network bytes. [Learn more](https://web.dev/efficient-animated-content/)',
+    'network bytes. [Learn more about efficient animation formats](https://web.dev/efficient-animated-content/)',
```
Comment (adamraine) [inline lighthouse-core/audits/byte-efficiency/efficient-animated-content.js:21]:
```suggestion
    'network bytes. [Learn more about efficient video formats](https://web.dev/efficient-animated-content/)',
```

File: lighthouse-core/audits/csp-xss.js [hunk 8]
```diff
@@ -21,7 +21,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that evaluates the security of a page's CSP. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. "CSP" stands for "Content Security Policy". "XSS" stands for "Cross Site Scripting". "CSP" and "XSS" do not need to be translated. */
   description: 'A strong Content Security Policy (CSP) significantly ' +
     'reduces the risk of cross-site scripting (XSS) attacks. ' +
-    '[Learn more](https://web.dev/csp-xss/)',
+    '[Learn how to use CSP to prevent XSS](https://web.dev/csp-xss/)',
```
Comment (adamraine) [inline lighthouse-core/audits/csp-xss.js:24]:
```suggestion
    '[Learn how to use a CSP to prevent XSS](https://web.dev/csp-xss/)',
```

**Review by adamraine — COMMENTED** [review]
Comments for Byte Efficiency (mostly)

File: lighthouse-core/audits/accessibility/aria-tooltip-name.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (alexnj) [reply lighthouse-core/audits/accessibility/aria-tooltip-name.js:22]: Currently I've reduced variations down to mainly two, "Learn more about ..." and "Learn how to ...". Beyond that prefix, most just try to fit into existing text. Here the existing text has repeated "accessible name" and "generic name", so may be "name" fits better?

File: lighthouse-core/audits/dobetterweb/notification-on-start.js [hunk 9]
```diff
@@ -22,7 +22,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user why they should not ask for notification permission on load. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Users are mistrustful of or confused by sites that request to send ' +
       'notifications without context. Consider tying the request to user gestures ' +
-      'instead. [Learn more](https://web.dev/notification-on-start/).',
+      'instead. [Learn more about notification permission](https://web.dev/notification-on-start/).',
```
Comment (paulirish) [inline lighthouse-core/audits/dobetterweb/notification-on-start.js:25]:
```suggestion
      'instead. [Learn more about responsibility getting permission for notifications](https://web.dev/notification-on-start/).',
```

**Review by paulirish — COMMENTED** [review]
as Adam did a11y and BE audits. I continued in the github order and completed through the `dobetterweb` audits, ending with uses-passive-event-listeners.js`

File: lighthouse-core/audits/unsized-images.js [hunk 10]
```diff
@@ -20,7 +20,7 @@ const UIStrings = {
   /** Title of a Lighthouse audit that provides detail on whether all images have explicit width and height. This descriptive title is shown to users when one or more images does not have explicit width and height */
   failureTitle: 'Image elements do not have explicit `width` and `height`',
   /** Description of a Lighthouse audit that tells the user why they should include explicit width and height for all images. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
-  description: 'Set an explicit width and height on image elements to reduce layout shifts and improve CLS. [Learn more](https://web.dev/optimize-cls/#images-without-dimensions)',
+  description: 'Set an explicit width and height on image elements to reduce layout shifts and improve CLS. [Learn more about image dimensions](https://web.dev/optimize-cls/#images-without-dimensions)',
```
Comment (paulirish) [inline lighthouse-core/audits/unsized-images.js:23]:
```suggestion
  description: 'Set an explicit width and height on image elements to reduce layout shifts and improve CLS. [Learn more about setting image dimensions](https://web.dev/optimize-cls/#images-without-dimensions)',
```

File: lighthouse-core/audits/seo/meta-description.js [hunk 11]
```diff
@@ -16,7 +16,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user *why* they need to have meta descriptions on their page. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Meta descriptions may be included in search results to concisely summarize ' +
       'page content. ' +
-      '[Learn more](https://web.dev/meta-description/).',
+      '[Learn more about meta description](https://web.dev/meta-description/).',
```
Comment (paulirish) [inline lighthouse-core/audits/seo/meta-description.js:19]:
```suggestion
      '[Learn more about the meta description](https://web.dev/meta-description/).',
```

File: lighthouse-core/audits/seo/canonical.js [hunk 12]
```diff
@@ -17,7 +17,7 @@ const UIStrings = {
   failureTitle: 'Document does not have a valid `rel=canonical`',
   /** Description of a Lighthouse audit that tells the user *why* they need to have a valid rel=canonical link. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Canonical links suggest which URL to show in search results. ' +
-    '[Learn more](https://web.dev/canonical/).',
+    '[Learn more about Canonical links](https://web.dev/canonical/).',
```
Comment (paulirish) [inline lighthouse-core/audits/seo/canonical.js:20]:
```suggestion
    '[Learn more about canonical links](https://web.dev/canonical/).',
```

File: lighthouse-core/audits/non-composited-animations.js [hunk 13]
```diff
@@ -19,7 +19,7 @@ const UIStrings = {
   title: 'Avoid non-composited animations',
   /** Description of a diagnostic LH audit that shows the user animations that are not composited. Janky means frames may be skipped and the animation will look bad. Acceptable alternatives here might be 'poor', or 'slow'. */
   description: 'Animations which are not composited can be janky and increase CLS. ' +
-    '[Learn more](https://web.dev/non-composited-animations)',
+    '[Learn more about non-composited animations](https://web.dev/non-composited-animations)',
```
Comment (paulirish) [inline lighthouse-core/audits/non-composited-animations.js:22]:
```suggestion
    '[Learn about avoiding non-composited animations](https://web.dev/non-composited-animations)',
```

File: lighthouse-core/audits/network-server-latency.js [hunk 14]
```diff
@@ -16,7 +16,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user that server latency can effect their website's performance negatively. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Server latencies can impact web performance. ' +
     'If the server latency of an origin is high, it\'s an indication the server is overloaded ' +
-    'or has poor backend performance. [Learn more](https://hpbn.co/primer-on-web-performance/#analyzing-the-resource-waterfall).',
+    'or has poor backend performance. [Learn more about server latencies](https://hpbn.co/primer-on-web-performance/#analyzing-the-resource-waterfall).',
```
Comment (paulirish) [inline lighthouse-core/audits/network-server-latency.js:19]:
```suggestion
    'or has poor backend performance. [Learn more about server response time](https://hpbn.co/primer-on-web-performance/#analyzing-the-resource-waterfall).',
```

File: lighthouse-core/audits/network-rtt.js [hunk 15]
```diff
@@ -16,7 +16,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user that a high network round trip time (RTT) can effect their website's performance because the server is physically far away from them thus making the RTT high. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Network round trip times (RTT) have a large impact on performance. ' +
     'If the RTT to an origin is high, it\'s an indication that servers closer to the user could ' +
-    'improve performance. [Learn more](https://hpbn.co/primer-on-latency-and-bandwidth/).',
+    'improve performance. [Learn more about Network Round Trip Times](https://hpbn.co/primer-on-latency-and-bandwidth/).',
```
Comment (paulirish) [inline lighthouse-core/audits/network-rtt.js:19]:
```suggestion
    'improve performance. [Learn more about the Round Trip Time](https://hpbn.co/primer-on-latency-and-bandwidth/).',
```

File: lighthouse-core/audits/metrics/total-blocking-time.js [hunk 16]
```diff
@@ -12,7 +12,8 @@ const i18n = require('../../lib/i18n/i18n.js');
 const UIStrings = {
   /** Description of the Total Blocking Time (TBT) metric, which calculates the total duration of blocking time for a web page. Blocking times are time periods when the page would be blocked (prevented) from responding to user input (clicks, taps, and keypresses will feel slow to respond). This is displayed within a tooltip when the user hovers on the metric name to see more. No character length limits.*/
   description: 'Sum of all time periods between FCP and Time to Interactive, ' +
-      'when task length exceeded 50ms, expressed in milliseconds. [Learn more](https://web.dev/lighthouse-total-blocking-time/).',
+      'when task length exceeded 50ms, expressed in milliseconds. ' +
+      '[Learn more about Total Blocking Time metric](https://web.dev/lighthouse-total-blocking-time/).',
```
Comment (paulirish) [inline lighthouse-core/audits/metrics/total-blocking-time.js:16]:
```suggestion
      '[Learn more about the Total Blocking Time metric](https://web.dev/lighthouse-total-blocking-time/).',
```

File: lighthouse-core/audits/metrics/speed-index.js [hunk 17]
```diff
@@ -12,7 +12,7 @@ const ComputedSi = require('../../computed/metrics/speed-index.js');
 const UIStrings = {
   /** Description of the Speed Index metric, which summarizes how quickly the page looked visually complete. This is displayed within a tooltip when the user hovers on the metric name to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Speed Index shows how quickly the contents of a page are visibly populated. ' +
-      '[Learn more](https://web.dev/speed-index/).',
+      '[Learn more about Speed Index metric](https://web.dev/speed-index/).',
```
Comment (paulirish) [inline lighthouse-core/audits/metrics/speed-index.js:15]:
```suggestion
      '[Learn more about the Speed Index metric](https://web.dev/speed-index/).',
```

File: lighthouse-core/audits/metrics/max-potential-fid.js [hunk 18]
```diff
@@ -12,7 +12,8 @@ const i18n = require('../../lib/i18n/i18n.js');
 const UIStrings = {
   /** Description of the Maximum Potential First Input Delay metric that marks the maximum estimated time between the page receiving input (a user clicking, tapping, or typing) and the page responding. This description is displayed within a tooltip when the user hovers on the metric name to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'The maximum potential First Input Delay that your users could experience is the ' +
-      'duration of the longest task. [Learn more](https://web.dev/lighthouse-max-potential-fid/).',
+      'duration of the longest task. ' +
+      '[Learn more about Maximum Potential First Input Delay metric](https://web.dev/lighthouse-max-potential-fid/).',
```
Comment (paulirish) [inline lighthouse-core/audits/metrics/max-potential-fid.js:16]:
```suggestion
      '[Learn more about the Maximum Potential First Input Delay metric](https://web.dev/lighthouse-max-potential-fid/).',
```

File: lighthouse-core/audits/metrics/largest-contentful-paint.js [hunk 19]
```diff
@@ -12,7 +12,7 @@ const ComputedLcp = require('../../computed/metrics/largest-contentful-paint.js'
 const UIStrings = {
   /** Description of the Largest Contentful Paint (LCP) metric, which marks the time at which the largest text or image is painted by the browser. This is displayed within a tooltip when the user hovers on the metric name to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Largest Contentful Paint marks the time at which the largest text or image is ' +
-      `painted. [Learn more](https://web.dev/lighthouse-largest-contentful-paint/)`,
+      `painted. [Learn more about Largest Contentful Paint metric](https://web.dev/lighthouse-largest-contentful-paint/)`,
```
Comment (paulirish) [inline lighthouse-core/audits/metrics/largest-contentful-paint.js:15]:
```suggestion
      `painted. [Learn more about the Largest Contentful Paint metric](https://web.dev/lighthouse-largest-contentful-paint/)`,
```

File: lighthouse-core/audits/metrics/interactive.js [hunk 20]
```diff
@@ -11,8 +11,8 @@ const Interactive = require('../../computed/metrics/interactive.js');
 
 const UIStrings = {
   /** Description of the Time to Interactive (TTI) metric, which evaluates when a page has completed its primary network activity and main thread work. This is displayed within a tooltip when the user hovers on the metric name to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
-  description: 'Time to interactive is the amount of time it takes for the page to become fully ' +
-    'interactive. [Learn more](https://web.dev/interactive/).',
+  description: 'Time to Interactive is the amount of time it takes for the page to become fully ' +
+    'interactive. [Learn more about Time to Interactive metric](https://web.dev/interactive/).',
```
Comment (paulirish) [inline lighthouse-core/audits/metrics/interactive.js:15]:
```suggestion
    'interactive. [Learn more about the Time to Interactive metric](https://web.dev/interactive/).',
```

File: lighthouse-core/audits/metrics/first-meaningful-paint.js [hunk 21]
```diff
@@ -12,7 +12,7 @@ const ComputedFmp = require('../../computed/metrics/first-meaningful-paint.js');
 const UIStrings = {
   /** Description of the First Meaningful Paint (FMP) metric, which marks the time at which a majority of the content has been painted by the browser. This is displayed within a tooltip when the user hovers on the metric name to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'First Meaningful Paint measures when the primary content of a page is ' +
-      'visible. [Learn more](https://web.dev/first-meaningful-paint/).',
+      'visible. [Learn more about First Meaningful Paint metric](https://web.dev/first-meaningful-paint/).',
```
Comment (paulirish) [inline lighthouse-core/audits/metrics/first-meaningful-paint.js:15]:
```suggestion
      'visible. [Learn more about the First Meaningful Paint metric](https://web.dev/first-meaningful-paint/).',
```

File: lighthouse-core/audits/metrics/first-contentful-paint.js [hunk 22]
```diff
@@ -12,7 +12,7 @@ const ComputedFcp = require('../../computed/metrics/first-contentful-paint.js');
 const UIStrings = {
   /** Description of the First Contentful Paint (FCP) metric, which marks the time at which the first text or image is painted by the browser. This is displayed within a tooltip when the user hovers on the metric name to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'First Contentful Paint marks the time at which the first text or image is ' +
-      `painted. [Learn more](https://web.dev/first-contentful-paint/).`,
+      'painted. [Learn more about First Contentful Paint metric](https://web.dev/first-contentful-paint/).',
```
Comment (paulirish) [inline lighthouse-core/audits/metrics/first-contentful-paint.js:15]:
```suggestion
      'painted. [Learn more about the First Contentful Paint metric](https://web.dev/first-contentful-paint/).',
```

File: lighthouse-core/audits/metrics/first-contentful-paint-3g.js [hunk 23]
```diff
@@ -18,7 +18,8 @@ class FirstContentfulPaint3G extends Audit {
       id: 'first-contentful-paint-3g',
       title: 'First Contentful Paint (3G)',
       description: 'First Contentful Paint 3G marks the time at which the first text or image is ' +
-        `painted while on a 3G network. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint).`,
+        'painted while on a 3G network. ' +
+        '[Learn more about First Contentful Paint metric](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint).',
```
Comment (paulirish) [inline lighthouse-core/audits/metrics/first-contentful-paint-3g.js:22]:
```suggestion
        '[Learn more about the First Contentful Paint (3G) metric](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint).',
```

File: lighthouse-core/audits/metrics/experimental-interaction-to-next-paint.js [hunk 24]
```diff
@@ -12,7 +12,8 @@ const i18n = require('../../lib/i18n/i18n.js');
 const UIStrings = {
   /** Description of the Interaction to Next Paint metric. This description is displayed within a tooltip when the user hovers on the metric name to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Interaction to Next Paint measures page responsiveness, how long it ' +
-               'takes the page to visibly respond to user input. [Learn more](https://web.dev/inp/).',
+               'takes the page to visibly respond to user input. ' +
+               '[Learn more about Interaction to Next Paint metric](https://web.dev/inp/).',
```
Comment (paulirish) [inline lighthouse-core/audits/metrics/experimental-interaction-to-next-paint.js:16]:
```suggestion
               '[Learn more about the Interaction to Next Paint metric](https://web.dev/inp/).',
```

File: lighthouse-core/audits/metrics/cumulative-layout-shift.js [hunk 25]
```diff
@@ -12,7 +12,8 @@ const i18n = require('../../lib/i18n/i18n.js');
 const UIStrings = {
   /** Description of the Cumulative Layout Shift metric that indicates how much the page changes its layout while it loads. If big segments of the page shift their location during load, the Cumulative Layout Shift will be higher. This description is displayed within a tooltip when the user hovers on the metric name to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Cumulative Layout Shift measures the movement of visible ' +
-               'elements within the viewport. [Learn more](https://web.dev/cls/).',
+               'elements within the viewport. ' +
+               '[Learn more about Cumulative Layout Shift metric](https://web.dev/cls/).',
```
Comment (paulirish) [inline lighthouse-core/audits/metrics/cumulative-layout-shift.js:16]:
```suggestion
               '[Learn more about the Cumulative Layout Shift metric](https://web.dev/cls/).',
```

File: lighthouse-core/audits/maskable-icon.js [hunk 26]
```diff
@@ -17,7 +17,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user why they their manifest should have at least one maskable icon. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'A maskable icon ensures that the image fills the entire ' +
     'shape without being letterboxed when installing ' +
-    'the app on a device. [Learn more](https://web.dev/maskable-icon-audit/).',
+    'the app on a device. [Learn more about maskable icons](https://web.dev/maskable-icon-audit/).',
```
Comment (paulirish) [inline lighthouse-core/audits/maskable-icon.js:20]:
```suggestion
    'the app on a device. [Learn about maskable manifest icons](https://web.dev/maskable-icon-audit/).',
```

File: lighthouse-core/audits/manual/pwa-each-page-has-url.js [hunk 27]
```diff
@@ -13,7 +13,7 @@ const UIStrings = {
   title: 'Each page has a URL',
   /** Description of a Lighthouse audit that tells the user why they should use unique URLs for each web page. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Ensure individual pages are deep linkable via URL and that URLs are ' +
-      'unique for the purpose of shareability on social media. [Learn more](https://web.dev/pwa-each-page-has-url/).',
+      'unique for the purpose of shareability on social media. [Learn more about deep links](https://web.dev/pwa-each-page-has-url/).',
```
Comment (paulirish) [inline lighthouse-core/audits/manual/pwa-each-page-has-url.js:16]:
```suggestion
      'unique for the purpose of shareability on social media. [Learn more about providing deep links](https://web.dev/pwa-each-page-has-url/).',
```

File: lighthouse-core/audits/manual/pwa-cross-browser.js [hunk 28]
```diff
@@ -14,7 +14,7 @@ const UIStrings = {
   title: 'Site works cross-browser',
   /** Description of a Lighthouse audit that tells the user why they should make sites work across different browsers. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'To reach the most number of users, sites should work across ' +
-  'every major browser. [Learn more](https://web.dev/pwa-cross-browser/).',
+  'every major browser. [Learn how to make sites work across browsers](https://web.dev/pwa-cross-browser/).',
```
Comment (paulirish) [inline lighthouse-core/audits/manual/pwa-cross-browser.js:17]:
```suggestion
  'every major browser. [Learn about cross-browser compatibility](https://web.dev/pwa-cross-browser/).',
```

File: lighthouse-core/audits/image-size-responsive.js [hunk 29]
```diff
@@ -23,7 +23,8 @@ const UIStrings = {
   failureTitle: 'Serves images with low resolution',
   /** Description of a Lighthouse audit that tells the user why they should maintain an appropriate size for all images. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Image natural dimensions should be proportional to the display size and the ' +
-    'pixel ratio to maximize image clarity. [Learn more](https://web.dev/serve-responsive-images/).',
+    'pixel ratio to maximize image clarity. ' +
+    '[Learn more about responsive images](https://web.dev/serve-responsive-images/).',
```
Comment (paulirish) [inline lighthouse-core/audits/image-size-responsive.js:27]:
```suggestion
    '[Learn about providing responsive images](https://web.dev/serve-responsive-images/).',
```

**Review by paulirish — APPROVED** [review]
aiight i went through the rest. I didnt doublecheck what adam did.

some small fixes here and there.

lgtm % the suggestions.

File: lighthouse-core/audits/dobetterweb/notification-on-start.js (hunk 9 above)
Comment (alexnj) [reply lighthouse-core/audits/dobetterweb/notification-on-start.js:25]: Seems like a typo, did you mean `Learn more about responsibly getting permission for notifications`?

Comment (paulirish) [reply lighthouse-core/audits/dobetterweb/notification-on-start.js:25]: hah yes.

**Review by adamraine — APPROVED** [review]
LGTM

File: lighthouse-core/audits/accessibility/aria-required-parent.js [hunk 30]
```diff
@@ -23,7 +23,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user *why* they should try to pass. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Some ARIA child roles must be contained by specific parent roles to ' +
       'properly perform their intended accessibility functions. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/aria-required-parent).',
+      '[Learn more about ARIA roles and their required parent element](https://dequeuniversity.com/rules/axe/4.4/aria-required-parent).',
```
Comment (connorjclark) [inline lighthouse-core/audits/accessibility/aria-required-parent.js:26]:
```suggestion
      '[Learn more about ARIA roles and required parent element](https://dequeuniversity.com/rules/axe/4.4/aria-required-parent).',
```

(or add "their" to the string above in aria-required-children ?)

File: lighthouse-core/audits/accessibility/aria-treeitem-name.js [hunk 31]
```diff
@@ -20,7 +20,7 @@ const UIStrings = {
   /** Title of an accessibility audit that evaluates if treeitem HTML elements do not have accessible names. This title is descriptive of the failing state and is shown to users when there is a failure that needs to be addressed. */
   failureTitle: 'ARIA `treeitem` elements do not have accessible names.',
   /** Description of a Lighthouse audit that tells the user *why* they should have accessible names for HTML elements. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
-  description: 'When an element doesn\'t have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn more](https://dequeuniversity.com/rules/axe/4.4/aria-treeitem-name).',
+  description: 'When an element doesn\'t have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn more about naming `treeitem` elements](https://dequeuniversity.com/rules/axe/4.4/aria-treeitem-name).',
```
Comment (connorjclark) [inline lighthouse-core/audits/accessibility/aria-treeitem-name.js:23]: nit: this string and previous don't match in thier construction

File: lighthouse-core/audits/accessibility/bypass.js [hunk 32]
```diff
@@ -23,7 +23,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user *why* they should try to pass. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Adding ways to bypass repetitive content lets keyboard users navigate the ' +
       'page more efficiently. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/bypass).',
+      '[Learn more about bypass navigation mechanisms](https://dequeuniversity.com/rules/axe/4.4/bypass).',
```
Comment (connorjclark) [inline lighthouse-core/audits/accessibility/bypass.js:26]: bypassing?

Comment (connorjclark) [reply lighthouse-core/audits/accessibility/bypass.js:26]: or: Learn more about how to bypass ...

File: lighthouse-core/audits/accessibility/duplicate-id-active.js [hunk 33]
```diff
@@ -20,7 +20,7 @@ const UIStrings = {
   /** Title of an accesibility audit that checks if there are any duplicate id HTML attributes on active, focusable elements. This title is descriptive of the failing state and is shown to users when there is a failure that needs to be addressed. */
   failureTitle: '`[id]` attributes on active, focusable elements are not unique',
   /** Description of a Lighthouse audit that tells the user *why* they should try to pass. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
-  description: 'All focusable elements must have a unique `id` to ensure that they\'re visible to assistive technologies. [Learn more](https://dequeuniversity.com/rules/axe/4.4/duplicate-id-active).',
+  description: 'All focusable elements must have a unique `id` to ensure that they\'re visible to assistive technologies. [Learn more about `id` attribute](https://dequeuniversity.com/rules/axe/4.4/duplicate-id-active).',
```
Comment (connorjclark) [inline lighthouse-core/audits/accessibility/duplicate-id-active.js:23]: the link is about the duplicate id rule, not "about the id attribute"

Comment (connorjclark) [reply lighthouse-core/audits/accessibility/duplicate-id-active.js:23]: "learn more about how duplicate ids are problematic"

"learn more about how duplicate ids"

File: lighthouse-core/audits/accessibility/duplicate-id-aria.js [hunk 34]
```diff
@@ -20,7 +20,7 @@ const UIStrings = {
   /** Title of an accesibility audit that checks if there are any duplicate ARIA IDs on the page. This title is descriptive of the failing state and is shown to users when there is a failure that needs to be addressed. */
   failureTitle: 'ARIA IDs are not unique',
   /** Description of a Lighthouse audit that tells the user *why* they should try to pass. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
-  description: 'The value of an ARIA ID must be unique to prevent other instances from being overlooked by assistive technologies. [Learn more](https://dequeuniversity.com/rules/axe/4.4/duplicate-id-aria).',
+  description: 'The value of an ARIA ID must be unique to prevent other instances from being overlooked by assistive technologies. [Learn more about ARIA IDs](https://dequeuniversity.com/rules/axe/4.4/duplicate-id-aria).',
```
Comment (connorjclark) [inline lighthouse-core/audits/accessibility/duplicate-id-aria.js:23]: same as previous comment

File: lighthouse-core/audits/accessibility/html-has-lang.js [hunk 35]
```diff
@@ -24,7 +24,7 @@ const UIStrings = {
       'that the page is in the default language that the user chose when setting up the ' +
       'screen reader. If the page isn\'t actually in the default language, then the screen ' +
       'reader might not announce the page\'s text correctly. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/html-has-lang).',
+      '[Learn more about `lang` attribute](https://dequeuniversity.com/rules/axe/4.4/html-has-lang).',
```
Comment (connorjclark) [inline lighthouse-core/audits/accessibility/html-has-lang.js:27]: missing "the" (the `lang` attribute)

File: lighthouse-core/audits/accessibility/html-lang-valid.js [hunk 36]
```diff
@@ -23,7 +23,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user *why* they should try to pass. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Specifying a valid [BCP 47 language](https://www.w3.org/International/questions/qa-choosing-language-tags#question) ' +
       'helps screen readers announce text properly. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/html-lang-valid).',
+      '[Learn more about `lang` attributes](https://dequeuniversity.com/rules/axe/4.4/html-lang-valid).',
```
Comment (connorjclark) [inline lighthouse-core/audits/accessibility/html-lang-valid.js:26]: doesn't match in construction the previous string (seems like this text should be the same for both)

(by previous string in this comment and others, I mean previous file in order of GH review)

File: lighthouse-core/audits/accessibility/image-alt.js [hunk 37]
```diff
@@ -22,7 +22,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user *why* they should try to pass. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Informative elements should aim for short, descriptive alternate text. ' +
       'Decorative elements can be ignored with an empty alt attribute. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/image-alt).',
+      '[Learn more about `alt` attribute](https://dequeuniversity.com/rules/axe/4.4/image-alt).',
```
Comment (connorjclark) [inline lighthouse-core/audits/accessibility/image-alt.js:25]: missing the / or should be "attributes" for correct grammar

File: lighthouse-core/audits/accessibility/td-headers-attr.js [hunk 38]
```diff
@@ -26,7 +26,7 @@ const UIStrings = {
   description: 'Screen readers have features to make navigating tables easier. Ensuring ' +
       '`<td>` cells using the `[headers]` attribute only refer to other cells in the same ' +
       'table may improve the experience for screen reader users. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/td-headers-attr).',
+      '[Learn more about the headers attribute](https://dequeuniversity.com/rules/axe/4.4/td-headers-attr).',
```
Comment (connorjclark) [inline lighthouse-core/audits/accessibility/td-headers-attr.js:29]: > \`headers\`

Also, here and elsewhere: should we be doing
> \`[headers]\`

? Could be a followup. Also may need parser support. Also might be worth inventing something like 

> @ header (ignore space, cant avoid github parsing at symbol) 
> or attr@header

as shorthand.

File: lighthouse-core/audits/accessibility/valid-lang.js [hunk 39]
```diff
@@ -22,7 +22,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user *why* they should try to pass. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. */
   description: 'Specifying a valid [BCP 47 language](https://www.w3.org/International/questions/qa-choosing-language-tags#question) ' +
       'on elements helps ensure that text is pronounced correctly by a screen reader. ' +
-      '[Learn more](https://dequeuniversity.com/rules/axe/4.4/valid-lang).',
+      '[Learn more about `lang` attribute](https://dequeuniversity.com/rules/axe/4.4/valid-lang).',
```
Comment (connorjclark) [inline lighthouse-core/audits/accessibility/valid-lang.js:25]: plural/or missing the

would be good to pick one style of this. learn more about the X attribute – or more learn about X attributes. My weak preference is for the former

File: lighthouse-core/audits/apple-touch-icon.js [hunk 40]
```diff
@@ -20,7 +20,7 @@ const UIStrings = {
   /** Description of a Lighthouse audit that tells the user that having an apple-touch-icon allows websites to include an app icon to their installed progressive web apps, similar to a native app. This is displayed after a user expands the section to see more. No character length limits. 'Learn More' becomes link text to additional documentation. "apple-touch-icon" is an HTML attribute value and should not be translated. */
   description: 'For ideal appearance on iOS when users add a progressive web app to the home ' +
     'screen, define an `apple-touch-icon`. It must point to a non-transparent 192px (or 180px) ' +
-    'square PNG. [Learn More](https://web.dev/apple-touch-icon/).',
+    'square PNG. [Learn more about `apple-touch-icon`](https://web.dev/apple-touch-icon/).',
```
Comment (connorjclark) [inline lighthouse-core/audits/apple-touch-icon.js:23]: 👍

File: lighthouse-core/audits/autocomplete.js [hunk 41]
```diff
@@ -25,7 +25,7 @@ const UIStrings = {
   description: '`autocomplete` helps users submit forms quicker. To reduce user ' +
    'effort, consider enabling by setting the `autocomplete` ' +
    'attribute to a valid value.' +
-  ' [Learn more](https://developers.google.com/web/fundamentals/design-and-ux/input/forms#use_metadata_to_enable_auto-complete)',
+  ' [Learn more about `autocomplete` in forms](https://developers.google.com/web/fundamentals/design-and-ux/input/forms#use_metadata_to_enable_auto-complete)',
```
Comment (connorjclark) [inline lighthouse-core/audits/autocomplete.js:28]: 👍

File: lighthouse-core/audits/accessibility/bypass.js (hunk 32 above)
Comment (alexnj) [reply lighthouse-core/audits/accessibility/bypass.js:26]: The right terminology seems to be [`bypass blocks`](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks). So may be `Learn more about bypass blocks` or `Learn how to provide a bypass block`.

File: lighthouse-core/audits/accessibility/aria-treeitem-name.js (hunk 31 above)
Comment (alexnj) [reply lighthouse-core/audits/accessibility/aria-treeitem-name.js:23]: Start with `When a treeitem element doesn't have an...`?

File: lighthouse-core/audits/accessibility/duplicate-id-active.js (hunk 33 above)
Comment (alexnj) [reply lighthouse-core/audits/accessibility/duplicate-id-active.js:23]: Yeah, good catch! `Learn how to fix duplicate ``id``s`?

File: lighthouse-core/audits/accessibility/td-headers-attr.js (hunk 38 above)
Comment (alexnj) [reply lighthouse-core/audits/accessibility/td-headers-attr.js:29]: I did investigate the possibility of supporting nested squares in md links. We're currently using [regex](https://github.com/alexnj/lighthouse/blob/master/report/renderer/util.js#L258) to match links, and a clean way would be to nest like in PCRE but it's not supported in JavaScript regex. 

An okay work-around would be a single level of nesting (as [I tried here](https://github.com/alexnj/lighthouse/commit/70f07cd8927328ae7c3f42f9842cfbb8513827e9)). That said, this only complicates the screen reader experience, without real benefits; so I didn't pursue. Wdyt?

File: lighthouse-core/audits/accessibility/valid-lang.js (hunk 39 above)
Comment (alexnj) [reply lighthouse-core/audits/accessibility/valid-lang.js:25]: Agree, former is better. I seem to have made this pattern all over; will check for this before I proceed.

File: lighthouse-core/audits/accessibility/td-headers-attr.js (hunk 38 above)
Comment (connorjclark) [reply lighthouse-core/audits/accessibility/td-headers-attr.js:29]: I'm thinking it'll be cumbersome to author strings like that. would much rather do a post-processing / annotation shorthand thing

**Review by connorjclark — APPROVED** [review]
