### PR TITLE
misc(build): ensure distDir is present before emptying it

### LINKED ISSUE #12800: `yarn build:all` throws exception upon building from source
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

N/A

### What happened?

(Proposing a patch ) I was trying to build it from source code according to the documentation [here](https://github.com/GoogleChrome/lighthouse/#setup). But on running the fourth step (`yarn build:all`) it threw an exception since Lighthouse was trying to build the `/dist` and hence deleting the existing ones first.

### What did you expect?

I expect a successful execution of the above step which will build all the necessary pages and viewers.

### What have you tried?

I tried commenting few lines of code that were executing `fs.rmdirsync()` during this step of `yarn build` and it worked.
My question is, should I open a PR for this issue since it is problematic for everyone on their first build?

### How were you running Lighthouse?

CLI

### Lighthouse Version

8.1.0

### Chrome Version

90.0.4430.212

### Node Version

v16.5.0

### Relevant log output

```shell
node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/home/azureuser/lighthouse/dist/dt-report-resources'
    at Object.statSync (node:fs:1526:3)
    at __node_internal_ (node:internal/fs/utils:767:8)
    at Object.rmdirSync (node:fs:1146:15)
    at Object.<anonymous> (/home/azureuser/lighthouse/build/build-dt-report-resources.js:29:4)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/azureuser/lighthouse/dist/dt-report-resources'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: npm run build-all:task
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.<anonymous> (/home/azureuser/lighthouse/node_modules/npm-run-posix-or-windows/bin/cli.js:18:19)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 21051,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by paulirish**
fixes #12800 ( i could repro )

### CODE REVIEW

**Review by adamraine — APPROVED** [review]

File: build/build-dt-report-resources.js [hunk 1]
```diff
@@ -26,8 +26,9 @@ function writeFile(name, content) {
   fs.writeFileSync(`${distDir}/${name}`, content);
 }
 
+fs.mkdirSync(distDir, {recursive: true}); // Ensure dist is present, else rmdir will throw
 fs.rmdirSync(distDir, {recursive: true});
-fs.mkdirSync(distDir);
```
Comment (connorjclark) [inline build/build-dt-report-resources.js:30]: Instead we can use fs.rmSync with force: true and recursive: true.

Comment (brendankenny) [reply build/build-dt-report-resources.js:30]: `rm`/`rmSync` aren't supported until Node 14

Comment (paulirish) [reply build/build-dt-report-resources.js:30]: `rmSync` is new in node 14. (not in 12). :/

`fsPromises.rm` has force, but will require a bigger diff in this file.
