### PR TITLE
core(vulnerable-libs): add fix for recovering from bad versions

### LINKED ISSUE #3624: jQuery slim build reports "invalid version"
I'm using the jQuery slim build on a website, lighthouse is reporting "invalid version", my guess is it parses some kind of semver like versions while the jQuery slim version looks like this:
```
3.2.1 -ajax,-ajax/jsonp,-ajax/load,-ajax/parseXML,-ajax/script,-ajax/var/location,-ajax/var/nonce,-ajax/var/rquery,-ajax/xhr,-manipulation/_evalUrl,-event/ajax,-effects,-effects/Tween,-effects/animatedSelector
```

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #3624

### CODE REVIEW

File: lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js [hunk 1]
```diff
@@ -11,6 +11,21 @@ const assert = require('assert');
...
+  describe('#normalizeVersion', () => {
+    it('should leave valid and unsavable versions untouched', () => {
+      assert.equal(NoVulnerableLibrariesAudit.normalizeVersion(null), null);
+      assert.equal(NoVulnerableLibrariesAudit.normalizeVersion('52.1.13'), '52.1.13');
+      assert.equal(NoVulnerableLibrariesAudit.normalizeVersion('52.1.13-rc.1'), '52.1.13-rc.1');
+      assert.equal(NoVulnerableLibrariesAudit.normalizeVersion('c0ab71056b936'), 'c0ab71056b936');
+    })
+
+    it('should fix bad version numbers', () => {
+      assert.equal(NoVulnerableLibrariesAudit.normalizeVersion('11.51'), '11.51.0');
```
Comment (paulirish) [inline lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js]: we want it to do this?

File: lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js [hunk 2]
```diff
@@ -62,6 +82,15 @@ class NoVulnerableLibrariesAudit extends Audit {
...
+    try {
+      semver.satisfies(lib.version, '*');
+    } catch (err) {
+      err.pkgName = lib.npmPkgName;
+      // Report the failure and skip this library if the version was ill-specified
+      Sentry.captureException(err, {level: 'warning'});
+      return vulns;
+    }
+
     lib.pkgLink = 'https://snyk.io/vuln/npm:' + lib.npmPkgName
```
Comment (paulirish) [inline lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js]: do me a favor and update this line to

```js
 lib.pkgLink = `https://snyk.io/vuln/npm:${lib.npmPkgName}#lh@${lib.version}`;
```

File: lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js [hunk 3]
```diff
@@ -62,6 +82,15 @@ class NoVulnerableLibrariesAudit extends Audit {
       return vulns;
     }
 
+    try {
```
Comment (paulirish) [inline lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js]: idea: instead of try/catch we could make another call to `semver.valid()` . i don't care much either way. you?

Comment (patrickhulce) [reply lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js]: well I wanted to reuse the error object it generates to beacon to sentry, but I suppose not the end of the world to create our own with `captureMessage` instead?

I'm don't feel particularly strongly either way

File: lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js (hunk 2 above)
Comment (patrickhulce) [reply lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js]: heh done

File: lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js]: seemed reasonable to me as there were a lot in sentry, but I'm not sure any libraries that we for which we get just `major.minor` actually have a corresponding npm package

I'm fine to revert if you thing its bad

Comment (paulirish) [reply lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js]: nah its fine
