### PR TITLE
Fix service worker gatherer by waiting for active state

### LINKED ISSUE #1815: Flakiness with "Registers a service worker" audit
We have installed service worker, but lighthouse report saying service worker not installed. 
Site URL : https://fuzecaresystem.com/

Please check screenshot:
capture

### PR DESCRIPTION
**Pull request by wardpeet**
Fixes #1815 where we don't wait until the service worker is active. 
Happens mostly on slow connections

not sure if I should mock and create a test for this?

### CODE REVIEW

**Comment by paulirish** [comment]
Do we have a fairly solid repro for the bug? 

I'm trying it with heavier throttling on both caltrainschedule and fuzecaresystem and i can't repro the bug.

**Comment by wardpeet** [comment]
if you like I can add a failing test case to the mix. In my test case you can see the issue at end. First it's installing and the audit goes right through it, now it waits for activated.

I throttled my connection with charles and could reproduce it quite often. One time I didn't have a service worker, the other time I did.

**Comment by wardpeet** [comment]
@paulirish here is a url that I could reproduce it with
https://fuzecaresystem.com/ see #1815  for more info

**Comment by wardpeet** [comment]
Referencing #1815

**Comment by stramel** [comment]
Can we get this merged in soon?

File: lighthouse-core/gather/driver.js [hunk 1]
```diff
@@ -263,10 +263,25 @@ class Driver {
...
   getServiceWorkerVersions() {
     return new Promise((resolve, reject) => {
-      this.once('ServiceWorker.workerVersionUpdated', data => {
-        this.sendCommand('ServiceWorker.disable')
-          .then(_ => resolve(data), reject);
-      });
+      const versionUpdatedListener = data => {
+        // find a service worker with runningStatus that looks like active
+        // on slow connections the serviceworker might still be installing
+        const nonRedundantServiceWorkers = data.versions.filter(sw => {
```
Comment (ebidel) [inline lighthouse-core/gather/driver.js]: suggest `nonRedundantServiceWorkers` -> `activateCandidates`

File: lighthouse-core/gather/driver.js [hunk 2]
```diff
@@ -263,10 +263,25 @@ class Driver {
...
+          return sw.status !== 'redundant';
+        });
+        const activeServiceWorker = nonRedundantServiceWorkers.find(sw => {
+          return sw.status === 'activated';
+        });
+
+        const hasActiveServiceWorker = nonRedundantServiceWorkers.length && activeServiceWorker;
```
Comment (ebidel) [inline lighthouse-core/gather/driver.js]: Do you need this boolean? Isn't `activeServiceWorker` enough?

Comment (wardpeet) [inline lighthouse-core/gather/driver.js]: when reading the code over again it seems like you are right

File: lighthouse-core/gather/driver.js (hunk 1 above)
Comment (wardpeet) [inline lighthouse-core/gather/driver.js]: will update

File: lighthouse-core/gather/driver.js [hunk 3]
```diff
@@ -272,10 +272,25 @@ class Driver {
...
+        // find a service worker with runningStatus that looks like active
+        // on slow connections the serviceworker might still be installing
+        const activateCandidates = data.versions.filter(sw => {
+          return sw.status !== 'redundant';
+        });
+        const activeServiceWorker = activateCandidates.find(sw => {
+          return sw.status === 'activated';
+        });
+
+        const hasActiveServiceWorker = activeServiceWorker;
```
Comment (ebidel) [inline lighthouse-core/gather/driver.js]: nite: let's just remove and use `activeServiceWorker`

**Comment by stramel** [comment]
LGTM :+1:
