### PR TITLE
core(noopener-audit): noreferrer implies noopener

### LINKED ISSUE #2482: noopener audit should also allow `noreferrer`
Failing HTML:
```html
<a href="https://example.com" target="_blank" rel="noreferrer">text</a>
```

According to https://mathiasbynens.github.io/rel-noopener/ , using `noreferrer` by itself fixes the vulnerability too.

If `noreferrer` is enough, then wouldn't putting `noopener` next to it would be redundant?

### PR DESCRIPTION
**Pull request by jwheare**
This fixes #2482 and updates #2485 fixing conflicts.

The added tests were checked with ./lighthouse-cli/test/smokehouse/dobetterweb/run-tests.sh

Not sure why the byte-efficiency test is failing in appveyor, it happened to me too locally, but I haven't made any changes that would affect it from what I can tell.

### CODE REVIEW

**Comment by patrickhulce** [comment]
thanks for the PR @jwheare! last time this died from lack of consensus on recommending both/just one/etc.

I'm still in favor of allowing either to pass like you've implemented here. @paulirish WDYT now?

File: lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js [hunk 1]
```diff
@@ -16,9 +16,10 @@ class ExternalAnchorsUseRelNoopenerAudit extends Audit {
     return {
       name: 'external-anchors-use-rel-noopener',
       description: 'Opens external anchors using `rel="noopener"`',
```
Comment (paulirish) [inline lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js]: > Links to cross-origin destinations are safe

File: lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js [hunk 2]
```diff
@@ -16,9 +16,10 @@ class ExternalAnchorsUseRelNoopenerAudit extends Audit {
...
-      failureDescription: 'Does not open external anchors using `rel="noopener"`',
-      helpText: 'Open new tabs using `rel="noopener"` to improve performance and ' +
-          'prevent security vulnerabilities. ' +
+      failureDescription: 'Does not open external anchors using `rel="noopener"` or ' +
```
Comment (paulirish) [inline lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js]: > Links to cross-origin destinations are unsafe

File: lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js [hunk 3]
```diff
@@ -16,9 +16,10 @@ class ExternalAnchorsUseRelNoopenerAudit extends Audit {
...
+          '`rel="noreferrer"`',
+      helpText: 'Open new tabs using `rel="noopener"` or `rel="noreferrer"` to improve ' +
```
Comment (paulirish) [inline lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js]: > Add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities.

**Comment by jwheare** [comment]
Wording changes sound good to me.

Is the text on https://developers.google.com/web/tools/lighthouse/audits/noopener editable in a repo somewhere? Would be good to update that to mention noreferrer too.

**Comment by paulirish** [comment]
it's editable here: https://github.com/google/WebFundamentals/blob/master/src/content/en/tools/lighthouse/audits/noopener.md
