### PR TITLE
misc: only allow 1 error from each audit/gatherer

### LINKED ISSUE #5994: Only capture similar exceptions in sentry once per audit
Discussed in #5993. We're lowering the overall sample rate, but to get an idea of relative error rates, we need to stop capturing a bunch of exceptions per audit. e.g. if multiple offscreen images have issues with their sizing information, we capture an exception per image.

Instead we should capture a single exception for the whole audit, noting the issue and giving enough information that the specific problem image can be tracked down (e.g. maybe just log the first one, which gets you details, not just that there was a problem in general).

Places to fix:
- [x] `fonts.js` ~#5993~
- [ ] `offscreen-images.js`
- [ ] `uses-responsive-images.js`
- [ ] `no-vulnerable-libraries.js`
- [ ] `optimized-images.js`
- [ ] `response-compression.js`

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
WDYT about this @brendankenny ?

**Related Issues/PRs**
closes #5994

### CODE REVIEW

**Comment by brendankenny** [comment]
also, this makes me wish that we had `sentry-test.js` :)

File: lighthouse-core/lib/sentry.js [hunk 1]
```diff
@@ -74,6 +76,19 @@ function init(opts) {
       // @ts-ignore Non-standard property added to flag error as not needing capturing.
       if (err.expected) return;
 
+      const tags = opts.tags || {};
+      if (tags.audit) {
+        const key = `audit-${tags.audit}-${err.message}`;
+        if (sentryExceptionCache.has(key)) return;
```
Comment (exterkamp) [inline lighthouse-core/lib/sentry.js]: Just curious:  Could 1 exception have both audit and gatherer tags?  In which case returning here would not allow the gatherer tags to be analyzed?  I don't think so, but wanted to make sure.

File: lighthouse-core/lib/sentry.js [hunk 2]
```diff
@@ -74,6 +76,19 @@ function init(opts) {
...
+        sentryExceptionCache.set(key, true);
+      }
+
+      if (tags.gatherer) {
+        const key = `gatherer-${tags.gatherer}-${err.message}`;
+        if (sentryExceptionCache.has(key)) return;
```
Comment (exterkamp) [inline lighthouse-core/lib/sentry.js]: Why check `has`?  Can't it just `set` it and override the old version in the map?  Or is that not readable JS? :confused:

File: lighthouse-core/lib/sentry.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-core/lib/sentry.js]: nope, it either happens in an audit, or a gatherer, or neither :)

File: lighthouse-core/lib/sentry.js (hunk 2 above)
Comment (patrickhulce) [reply lighthouse-core/lib/sentry.js]: if it has the key we want to `return` and skip the rest of execution, not just the rest of the block. worth adding a comment since it's confusing already? :)
