### PR TITLE
core(console-messages): use source-location

### LINKED ISSUE #11761: "document.write()" line number is 0-indexed instead of 1-indexed
#### Provide the steps to reproduce
1. Run LH on https://www.freepik.com/
  

#### What is the current behavior?
The line of code where "document.write()" appears will be 0.

image98

Does this indicate that "document.write()" is not being used?
Or is the line of code wrong?

#### What is the expected behavior?
If you are not using "document.write()", I don't think it should be output to the audit.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: v6.5.0
* Chrome version:  86.0.4240.198
* Node.js version: v12.18.4
* Operating System: Windows10

**Related issues**
NA

### PR DESCRIPTION
**Pull request by connorjclark**
Change all audits that rely on `ConsoleMessages` to produce a `source-location` column, instead of `url` + "location" columns.

I also tweaked all the `source-location` columns to use the `UIStrings.columnSource` label.

Audits now using `source-location` and previously weren't:

- `deprecations`
- `geolocation-on-start`
- `no-document-write`
- `notification-on-start`
- `uses-passive-event-listeners`
- `errors-in-console`

Audits now using `UIStrings.columnSource` for `source-location` and previously weren't:

- `deprecations`
- `no-unload-listeners`

before

image

after

image

fixes #11761

(related #10930–this PR is low impact, only fixing the off-by-one line number + adding column, but once this other PR lands we'll also supercharge the URL here by using a source map for JS events)

### CODE REVIEW

File: lighthouse-core/audits/deprecations.js [hunk 1]
```diff
@@ -57,33 +58,16 @@ class Deprecations extends Audit {
...
 
     const deprecations = entries.filter(log => log.source === 'deprecation').map(log => {
-      // HTML deprecations will have no url and no way to attribute to a specific line.
-      /** @type {LH.Audit.Details.SourceLocationValue=} */
-      let source;
-      if (log.url) {
-        // JS deprecations will have a stack trace.
-        // CSS deprecations only expose a line number.
-        const topCallFrame = log.stackTrace && log.stackTrace.callFrames[0];
-        const line = log.lineNumber || 0;
```
Comment (connorjclark) [inline lighthouse-core/audits/deprecations.js:67]: the call frames are now used in `ConsoleMessages` to set line/col, so we can just defer to that here now.

File: lighthouse-core/audits/errors-in-console.js [hunk 2]
```diff
@@ -81,14 +81,15 @@ class ErrorLogs extends Audit {
...
-    /** @type {Array<{source: string, description: string|undefined, url: string|undefined}>} */
+    /** @type {Array<{source: string, description: string|undefined, sourceLocation: LH.Audit.Details.SourceLocationValue|undefined}>} */
     const consoleRows = artifacts.ConsoleMessages
       .filter(item => item.level === 'error')
       .map(item => {
         return {
           source: item.source,
           description: item.text,
           url: item.url,
+          sourceLocation: ConsoleMessages.createSourceLocation(item),
```
Comment (connorjclark) [inline lighthouse-core/audits/errors-in-console.js:92]: It's unfortunate that `source` can't be used here, like every other audit.

File: lighthouse-core/audits/errors-in-console.js [hunk 3]
```diff
@@ -81,14 +81,15 @@ class ErrorLogs extends Audit {
...
 
-    /** @type {Array<{source: string, description: string|undefined, url: string|undefined}>} */
+    /** @type {Array<{source: string, description: string|undefined, sourceLocation: LH.Audit.Details.SourceLocationValue|undefined}>} */
     const consoleRows = artifacts.ConsoleMessages
       .filter(item => item.level === 'error')
       .map(item => {
         return {
           source: item.source,
           description: item.text,
           url: item.url,
```
Comment (connorjclark) [inline lighthouse-core/audits/errors-in-console.js:91]: wondering if `url` should stick around and be removed in v8 (ditto for all these other audits), or are we good with removing the old properties immediately?

Comment (Beytoven) [reply lighthouse-core/audits/errors-in-console.js:91]: I don't have a strong opinion on whether we should keep the `url` field around until v8. However, if you decide to leave it for now please add a TODO to remove it later.

**Review by Beytoven — APPROVED** [review]
LGTM

**Review by brendankenny — COMMENTED** [review]
it seems like a bad sign that there are no test changes in here when the audit details types are changing. Was there a major lack of coverage due to being old audits?

File: lighthouse-core/gather/gatherers/console-messages.js [hunk 4]
```diff
@@ -31,6 +31,22 @@ function remoteObjectToString(obj) {
 }
 
 class ConsoleMessages extends Gatherer {
+  /**
+   * @param {LH.Artifacts.ConsoleMessage} entry
+   * @return {LH.Audit.Details.SourceLocationValue | undefined}
+   */
+  static createSourceLocation(entry) {
```
[the remark this answers is not in the document]
Comment (patrickhulce) [reply lighthouse-core/gather/gatherers/console-messages.js:38]: idk, it doesn't seem so bad to me. the logic for a genericly used "this is how you transform my results into useful audit details" doesn't really have a great place to live at the moment and living close to the gatherer implementation that produces that input is reasonable.

was there a specific alternative you had in mind?

[the remark this answers is not in the document]
Comment (brendankenny) [reply lighthouse-core/gather/gatherers/console-messages.js:38]: > idk, it doesn't seem so bad to me. the logic for a genericly used "this is how you transform my results into useful audit details" doesn't really have a great place to live at the moment and living close to the gatherer implementation that produces that input is reasonable.
> 
> was there a specific alternative you had in mind?

yeah, my instinct is to keep audit stuff out of gatherers because the more crossover there is the harder it is to reason about them separately, but it's a fair argument for this.

- Inline instead of a function call is one option (the transformation isn't a complicated one)
- Another is `audit.js`, where we've put other functions like this. It might be a good place for this too so that it's clear when these kinds of utilities are reaching critical mass and we really do need a good place (or places) for them to live

If folks disagree let's just drop it, this isn't a big deal, but it's also worth looking ahead to the mentioned #10930, at which point this audit details will need `ConsoleMessages` _and_ `SourceMaps` and `ScriptElements` to do the source map lookup and it becomes a bigger deal :)

[the remark this answers is not in the document]
Comment (patrickhulce) [reply lighthouse-core/gather/gatherers/console-messages.js:38]: heh, the combo of sourcemaps *and* scriptelements being necessary is definitely a -1 for living on `ConsoleMessages`, audit.js SGTM :)

File: lighthouse-core/test/results/sample_v2.json [hunk 5]
```diff
@@ -763,7 +819,7 @@
               "url": "http://localhost:10200/dobetterweb/dbw_tester.js",
               "urlProvider": "network",
               "line": 13,
-              "column": 9
```
[the remark this answers is not in the document]
Comment (connorjclark) [reply lighthouse-core/test/results/sample_v2.json]: thanks for catching, I forgot to copy the "call frame" thing.

[the remark this answers is not in the document]
Comment (connorjclark) [reply lighthouse-core/test/results/sample_v2.json]: Oh, no, that is handled in the artifact creation...the issue is that the sample artifact for ConsoleMessages need to be updated

File: lighthouse-core/test/results/artifacts/artifacts.json [hunk 6]
```diff
@@ -1100,17 +1108,10 @@
...
-      "timestamp": 1607553423368.14,
+      "timestamp": 1610571266318.583,
       "url": "http://localhost:10200/dobetterweb/dbw_tester.html",
-      "lineNumber": 371
-    },
-    {
-      "eventType": "protocolLog",
-      "source": "deprecation",
-      "level": "warning",
-      "text": "/deep/ combinator is no longer supported in CSS dynamic profile. It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.",
```
Comment (connorjclark) [inline lighthouse-core/test/results/artifacts/artifacts.json:1111]: I suppose this deprecation noticed has been since deleted in Chromium.

File: lighthouse-core/audits/errors-in-console.js (hunk 3 above)
Comment (patrickhulce) [reply lighthouse-core/audits/errors-in-console.js:91]: I like leaving it here too 👍

File: lighthouse-core/test/results/artifacts/artifacts.json [hunk 7]
```diff
@@ -806,9 +806,10 @@
           }
         ]
       },
-      "timestamp": 1607553418610.9011,
+      "timestamp": 1610571261691.184,
       "url": "http://localhost:10200/dobetterweb/dbw_tester.js",
-      "lineNumber": 13
+      "lineNumber": 13,
+      "columnNumber": 9
```
Comment (patrickhulce) [inline lighthouse-core/test/results/artifacts/artifacts.json:812]: 🎉

**Review by patrickhulce — APPROVED** [review]
LGTM

**Review by brendankenny — APPROVED** [review]
LGTM!
