### PR TITLE
tests(devtools): fix webserver

### LINKED ISSUE #12209: smoke-devtools running indefinitely
Seen in https://github.com/GoogleChrome/lighthouse/pull/12207/checks?check_run_id=2042895469

Runs somewhat slowly but completes, but then sits on "Waiting for server".

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #12209

### CODE REVIEW

File: lighthouse-core/test/chromium-web-tests/web-test-server.sh [hunk 1]
```diff
@@ -17,7 +17,7 @@ export latest_content_shell="$LH_ROOT/.tmp/chromium-web-tests/content-shells/$la
 #   - /inspector-sources -> the inspector resources from the content shell
 #   - CORS (Access-Control-Allow-Origin header)
 
-ln -s "$DEVTOOLS_PATH/out/Default/resources/inspector" "$DEVTOOLS_PATH/test/webtests/http/tests/inspector-sources"
+ln -s "$latest_content_shell/out/Release/resources/inspector" "$DEVTOOLS_PATH/test/webtests/http/tests/inspector-sources"
```
Comment (connorjclark) [inline lighthouse-core/test/chromium-web-tests/web-test-server.sh:20]: How I debugged...

I removed the output redirection of the webserver to dev/null and noticed 404s. integration_runner.js was missing. I realized line wasn't doing what the comment suggested... the `inspector-sources` file is meant to come from content_shell, the reason is that the compiled devtools framework code should match the content shell binary.

I guess `integration_runner.js` was being generated by devtools before, but no longer is. the incorrect symbolic link was overlooked because of that.

Comment (connorjclark) [reply lighthouse-core/test/chromium-web-tests/web-test-server.sh]: Scratch that. DT team refactored the BUILD rules, and so we weren't building the right thing any more. And the output folder changed slightly.

File: third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt [hunk 2]
```diff
@@ -2,11 +2,11 @@ Tests that exporting works.
 
 ++++++++ testExportHtml
 
-# of .lh-audit divs (original): 137
+# of .lh-audit divs (original): 136
```
Comment (adamraine) [inline third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt:5]: What changed here?

Comment (connorjclark) [reply third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt:5]: file last changed with csp-xss https://github.com/GoogleChrome/lighthouse/commits/master/third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt

I don't see why this would have changed, since the audit is in experimental, so doesn't show in DT.

**Review by adamraine — APPROVED** [review]
