### PR TITLE
Fixes #1071 - handles eval'd script in callsite collector

### LINKED ISSUE #1071: Extension Error: Parameter 'url' must be a string, not undefined
**Lighthouse Version**: 1.2.1
**Chrome Version**: 54.0.2840.99
**Error Message**: Parameter 'url' must be a string, not undefined
**Stack Trace**:
 ```
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:41949:11)
    at Object.urlParse [as parse] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:41943:5)
    at artifacts.ConsoleTimeUsage.usage.filter.err (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:808:18)
    at Array.filter (native)
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:807:54)
    at chain.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11082:24)
```

### PR DESCRIPTION
**Pull request by ebidel**
R: @brendankenny @patrickhulce @paulirish 

According to  https://crbug.com/646849, eval'd script does not include the url context where the script was run. So for our callsite collector, we were throwing an error trying to parse a `.url` property that did not exist. This PR handles eval'd scripts and sets the .url to be the last entry of the stacktrace.

Example run: http://onset.github.io/lighthouse-test/

screen shot 2016-11-28 at 4 59 41 pm

### CODE REVIEW

File: lighthouse-core/gather/driver.js [hunk 1]
```diff
@@ -702,13 +702,23 @@ function captureJSCallUsage(funcRef, set) {
...
-      // const stackTrace = structStackTrace.slice(1).map(
-      //    callsite => callsite.toString());
-      return {url: file, args, line, col}; // return value is e.stack
+      const isEval = callFrame.isEval();
+      const stackTrace = structStackTrace.slice(1).map(callsite => callsite.toString());
+
+      // If we don't have an URL, (e.g. eval'd code), use the last entry in the
+      // stack trace to give some context. See https://crbug.com/646849.
+      if (!url) {
+        url = stackTrace[0];
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: strip out the column/line number from the entry?

Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: also, maybe add a note to the comment that the `line` and `col` already point to the last entry's location?

File: lighthouse-core/audits/dobetterweb/no-console-time.js [hunk 2]
```diff
@@ -63,7 +63,10 @@ class NoConsoleTimeAudit extends Audit {
     const pageHost = url.parse(artifacts.URL.finalUrl).host;
     // Filter usage from other hosts.
```
Comment (brendankenny) [inline lighthouse-core/audits/dobetterweb/no-console-time.js]: add something about keeping eval callsites?

File: lighthouse-core/audits/dobetterweb/no-console-time.js [hunk 3]
```diff
@@ -63,7 +63,10 @@ class NoConsoleTimeAudit extends Audit {
...
     const results = artifacts.ConsoleTimeUsage.usage.filter(err => {
-      return url.parse(err.url).host === pageHost;
+      if (!err.url) {
```
Comment (brendankenny) [inline lighthouse-core/audits/dobetterweb/no-console-time.js]: it seems like from your driver changes there will never not be a url?

File: lighthouse-core/audits/dobetterweb/no-console-time.js (hunk 2 above)
Comment (ebidel) [inline lighthouse-core/audits/dobetterweb/no-console-time.js]: done

File: lighthouse-core/audits/dobetterweb/no-console-time.js (hunk 3 above)
Comment (ebidel) [inline lighthouse-core/audits/dobetterweb/no-console-time.js]: Removed the extra check.

File: lighthouse-core/gather/driver.js [hunk 4]
```diff
@@ -702,13 +702,23 @@ function captureJSCallUsage(funcRef, set) {
...
       const line = callFrame.getLineNumber();
       const col = callFrame.getColumnNumber();
-      // TODO: add back when we want stack traces. See https://github.com/GoogleChrome/lighthouse/issues/957
-      // const stackTrace = structStackTrace.slice(1).map(
-      //    callsite => callsite.toString());
-      return {url: file, args, line, col}; // return value is e.stack
+      const isEval = callFrame.isEval();
+      const stackTrace = structStackTrace.slice(1).map(callsite => callsite.toString());
+
+      // If we don't have an URL, (e.g. eval'd code), use the last entry in the
```
Comment (patrickhulce) [inline lighthouse-core/gather/driver.js]: could you also give an example here as to what the url will be? I know you could piece it together from the v8 API, but it'd be nice to get a sense for what it's getting at here too :)

Comment (ebidel) [inline lighthouse-core/gather/driver.js]: Might be hard to do. It's a stacktrace line

**Comment by ebidel** [comment]
PTAL

File: lighthouse-core/gather/driver.js (hunk 4 above)
Comment (patrickhulce) [inline lighthouse-core/gather/driver.js]: yeah perfect 👍

Comment (ebidel) [inline lighthouse-core/gather/driver.js]: done
