### PR TITLE
fix(OffscreenImages): find images with no area

### LINKED ISSUE #1914: OffscreenImages: flag images with 0 area
Testing https://www.chromestatus.com/features, I get a debugString in the offscreen images audit for an .svg file. 

screen shot 2017-03-27 at 3 29 50 pm

Shall we ignore svgs in this auidt?

### PR DESCRIPTION
**Pull request by patrickhulce**
R: @ebidel

fixes #1914

### CODE REVIEW

File: lighthouse-core/audits/byte-efficiency/offscreen-images.js [hunk 1]
```diff
@@ -72,7 +72,8 @@ class OffscreenImages extends Audit {
     const url = URL.getDisplayName(image.src, {preserveQuery: true});
     const totalPixels = image.clientWidth * image.clientHeight;
     const visiblePixels = this.computeVisiblePixels(image.clientRect, viewportDimensions);
-    const wastedRatio = 1 - visiblePixels / totalPixels;
+    // Treat images with 0 area as if they're offscreen
```
Comment (ebidel) [inline lighthouse-core/audits/byte-efficiency/offscreen-images.js]: nit: link to https://github.com/GoogleChrome/lighthouse/issues/1914 if you want and mention that this can happen if the container is `display: none`.

Comment (ebidel) [inline lighthouse-core/audits/byte-efficiency/offscreen-images.js]: Yea this is interesting. https://www.chromestatus.com/features uses the ring.svg image for a loading animation. When the features are loaded, the img's container is hidden. So technically, the image is needed on page load. It's just hidden later on. See any ways around such a false positive?

Comment (brendankenny) [inline lighthouse-core/audits/byte-efficiency/offscreen-images.js]: > See any ways around such a false positive?

there was @paulirish's suggestion to look at what images were actually decoded, indicating that Chrome thought that the image was needed. That makes other aspects of the audit more difficult to do.

Comment (ebidel) [inline lighthouse-core/audits/byte-efficiency/offscreen-images.js]: Agreed. Don't want to derail this fix. 

@patrickhulce maybe file a bug capturing this info? We can improve the audit in the future.

Comment (patrickhulce) [inline lighthouse-core/audits/byte-efficiency/offscreen-images.js]: done
