### PR TITLE
core(tracing): handle FrameCommittedInBrowser with processPseudoId

### LINKED ISSUE #14798: Unable to determine tid for renderer process
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://treo.sh/

### What happened?

"FrameCommittedInBrowser" event had a `processPseudoId` instead of a `processId`

Screenshot 2023-02-15 at 09 43 01

So `mainFramePids` only contained `undefined` and Lighthouse returned an error: "Unable to determine tid for renderer process"

### What did you expect?

Not to get an error

### What have you tried?

Lighthouse returned an error

### How were you running Lighthouse?

node

### Lighthouse Version

10.0.1

### Chrome Version

Version 112.0.5597.0 (Official Build) canary (x86_64 translated), but happens in others too

### Node Version

_No response_

### OS

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by paulirish**
fixes #14798 

There are some traces where the pid isnt available when the frame is created. In these situations, the `FrameCommittedInBrowser` event has an undefined `processId` prop, and empty string `name` prop, and a hexadecimal `processPseudoId`. Later a `ProcessReadyInBrowser` event provides the processId.

I'm not sure how common this is, or the exact circumstances. I've only discovered one of my saved traces (out of 200+) had this pattern, but.. matt ran into it #14798 too. 

Regardless, here's a fix w/ a test.

### CODE REVIEW

File: core/test/lib/tracehouse/trace-processor-test.js [hunk 1]
```diff
@@ -964,5 +963,33 @@ Object {
...
+      procReadyEvt.name = 'ProcessReadyInBrowser';
+      procReadyEvt.args.data = {frame, processId, processPseudoId: '0xbaabaa'};
+      procReadyEvt.ts = fcibEvt.ts + 10;
+      psuedoProcTrace.traceEvents.push(procReadyEvt);
+
+      const psuedoProcSummarized = summarizeTrace(psuedoProcTrace);
+      expect(psuedoProcSummarized.mainFramePids.size).toEqual(1);
+      // The primary process events should make up more than 40% of all key trace events
+      expect(psuedoProcSummarized.processEventsPct).toBeGreaterThanOrEqual(0.4);
+    }
```
Comment (adamraine) [inline core/test/lib/tracehouse/trace-processor-test.js:993]: Could this just be a separate test?

File: core/lib/tracehouse/trace-processor.js [hunk 2]
```diff
@@ -489,20 +489,22 @@ class TraceProcessor {
    */
   static findMainFramePidTids(mainFrameInfo, keyEvents) {
     const frameCommittedEvts = keyEvents.filter(evt =>
```
Comment (adamraine) [inline core/lib/tracehouse/trace-processor.js:491]: nit: this no longer has just frame committed events, maybe rename to something like `frameProcessEvts`?

**Review by adamraine — APPROVED** [review]

File: core/lib/tracehouse/trace-processor.js [hunk 3]
```diff
@@ -488,21 +488,23 @@ class TraceProcessor {
    * @return {Map<number, number>} Map where keys are process IDs and their values are thread IDs
    */
   static findMainFramePidTids(mainFrameInfo, keyEvents) {
-    const frameCommittedEvts = keyEvents.filter(evt =>
-      evt.name === 'FrameCommittedInBrowser' &&
+    const frameProcessEvts = keyEvents.filter(evt =>
+      // ProcessReadyInBrowser is used when a processID isn't available when the FrameCommittedInBrowser trace event is emitted.
+      // In that case. FrameCommittedInBrowser has no processId, but a processPseudoId. and the ReadyInBrowser event declares the proper processId.
```
Comment (brendankenny) [inline core/lib/tracehouse/trace-processor.js:493]: total nit, but maybe move the `filter(Boolean)` below into this filter (as `&& e?.args?.data?.processId` or whatever) so it's closer to the comment explaining it

File: core/lib/tracehouse/trace-processor.js [hunk 4]
```diff
@@ -488,21 +488,23 @@ class TraceProcessor {
...
+    const mainFramePids = frameProcessEvts.length
+      ? frameProcessEvts.map(e => e?.args?.data?.processId).filter(Boolean)
       // …But old traces and some timespan traces may not. In these situations, we'll assume the
       // primary process ID remains constant (as there were no navigations).
       : [mainFrameInfo.startingPid];
 
     const pidToTid = new Map();
 
-    mainFramePids.forEach(pid => {
+    Array.from(new Set(mainFramePids)).forEach(pid => {
```
Comment (brendankenny) [inline core/lib/tracehouse/trace-processor.js:507]: even more of a nit: could skip the `Array.from` with `for (const pid of new Set(mainFramePids)) {`

File: core/test/lib/tracehouse/trace-processor-test.js [hunk 5]
```diff
@@ -943,26 +944,51 @@ Object {
...
+      // A 'normal' FrameCommittedInBrowser's data is:
+      //                 {"frame":"FRAME_ID","name":"","processId":72647,"url":"https://memegen.corp.google.com/"}
+      // But if the processId isn't ready at frame creation, we get this pair:
+      // {"args":{"data":{"frame":"FRAME_ID","name":"","processPseudoId":"0x7ff70022ca00","url":"https://memegen.com/"}},"cat":"disabled-by-default-devtools.timeline","name":"FrameCommittedInBrowser","ph":"I","pid":744,"s":"t","tid":775,"ts":123265406529,"tts":10824502153},
+      // {"args":{"data":{"frame":"FRAME_ID","processId":72647,"processPseudoId":"0x7ff70022ca00"}},"cat":"disabled-by-default-devtools.timeline","name":"ProcessReadyInBrowser","ph":"I","pid":744,"s":"t","tid":775,"ts":123265450207,"tts":10824519750},
+      const psuedoProcTrace = JSON.parse(JSON.stringify(decentlyModernTrace));
+      const fcibEvt = psuedoProcTrace.traceEvents.find(e => e.name === 'FrameCommittedInBrowser');
+      const {url, processId, frame, name} = fcibEvt.args.data;
+      expect(processId).toBeTruthy();
+      fcibEvt.args.data = {frame, name, url, processPseudoId: '0xbaabaa'};
```
Comment (brendankenny) [inline core/test/lib/tracehouse/trace-processor-test.js:980]: from the pr description, should this include `processId: ''` just for completeness?

File: core/test/lib/tracehouse/trace-processor-test.js [hunk 6]
```diff
@@ -943,26 +944,51 @@ Object {
...
+
+      const procReadyEvt = JSON.parse(JSON.stringify(fcibEvt));
+      procReadyEvt.name = 'ProcessReadyInBrowser';
+      procReadyEvt.args.data = {frame, processId, processPseudoId: '0xbaabaa'};
```
Comment (brendankenny) [inline core/test/lib/tracehouse/trace-processor-test.js:984]: Oh, do the `processPseudoId`s match? Almost feels like information we should be using in trace-processor (only look at `ProcessReadyInBrowser` events that have a `processPseudoId` that matches a `FrameCommittedInBrowser` without a `proccessId`?) but maybe it can never matter

**Review by brendankenny — APPROVED** [review]
nice fix!

File: core/lib/tracehouse/trace-processor.js (hunk 3 above)
Comment (brendankenny) [reply core/lib/tracehouse/trace-processor.js:493]: I guess it's less clear then that any `undefined` from `e?.args?.data?.processId` is immediately filtered out (instead it's pre-filtered), though tsc doesn't care (`mainFramePids` is `Array<number|undefined>` either way)

File: core/test/lib/tracehouse/trace-processor-test.js (hunk 6 above)
Comment (paulirish) [reply core/test/lib/tracehouse/trace-processor-test.js:984]: yah we definitely could. and I considered it. But I think it's kinda overkill.
I'm happy to revisit.

File: core/lib/tracehouse/trace-processor.js (hunk 3 above)
Comment (paulirish) [reply core/lib/tracehouse/trace-processor.js]: its a good idea. i did it.
