### PR TITLE
core: special case AppManifest as baseArtifact

### LINKED ISSUE #6881: Lighthouse unable to fetch manifest.json, favicons in Canary 73.0.3654.0
Problem
=====
Favicons and Manifest.json are not accessible to Lighthouse in Canary 73, but they are accessible to Lighthouse in Chrome 71. Failure to retrieve resources by clicking on corresponding hrefs in source view suggests the problem may be Canary itself, not Lighthouse.

OS, Browsers, URL
============
OS: Windows 8.1
Browsers: Chrome 71.0.3578.98 & Canary 73.0.3654.0
URL tested: https://ives-fourth-symphony.com

Lighthouse setup:
=================
Incognito Mode, all browser extensions off
Device: Mobile
All Audits Selected
Throttling: Simulated Fast 3G
Clear Storage: checked

Chrome 71.0.3578.98
===================
No PWA errors detected

Canary 73.0.3654.0
==================
Multiple PWA errors, all from inability to fetch manifest.json:

3: "No usable web app manifest found on page"
6: Failures: No manifest was fetched
8: Failures: No manifest was fetched
9: Failures: No manifest was fetched

The problem may be the browser itself, not Lighthouse.

View source of page in each browser
========================
Go to: view-source:https://ives-fourth-symphony.com/
Search for "href=manifest" and "href=favicon" in the view-source to select the manifest.json and the two favicons
Try clicking on the three links in the two browsers

Chrome 71.0.3578.98
===================
Success: Each link opens in a new tab

Canary 73.0.3654.0
==================
Failure: Neither resource is fetched by clicking on the links:

Theory: Something is wrong with Canary Version 73.0.3654.0

Please advise

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
See https://github.com/GoogleChrome/lighthouse/pull/6882#issuecomment-452459363

Cleans up our start URL gatherer to not fetch and parse the manifest again.

**Related Issues/PRs**
@brendankenny's preferred implementation of #6882 
closes #6881

### CODE REVIEW

File: types/artifacts.d.ts [hunk 1]
```diff
@@ -29,6 +29,8 @@ declare global {
       NetworkUserAgent: string;
       /** The benchmark index that indicates rough device class. */
       BenchmarkIndex: number;
+      /** The application manifest if one was fetched. */
+      AppManifest: Artifacts.Manifest | null;
```
Comment (brendankenny) [inline types/artifacts.d.ts]: to me this makes me question if it's actually related to an appcache manifest :) If we want to be more precise, how do you feel about `WebAppManifest`?

File: lighthouse-core/gather/gather-runner.js [hunk 2]
```diff
@@ -427,6 +429,41 @@ class GatherRunner {
...
+   * there.
+   *
+   * Returns the parsed manifest or null if the page had no manifest. If the manifest
+   * was unparseable as JSON, manifest.value will be undefined and manifest.warning
+   * will have the reason. See manifest-parser.js for more information.
+   *
+   * @param {LH.Gatherer.PassContext} passContext
+   * @return {Promise<LH.Artifacts['Manifest']>}
+   */
+  static async getAppManifest(passContext) {
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: should we merge most of this into `driver.getAppManifest()`? Not the `baseArtifacts` check, of course, and probably not the parse step(?)

File: lighthouse-core/gather/gather-runner.js [hunk 3]
```diff
@@ -427,6 +429,41 @@ class GatherRunner {
...
+    if (passContext.baseArtifacts.AppManifest) return passContext.baseArtifacts.AppManifest;
+
+    const BOM_LENGTH = 3;
+    const BOM_FIRSTCHAR = 65279;
+
+    const manifestPromise = passContext.driver.getAppManifest();
+    /** @type {Promise<void>} */
+    const timeoutPromise = new Promise(resolve => setTimeout(resolve, 3000));
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: I think we can remove this with the default timeouts now

File: lighthouse-core/gather/gatherers/manifest.js [hunk 4]
```diff
@@ -6,40 +6,18 @@
...
-const BOM_FIRSTCHAR = 65279;
 
 /**
- * Uses the debugger protocol to fetch the manifest from within the context of
- * the target page, reusing any credentials, emulation, etc, already established
- * there. The artifact produced is the fetched string, if any, passed through
+ * The artifact produced is the fetched manifest string, if any, passed through
  * the manifest parser.
  */
 class Manifest extends Gatherer {
```
Comment (brendankenny) [inline lighthouse-core/gather/gatherers/manifest.js]: any reason to keep this? TODO for followup to split up the changes nicely? Or is it worth keeping for some reason?

File: types/gatherer.d.ts [hunk 5]
```diff
@@ -20,6 +20,7 @@ declare global {
       options?: object;
       /** Push to this array to add top-level warnings to the LHR. */
       LighthouseRunWarnings: Array<string>;
+      baseArtifacts: BaseArtifacts;
```
Comment (brendankenny) [inline types/gatherer.d.ts]: we might want to play around with `Readonly` for this, but that can be something for another day :)

File: lighthouse-core/gather/gatherers/start-url.js [hunk 6]
```diff
@@ -61,7 +54,7 @@ class StartUrl extends Gatherer {
    * @param {string} startUrl
    * @return {Promise<{statusCode: number, explanation: string}>}
    */
-  _attemptManifestFetch(driver, startUrl) {
+  _attemptStartURLFetch(driver, startUrl) {
```
Comment (brendankenny) [inline lighthouse-core/gather/gatherers/start-url.js]: ha, whoops

File: types/artifacts.d.ts (hunk 1 above)
Comment (patrickhulce) [reply types/artifacts.d.ts]: someone should tell driver and the devtools protocol then 😛 

that wfm 👍

File: lighthouse-core/gather/gatherers/manifest.js (hunk 4 above)
Comment (patrickhulce) [reply lighthouse-core/gather/gatherers/manifest.js]: boy am I regretting that 😆

Comment (patrickhulce) [reply lighthouse-core/gather/gatherers/manifest.js]: yeah I'm gonna make this a TODO

**Comment by patrickhulce** [comment]
@brendankenny this is ready for a second look now btw

File: lighthouse-core/gather/gather-runner.js [hunk 7]
```diff
@@ -467,6 +493,7 @@ class GatherRunner {
         }
         await GatherRunner.beforePass(passContext, gathererResults);
         await GatherRunner.pass(passContext, gathererResults);
+        baseArtifacts.WebAppManifest = await GatherRunner.getWebAppManifest(passContext);
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: we have two other checks against `isFirstPass` already in this method, can we move the check for this line out here too and avoid putting it on `passContext` (and it'll be more obvious we aren't overwriting it on every turn of the loop)?

File: lighthouse-core/gather/gatherers/start-url.js [hunk 8]
```diff
@@ -16,27 +15,21 @@ class StartUrl extends Gatherer {
...
-      });
+    return this._attemptStartURLFetch(passContext.driver, startUrlInfo.startUrl).catch(() => {
+      return {statusCode: -1, explanation: 'Unable to fetch start URL via service worker.'};
+    });
   }
 
   /**
    * Read the parsed manifest and return failure reasons or the startUrl
-   * @param {?{value?: {start_url: {value: string, warning?: string}}, warning?: string}} manifest
+   * @param {LH.Artifacts['Manifest']} manifest
```
Comment (brendankenny) [inline lighthouse-core/gather/gatherers/start-url.js]: `LH.Artifacts['WebAppManifest']`

File: lighthouse-core/test/gather/gatherers/start-url-test.js [hunk 9]
```diff
@@ -127,34 +138,37 @@ describe('Start-url gatherer', () => {
...
+      baseArtifacts: createArtifactsWithURL('https://ifixit-pwa.appspot.com/'),
       driver: wrapSendCommand(mockDriver, ''),
     };
 
-    return startUrlGatherer.afterPass(options, tracingData)
-      .then(artifact => {
-        assert.equal(artifact.explanation, 'Timed out waiting for fetched start_url.');
-      });
+    const resultPromise = startUrlGatherer.afterPass(passContext);
+    jest.advanceTimersByTime(5000);
```
Comment (brendankenny) [inline lighthouse-core/test/gather/gatherers/start-url-test.js]: wellllllll this is nice

File: lighthouse-core/test/gather/gatherers/start-url-test.js [hunk 10]
```diff
@@ -89,18 +99,20 @@ describe('Start-url gatherer', () => {
...
     const startUrlGatherer = new StartUrlGatherer();
     const startUrlGathererWithFragment = new StartUrlGatherer();
-    const options = {
+    const passContext = {
       url: 'https://ifixit-pwa.appspot.com/',
+      baseArtifacts: createArtifactsWithURL('https://ifixit-pwa.appspot.com/'),
       driver: wrapSendCommand(mockDriver, 'https://ifixit-pwa.appspot.com/', 200, true),
     };
-    const optionsWithQueryString = {
+    const passContextWithFragment = {
```
Comment (brendankenny) [inline lighthouse-core/test/gather/gatherers/start-url-test.js]: :)

File: lighthouse-core/test/gather/gatherers/start-url-test.js [hunk 11]
```diff
@@ -28,18 +28,25 @@ const wrapSendCommand = (mockDriver, url, status = 200, fromServiceWorker = fals
...
+    return {WebAppManifest: {value: {start_url: {value: url}}}};
+  }
+
+  beforeEach(() => {
+    jest.useFakeTimers();
+    baseArtifacts = {WebAppManifest: null};
+  });
+
+  afterEach(() => {
+    jest.advanceTimersByTime(5000);
```
Comment (brendankenny) [inline lighthouse-core/test/gather/gatherers/start-url-test.js]: why is this needed *after* each test is done?

File: lighthouse-core/gather/gather-runner.js [hunk 12]
```diff
@@ -427,6 +429,28 @@ class GatherRunner {
...
+   * Returns the parsed manifest or null if the page had no manifest. If the manifest
+   * was unparseable as JSON, manifest.value will be undefined and manifest.warning
+   * will have the reason. See manifest-parser.js for more information.
+   *
+   * @param {LH.Gatherer.PassContext} passContext
+   * @return {Promise<LH.Artifacts['Manifest']>}
+   */
+  static async getWebAppManifest(passContext) {
+    // If we already have a manifest, return it.
+    if (passContext.baseArtifacts.WebAppManifest) return passContext.baseArtifacts.WebAppManifest;
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: not needed with the `isFirstPass` check below?

File: types/artifacts.d.ts [hunk 13]
```diff
@@ -29,6 +29,8 @@ declare global {
       NetworkUserAgent: string;
       /** The benchmark index that indicates rough device class. */
       BenchmarkIndex: number;
+      /** Parsed version of the page's Web App Manifest, or null if none found.. */
```
[the remark this answers is not in the document]
Comment (patrickhulce) [reply types/artifacts.d.ts]: done

File: lighthouse-core/test/gather/driver-test.js [hunk 14]
```diff
@@ -318,6 +318,36 @@ describe('Browser Driver', () => {
       assert.equal(sendCommandParams[0], undefined);
     });
   });
+
+  describe('.getAppManifest', () => {
+    it('should return null when no manifest', async () => {
+      const sendCommand = jest.spyOn(connection, 'sendCommand');
```
[the remark this answers is not in the document]
Comment (patrickhulce) [reply lighthouse-core/test/gather/driver-test.js]: sure that's fine

File: lighthouse-core/gather/gather-runner.js [hunk 15]
```diff
@@ -427,6 +429,28 @@ class GatherRunner {
...
+   * Uses the debugger protocol to fetch the manifest from within the context of
+   * the target page, reusing any credentials, emulation, etc, already established
+   * there.
+   *
+   * Returns the parsed manifest or null if the page had no manifest. If the manifest
+   * was unparseable as JSON, manifest.value will be undefined and manifest.warning
+   * will have the reason. See manifest-parser.js for more information.
+   *
+   * @param {LH.Gatherer.PassContext} passContext
+   * @return {Promise<LH.Artifacts['Manifest']>}
```
[the remark this answers is not in the document]
Comment (patrickhulce) [reply lighthouse-core/gather/gather-runner.js]: done

File: lighthouse-core/gather/gather-runner.js (hunk 7 above)
Comment (patrickhulce) [reply lighthouse-core/gather/gather-runner.js]: sure, done

File: lighthouse-core/gather/gatherers/start-url.js (hunk 8 above)
Comment (patrickhulce) [reply lighthouse-core/gather/gatherers/start-url.js]: done

File: lighthouse-core/test/gather/gatherers/start-url-test.js (hunk 11 above)
Comment (patrickhulce) [reply lighthouse-core/test/gather/gatherers/start-url-test.js]: the other tests not touched by this don't properly cleanup their timer, I'll add a todo to fix this another time?

File: lighthouse-core/gather/gather-runner.js (hunk 12 above)
Comment (patrickhulce) [reply lighthouse-core/gather/gather-runner.js]: fair, removed

File: lighthouse-core/test/gather/gatherers/start-url-test.js (hunk 11 above)
Comment (brendankenny) [reply lighthouse-core/test/gather/gatherers/start-url-test.js]: > the other tests not touched by this don't properly cleanup their timer, I'll add a todo to fix this another time?

yeah, sounds good. I think `advanceTimersByTime` is going to be a game changer for a lot of our older tests and it would be nice to update anyways

**Comment by tmb-github** [comment]
Whatever's been done with the PWA tester in Lighthouse seems to have (or may have) broken it with regards to testing Performance in the other parts of the audit, as well as blocked the PWA audit score as well. 

In Chrome 71 (still current as I write this), this site gets 100% on performance and PWA; in the Chrome 74.0.3686.0 available today, this site gets 0% performance and 0% PWA despite 100 in all PWA categories except 2 of them:

https://ives-fourth-symphony.com

This may or may not be related to the manifest fetching rewrite, but the coincidence of the two prompted me to report this here.

**Comment by patrickhulce** [comment]
Thanks @tmb-github! The version of Lighthouse in Chrome doesn't have this commit yet, and locally this hash passes on that site, so looks like they're unrelated.
image


Is it possible you're bumping into #6968?

**Comment by tmb-github** [comment]
Please try the same audit again on the new stable Chrome 72.0.3626.81 (Official Build) (64-bit), released today. Nothing can be fetched for the PWA audit nor the Performance audit.

**Comment by tmb-github** [comment]
untitled

**Comment by patrickhulce** [comment]
Thanks @tmb-github it's due to some infrastructure serving outdated version of audits panel that's incompatible with newer Chrome. The team is on it.
