### PR TITLE
remove handleRawError call from extension connection

### LINKED ISSUE #1696: Extension Error: this.handleRawError is not a function
**Lighthouse Version**: 1.5.1
**Chrome Version**: 56.0.2924.87
**URL**: https://demo.theteamie.com/
**Error Message**: this.handleRawError is not a function
**Stack Trace**:
 ```TypeError: this.handleRawError is not a function
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:8769:33)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

### PR DESCRIPTION
**Pull request by brendankenny**
fixes #1696

Missed this in #1474. Simply replaces the call of `handleRawError` in `extension.js` with what it contained before removal.

### CODE REVIEW

File: lighthouse-core/gather/connections/extension.js [hunk 1]
```diff
@@ -116,18 +116,14 @@ class ExtensionConnection extends Connection {
...
+          errorMessage = errorMessage || 'Unknown debugger protocol error.';
 
-          // handleRawError returns or throws synchronously, so try/catch awkwardly.
-          try {
-            return resolve(this.handleRawError(error, command));
-          } catch (err) {
-            return reject(err);
-          }
+          log.formatProtocol('method <= browser ERR', {method: command}, 'error');
+          reject(new Error(`Protocol error (${command}): ${errorMessage}`));
```
Comment (ebidel) [inline lighthouse-core/gather/connections/extension.js]: `return reject`?

Comment (brendankenny) [inline lighthouse-core/gather/connections/extension.js]: good call

Comment (brendankenny) [inline lighthouse-core/gather/connections/extension.js]: done
