### PR TITLE
core(font-display): do not use invalid sourceURLs

### LINKED ISSUE #8534: Font display doesn't handle styles with relative/invalid sourceURL comments
#### Provide the steps to reproduce
1. Run LH on https://weston.ruter.net/

#### What is the current behavior?
Font display audit fails

#### What is the expected behavior?
Font display audit doesn't fail

I've traced this down to to the inline style which comes through with an invalid/relative `source.header.sourceURL`, this throws because it's not a valid URL and we don't end up whitelisting the font URL.

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/7708#issuecomment-485598419

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
Apparently `/*# sourceURL=custom-url.css */` sets the `sourceURL` in DevTools to whatever the attribute was, so we should handle that case.

**Related Issues/PRs**
fixes #8534

### CODE REVIEW

**Comment by westonruter** [comment]
> Apparently `<style custom-name>` sets the `sourceURL` in DevTools to whatever the attribute was, so we should handle that case.

Actually, the custom URL was set manually. See https://github.com/GoogleChrome/lighthouse/issues/8534#issuecomment-485617493

**Comment by patrickhulce** [comment]
Thanks @westonruter! Updated accordingly :)

File: lighthouse-core/test/audits/font-display-test.js [hunk 1]
```diff
@@ -231,6 +231,8 @@ describe('Performance: Font Display audit', () => {
   });
 
   it('handles varied font-display declarations', async () => {
+    // Make sure we don't use sourceURL when it's not a valid URL, see https://github.com/GoogleChrome/lighthouse/issues/8534
+    stylesheet.header.sourceURL = 'custom-attribute';
```
Comment (brendankenny) [inline lighthouse-core/test/audits/font-display-test.js]: any chance you could split this off into its own test? I could see us revising `font-display` at some point and having to reconfigure the tests and losing this very important line :)

Comment (patrickhulce) [reply lighthouse-core/test/audits/font-display-test.js]: sure
