### PR TITLE
core(js-usage): normalize url key

### LINKED ISSUE #11261: LightHouse HTML report generated in Debian not rendering in browser
Hi 

   Am trying to generated the LH HTML report programmatically using NodeJs, Pupetteer and lighthouse. Have verified the report on the windows environment and works fine. While testing the same in the Linux Debian environment both Json and HTML reports are generated successfully. Being a container environment with Debian chrome was launched with --no-sandbox option. While opening the report in chrome only blank page is shown up. There was browser level page error with the following stacktrace. Let me know if am missing anything / fix to solve the problem ? 
   
    
    Browser error stack trace 
    -------------------------- 
	
	Uncaught Error: query a not found
    at DOM.find (compiled-reportrenderer.js:845)
    at DetailsRenderer.renderSourceLocation (compiled-reportrenderer.js:1610)
    at DetailsRenderer._renderTableValue (compiled-reportrenderer.js:1305)
    at DetailsRenderer._renderTableRow (compiled-reportrenderer.js:1459)
    at DetailsRenderer._renderTableRowsFromItem (compiled-reportrenderer.js:1493)
    at DetailsRenderer._renderTable (compiled-reportrenderer.js:1525)
    at DetailsRenderer.render (compiled-reportrenderer.js:1121)
    at PerformanceCategoryRenderer.populateAuditValues (compiled-reportrenderer.js:3590)
    at PerformanceCategoryRenderer.renderAudit (compiled-reportrenderer.js:3546)
    at Array.map (<anonymous>)
	
      Code Snippet 
       -------------- 

	const repGen = require('lighthouse/lighthouse-core/report/report-generator');
	.
	.
	.
	const testreport = await lighthouse(url, {
			port: (new URL(browser.wsEndpoint())).port,
			output: 'json',
			logLevel: 'SEVERE',
			disableDeviceEmulation: true,
			chromeFlags: ['--disable-mobile-emulation', '--disable-storage-reset']
		}, config);

	const json = repGen.generateReport(testreport.lhr,'json'); 
	const html = repGen.generateReport(testreport.lhr,'html'); 
	
			
	Version details 
	Chrome 		: 79.0.3945.130 (64-bit) 
	lighthouse 	: 6.2.0
        NodeJs            : v12.18.3
	Puppeteer	: 5.2.1
	Chromium 	: r782078

### PR DESCRIPTION
**Pull request by connorjclark**
For some reason the `url` for script coverage is relative to the document. This messes up some assumptions downstream:

* for the unload listener https://github.com/GoogleChrome/lighthouse/issues/11261#issuecomment-678463987
* overlooking coverage for some js https://github.com/GoogleChrome/lighthouse/blob/e1a0bf08f071bc58ede7e0d5c61a6df1354d8b4d/lighthouse-core/audits/byte-efficiency/unused-javascript.js#L89

EDIT: the reason is because of magic `sourceURL` comments.

fixes #11261

### CODE REVIEW

**Comment by connorjclark** [comment]
Update: nothing to do with iframes or xhr. It's all because of `//# sourceURL=`. This overrides the actual network request url in `ScriptCoverage.url`. ex: normally the coverage object for an inline script uses html document for the url. but not if there's a sourceURL comment.

IMO there really should be a distinction in the protocol between network urls and the magic comment urls. This has already bit us [before](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/seo/font-size.js#L163).

**Comment by connorjclark** [comment]
in a gatherer, how might I turn a scriptId into a URL (if applicable)?

**Comment by patrickhulce** [comment]
> in a gatherer, how might I turn a scriptId into a URL (if applicable)?

AFAIK `Debugger.scriptParsed` *is* the way to get this, so if the URL it provides is not the real URL then we might be stuck. DevTools folks/@paulirish would know better though. 

I have this problem in DevTools where it's impossible to get back the non-sourcemap comment URL of what I'm looking at, so that leads me to believe it might be a limitation with the current protocol setup. I hope I'm wrong 🤞

**Comment by connorjclark** [comment]
> AFAIK Debugger.scriptParsed is the way to get this, so if the URL it provides is not the real URL then we might be stuck. DevTools folks/@paulirish would know better though.

yup, the `url` there is also overriden by magic url.

however, `embedderName` seems to be the "original" url ...

File: lighthouse-core/gather/gatherers/js-usage.js [hunk 1]
```diff
@@ -17,6 +17,10 @@ class JsUsage extends Gatherer {
   async beforePass(passContext) {
     await passContext.driver.sendCommand('Profiler.enable');
     await passContext.driver.sendCommand('Profiler.startPreciseCoverage', {detailed: false});
+
+    // passContext.driver.on('Debugger.scriptParsed', (e) => {
```
Comment (paulirish) [inline lighthouse-core/gather/gatherers/js-usage.js:21]: delete?

File: lighthouse-core/gather/gatherers/js-usage.js [hunk 2]
```diff
@@ -25,6 +29,11 @@ class JsUsage extends Gatherer {
    */
   async afterPass(passContext) {
     const driver = passContext.driver;
+    const finalUrl = passContext.baseArtifacts.URL.finalUrl;
+
+    const devtoolsLog = passContext.baseArtifacts.devtoolsLogs[passContext.passConfig.passName];
+
+    devtoolsLog[0]
```
Comment (paulirish) [inline lighthouse-core/gather/gatherers/js-usage.js:36]: sup

File: lighthouse-core/gather/gatherers/js-usage.js [hunk 3]
```diff
@@ -34,9 +43,23 @@ class JsUsage extends Gatherer {
     /** @type {Record<string, Array<LH.Crdp.Profiler.ScriptCoverage>>} */
     const usageByUrl = {};
     for (const scriptUsage of scriptUsages) {
-      const scripts = usageByUrl[scriptUsage.url] || [];
+      // ScriptCoverages without a URL are from code we run over the protocol.
```
Comment (paulirish) [inline lighthouse-core/gather/gatherers/js-usage.js:46]: I _think_ it's a little bigger than that. I presume url-less scripts are generally "anonymous scripts"..  
[Looking at the chromium source](https://source.chromium.org/chromium/chromium/src/+/master:v8/src/inspector/v8-profiler-agent-impl.cc;l=392-401;drc=fa3aada528577aab1ad9a282108e44bf318310bf).. yeah this appears to be any script that doesnt have a sourceURL or a resolvable URL.  and yeah that's anonymous. 

anon scripts include `eval()`, `new Function`, `onload="..."` etc. I guess the `Runtime.evaluate` payloads end up as anonymous too.

Anyway, anonymous scripts dont give us much attribution to report to the user. 
so i'm fine filtering them out.

can you tweak the comment to capture this? ^

File: lighthouse-core/gather/gatherers/js-usage.js [hunk 4]
```diff
@@ -34,9 +43,23 @@ class JsUsage extends Gatherer {
...
+      // `ScriptCoverage.url` can be overridden by a magic sourceURL comment.
+      // Lookup the url via the scriptId, if possible.
+      let scriptUsageUrl = scriptUsage.url;
+
+      // ...
+      // TODO how to map script id to url ...
+
+      // `scriptUsage.url` can sometimes be relative to the final url, so normalize to an absolute
+      // url by using the URL ctor.
+      const url = new URL(scriptUsageUrl, finalUrl).href;
```
Comment (paulirish) [inline lighthouse-core/gather/gatherers/js-usage.js:59]: i have a suspicion this baseUrl isn't what we want... we really want the URL of the frame that this script is executing in.

(being in a 3rd party iframe would mess this up)


this obv makes the implementation a bit more complicated. :(

**Comment by paulirish** [comment]
> have this problem in DevTools where it's impossible to get back the non-sourcemap comment URL

@patrickhulce you talking about sourceURL?  you talking about  this case?

```html
<body> 
  hi
  <script src="script.js"></script>
</body>
```

```js
console.log(' hello from script.js');
//# sourceURL=hahah-whoami-really.js
```

File: lighthouse-core/gather/gatherers/js-usage.js (hunk 4 above)
Comment (connorjclark) [reply lighthouse-core/gather/gatherers/js-usage.js:59]: I actually should remove this, its only relative when its essentially random user input.

**Comment by patrickhulce** [comment]
@paulirish yeah exactly, how on earth do I see where this file really came from? the real file doesn't show up at all in the sources pane and there's no annotation anywhere that this was from a sourceURL comment

http://melodic-class.glitch.me/devtools-source-url.html

image

**Comment by connorjclark** [comment]
@patrickhulce only way I found is to search for the filename in Search panel.

**Comment by connorjclark** [comment]
me:
> IMO there really should be a distinction in the protocol between network urls and the magic comment urls. This has already bit us before.

image


https://chromium-review.googlesource.com/c/v8/v8/+/2317310

:)

**Comment by paulirish** [comment]
> @paulirish yeah exactly, how on earth do I see where this file really came from?

yup. just did the same experiment (plus a few more)... devtools kinda sucks with how it handles a few of these cases. surprised they dont resolve relative sourceURLs against the "script origin". they should.

image





indeed `embedderName` looks like our solution.

screenshot from connor:
image (8)

sweet. and also this means we can use embedderName as the baseUrl.. and dont need to worry about the frame tree.  phew.

**Comment by connorjclark** [comment]
> sweet. and also this means we can use embedderName as the baseUrl.. and dont need to worry about the frame tree. phew.

Let's not apply the user-provided strings here at all. The unused-javascript audit is applying the key of this artifact to lookup a network record. We need the key (the url...) to be the network url.

File: lighthouse-core/gather/gatherers/js-usage.js [hunk 5]
```diff
@@ -11,6 +11,22 @@ const Gatherer = require('./gatherer.js');
...
+    /** @type {LH.Crdp.Debugger.ScriptParsedEvent[]} */
+    this._scriptParsedEvents = [];
+    this.onScriptParsed = this.onScriptParsed.bind(this);
+  }
+
+  /**
+   * @param {LH.Crdp.Debugger.ScriptParsedEvent} event
+   */
+  onScriptParsed(event) {
+    if (event.sourceMapURL) {
```
Comment (paulirish) [inline lighthouse-core/gather/gatherers/js-usage.js:25]: what does this have to do with anything?

File: lighthouse-core/gather/gatherers/js-usage.js [hunk 6]
```diff
@@ -11,6 +11,22 @@ const Gatherer = require('./gatherer.js');
...
+    super();
+    /** @type {LH.Crdp.Debugger.ScriptParsedEvent[]} */
+    this._scriptParsedEvents = [];
+    this.onScriptParsed = this.onScriptParsed.bind(this);
+  }
+
+  /**
+   * @param {LH.Crdp.Debugger.ScriptParsedEvent} event
+   */
+  onScriptParsed(event) {
```
Comment (paulirish) [inline lighthouse-core/gather/gatherers/js-usage.js:24]: you're missing a 

`    driver.on('Debugger.scriptParsed', this.onScriptParsed);`

**Comment by connorjclark** [comment]
> this seems inconsistent with our treatment of sourcemaps. :/

I agree, but resolving will require larger changes within unused-javascript (for one, making network record not necessary). And given it's just to give a better name for inline scripts using `sourceURL`, I'm not inclined to prioritize the work.

Thinking out loud, an easy resolution might be to replace the `url` in `unused-javascript` items with `JsUsage[realurl][0].url`, which should either be the real url or the `sourceURL` (`LinkValue` is probably better so we can link to the real url, and not end up with the same issues that exist in DevTools)

File: lighthouse-core/gather/gatherers/js-usage.js (hunk 6 above)
Comment (connorjclark) [reply lighthouse-core/gather/gatherers/js-usage.js:24]: thanks! I was just debugging why my test wasn't work and this comment was a blessing 🙏

File: lighthouse-core/gather/gatherers/js-usage.js (hunk 5 above)
Comment (connorjclark) [reply lighthouse-core/gather/gatherers/js-usage.js]: nada I copied from `source-maps`....

**Comment by paulirish** [comment]
> our treatment of sourcemaps

recapping.....

* `sourceURL` is a way to tell tools that the current script has a url, mostly it's used for improved debuggability on eval() or inline scripts. used cleverly, it can mimic sourcemaps... one of [webpack's many `devtool` settings](https://webpack.js.org/configuration/devtool/) uses sourceURL+eval.  (Oh and you can change a script's real URL to a fake one with sourceURL.)
* source maps tell tools that the current script is comprised of 1+ source files, and shows how. the URLs it includes in its `sources` property can be arbitrary too, so you could wreak similar kinds of havoc if you wanted to.

(fun fact: you can actually use both sourceURL and sourcemappingurl on the same anonymous script to give it identity and describe it's provenance) 

-----

for sourcemaps we use subitems to show how a generated/compiled/network source is comprised of its original mapped sources: 
image

and in #10930 we are showing mapped source locations instead of the generated/compiled/network location.
image


-------

> > this seems inconsistent with our treatment of sourcemaps. :/
> 
> I agree, but resolving will require larger changes within unused-javascript (for one, making network record not necessary). And given it's just to give a better name for inline scripts using `sourceURL`, I'm not inclined to prioritize the work.
> 
> Thinking out loud, an easy resolution might be to replace the `url` in `unused-javascript` items with `JsUsage[realurl][0].url`, which should either be the real url or the `sourceURL` (`LinkValue` is probably better so we can link to the real url, and not end up with the same discoverability issues that exist in DevTools)


K yeah. it sounds like we're mostly on the same page here then.

at first blush that resolution seems pretty good. i agree the complete solution is quite complicated and changes a lot of ways that we've been modeling scripts vs requests. i need some more time to noodle on the problem. and perhaps we can bring this discussion to the eng sync.

**Comment by connorjclark** [comment]
Made an issue: https://github.com/GoogleChrome/lighthouse/issues/11334

I think this particular PR could land, though. Keying these coverage data by the network url is the most natural thing to do here. I think any usage of urls from `sourceURL` comments should be done explicitly within the audits.

File: lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js [hunk 7]
```diff
@@ -116,7 +116,7 @@ const expectations = [
               },
               {
                 url: 'inline: \n  function unusedFunction() {\n    // Un...',
-                wastedBytes: '6581 +/- 100',
+                wastedBytes: '6700 +/- 100',
```
Comment (connorjclark) [inline lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js:119]: tiny lil' change because of the source url comment

File: lighthouse-core/gather/gatherers/js-usage.js (hunk 3 above)
Comment (connorjclark) [reply lighthouse-core/gather/gatherers/js-usage.js:54]: makes sense, and matches the ScriptParsedEvents I see from store.google.com.

I think we should go a bit further and also `continue` if `scriptParsedEvent.embedderName === ''`, at least for now. We don't have a way to use coverage data for anonymous functions in the audit anyway, so collecting is pointless atm, although i suppose it doesn't hurt .... wdyt?

File: lighthouse-core/gather/gatherers/js-usage.js [hunk 8]
```diff
@@ -11,12 +11,29 @@ const Gatherer = require('./gatherer.js');
...
+    }
+  }
+
   /**
    * @param {LH.Gatherer.PassContext} passContext
    */
   async beforePass(passContext) {
     await passContext.driver.sendCommand('Profiler.enable');
     await passContext.driver.sendCommand('Profiler.startPreciseCoverage', {detailed: false});
+    await passContext.driver.on('Debugger.scriptParsed', this.onScriptParsed);
```
Comment (patrickhulce) [inline lighthouse-core/gather/gatherers/js-usage.js:36]: send `Debugger.enable`? we're technically covered by driver always doing this, but feels good for clarity

File: lighthouse-core/test/gather/gatherers/js-usage-test.js [hunk 9]
```diff
@@ -0,0 +1,97 @@
...
+  it('uses ScriptParsedEvent embedderName over coverage data url', async () => {
+    const coverage = [{scriptId: '1', url: 'LOL WHAT'}];
+    const scriptParsedEvents = [{scriptId: '1', embedderName: 'https://www.example.com'}];
+    const artifact = await runJsUsage({coverage, scriptParsedEvents});
+    expect(artifact).toMatchInlineSnapshot(`
+      Object {
+        "https://www.example.com": Array [
+          Object {
+            "scriptId": "1",
+            "url": "LOL WHAT",
```
Comment (patrickhulce) [inline lighthouse-core/test/gather/gatherers/js-usage-test.js:91]: this is a somewhat confusing result, should we override here too and save this url under another property name?

thanks for these tests btw! :)

File: lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js [hunk 10]
```diff
@@ -147,7 +147,7 @@ const expectations = [
             // the specific ms value here is not meaningful for this smoketest
             // *some* savings should be reported
             overallSavingsMs: '>0',
-            overallSavingsBytes: '>=25000',
+            overallSavingsBytes: '35000 +/- 1000',
```
[the remark this answers is not in the document]
Comment (patrickhulce) [reply lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js:150]: WDYT about adding some assertions against the JsUsage artifact in smokes?

File: lighthouse-core/test/gather/gatherers/js-usage-test.js [hunk 11]
```diff
@@ -0,0 +1,97 @@
...
+    }
+    const connectionStub = new Connection();
+    connectionStub.sendCommand = sendCommandMock;
+    connectionStub.on = onMock;
+
+    const driver = new Driver(connectionStub);
+
+    const gatherer = new JsUsage();
+    await gatherer.beforePass({driver});
+    jest.advanceTimersByTime(1);
```
Comment (patrickhulce) [inline lighthouse-core/test/gather/gatherers/js-usage-test.js:50]: where are the timeouts coming from?

File: lighthouse-core/test/gather/gatherers/js-usage-test.js (hunk 9 above)
Comment (connorjclark) [reply lighthouse-core/test/gather/gatherers/js-usage-test.js:91]: We don't use that property anywhere. Maybe we should be mapping the `ScriptCoverage` instead of gathering the entire object. Do you want to modify this now or wait until it is needed?

File: lighthouse-core/test/gather/gatherers/js-usage-test.js (hunk 11 above)
Comment (connorjclark) [reply lighthouse-core/test/gather/gatherers/js-usage-test.js:50]: event callback doesnt happen in time without this

File: lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (connorjclark) [reply lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js:165]: done, like that?

File: lighthouse-core/test/gather/gatherers/js-usage-test.js (hunk 11 above)
Comment (patrickhulce) [reply lighthouse-core/test/gather/gatherers/js-usage-test.js:49]: ah the script parsed listeners! comment that? :)

File: lighthouse-core/test/gather/gatherers/js-usage-test.js (hunk 9 above)
Comment (patrickhulce) [reply lighthouse-core/test/gather/gatherers/js-usage-test.js:90]: Gotcha, I worry about the wrong value sitting there and getting accidentally used in the future instead of the key and we *definitely* won't notice it in *that* review, heh

maybe just change the type of this artifact to `Omit<Crdp.Profiler.ScriptCoverage, 'url'>` so no one accidentally uses it?

File: lighthouse-core/gather/gatherers/js-usage.js (hunk 3 above)
Comment (paulirish) [reply lighthouse-core/gather/gatherers/js-usage.js]: > I think we should go a bit further and also `continue` if `scriptParsedEvent.embedderName === ''`

yup sg

File: lighthouse-core/gather/gatherers/js-usage.js [hunk 12]
```diff
@@ -34,9 +51,22 @@ class JsUsage extends Gatherer {
     /** @type {Record<string, Array<LH.Crdp.Profiler.ScriptCoverage>>} */
     const usageByUrl = {};
     for (const scriptUsage of scriptUsages) {
-      const scripts = usageByUrl[scriptUsage.url] || [];
+      // ScriptCoverages without a URL are from code we run over the protocol.
+      // We shouldn't analyze ourselves, so skip.
+      if (scriptUsage.url === '') continue;
+
+      // `ScriptCoverage.url` can be overridden by a magic sourceURL comment.
+      // Get the associated ScriptParsedEvent and use embedderName, which is the original url.
```
Comment (paulirish) [inline lighthouse-core/gather/gatherers/js-usage.js:59]: can you describe embeddername a tad more and link up the CL that added it?

Comment (connorjclark) [reply lighthouse-core/gather/gatherers/js-usage.js:59]: Added a link but...what more is there to say?

File: lighthouse-core/test/gather/gatherers/js-usage-test.js (hunk 9 above)
Comment (connorjclark) [reply lighthouse-core/test/gather/gatherers/js-usage-test.js:90]: oops, actually no-unload-listeners uses it. easy fix tho.

File: lighthouse-core/gather/gatherers/js-usage.js (hunk 12 above)
Comment (paulirish) [reply lighthouse-core/gather/gatherers/js-usage.js:59]: sure that's fine
