### PR TITLE
fix: responsive image audits for vectors and duplicates

### LINKED ISSUE #1747: Responsive images: don't warn about vectors
Vector sizing can be tricky to determine what's actually "waste", we should just ignore for now.

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #1747 and #1748

### CODE REVIEW

File: lighthouse-core/audits/byte-efficiency/uses-responsive-images.js [hunk 1]
```diff
@@ -90,29 +87,32 @@ class UsesResponsiveImages extends Audit {
...
     const DPR = contentWidth.devicePixelRatio;
-    const results = images.reduce((results, image) => {
-      if (!image.networkRecord) {
+    const resultsMap = images.reduce((results, image) => {
+      if (!image.networkRecord || image.networkRecord.mimeType === 'image/svg+xml') {
         return results;
       }
 
       const processed = UsesResponsiveImages.computeWaste(image, DPR);
-      if (!processed) {
```
Comment (ebidel) [inline lighthouse-core/audits/byte-efficiency/uses-responsive-images.js]: we don't need the `null` check anymore?

Comment (patrickhulce) [inline lighthouse-core/audits/byte-efficiency/uses-responsive-images.js]: correct, it will either throw or return an object now
