### PR TITLE
core(uses-long-cache-ttl): ignore private, must-validate, no-cache

### LINKED ISSUE #6140: Third-party Google Assets don't follow their own audit rules, causing report errors
When I run lighthouse reports, my only errors and warnings come from assets delivered by the creator of lighthouse: Google.

Specifically, this warning/error shows up.

## Uses inefficient cache policy on static assets
*All* the items in this report come from 
  * `securepubads.g.doubleclick.net` (google property).
  * `googletagmanager.com` (google property)
  * `pagead2.googlesyndication.com` (google property)
  * `www.google-analytics.com` (google property)
  * `tpc.googlesyndication.com` (google property)

Why does Google serve assets that fail to follow their own recommendations as based on lighthouse?  If they recommend static assets be sent with proper caching headers, why doesn't google follow through with that? Some of their assets have a ttl of *0* or *15m*!

If they aren't going to follow their own recommendations, then it seems that lighthouse should exclude their own domains from this analysis, since it creates a bunch of false positives which I can do nothing about.

### PR DESCRIPTION
**Pull request by Hoten**
Fixes #6140.

### CODE REVIEW

File: lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js [hunk 1]
```diff
@@ -103,11 +103,10 @@ describe('Cache headers audit', () => {
 
     const networkRecords = [
       networkRecord({headers: {
-        'cache-control': 'must-revalidate,max-age=3600',
```
Comment (patrickhulce) [inline lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js]: can we come up with a different directive to stick in here to make sure we parse properly :)

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js [hunk 2]
```diff
@@ -202,6 +202,12 @@ class CacheHeaders extends Audit {
           cacheControl
         );
 
+        // Ignore assets where policy implies they should not be cached long periods
+        if (cacheControl &&
+          (cacheControl['must-validate'] || cacheControl['no-cache'] || cacheControl['private'])) {
```
Comment (patrickhulce) [inline lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: Can we figure out how to consolidate some of this with the logic in `computeCacheLifetimeInSeconds` in L115? right now these type of checks are in there to return a lifetime of `0`

Comment (Hoten) [reply lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: maybe? these cache controls could still have ttls, so it'd make `computeCacheLifetimeInSeconds` a bit of a liar. I get that if we have this method return 0 for all cases we want to ignore, things work. which is cool, I'm just arguing semantics I suppose.

File: lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js (hunk 1 above)
Comment (Hoten) [reply lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js]: ya

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js (hunk 2 above)
Comment (patrickhulce) [reply lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: it doesn't have to be moving this there, we can extract the L115 part too (and probably should it's not the most obvious right now). I'm just advocating for collecting the special cases we handle so it's clear what's going on.

Comment (Hoten) [reply lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: Done. How's that?

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js [hunk 3]
```diff
@@ -218,7 +238,9 @@ class CacheHeaders extends Audit {
 
         results.push({
           url,
-          cacheControl,
+          // Include cacheControl in results, but cast as any so table types
+          // are happy. cacheControl is not shown in the table so this is OK.
+          cacheControl: /** @type {any} */ (cacheControl),
```
Comment (Hoten) [inline lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: thoughts?

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js [hunk 4]
```diff
@@ -169,6 +160,36 @@ class CacheHeaders extends Audit {
...
+        cacheControl['must-validate'] ||
+        cacheControl['no-cache'] ||
+        cacheControl['no-store'] ||
+        cacheControl['private'])) {
+      return false;
+    }
+
+    if (cacheLifetimeInSeconds !== null && cacheLifetimeInSeconds <= 0) return false;
+
+    if (cacheHitProbability > IGNORE_THRESHOLD_IN_PERCENT) return false;
```
Comment (patrickhulce) [inline lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: I'm wondering if we should just move the `cacheHitProbability` calculation to after this `shouldProcessRecord` and switch the ignore threshold to the equivalent time.

That might make it easier to figure out what's going on....

Comment (Hoten) [reply lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: > switch the ignore threshold to the equivalent time

I don't understand what you mean by this.

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js (hunk 3 above)
Comment (Hoten) [reply lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: summoning @brendankenny

File: lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js [hunk 5]
```diff
@@ -74,6 +74,22 @@ describe('Cache headers audit', () => {
     });
   });
 
+  it('ignores nonpositive and nonfinite max-age headers', () => {
+    const infinityMaxAgeStringValue = '1'.repeat(400);
+    assert.equal(Number.parseInt(infinityMaxAgeStringValue), Infinity);
+    const networkRecords = [
```
Comment (Hoten) [inline lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js]: so, we wish to ignore all of these records right?

FYI `max-age=blahblah` would not be ignored.

Shouldn't something silly like `max-age=-anything` be surfaced? or is that out of scope for this audit

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js (hunk 4 above)
Comment (patrickhulce) [reply lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: cacheLifetimeInSeconds gets converted into a cacheHitProbability

instead of ignoring records with a `cacheHitProbability` above 92.5% what if we ignored records with `cacheLifetimeInSeconds` above 2 weeks (should be the equivalent of 92.5%)

File: lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js (hunk 5 above)
Comment (patrickhulce) [reply lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js]: what did the spec say for cacheControl? for `expires` it was anything invalid is treated as no cache lifetime, so if cache-control is the same we should probably surface them as having no caching?

**Comment by brendankenny** [comment]
Would really love a PR summary on things like this where parsing the conversation in the original issue takes way too long :P

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js (hunk 3 above)
Comment (brendankenny) [reply lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: > cacheControl is not shown in the table so this is OK.

It's not ok, why use a table if you don't want it to be a table, but it's not your fault that you're inheriting this :)

Will you add a `TODO(bckenny): fix DetailsItem` to the comment?

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js (hunk 4 above)
Comment (patrickhulce) [reply lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: > I could be making an opposite suggestion to what @patrickhulce has suggested before, but to me there are two different sets of checks in here:

I didn't do a great job of clearly saying what I was lookin for before (sorry @Hoten !!) so it certainly could have been interpreted as opposite to that :)

My primary concern is not sprinkling around the different cases where things get ignored for the same category of reason, before this we checked `private` somewhere different from `no-cache` which are both ignored because of the signal in the `cache-control` directive.

I think it's relatively difficult to segment `shouldProcessRecord` and `computeCacheLifetime` as cleanly as you've done in that example @brendankenny  because there are some interdependencies, but if everyone's happy with some duplicated logic and think it's easy to read, I'm onboard.

IMO the fact that we're dealing with some mixture of `pragma`, `expires`, and `cache-control` all at the same time also complicates this, but I guess those two other cases are pretty simple.

Comment (Hoten) [reply lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: understood. I ran a bit too much with the idea of only using one `continue` ;)

**Comment by Hoten** [comment]
anything more?

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js [hunk 6]
```diff
@@ -169,6 +160,30 @@ class CacheHeaders extends Audit {
     );
   }
 
+  /**
+   * @param {Map<string, string>} headers
```
Comment (brendankenny) [inline lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: can you add a jsdoc description to this? Don't want to be redundant with the comments below, just a general category for what would disqualify a record

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js [hunk 7]
```diff
@@ -169,6 +160,30 @@ class CacheHeaders extends Audit {
...
+   * @param {ReturnType<typeof parseCacheControl>} cacheControl
+   * @returns {boolean}
+   */
+  static shouldProcessRecord(headers, cacheControl) {
```
Comment (brendankenny) [inline lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: should we rename `shouldSkipRecord` or something since it's only used negated?

File: lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js [hunk 8]
```diff
@@ -197,15 +212,20 @@ class CacheHeaders extends Audit {
...
-          headers,
-          cacheControl
-        );
+        if (!this.shouldProcessRecord(headers, cacheControl)) {
+          continue;
+        }
 
-        // Ignore assets with an explicit no-cache policy
-        if (cacheLifetimeInSeconds === 0) continue;
+        // Ignore if cacheLifetimeInSeconds is defined and a nonpositive number.
```
Comment (brendankenny) [inline lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js]: the `is defined` throws me for a loop when reading this. `Ignore if cacheLifetimeInSeconds is a nonpositive number` seems sufficient and is still a true description :)
