### PR TITLE
tests(smokehouse): adjust byte efficiency CPU multiplier

### LINKED ISSUE #4808: Byte-efficiency smoketests fail on appveyor
since moving to lantern for byte-efficiency savings estimates the smoketests are failin on appveyor. It's  not a canary v. stable issues since they all pass locally and on travis. 

My current guess is that because appveyor is astronomically slower than travis/local, the CPU tasks x4 are waaaaaay longer than expected and the savings from any network just gets washed out.

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #4808

### CODE REVIEW

File: lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js [hunk 1]
```diff
@@ -136,6 +136,8 @@ class UnusedBytes extends Audit {
    */
   static createAuditResult(result, graph) {
     const simulatorOptions = PredictivePerf.computeRTTAndServerResponseTime(graph);
+    // TODO: calibrate multipliers, see https://github.com/GoogleChrome/lighthouse/issues/820
+    Object.assign(simulatorOptions, {cpuTaskMultiplier: 1, layoutTaskMultiplier: 1});
```
Comment (paulirish) [inline lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js]: why reset these multipliers to 1 rather than their defaults?

Comment (patrickhulce) [reply lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js]: well in our pre-lantern case the throttling is usually being applied by devtools, so pumping it through another 4x multiplier is sorta unfair. This shouldn't really matter once #4766 and follow-ups land

Comment (paulirish) [reply lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js]: aye true. k.
