### PR TITLE
Checks for HTTPS redirect

### LINKED ISSUE #263: Audit: http -> https redirect in place
Something we see some sites fail at is redirecting Chrome users to HTTPS. Would be good to make sure we audit for this.

### PR DESCRIPTION
**Pull request by paullewis**
A bunch of things:

1. Requires that #267 lands first, because it needs the Security domain enabled.
2. It's a bit ick insofar as it has to clear the backlog of Security events, so there's a fairly bleh timeout that waits up to 3 seconds to make sure we've got all the security events back.
3. It's not clear about whether we want to just trust `schemeIsCryptographic` or if we want to push on the security level to be 'secure' (which it doesn't seem to be in a bunch of cases, though why is unclear!).
4. This also includes an additional round-trip to `about:blank` and then to the HTTP version of the URL. You can't XHR the HTTP version because it triggers the Mixed Content warnings and is blocked by Chrome. We have baked in the second round trip to the scheduler to test the SW, so either we need to do the same thing here, or maybe we don't and it's just fine... One for us to discuss, but we should be consistent.

Also, fixes #263.

### CODE REVIEW

File: src/gatherers/http-redirect.js [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+    };
+  }
+
+  afterReloadPageLoad(options) {
+    const driver = options.driver;
+    const url = options.url;
+    const httpURL = options.url.replace(/^https/, 'http');
+
+    // If the URL hasn't changed then the origin URL was HTTP.
+    if (httpURL === url) {
```
Comment (paulirish) [inline src/gatherers/http-redirect.js]: options.url is the original url. 
so if there was a redirect on an original HTTP url, it's still gonna be HTTP. 
Not sure we have a readily accessible property which is "what is the current URL of the target?" that you'd want to use here.

running `lighthouse http://pwa.rocks" ends up with a "undefined" result for the audit.

Comment (paullewis) [inline src/gatherers/http-redirect.js]: Okay, so drop this check?

Comment (paullewis) [inline src/gatherers/http-redirect.js]: Yeah the problem is I didn't wrap this as an object with a value prop. Fixed.

File: src/gatherers/http-redirect.js [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+'use strict';
+
+const Gather = require('./gather');
+
+class HTTPRedirect extends Gather {
+
+  static _error(errorString) {
+    return {
+      redirectsHTTP: {
+        raw: undefined,
```
Comment (brendankenny) [inline src/gatherers/http-redirect.js]: why `raw` here?

**Comment by brendankenny** [comment]
It would be nice to just observe the navigation as it goes. With a supplied http url, that's easy, we can just watch the url change as the first navigation happens. For a supplied https url, it seems like there's no way around an additional navigation, but it feels like there should be :) We really just want to curl and see if it redirects, not sure why this is so hard

**Comment by brendankenny** [comment]
I think the redirect should definitely live in the scheduler. It's icky as you say, but that's no excuse to hide our mess :)

File: src/gatherers/http-redirect.js (hunk 1 above)
Comment (paulirish) [inline src/gatherers/http-redirect.js]: I'd drop this check. Let's not assume a redirect happened because we started with an http URL to begin with. (because of HSTS, etc)

We dont' want our pageload metrics to include a redirect (for now). So i'd prefer we don't encourage starting with http urls.

File: src/gatherers/http-redirect.js [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+      };
+
+      return Promise.resolve();
+    }
+
+    return new Promise((resolve, reject) => {
+      let securityStateChangedTimeout;
+      let noSecurityChangesTimeout;
+
+      driver.on('Security.securityStateChanged', data => {
```
Comment (brendankenny) [inline src/gatherers/http-redirect.js]: need to remove listener when you're finished

**Comment by paulirish** [comment]
I thought we could clean up the event listening dance by disabling the security domain and turning it on just to catch state.
Checked with Pavel and this is totally legit.

I have a PR against lewis's branch that introduces this little guy:
image

The PR: https://github.com/paullewis/lighthouse/pull/3

**Comment by paulirish** [comment]
> I think the redirect should definitely live in the scheduler

I have to agree, unfortunately. It's kind of hidden that the page now does 3 reloads, but it does.

**Comment by paullewis** [comment]
Yeah I'm fine with that. I think we should do a couple of things here:

- Warn if the URL has no protocol or the protocol is http:// (where exactly we do that is up for grabs)
- Move the reload to the scheduler

Thoughts?

File: src/gatherers/http-redirect.js (hunk 1 above)
Comment (paullewis) [inline src/gatherers/http-redirect.js]: Done. Added a warning.

File: src/gatherers/http-redirect.js (hunk 2 above)
Comment (paullewis) [inline src/gatherers/http-redirect.js]: Done.

**Comment by paullewis** [comment]
Okay, all feedback addressed. PTAL.

File: cli/index.js [hunk 4]
```diff
@@ -53,6 +53,12 @@ const outputMode = cli.flags.output || 'pretty';
 const outputPath = cli.flags.outputPath || 'stdout';
 const flags = cli.flags;
 
+// If the URL isn't https or localhost complain to the user.
+if (url.indexOf('https') !== 0 && url.indexOf('localhost') === -1) {
```
Comment (brendankenny) [inline cli/index.js]: obviously a corner case, but probably want to check for `localhost` only in the `hostname`

Comment (paullewis) [inline cli/index.js]: Bleh that involves parsing it... I could do `url.indexOf('http://localhost')`

Comment (paullewis) [inline cli/index.js]: Done.

File: src/lib/drivers/driver.js [hunk 5]
```diff
@@ -140,6 +140,17 @@ class DriverBase {
     });
   }
 
+  getSecurityState() {
+    return new Promise((resolve, _) => {
```
Comment (brendankenny) [inline src/lib/drivers/driver.js]: s/_/reject just because that's what we usually use

File: src/gatherers/http-redirect.js [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+        debugString: errorString
+      }
+    };
+  }
+
+  constructor() {
+    super();
+    this._resolved = false;
+    this._artifactsResolved = undefined;
+    this._onSecurityStateChanged = undefined;
```
Comment (brendankenny) [inline src/gatherers/http-redirect.js]: no longer used

Comment (brendankenny) [inline src/gatherers/http-redirect.js]: actually, all three of the above don't appear to be used?

File: src/gatherers/http-redirect.js [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+'use strict';
+
+const Gather = require('./gather');
+
+class HTTPRedirect extends Gather {
+
+  static _error(errorString) {
```
Comment (brendankenny) [inline src/gatherers/http-redirect.js]: not used anymore

File: src/gatherers/http-redirect.js (hunk 6 above)
Comment (paullewis) [inline src/gatherers/http-redirect.js]: Done.

File: src/gatherers/http-redirect.js (hunk 7 above)
Comment (paullewis) [inline src/gatherers/http-redirect.js]: Done.

File: src/lib/drivers/driver.js (hunk 5 above)
Comment (paullewis) [inline src/lib/drivers/driver.js]: Done.

**Comment by brendankenny** [comment]
LGTM! 🔀🔐🔍 obvs @paulirish should take a look

File: cli/index.js [hunk 8]
```diff
@@ -53,6 +53,12 @@ const outputMode = cli.flags.output || 'pretty';
 const outputPath = cli.flags.outputPath || 'stdout';
 const flags = cli.flags;
 
+// If the URL isn't https or localhost complain to the user.
+if (url.indexOf('https') !== 0 && url.indexOf('http://localhost') !== 0) {
+  log.warn('Lighthouse', 'The URL provided should be on HTTPS');
+  log.warn('Lighthouse', 'Performance stats will be skewed redirecting from HTTP to HTTPS.');
```
Comment (paulirish) [inline cli/index.js]: what a beauty.

**Comment by paulirish** [comment]
This came out looking great. Nice work, @paullewis
