### PR TITLE
misc: refactor collect-strings.js to use glob and work on windows

### LINKED ISSUE #9403: `yarn update:sample-json` doesn't work on windows.
~~`assert-golden-lhr-unchanged.sh` is not OS-independent.~~

This blocks most contributions from developers using Windows.

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #9403.

### CODE REVIEW

File: lighthouse-core/scripts/i18n/collect-strings.js [hunk 1]
```diff
@@ -22,10 +22,10 @@ const UISTRINGS_REGEX = /UIStrings = (.|\s)*?\};\n/im;
...
 
 const ignoredPathComponents = [
-  '/.git',
-  '/scripts',
-  '/node_modules',
-  '/test/',
+  `${path.sep}.git`,
+  `${path.sep}scripts`,
+  `${path.sep}node_modules`,
+  `${path.sep}test${path.sep}`,
```
Comment (connorjclark) [inline lighthouse-core/scripts/i18n/collect-strings.js]: i kinda hate this, wb this instead

```
[
  '/.git',
  '/scripts',
  '/node_modules',
  '/test/',
  '-test.js',
  '-renderer.js',
].map(str => str.replace(/\//g, path.sep));
```

Comment (exterkamp) [reply lighthouse-core/scripts/i18n/collect-strings.js]: Meh, this seems even more obtuse imo.

File: lighthouse-core/scripts/i18n/collect-strings.js [hunk 2]
```diff
@@ -86,7 +86,10 @@ function collectAllStringsInDir(dir, strings = {}) {
             const key = property.key.name;
             const message = exportVars.UIStrings[key];
             const description = computeDescription(ast, property, lastPropertyEndIndex);
-            strings[`${relativePath} | ${key}`] = {message, description};
+            const pathKey = relativePath
+              // Windows compat.
```
Comment (patrickhulce) [inline lighthouse-core/scripts/i18n/collect-strings.js]:
```suggestion
              // Replace Windows path separators with unix path separators for Windows compat.
```

File: lighthouse-core/scripts/i18n/collect-strings.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-core/scripts/i18n/collect-strings.js]: I actually like that @connorjclark, the readability of the paths is the important thing IMO, the fact that we want to support multiple OS is the secondary concern, maybe just add the 

`// Ensure we use the OS-specific path separator` comment to the map line?

**Comment by brendankenny** [comment]
sooooo...what if we just switched to using `glob` (already in our devDeps)? Handling OS-specific file stuff, searching for `*.js` files unless they match this set of patterns, and recursive subdirectory search are all included out of the box

**Comment by paulirish** [comment]
> sooooo...what if we just switched to using glob

+1. I was kinda surprised to see us doing recursive directory descent ourselves. 

i guess it'd be something a la

```js
glob.sync("**/*.js", {
	ignore: ignoredPathComponents
}, fn);
```

though we could also read in our .gitignore and give that to ignore. Would take care of most of these.

**Comment by brendankenny** [comment]
`cwd` would also need to be set to `dir`, and setting `root` to `LH_ROOT` should give the `relativePath` for free (which should be normalized to posix `/`)

**Comment by brendankenny** [comment]
running `yarn i18n:checks` in appveyor would keep this from regressing on windows, but that involves making `assert-strings-collected.sh` work cross platform, so that's maybe something for the back burner :)

**Comment by connorjclark** [comment]
Updated. Will have to continue when I'm on a windows machine again. But:

1) `ignore` doesn't seem to work.
2) I don't see any affect using `root` when `cwd` is also used.

File: lighthouse-core/scripts/i18n/collect-strings.js [hunk 3]
```diff
@@ -44,52 +45,59 @@ function computeDescription(ast, property, startRange) {
...
-          }
-        }
+function collectAllStringsInDir(dir) {
+  /** @type {Record<string, ICUMessageDefn>} */
+  const strings = {};
+
+  const files = glob.sync('**/*.js', {
+    cwd: dir,
+    // TODO: why doesn't this work ...
+    // ignore: ignoredPathComponents,
```
Comment (patrickhulce) [inline lighthouse-core/scripts/i18n/collect-strings.js]: probably because our ignored patterns aren't globs yet :)

**Comment by brendankenny** [comment]
> I don't see any affect using root when cwd is also used.

whoops, root is not what we want, never mind! :)

**Comment by brendankenny** [comment]
> whoops, `root` is not what we want, never mind! :)

I think you actually want something like

`glob.sync(path.posix.relative(LH_ROOT, dir) + '/**/*.js', {cwd: LH_ROOT, ignore: ignoreGlobs})`

`posix` is important so it does the separators right (glob only takes `/`), and it needs to be relative (and not just `${dir}/**/*.js`) so that it doesn't give absolute paths.

Maybe there's a better way, though.

**Comment by connorjclark** [comment]
weeeee working now. Still need to test on windows.

**Comment by connorjclark** [comment]
working in windows now.

the `posix` thing had to go. It was giving me this in windows:

```
path.posix.relative(LH_ROOT, dir)
=> ../C:\Users\Connor\code\lighthouse\lighthouse-core
```

File: lighthouse-core/lib/i18n/locales/en-XL.json [hunk 4]
```diff
@@ -1348,5 +1348,47 @@
   },
   "lighthouse-core/report/html/renderer/util.js | warningHeader": {
     "message": "Ŵár̂ńîńĝś: "
+  },
+  "stack-packs/packs/wordpress.js | efficient_animated_content": {
```
Comment (connorjclark) [inline lighthouse-core/lib/i18n/locales/en-XL.json]: These weren't being collected for en-XL before.

File: lighthouse-core/scripts/i18n/collect-strings.js [hunk 5]
```diff
@@ -44,52 +45,51 @@ function computeDescription(ast, property, startRange) {
...
-            const description = computeDescription(ast, property, lastPropertyEndIndex);
-            strings[`${relativePath} | ${key}`] = {message, description};
-            lastPropertyEndIndex = property.range[1];
-          }
-        }
+function collectAllStringsInDir(dir) {
+  /** @type {Record<string, ICUMessageDefn>} */
+  const strings = {};
+
+  const files = glob.sync(path.relative(LH_ROOT, dir) + '/**/*.js', {
```
Comment (patrickhulce) [inline lighthouse-core/scripts/i18n/collect-strings.js]: comment about glob only accepting `/`? I'm surprised that `path.relative` works on windows for this since it's going to have slashes going the wrong way....

Comment (connorjclark) [reply lighthouse-core/scripts/i18n/collect-strings.js]: Evidently, glob doesn't only accept `/`. and I guess it does allow for mixed - path separators. I wonder if any comment at all would be more confusing than no comment :P

Comment (patrickhulce) [reply lighthouse-core/scripts/i18n/collect-strings.js]: Are we 100% positive it's working as expected...

https://github.com/isaacs/node-glob#windows is so convincing that only `/` works! 😆

Comment (connorjclark) [reply lighthouse-core/scripts/i18n/collect-strings.js]: is `node-glob` === `glob`?

Comment (connorjclark) [reply lighthouse-core/scripts/i18n/collect-strings.js]: anyway, I have empirical evidence that it work .... on my one Windows machine ;) Running collect strings resulted in no unstaged changes. Got all the expected output.

Comment (patrickhulce) [reply lighthouse-core/scripts/i18n/collect-strings.js]: > is node-glob === glob

[Yep](https://www.npmjs.com/package/glob#windows) :)

Just makes me nervous...

File: lighthouse-core/scripts/i18n/collect-strings.js [hunk 6]
```diff
@@ -44,52 +45,51 @@ function computeDescription(ast, property, startRange) {
 
 /**
  * @param {string} dir
- * @param {Record<string, ICUMessageDefn>} strings
+ * @return {Record<string, ICUMessageDefn>}
```
Comment (brendankenny) [inline lighthouse-core/scripts/i18n/collect-strings.js]: can you revert the changes to the param/return type (here and for `createPsuedoLocaleStrings`) so it's only an internal change? the changes are fine, but it's going to make updating #9114 that much more work after this lands

File: lighthouse-core/scripts/i18n/collect-strings.js (hunk 5 above)
Comment (brendankenny) [reply lighthouse-core/scripts/i18n/collect-strings.js]: apparently this is a whole thing: https://github.com/isaacs/minimatch/pull/109, https://github.com/isaacs/node-glob/issues/212 🤷‍♂

File: lighthouse-core/scripts/i18n/collect-strings.js (hunk 6 above)
Comment (connorjclark) [reply lighthouse-core/scripts/i18n/collect-strings.js]: let's just chill this until after placeholders land

File: lighthouse-core/scripts/i18n/collect-strings.js (hunk 5 above)
Comment (connorjclark) [reply lighthouse-core/scripts/i18n/collect-strings.js]: aight, passing these to path.join normalizes to the OS's file sep.

Comment (patrickhulce) [reply lighthouse-core/scripts/i18n/collect-strings.js]: Which despite what the docs of node-glob state, it does seem to then convert to `/`

https://github.com/isaacs/node-glob/blob/e3fe170d9156e7c444a57b44a9e45e46c66f2dbf/glob.js#L701-L702

AFAICT :)

**Comment by connorjclark** [comment]
@exterkamp oh no i didn't realize how much this would conflict oh god

**Comment by connorjclark** [comment]
ready to gogogo

File: lighthouse-core/scripts/i18n/collect-strings.js [hunk 7]
```diff
@@ -382,82 +379,77 @@ const seenStrings = new Map();
...
+function collectAllStringsInDir(dir) {
+  /** @type {Record<string, ICUMessageDefn>} */
+  const strings = {};
 
+  const globPattern = path.join(path.relative(LH_ROOT, dir), '/**/*.js');
+  const files = glob.sync(globPattern, {
+    cwd: LH_ROOT,
+    ignore: ignoredPathComponents,
+  });
+  for (const relativePathToRoot of files) {
```
Comment (patrickhulce) [inline lighthouse-core/scripts/i18n/collect-strings.js]:
```suggestion
  for (const relativePathFromRoot of files) {
```

Comment (patrickhulce) [reply lighthouse-core/scripts/i18n/collect-strings.js]: or filePathRelativeToRoot? :)

**Comment by connorjclark** [comment]
> I believe you have the approvals @connorjclark were you wanting a re-review? :)

well it was 10PM and I just did a weird merge. wanted @exterkamp to stamp

File: lighthouse-core/scripts/i18n/collect-strings.js (hunk 7 above)
Comment (connorjclark) [reply lighthouse-core/scripts/i18n/collect-strings.js]: `relativeToRootPath` to match `absolutePath`.

File: lighthouse-core/scripts/i18n/collect-strings.js [hunk 8]
```diff
@@ -113,13 +113,9 @@ function convertMessageToCtc(message, examples = {}) {
 
   // Process each placeholder type
   _processPlaceholderMarkdownCode(icuDefn);
-
   _processPlaceholderMarkdownLink(icuDefn);
-
   _processPlaceholderCustomFormattedIcu(icuDefn);
-
   _processPlaceholderDirectIcu(icuDefn, examples);
-
```
Comment (brendankenny) [inline lighthouse-core/scripts/i18n/collect-strings.js]: Whitespace like this come down to author preference and should really be discussed in the original PR rather than changed in the next commit (inviting style edit wars). Presumably @exterkamp preferred it and no one brought it up in the review, so unless there's a reason to change it, the default move should be to leave it unchanged.

File: lighthouse-core/scripts/i18n/collect-strings.js [hunk 9]
```diff
@@ -382,82 +379,77 @@ const seenStrings = new Map();
 let collisions = 0;
 
 /**
- * @param {string} dir
- * @param {Record<string, ICUMessageDefn>} strings
+ * @param {string} dir absolute path
```
Comment (exterkamp) [inline lighthouse-core/scripts/i18n/collect-strings.js]: Comment on this, something like
```
 * Collects all lhl messsages defined in UIString vars from within Javascript files located in dir, 
 * and converts them into ctc format.
```

File: lighthouse-core/scripts/i18n/collect-strings.js [hunk 10]
```diff
@@ -382,82 +379,77 @@ const seenStrings = new Map();
...
+ * @return {Record<string, ICUMessageDefn>}
```
Comment (exterkamp) [inline lighthouse-core/scripts/i18n/collect-strings.js]: Good idea with the returning, I like this better!

File: lighthouse-core/scripts/i18n/collect-strings.js [hunk 11]
```diff
@@ -382,82 +379,77 @@ const seenStrings = new Map();
...
+        // check for duplicates, if duplicate, add @description as @meaning to both
+        if (seenStrings.has(icuDefn.message)) {
+          icuDefn.meaning = icuDefn.description;
+          const seenId = seenStrings.get(icuDefn.message);
+          if (seenId) {
+            if (!strings[seenId].meaning) {
+              strings[seenId].meaning = strings[seenId].description;
+              collisions++;
+            }
+            collisions++;
```
Comment (exterkamp) [inline lighthouse-core/scripts/i18n/collect-strings.js]: +1 to @paulirish for keeping this global so this isn't a problem :smile:

File: lighthouse-core/scripts/i18n/collect-strings.js (hunk 8 above)
Comment (connorjclark) [reply lighthouse-core/scripts/i18n/collect-strings.js]: ok sorry bud

File: lighthouse-core/scripts/i18n/collect-strings.js (hunk 11 above)
Comment (connorjclark) [reply lighthouse-core/scripts/i18n/collect-strings.js]: sorry i have no idea what your comment is referencing but this line of code looks like i screwed up a merge?

is it supposed to double count collisions

Comment (connorjclark) [reply lighthouse-core/scripts/i18n/collect-strings.js]: nvm looks good

**Comment by connorjclark** [comment]
> Didn't test on Windows on the latest iteration, but I did before and it was good, and I will again later today.

i tested it already btw.

mergin'
