### PR TITLE
core(image-elements): gather correct natural size for srcset

### LINKED ISSUE #11095: Image resolution test doesn't detect resolution of Jetpack image CDN images
#### Provide the steps to reproduce
1. Run LH on https://brentlogan.com/
  
#### What is the current behavior?
First large image is served with the following html

~~~html
<img src="https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?fit=2400%2C1800&amp;ssl=1" width="2400" height="1800" data-src="https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?fit=2400%2C1800&amp;ssl=1" class="attachment-medium_large size-medium_large lazyloaded" alt="Wheat" data-srcset="https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?w=2400&amp;ssl=1 2400w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=600%2C450&amp;ssl=1 600w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=1024%2C768&amp;ssl=1 1024w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=1536%2C1152&amp;ssl=1 1536w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=2048%2C1536&amp;ssl=1 2048w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=1200%2C900&amp;ssl=1 1200w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=1320%2C990&amp;ssl=1 1320w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?w=1680&amp;ssl=1 1680w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 1362px) 62vw, 840px" srcset="https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?w=2400&amp;ssl=1 2400w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=600%2C450&amp;ssl=1 600w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=1024%2C768&amp;ssl=1 1024w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=1536%2C1152&amp;ssl=1 1536w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=2048%2C1536&amp;ssl=1 2048w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=1200%2C900&amp;ssl=1 1200w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?resize=1320%2C990&amp;ssl=1 1320w, https://i2.wp.com/brentlogan.com/wp-content/uploads/2020/07/IMG_20200710_185612.jpg?w=1680&amp;ssl=1 1680w" style="">
~~~

LH yields the following results

Brent_Logan

#### What is the expected behavior?
LH detects the high-resolution image

#### Environment Information
* Affected Channels: Chrome dev tools
* Lighthouse version: Lighthouse 6.1.0
* Chrome version: Version 86.0.4201.0 (Official Build) canary (64-bit)
* Node.js version: N/A
* Operating System: macOS Version 10.15.5 (19F101)

**Related issues**

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
We weren't collecting the correct `naturalWidth`/`naturalHeight` for images that use `srcset`. Added a smoketest for this and other `image-size-responsive` cases to the byte efficiency tester.

**Related Issues/PRs**
fixes #11095

### CODE REVIEW

File: lighthouse-core/audits/byte-efficiency/uses-responsive-images.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ const UIStrings = {
 
 const str_ = i18n.createMessageInstanceIdFn(__filename, UIStrings);
 
-const IGNORE_THRESHOLD_IN_BYTES = 2048;
+const IGNORE_THRESHOLD_IN_BYTES = 4096;
```
Comment (patrickhulce) [inline lighthouse-core/audits/byte-efficiency/uses-responsive-images.js:33]: This was the only image audit on 2KB, we actually [documented](https://web.dev/uses-responsive-images/?utm_source=lighthouse&utm_medium=cli) this value as 25KiB though I have no idea where that came from. Either way 4KiB seems more than reasonable and inline with other image byte efficiency audits.

File: lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js [hunk 2]
```diff
@@ -220,6 +221,18 @@ const expectations = [
             },
           },
         },
+        // Checks that images aren't TOO SMALL.
+        'image-size-responsive': {
+          details: {
+            items: {
```
Comment (connorjclark) [inline lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js:227]: just use an array.

File: lighthouse-core/audits/byte-efficiency/uses-responsive-images.js (hunk 1 above)
Comment (connorjclark) [reply lighthouse-core/audits/byte-efficiency/uses-responsive-images.js:33]: have you opened a pr to fix that?

File: types/artifacts.d.ts [hunk 3]
```diff
@@ -389,6 +389,8 @@ declare global {
 
       export interface ImageElement {
         src: string;
+        /** The srcset attribtue value. @see https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset */
```
Comment (connorjclark) [inline types/artifacts.d.ts:392]: spell check

File: lighthouse-core/audits/byte-efficiency/uses-responsive-images.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-core/audits/byte-efficiency/uses-responsive-images.js:33]: Nope

Comment (patrickhulce) [reply lighthouse-core/audits/byte-efficiency/uses-responsive-images.js:33]: https://github.com/GoogleChrome/web.dev/pull/3498
