### PR TITLE
clients: skip h2 audit in LR

### LINKED ISSUE #6539: Incorrectly reporting not supporting http/2
it says "Does not use HTTP/2 for all of its resources 6 requests not served via HTTP/2", but the server is correctly using h2

#### Environment Information
* https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.nodex.co.uk
* Lighthouse version: 4.0.0-alpha-0

------

EDIT(admin): This bug affects anything served by the PageSpeed API. (including web.dev). Root issue: b/32022322

### PR DESCRIPTION
**Pull request by paulirish**
fixes #6539 

<3 our config.

### CODE REVIEW

File: lighthouse-core/config/lr-desktop-config.js [hunk 1]
```diff
@@ -18,6 +18,7 @@ const config = {
       throughputKbps: 10 * 1024,
       cpuSlowdownMultiplier: 1,
     },
+    skipAudits: ['uses-http2'],
```
Comment (brendankenny) [inline lighthouse-core/config/lr-desktop-config.js]: maybe put a comment, TODO, or link to a bug?

**Comment by patrickhulce** [comment]
> we probably need to come up with a way to organize and mark web.dev/API bugs. e.g. this doesn't really fix the problem, it just makes it go away for now :)

I created the `web.dev` label we can use that for now :)
