### PR TITLE
core(optimized-images): cap execution to 5 seconds

### LINKED ISSUE #7173: OptimizedImages gatherer can take >20s
Locally, I see it take 30s when running LH on https://www.portuguesetrails.com/en
On LR, that's enough to hit our 60s render timeout and fail the entire run. (Which it does)

I think 15s is a decent time budget for this gatherer. (And probably all gatherers).

1. We can look into speeding up this gatherer.
2. We can enforce a deadline for all gatherers.

Thoughts? @patrickhulce

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
We cap execution of our OptimizedImage gatherer at 5s and estimate the savings on all the images we didn't get to.

I know it got big, but it's really just the capping + all the consequences of capping + tests.

**Related Issues/PRs**
closes #7173

### CODE REVIEW

File: lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js [hunk 1]
```diff
@@ -126,48 +84,24 @@ class OptimizedImages extends Gatherer {
...
-          fromProtocol: false,
-          originalSize: isBase64DataUri ? base64Length : networkRecord.resourceSize,
-          jpegSize: isBase64DataUri ? stats.jpeg.base64 : stats.jpeg.binary,
-          webpSize: isBase64DataUri ? stats.webp.base64 : stats.webp.binary,
-        };
-      });
-    });
+  async calculateImageStats(driver, networkRecord) {
+    const originalSize = networkRecord.resourceSize;
+    // We'll use our heuristic on the audit side for images that are too large and once we've hit our cap.
```
Comment (paulirish) [inline lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js]: reword comment so it fits the order of the conditional? :)

**Comment by patrickhulce** [comment]
> Yes?

Yes!

> To me the only tricky thing is that we don't attempt images >2mb but prioritize all results by size. But I understand the tradeoff here between precision of our estimate and runtime.

Yeah, this limit to me is more that we should be flagging this image via other means. If you're serving an image over 2MB, it's not just an "encode with the right JPEG settings issue" it's a "this image is way too effin' big issue", so let's not spend time focusing on it (related #7236). I'm open to other constants for this though. Maybe 3MB? 5MB?

Assuming it falls into the optimization bucket though, it does make sense to prioritize the biggest byte savings first.

**Comment by paulirish** [comment]
> Yeah, this limit to me is more that we should be flagging this image via other means. If you're serving an image over 2MB, it's not just an "encode with the right JPEG settings issue" it's a "this image is way too effin' big issue", so let's not spend time focusing on it 

Yah I like that approach.

Works for me.
