### PR TITLE
fix: DOM report injection loopholes

### LINKED ISSUE #1940: String.replace file injection technique can break page
Example: simply inserting `console.log('$');` into report-renderer.js causes our JS injection to escape the page.

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace, our replacement string (the js file content) we pass to `String.replace` will have:

`$'	Inserts the portion of the string that follows the matched substring.`

screen shot 2017-03-30 at 4 10 51 pm

### PR DESCRIPTION
**Pull request by patrickhulce**
R: @ebidel 

fixes #1940

### CODE REVIEW

File: lighthouse-core/report/v2/report-renderer.js [hunk 1]
```diff
@@ -17,6 +17,12 @@
 
 /* eslint-env browser */
 
+/**
+ * @fileoverview The entry point for rendering the Lighthouse report based on the JSON output.
+ *    This file is injected into the report HTML along with the JSON report.
+ *
+ * Dummy text for ensuring report robustness: </script> pre$`post
```
Comment (ebidel) [inline lighthouse-core/report/v2/report-renderer.js]: comedy :)
