### PR TITLE
Report: escape </script> tags

### LINKED ISSUE #996: HTML report doesn't escape closing `</script>` tags
Steps to reproduce:

1. Visit healthcare.gov and go through healthcare application until you reach `/marketplace/auth/enroll/consumers/?a=[application_id]&cache=true&t=[state]#/`
2. Run lighthouse
3. See this result:

I've attached the entirety of the report html at: https://gist.github.com/llimllib/931b448c9ec5cf7477959d9022210b18 . As you can see, line 1699 appears to be perfectly syntactically valid. Could this instead be a Chrome bug?

Google Chrome Version 54.0.2840.98 (64-bit)
MacOS Sierra
Lighthouse 1.2.0

It's interesting to note that the developer tools stops syntax highlighting properly at line 1699, which really makes me think this might be a parser error (!):

### PR DESCRIPTION
**Pull request by ebidel**
R: @brendankenny @GoogleChrome/lighthouse-owners 

This also updates the sample.json fixure to catch the latest report changes from an actual run.

### CODE REVIEW

File: lighthouse-core/report/report-generator.js [hunk 1]
```diff
@@ -137,6 +137,14 @@ class ReportGenerator {
   }
 
   /**
+   * Escape <script> tas.
```
Comment (llimllib) [inline lighthouse-core/report/report-generator.js]: tas -> tags

Comment (ebidel) [inline lighthouse-core/report/report-generator.js]: done

File: lighthouse-core/test/results/sample.json [hunk 2]
```diff
@@ -1,11 +1,13 @@
 {
   "lighthouseVersion": "x.x.x",
```
Comment (ebidel) [inline lighthouse-core/test/results/sample.json]: This just updates sample.json to be from an actual run. We've changed the shape of the JSON a lot with the DBW integration and none of those audits were being included here. I needed to add an example for the document.write audit and that was missing, so I updated to the latest format.
