### PR TITLE
tests: run code coverage in github actions

### LINKED ISSUE #11781: codecov OOM crash
While moving code coverage to GitHub Actions so we can sunset Travis #11770 #11194, an OOM crash was found when running our unit tests.

```
./node_modules/.bin/nyc --all --hook-run-in-context ./node_modules/.bin/jest lighthouse-core/test --runInBand --ci --coverage
```
node: v12.13.0 (happens on 10 too)

crash:
```
<--- Last few GCs --->

[1934:0x108008000]   191476 ms: Mark-sweep 2034.7 (2071.2) -> 2014.1 (2061.2) MB, 717.1 / 0.1 ms  (average mu = 0.269, current mu = 0.282) allocation failure scavenge might not succeed
[1934:0x108008000]   192387 ms: Mark-sweep 2031.7 (2073.7) -> 2014.8 (2061.8) MB, 806.7 / 0.1 ms  (average mu = 0.197, current mu = 0.114) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x10092fbd9]
Security context: 0x181b829808a1 <JSObject>
    1: deepCyclicCopyObject(aka deepCyclicCopyObject) [0x181b2805bde9] [/Users/cjamcl/src/lighthouse/node_modules/jest-util/build/deepCyclicCopy.js:~50] [pc=0x3a2d67113223](this=0x181b288004a9 <undefined>,0x181b33a459a1 <Object map = 0x181b182862e1>,0x181b47860b09 <Object map = 0x181b02332111>,0x181b2fc33f39 <JSWeakMap>)
    2: deepCyclicCopy(aka deepCyclicCopy...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20201207.155933.1934.0.001.json
Node.js report completed
 1: 0x10007e743 node::Abort() [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
 2: 0x10007e8c7 node::OnFatalError(char const*, char const*) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
 3: 0x100176267 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
 4: 0x100176203 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
 5: 0x1002fa2b5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
 6: 0x1002fb984 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
 7: 0x1002f8857 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
 8: 0x1002f683d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
 9: 0x100301f54 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
10: 0x100301fcf v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
11: 0x1002cebc7 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
12: 0x1005f7725 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
13: 0x10092fbd9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/cjamcl/.nvm/versions/node/v12.13.0/bin/node]
```

(Note: narrowing to fewer tests doesn't remove the crash, it simply makes it more flaky. for example, `lighthouse-core/test/audits` crashes...some of the time. running all is more consistent)
(Note: initially I thought removing `--runInBand` prevented the crash, however that was an artifact of running just a subset of the tests and not realizing crashing was flaky behavior)

Quick probes for which versions of Lighthouse crash:

v6.1.0: crash
v6.0.0: crash
v5.0.0: crash

At this point I'm scratching my head. If this crashes going back to v5, how did this ever work in travis?

--------

Here's a bisect script I wrote when I thought that was a good idea. (tries to) handle flakiness, and only fails if node crashes with OOM exit code

```
#!/usr/bin/env bash
set -ux

yarn

for ((n=0;n<5;n++))
do
  status=0
  ./node_modules/.bin/nyc --all --hook-run-in-context ./node_modules/.bin/jest lighthouse-core/test --runInBand --ci --coverage
  status=$?

  git rev-parse HEAD >> bisect-log.txt
  echo "$status" >> bisect-log.txt

  # Fail if OOM.
  if [ "$status" -eq 125 ] || [ "$status" -gt 127 ]; then
    exit 1
  fi
done

```

### PR DESCRIPTION
**Pull request by connorjclark**
This also replaces istanbul with c8, as coverage using istanbul has started to crash node.

part of #11194 

fixes #11781

### CODE REVIEW

**Comment by connorjclark** [comment]
image

`yarn coverage && open coverage/index.html`

**Comment by connorjclark** [comment]
question: can you really upload for the same "flag" to codecov?

answer: yes. https://codecov.io/gh/GoogleChrome/lighthouse/commit/047eb6242526e8f804947624b9e0c452270d2d25/build
image

**Comment by connorjclark** [comment]
This is ready for review. I'm using yarn `resolutions` to force my fork of a particular dep of `c8` so we don't have to wait for external projects to continue our removal of Travis.

File: lighthouse-core/lib/stack-collector.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ const libDetectorSource = fs.readFileSync(
 /**
  * Obtains a list of detected JS libraries and their versions.
  */
-/* istanbul ignore next */
+/* c8 ignore start */
```
Comment (Beytoven) [inline lighthouse-core/lib/stack-collector.js:42]: Does this one need a corresponding "c8 ignore stop"?

Comment (connorjclark) [reply lighthouse-core/lib/stack-collector.js:42]: done, good catch

File: package.json [hunk 2]
```diff
@@ -191,6 +190,9 @@
     "yargs": "^16.1.1",
     "yargs-parser": "^20.2.4"
   },
+  "resolutions": {
+    "v8-to-istanbul": "https://github.com/connorjclark/v8-to-istanbul.git#06abc4c4"
```
Comment (connorjclark) [inline package.json:194]: waiting on https://github.com/bcoe/c8/pull/273

**Comment by brendankenny** [comment]
I wonder why there's not a codecov status check on this PR?

**Comment by connorjclark** [comment]
They don't show any more for any PR. @paulirish did we disable that? can you look in admin panel?

**Review by Beytoven — APPROVED** [review]

**Comment by paulirish** [comment]
> They don't show any more for any PR. @paulirish did we disable that? can you look in admin panel?
> 
> in meantime, the GHA logs print a url.

clicking from the GHA logs i get a report for the commit, but then one more click to the PR (https://codecov.io/gh/GoogleChrome/lighthouse/pull/11770) shows this error message:

> Missing base report.
> Unable to compare commits because the base of the pull request did not upload a coverage report.
> Changes found in between 29b0eb0...a30953c (pseudo...base) which prevent comparing this pull request.

I wonder if that's why codecov isn't adding a status?

Poking around in https://app.codecov.io/gh/googlechrome/lighthouse there's no settings covering it. I remember saavan reached out to them and got responses, so we could do that..

**Comment by patrickhulce** [comment]
> Missing base report.
Unable to compare commits because the base of the pull request did not upload a coverage report.
Changes found in between 29b0eb0...a30953c (pseudo...base) which prevent comparing this pull request.
I wonder if that's why codecov isn't adding a status?

I'm guessing this is coming from the fact that we haven't been able to get codecov stats on master from travis for some time now. If it looks good for this branch, perhaps we proceed and then future PRs should have a comparison to tweak in a followup if things don't look right?

**Comment by paulirish** [comment]
looking through [the codecov discourse](https://community.codecov.io/search?q=pull%20request%20status), there's a lot of questions around this. some are that key commits don't have uploaded data.

1. i added a CODECOV_TOKEN to our repo secrets, though, according to the codecov action docs, it shouldn't change anything
2. i also verified that https://github.com/apps/codecov is installed for the LH repo. it is. (it's the only repo in our org with it)

-------------


> If it looks good for this branch, perhaps we proceed and then future PRs should have a comparison to tweak in a followup if things don't look right?

totes fine by me... i'm just surprised that we don't have a status for _this_ PR. 

ah i guess you mean this is broken because we don't have coverage numbers for master? that makes sense.

so yeah there's a good chance once this is merged and we're reporting successfully on master that things work out and PR statuses come back.

**Comment by thomasrockhu** [comment]
Tom from Codecov here. I'm not sure why statuses haven't come up, but if you push a new commit here, I can take a look!

**Comment by thomasrockhu** [comment]
At first glance, looks like this is the [problem](https://github.com/GoogleChrome/lighthouse/pull/11770/checks?check_run_id=1618391872). My guess is we do not properly handle the emojis (💡🏠) as workflow/job names. I'll open up a ticket with the product team about this, and I'll work on a fix in the uploader to deploy this week or next.

**Comment by connorjclark** [comment]
Great find, thanks for the help!

Ahh, vindication...can we remove these emojis now folks? :)

File: package.json (hunk 2 above)
Comment (bcoe) [reply package.json:194]: @connorjclark I apologize for the slow turnaround, was a little buried catching up after holidays.

Let me know if you bump into any issues.

File: .travis.yml [hunk 3]
```diff
@@ -0,0 +1,56 @@
+sudo: required
```
Comment (brendankenny) [inline .travis.yml:1]: probably don't want to re-add this :P

File: lighthouse-core/lib/page-functions.js [hunk 4]
```diff
@@ -27,7 +27,6 @@
  * promise. Instead, map to a successful object that contains this information.
  * @param {string|Error} err The error to convert
  */
-/* istanbul ignore next */
```
Comment (brendankenny) [inline lighthouse-core/lib/page-functions.js:30]: maybe worth adding to the fileoverview that this whole file is ignored for code coverage since it's intended to run in the browser?

File: yarn.lock [hunk 5]
```diff
@@ -556,11 +561,21 @@
...
+  version "1.0.0"
+  resolved "https://registry.yarnpkg.com/@types/is-windows/-/is-windows-1.0.0.tgz#1011fa129d87091e2f6faf9042d6704cdf2e7be0"
+  integrity sha512-tJ1rq04tGKuIJoWIH0Gyuwv4RQ3+tIu7wQrC0MV47raQ44kIzXSSFKfrxFUOWVRvesoF7mrTqigXmqoZJsXwTg==
+
 "@types/istanbul-lib-coverage@*", "@types/istanbul-lib-coverage@^2.0.0":
   version "2.0.1"
   resolved "https://registry.yarnpkg.com/@types/istanbul-lib-coverage/-/istanbul-lib-coverage-2.0.1.tgz#42995b446db9a48a11a07ec083499a860e9138ff"
   integrity sha512-hRJD2ahnnpLgsj6KWMYSrmXkM3rm2Dl1qkx6IOFD5FnuNPXJIG5L0dhgKXCYTRMGzU4n0wImQ/xfmRc4POUFlg==
 
+"@types/istanbul-lib-coverage@^2.0.1":
```
Comment (brendankenny) [inline yarn.lock:574]: relatively minor, but if you want to eliminate some unneeded duplicate deps:

```
diff --git a/yarn.lock b/yarn.lock
index 96b73a0bd..6b74d3fb5 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -566,12 +566,7 @@
   resolved "https://registry.yarnpkg.com/@types/is-windows/-/is-windows-1.0.0.tgz#1011fa129d87091e2f6faf9042d6704cdf2e7be0"
   integrity sha512-tJ1rq04tGKuIJoWIH0Gyuwv4RQ3+tIu7wQrC0MV47raQ44kIzXSSFKfrxFUOWVRvesoF7mrTqigXmqoZJsXwTg==
 
-"@types/istanbul-lib-coverage@*", "@types/istanbul-lib-coverage@^2.0.0":
-  version "2.0.1"
-  resolved "https://registry.yarnpkg.com/@types/istanbul-lib-coverage/-/istanbul-lib-coverage-2.0.1.tgz#42995b446db9a48a11a07ec083499a860e9138ff"
-  integrity sha512-hRJD2ahnnpLgsj6KWMYSrmXkM3rm2Dl1qkx6IOFD5FnuNPXJIG5L0dhgKXCYTRMGzU4n0wImQ/xfmRc4POUFlg==
-
-"@types/istanbul-lib-coverage@^2.0.1":
+"@types/istanbul-lib-coverage@*", "@types/istanbul-lib-coverage@^2.0.0", "@types/istanbul-lib-coverage@^2.0.1":
   version "2.0.3"
   resolved "https://registry.yarnpkg.com/@types/istanbul-lib-coverage/-/istanbul-lib-coverage-2.0.3.tgz#4ba8ddb720221f432e443bd5f9117fd22cfd4762"
   integrity sha512-sz7iLqvVUg1gIedBOvlkxPlc8/uVzyS5OwGz1cKjXzkl3FpL3al0crU8YGU1WoHkxn0Wxbw5tyi6hvzJKNzFsw==
@@ -3501,19 +3496,7 @@ glob-to-regexp@^0.3.0:
   resolved "https://registry.yarnpkg.com/glob-to-regexp/-/glob-to-regexp-0.3.0.tgz#8c5a1494d2066c570cc3bfe4496175acc4d502ab"
   integrity sha1-jFoUlNIGbFcMw7/kSWF1rMTVAqs=
 
-glob@^7.0.0, glob@^7.0.3, glob@^7.1.0, glob@^7.1.1, glob@^7.1.2, glob@^7.1.3:
-  version "7.1.4"
-  resolved "https://registry.yarnpkg.com/glob/-/glob-7.1.4.tgz#aa608a2f6c577ad357e1ae5a5c26d9a8d1969255"
-  integrity sha512-hkLPepehmnKk41pUGm3sYxoFs/umurYfYJCerbXEyFIWcAzvpipAgVkBqqT9RBKMGjnq6kMuyYwha6csxbiM1A==
-  dependencies:
-    fs.realpath "^1.0.0"
-    inflight "^1.0.4"
-    inherits "2"
-    minimatch "^3.0.4"
-    once "^1.3.0"
-    path-is-absolute "^1.0.0"
-
-glob@^7.1.4:
+glob@^7.0.0, glob@^7.0.3, glob@^7.1.0, glob@^7.1.1, glob@^7.1.2, glob@^7.1.3, glob@^7.1.4:
   version "7.1.6"
   resolved "https://registry.yarnpkg.com/glob/-/glob-7.1.6.tgz#141f33b81a7c2492e125594307480c46679278a6"
   integrity sha512-LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==
@@ -8328,7 +8311,7 @@ yargs@^15.0.0, yargs@^15.3.1:
     y18n "^4.0.0"
     yargs-parser "^18.1.2"
 
-yargs@^16.0.0:
+yargs@^16.0.0, yargs@^16.1.1:
   version "16.2.0"
   resolved "https://registry.yarnpkg.com/yargs/-/yargs-16.2.0.tgz#1c82bf0f6b6a66eafce7ef30e376f49a12477f66"
   integrity sha512-D1mvvtDG0L5ft/jGWkLpG1+m0eQxOfaBvTNELraWj22wSVUMWxZUvYgJYcKh6jGGIkJFhH4IZPQhR4TKpc8mBw==
@@ -8341,19 +8324,6 @@ yargs@^16.0.0:
     y18n "^5.0.5"
     yargs-parser "^20.2.2"
 
-yargs@^16.1.1:
-  version "16.1.1"
-  resolved "https://registry.yarnpkg.com/yargs/-/yargs-16.1.1.tgz#5a4a095bd1ca806b0a50d0c03611d38034d219a1"
-  integrity sha512-hAD1RcFP/wfgfxgMVswPE+z3tlPFtxG8/yWUrG2i17sTWGCGqWnxKcLTF4cUKDUK8fzokwsmO9H0TDkRbMHy8w==
-  dependencies:
-    cliui "^7.0.2"
-    escalade "^3.1.1"
-    get-caller-file "^2.0.5"
-    require-directory "^2.1.1"
-    string-width "^4.2.0"
-    y18n "^5.0.5"
-    yargs-parser "^20.2.2"
-
 yauzl@^2.10.0:
   version "2.10.0"
   resolved "https://registry.yarnpkg.com/yauzl/-/yauzl-2.10.0.tgz#c7eb17c93e112cb1086fa6d8e51fb0667b79a5f9"
```

**Review by brendankenny — CHANGES_REQUESTED** [review]
Really excited about this! Can we land? Seems like we could figure our the emoji thing afterwards

**Review by brendankenny — APPROVED** [review]
oops :)

File: lighthouse-core/lib/page-functions.js (hunk 4 above)
Comment (connorjclark) [reply lighthouse-core/lib/page-functions.js:30]: Is that information useful to someone looking at this file? Seems a concern only if you are looking at how c8 works, and naturally you'd be looking at c8.sh.

File: yarn.lock (hunk 5 above)
Comment (connorjclark) [reply yarn.lock:574]: Is there an automated process to do what you're doing manually?

File: lighthouse-core/lib/page-functions.js (hunk 4 above)
Comment (brendankenny) [reply lighthouse-core/lib/page-functions.js:30]: > Is that information useful to someone looking/editing/using functions form this module?

I think so. There's coverage magic going on and the only way to figure out why e.g. a new page function in here doesn't have to be ignored while a new page function that's defined within a gatherer file does have to be ignored is to know you have to look in `c8.sh` in the first place

File: yarn.lock (hunk 5 above)
Comment (brendankenny) [reply yarn.lock]: > Is there an automated process to do what you're doing manually?

I haven't seen any good tools that will de-dupe but try to minimize the churn but I haven't looked in a while

File: lighthouse-core/lib/page-functions.js [hunk 6]
```diff
@@ -9,6 +9,9 @@
 /**
  * @fileoverview
  * Helper functions that are passed by `toString()` by Driver to be evaluated in target page.
+ *
```
Comment (brendankenny) [inline lighthouse-core/lib/page-functions.js:12]:
```suggestion
 *
```

File: package.json [hunk 7]
```diff
@@ -38,21 +39,20 @@
     "test-legacy-javascript": "bash lighthouse-core/scripts/test-legacy-javascript.sh",
     "test-docs": "yarn --cwd docs/recipes/auth && jest docs/recipes/integration-test && yarn --cwd docs/recipes/custom-gatherer-puppeteer test",
     "test-proto": "yarn compile-proto && yarn build-proto-roundtrip",
-    "unit-core": "jest \"lighthouse-core/\"",
+    "unit-core": "jest \"lighthouse-core/test/audits\"",
     "unit-cli": "jest \"lighthouse-cli/\"",
     "unit-viewer": "jest \"lighthouse-viewer/.*-test.js\"",
     "unit": "yarn unit-core && yarn unit-cli && yarn unit-viewer",
-    "unit:ci": "npm run unit-core -- --runInBand --ci --coverage && npm run unit-cli -- --runInBand --ci --coverage && npm run unit-viewer -- --runInBand --ci --coverage",
+    "unit:ci": "NODE_OPTIONS=--max-old-space-size=4096 npm run unit-core -- --ci && npm run unit-cli -- --ci && npm run unit-viewer -- --ci",
```
[the remark this answers is not in the document]
Comment (connorjclark) [reply package.json:46]: yup, just saw it fails without in ubuntu

**Comment by thomasrockhu** [comment]
The issue should be resolved on the Codecov side now @connorjclark
