### PR TITLE
tests: fix flaky robots smoke failure

### LINKED ISSUE #13024: Robots txt audit is flaky in FR smoke tests
**Summary**
I've been starting to see flaky failures of the robots.txt audit in FR smoke tests (example: https://github.com/GoogleChrome/lighthouse/pull/12969/checks?check_run_id=3548610674#step:7:895) if this happens to anyone locally or you find more examples, it'd be good to start collecting for patterns.

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
~~Adding more debug data to the RobotsTxt artifact and running it many times to find the flake reason.~~ Found the flake! The error message we're getting here is "Waiting for the end of the IO stream exceeded the allotted time". I increased the timeout from 500ms to 1000ms, ran it 100 times and did not receive a single failure, so I'm calling that fixed (500ms is a decently short period to try and fetch a remote resource *and* read all its contents off the protocol, 1s seemed more reasonable) 👍 

**Related Issues/PRs**
fixes #13024

### CODE REVIEW

File: lighthouse-core/gather/gatherers/seo/robots-txt.js [hunk 1]
```diff
@@ -48,8 +48,8 @@ class RobotsTxt extends FRGatherer {
 
     const robotsUrl = new URL('/robots.txt', passContext.url).href;
     await passContext.driver.fetcher.enable();
-    return passContext.driver.fetcher.fetchResource(robotsUrl)
-      .catch(() => ({status: null, content: null}));
+    return passContext.driver.fetcher.fetchResource(robotsUrl, {timeout: 1_000})
```
Comment (connorjclark) [inline lighthouse-core/gather/gatherers/seo/robots-txt.js:51]: shouldn't we tweak the method's default instead? and since mostly all usages of this are done in parallel (source maps), I'd be comfortable upping it to 2s.

Comment (patrickhulce) [reply lighthouse-core/gather/gatherers/seo/robots-txt.js:51]: sure, wfm

**Review by adamraine — APPROVED** [review]
LGTM, thanks for looking into this.
