### PR TITLE
Throw better error message when url is not auditable

### LINKED ISSUE #2525: Extension Error: Cannot access contents of the page. Extension manifest must
**Lighthouse Version**: 2.1.0
**Chrome Version**: 61.0.3132.0
**Initial URL**: view-source:chrome-extension://akdgnmcogleenhbclghghlkkdndkjdjc/linkinfo.html?id=e8b97e2a876941dc590bce68bd81e921
**Error Message**: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
**Stack Trace**:
```
Error: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
    at Object.chrome.debugger.attach._ [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9837:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

### PR DESCRIPTION
**Pull request by wardpeet**
should throw a message that don't support non auditable pages like view-source, ...
Fixes #2525

Not sure it's the best solution though

### CODE REVIEW

File: lighthouse-extension/app/src/popup.js [hunk 1]
```diff
@@ -21,7 +21,9 @@ const NON_BUG_ERROR_MESSAGES = {
       'Chrome-specific urls. If necessary, use the Lighthouse CLI to do so.',
   // The user tries to review an error page or has network issues
   'Unable to load the page': 'Unable to load the page. Please verify the url you ' +
-      'are trying to review.'
+      'are trying to review.',
+  'Cannot access contents of the page': 'The Lighthouse extension can only audit ' +
+      ' http & https pages.',
```
Comment (ebidel) [inline lighthouse-extension/app/src/popup.js]: "Lighthouse can only audit URLs that start with http:// or https://."

**Comment by brendankenny** [comment]
does this actually fix #2525? The error pattern (`Unable to load the page`) won't match the error in that issue and so the updated explanation won't be shown

**Comment by paulirish** [comment]
I think you're looking at the wrong one?

the exception message is "Cannot access contents of the page. Extension manifest must request permission to access the respective host."

and this PR looks for "Cannot access contents of the page"

**Comment by brendankenny** [comment]
> I think you're looking at the wrong one?

oh, ha, new line :) 👍 👍
