### PR TITLE
Fix NaN% in CLI report

### LINKED ISSUE #761: DBW: json output contains NaN% and undefined
```
npm run start -- --config-path=lighthouse-core/config/dobetterweb.json --mobile=false https://www.chromestatus.com/features
```

There are `NaN%` for the scores (there shouldn't be scores) and `undefined` for the `Date.now() ` line/col violations. As part of fixing this, we should check that other line/col violations show up in the report.

screen shot 2016-10-10 at 5 45 02 pm

html is correct:

screen shot 2016-10-10 at 5 43 48 pm

### PR DESCRIPTION
**Pull request by paulirish**
fixes #761 

Details for reviewers: 

* getTotalWeight was manually turning 0 into 1, to avoid a `0/0` ==> `NaN` in the computing of `overall`. It was awkward. I've allowed them to have a value of `0`. 
* maxScore is set to 1 initially to allow `0/maxScore` to resolve to 0 and not `NaN` .

### CODE REVIEW

File: lighthouse-core/aggregator/aggregate.js [hunk 1]
```diff
@@ -37,12 +37,8 @@ class Aggregate {
    */
   static _getTotalWeight(expected) {
     const expectedNames = Object.keys(expected);
-    let weight = expectedNames.reduce((last, e) => last + expected[e].weight, 0);
-    if (weight === 0) {
-      weight = 1;
-    }
-
-    return weight;
+    let totalWeight = expectedNames.reduce((last, e) => last + (expected[e].weight || 0), 0);
```
Comment (wardpeet) [inline lighthouse-core/aggregator/aggregate.js]: In my opinion `(expected[e].weight || 0)`is a bit hard to read. maybe add a comment that you default to 0
