### PR TITLE
core(simulator): clearer intermediate timing types

### LINKED ISSUE #11692: Lantern simulator type improvements
**Summary**

Upgrade to typescript 4 revealed some issues in our lantern types with `NodeTimingIntermediate`. We can split the type into the different stages of "doneness" instead of abusing `Required` incorrectly.

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
@connorjclark I'm requesting your feedback here since you brought this up :)

There were many ways this could be done, but this felt like a decent balance between duplication in the right places, reading clarity, and type safety. I expect others might have different ideas of the tradeoffs though :)

**Related Issues/PRs**
fixes #11692

### CODE REVIEW

File: lighthouse-core/lib/dependency-graph/simulator/simulator.js [hunk 1]
```diff
@@ -531,12 +658,25 @@ class Simulator {
...
 /**
- * @typedef NodeTimingIntermediate
- * @property {number} [startTime]
- * @property {number} [endTime]
- * @property {number} [queuedTime] Helpful for debugging.
- * @property {number} [estimatedTimeElapsed]
- * @property {number} [timeElapsed]
- * @property {number} [timeElapsedOvershoot]
- * @property {number} [bytesDownloaded]
+ * @typedef NodeTimingComplete
```
Comment (connorjclark) [inline lighthouse-core/lib/dependency-graph/simulator/simulator.js:661]: IMO typedefs at the top of the file is a better place.

**Review by connorjclark — APPROVED** [review]
seems good to me.

I experimented with using a type predicate fn, but it didn't look like it improved anything at all 
image

I had some trouble separating all of these new functions from the actual meat of the class. Maybe all of these could be pulled into a new `NodeTimings` class?
