### PR TITLE
deps: update cssstyle to parse more named colors, CSS4 colors

### LINKED ISSUE #7139: background_color and theme_color fail for most named colours
#### Provide the steps to reproduce
1. Run LH on manifest with `"background_color": "rebeccapurple"`

#### What is the current behavior?
test fails:

screenshot 2019-02-02 22 01 08
screenshot 2019-02-02 22 00 57

#### What is the expected behavior?
Test passes

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**
This fails because a dependency of lighthouse has an incomplete enum of css color names. Relevant PR:
https://github.com/jsakas/CSSStyleDeclaration/pull/74

### PR DESCRIPTION
**Pull request by brendankenny**
90% of this is tests :)
(`manifest-parser.js` had no existing tests for its color parsing)

(*edit: unit tests. It does have integration tests through `themed-omnibox`, `splash-screen`, et al.*)

fixes #7139

### CODE REVIEW

**Comment by brendankenny** [comment]
this adds 2.6 KB to the bundle (.8 KB after gzip), almost entirely due to the [newly added named colors](https://github.com/jsakas/CSSStyleDeclaration/blob/e239aec4cd124b17a64d9a228b6787f63fd1a119/lib/named_colors.json)

File: lighthouse-core/test/lib/manifest-parser-test.js [hunk 1]
```diff
@@ -455,4 +455,99 @@ describe('Manifest Parser', function() {
       assert.equal(url0, undefined);
     });
   });
+
+  describe.only('background_color, theme_color', () => {
```
Comment (patrickhulce) [inline lighthouse-core/test/lib/manifest-parser-test.js]: remove `.only`

Comment (brendankenny) [reply lighthouse-core/test/lib/manifest-parser-test.js]: d'oh, they should have a test test for that :)

**Comment by brendankenny** [comment]
> nice! LGTM outside the test issue

LGTY but needs approval :)
