### PR TITLE
CRC audit: child chain renders using its own transfersize. Fixes #2597

### LINKED ISSUE #2597: Critical Request Chain size info is incorrect
There seems to be some issue with the sizes listed under Critical Request Chain. They are all listed as having the same size, and don't seem to match any of the actual sizes. 

Issue found in the built-in Lighthouse in Chrome Canary 61.0.3141.0  (64 bits) on Windows. Also found in Chrome Canary on OSX, but not sure which exact version.

Issue also exists in the Chrome Extension of Lighthouse (Version: 2.1.0). 

Seems to have been working properly back in February at least as can be seen in https://github.com/GoogleChrome/lighthouse/issues/1729

screen shot 2017-06-22 at 10 35 29
screen shot 2017-06-22 at 11 01 41

### PR DESCRIPTION
**Pull request by ebidel**
Children chains were using the overall `longestChain.transferSize` instead of their own size. 

Also updated the renderer test to actually be useful.

Fixes #2597

### CODE REVIEW

File: lighthouse-core/test/report/v2/renderer/crc-details-renderer-test.js [hunk 1]
```diff
@@ -92,37 +92,18 @@ describe('DetailsRenderer', () => {
...
-      </span>`;
-    assert.ok(chains[1].innerHTML, div.innerHTML);
+    // Children
+    assert.ok(chains[1].querySelector('.crc-node__tree-marker .vert-right'));
+    assert.equal(chains[1].querySelectorAll('.crc-node__tree-marker .right').length, 2);
+    assert.equal(chains[1].querySelector('.crc-node__tree-file').textContent, '/b.js');
+    assert.equal(chains[1].querySelector('.crc-node__tree-hostname').textContent, '(example.com)');
+    const durationNodes = chains[1].querySelectorAll('.crc-node__chain-duration');
+    assert.equal(durationNodes[0].textContent, ' - 5,000ms, ');
+    assert.equal(durationNodes[1].textContent, '1.95KB');
```
Comment (brendankenny) [inline lighthouse-core/test/report/v2/renderer/crc-details-renderer-test.js]: maybe put a comment/assertion message that this is the `transferSize` and 2000 bytes is being formatted to KB? Took me a little while to see where it came from/if the new transfer sizes were being tested.

**Comment by patrickhulce** [comment]
sorry this'll need a rebase for the `formateBytesToKB` typo :)

File: lighthouse-core/test/report/v2/renderer/crc-details-renderer-test.js (hunk 1 above)
Comment (ebidel) [inline lighthouse-core/test/report/v2/renderer/crc-details-renderer-test.js]: done
