### PR TITLE
fix Travis test timeouts

### LINKED ISSUE #833: smoke tests often time out on travis
Quite common to see Travis jobs go for ~10 minutes, at which point Travis kills the run. More end-to-end tests with smokehouse and now four versions of node increases the chance of these flakey tests.

### PR DESCRIPTION
**Pull request by brendankenny**
fixes #833 

- commit 2fed833: as described in #833, the issue on Travis is that the initial HTTP GET request to Chrome for debugger connection information sometimes never responds. This PR adds a 10 second timeout to that request, at which point it exits the process on a special exit code
- commit 227487a: add the ability to specify a port for the debugger protocol with a `--port` flag (defaulting to the current 9222). If you specify port 0, it will pick a random open port (via the [behavior of `server.listen`](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback))

With these changes in place, smokehouse now always uses a random port for the protocol and retries launching Chrome and running Lighthouse up to three times when LH fails with that specific exit code.

Both changes are necessary: when the GET request fails, the port appears to be out of commission, even after killing Chrome, so a new port must be used for the next attempt or it will continue to fail. Using a random port is also not sufficient on its own; even if using a random port on every Lighthouse run, it will still occasionally fail on our Travis setup and so will need to be re-run.

*Why* Chrome sometimes fails like this isn't clear, but I'm reasonably happy with this solution until (if) we figure this out.

The retries look like this in the smokehouse logs:
screen shot 2016-11-07 at 22 26 15

### CODE REVIEW

File: lighthouse-cli/bin.ts [hunk 1]
```diff
@@ -80,7 +83,8 @@ const cli = yargs
     'list-trace-categories': 'Prints a list of all required trace categories and exits',
     'config-path': 'The path to the config JSON.',
     'perf': 'Use a performance-test-only configuration',
-    'skip-autolaunch': 'Skip autolaunch of Chrome when accessing port 9222 fails',
+    'port': 'The port to use fo the debugging protocol. Use 0 for a random port',
```
Comment (paulirish) [inline lighthouse-cli/bin.ts]: fo fo for

File: lighthouse-core/gather/connections/cri.js [hunk 2]
```diff
@@ -66,6 +78,16 @@ class CriConnection extends Connection {
           reject(new Error(`Unable to fetch webSocketDebuggerUrl, status: ${response.statusCode}`));
         });
       });
+
+      request.setTimeout(CONNECT_TIMEOUT, _ => {
+        request.abort();
+
+        const err = new Error('Timeout waiting for initial Debugger Protocol connection.');
+        err.code = 'CRI_TIMEOUT';
```
Comment (paulirish) [inline lighthouse-core/gather/connections/cri.js]: to confirm, this is `code` property is nonstandard, right?

File: lighthouse-core/gather/connections/cri.js [hunk 3]
```diff
@@ -19,11 +19,23 @@
...
 const hostname = 'localhost';
-const port = process.env.PORT || 9222;
+const CONNECT_TIMEOUT = 10000;
 
 class CriConnection extends Connection {
   /**
+   * @param {number=} port Optional port number. Defaults to 9222;
+   * @constructor
+   */
+  constructor(port) {
```
Comment (paulirish) [inline lighthouse-core/gather/connections/cri.js]: should this take a connectOpts obj instead of named args? seems like our other connections would not take `port` as first arg.

File: lighthouse-cli/bin.ts [hunk 4]
```diff
@@ -116,6 +120,7 @@ Example: --output-path=./lighthouse-results.html`
   .default('disable-cpu-throttling', true)
   .default('output', Printer.GetValidOutputOptions()[Printer.OutputMode.pretty])
   .default('output-path', 'stdout')
+  .default('port', 9222)
```
Comment (paulirish) [inline lighthouse-cli/bin.ts]: will --port now work on the chrome-debug binary?

File: lighthouse-cli/bin.ts [hunk 5]
```diff
@@ -227,37 +256,46 @@ function showRuntimeError(err: LightHouseError) {
...
+      return lighthouseRun(urls, config, cli).catch(handleError);
+    } else {
+      // because you can't cancel a promise yet
+      const isSigint = new Promise((resolve, reject) => {
+        process.on(_SIGINT, () => reject(_SIGINT));
       });
-  }
+
+      return Promise
+        .race([launchChromeAndRun(urls, config, cli), isSigint])
```
Comment (paulirish) [inline lighthouse-cli/bin.ts]: isn't `cli` === `flags`?  Let's use that variable instead.

File: lighthouse-core/gather/connections/cri.js (hunk 2 above)
Comment (brendankenny) [inline lighthouse-core/gather/connections/cri.js]: yeah. It's used a bunch by node, so I stole it from them, but we can move back to parsing `error.message` if you want

Comment (paulirish) [inline lighthouse-core/gather/connections/cri.js]: no prob. i prefer using `.code` so let's go with that.

File: lighthouse-cli/bin.ts (hunk 4 above)
Comment (brendankenny) [inline lighthouse-cli/bin.ts]: not at the moment, but I can add that

File: lighthouse-cli/bin.ts (hunk 5 above)
Comment (brendankenny) [inline lighthouse-cli/bin.ts]: done

**Comment by brendankenny** [comment]
updated, PTAL

File: lighthouse-cli/bin.ts (hunk 4 above)
Comment (brendankenny) [inline lighthouse-cli/bin.ts]: would you want `chrome-debug` to support port 0 (aka give me a random port)? Not that useful, since the caller will have to know the port in order to talk to it on that port. If not, this is an easy fix and I can add it

**Comment by ebidel** [comment]
HERO!
