### PR TITLE
Fix score coloring. Fixes #1061

### LINKED ISSUE #1061: Low score colors misleading
screen shot 2016-11-28 at 10 17 39 am

It seems like the scores of 22, 21, and 48 should be red/orange to indicate they're negative values.

### PR DESCRIPTION
**Pull request by ebidel**
R: @patrickhulce @brendankenny @paulirish 

Before:

screen shot 2016-11-28 at 2 01 07 pm

Now:

screen shot 2016-11-28 at 1 59 53 pm

### CODE REVIEW

File: lighthouse-core/report/report-generator.js [hunk 1]
```diff
@@ -24,11 +24,21 @@ const fs = require('fs');
 const path = require('path');
 
 const RATINGS = {
-  GOOD: {label: 'good', minValue: 0.66, minScore: 75},
```
Comment (patrickhulce) [inline lighthouse-core/report/report-generator.js]: were these just totally unused hence the buggy color?

**Comment by patrickhulce** [comment]
nice, LGTM

File: lighthouse-core/report/report-generator.js (hunk 1 above)
Comment (ebidel) [inline lighthouse-core/report/report-generator.js]: Yea :)
