### PR TITLE
core(fetcher): ensure fetch doesn't cause unhandled promise

### LINKED ISSUE #11033: Unhandled promise rejection (lighthouse-core/gather/fetcher.js)
We're seeing a number of errors being thrown from `lighthouse-core/gather/fetcher.js` as unhandled promise rejections. 

Examples of errors:

- Protocol error (Fetch.failRequest): Fetch domain is not enabled
- Protocol error (Fetch.continueRequest): Invalid InterceptionId.
- Error: Invalid response status code: 404
- Invalid response status code: 403
- Invalid response status code: 301

<details><summary>Error output</summary>

```bash
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Invalid response status code: 404
      at ./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:119:18
      at Fetcher._onRequestPaused (./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:75:13)
      at EventEmitter.emit (events.js:315:20)
      at EventEmitter.emit (domain.js:482:12)
      at Driver._handleProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/driver.js:299:24)
      at EventEmitter.emit (events.js:315:20)
      at EventEmitter.emit (domain.js:482:12)
      at CalibreProtocol.emitProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:148:24)
      at CalibreProtocol.handleRawMessage (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:113:12)
      at WebSocket.<anonymous> (./node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:72:37)
} reason: Error: Invalid response status code: 404
    at ./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:119:18
    at Fetcher._onRequestPaused (./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:75:13)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:482:12)
    at Driver._handleProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/driver.js:299:24)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:482:12)
    at CalibreProtocol.emitProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:148:24)
    at CalibreProtocol.handleRawMessage (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:113:12)
    at WebSocket.<anonymous> (./node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:72:37)
(node:25717) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 10)
Error: Invalid response status code: 404
    at ./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:119:18
    at Fetcher._onRequestPaused (./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:75:13)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:482:12)
    at Driver._handleProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/driver.js:299:24)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:482:12)
    at CalibreProtocol.emitProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:148:24)
    at CalibreProtocol.handleRawMessage (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:113:12)
    at WebSocket.<anonymous> (./node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:72:37)
```

</details>

I'm seeing the error in Node and when using the Lighthouse CLI.

#### Provide the steps to reproduce

 Run:
```bash
lighthouse https://www.clarin.com/deportes/basquet/ginobili-volvio-hacer-magia-definicion-exquisita_0_H16J9aAaZ.html --view
```

#### What is the current behavior?

Lighthouse returns `Unhandled Rejection. Reason: Error: Invalid response status code: 404`. See [full output](https://gist.github.com/mikedijkstra/cff70091adaac0e01583357860b9655f).

#### What is the expected behavior?

Lighthouse report is generated and opened in the browser

#### Environment Information
* Affected Channels: CLI, Node
* Lighthouse version: 6.1
* Chrome version: 83.0.4103.116
* Node.js version: 12.18.0
* Operating System: Mac, Linux

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #11033

### CODE REVIEW

File: lighthouse-core/gather/fetcher.js [hunk 1]
```diff
@@ -168,10 +164,16 @@ class Fetcher {
...
 
-    return Promise.race([
+    const racePromise = Promise.race([
       timeoutPromise,
       requestInterceptionPromise,
     ]).finally(() => clearTimeout(timeoutHandle));
+
+    this.driver.evaluateAsync(`${injectIframe}(${JSON.stringify(url)})`, {
+      useIsolation: true,
+    }).catch(err => console.error(err));
```
Comment (connorjclark) [inline lighthouse-core/gather/fetcher.js:174]: should we bother logging this?

**Comment by connorjclark** [comment]
#11033 doesn't effect canary chrome or LR\*. We should follow up with a 6.1.1 release just for npm.

@patrickhulce and I don't know why Node 12 crashes on this error :o
image (2)

\* still need to confirm. @mikedijkstra can you provide some more URLs where this crash occurs?

File: lighthouse-core/gather/fetcher.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-core/gather/fetcher.js:174]: why not just put it into a `Promise.all([racePromise, injectPromise])` to get into the normal control flow?

**Comment by patrickhulce** [comment]
yeah I don't know why it's exiting https://github.com/GoogleChrome/lighthouse/issues/11033 hasn't landed yet...

File: lighthouse-core/gather/fetcher.js (hunk 1 above)
Comment (connorjclark) [reply lighthouse-core/gather/fetcher.js:174]: I don't see how. Send PR?

File: lighthouse-core/gather/fetcher.js [hunk 2]
```diff
@@ -168,10 +166,16 @@ class Fetcher {
...
+    const racePromise = Promise.race([
       timeoutPromise,
       requestInterceptionPromise,
     ]).finally(() => clearTimeout(timeoutHandle));
+
+    this.driver.evaluateAsync(`${injectIframe}(${JSON.stringify(url)})`, {
+      useIsolation: true,
+    }).catch(err => log.error('Fetcher', err));
+
+    return racePromise;
```
Comment (patrickhulce) [inline lighthouse-core/gather/fetcher.js:178]:
```suggestion
    const injectionPromise = this.driver.evaluateAsync(`${injectIframe}(${JSON.stringify(url)})`, {
      useIsolation: true,
    });

    const [fetchResult] = await Promise.all([racePromise, injectionPromise]);
    return fetchResult;
```

Comment (patrickhulce) [reply lighthouse-core/gather/fetcher.js:178]: this is what I meant.

Comment (connorjclark) [reply lighthouse-core/gather/fetcher.js:178]: That's where I stopped at because I thought tossing out the rest of the `Promise.all` return value was so unusual I must have misunderstood. sgtm :)

Comment (connorjclark) [reply lighthouse-core/gather/fetcher.js]: fyi (nbd)

image

I expected a string here.
