### PR TITLE
fix(connection): gracefully handle missing method

### LINKED ISSUE #2321: Lighthouse 2.0.0 crash
Tested with multiple URLs, all crash. 

OS: macOS 10.12.4

```
$ node -v && npm -v
v6.10.0
3.10.10
$ lighthouse --version
2.0.0
$ lighthouse http://google.com
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +514ms
  ChromeLauncher Waiting for browser.....✓ +3ms
  Lighthouse:warn The URL provided should be on HTTPS +422ms
  Lighthouse:warn Performance stats will be skewed redirecting from HTTP to HTTPS. +1ms
  status Initializing… +510ms
/usr/local/lib/node_modules/lighthouse/lighthouse-core/lib/log.js:111
    const maxLength = columns - data.method.length - prefix.length - loggingBufferColumns;
                                           ^

TypeError: Cannot read property 'length' of undefined
    at Function.formatProtocol (/usr/local/lib/node_modules/lighthouse/lighthouse-core/lib/log.js:111:44)
    at CriConnection.handleRawMessage (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:111:9)
    at WebSocket.ws.on.data (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:78:37)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/usr/local/lib/node_modules/lighthouse/node_modules/ws/lib/WebSocket.js:841:10)
    at /usr/local/lib/node_modules/lighthouse/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/usr/local/lib/node_modules/lighthouse/node_modules/ws/lib/Receiver.js:371:5)
    at /usr/local/lib/node_modules/lighthouse/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/usr/local/lib/node_modules/lighthouse/node_modules/ws/lib/Receiver.js:347:3)
```

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #2321 

also observed errors in devtools when we get command callbacks for commands LH didn't send

### CODE REVIEW

**Comment by patrickhulce** [comment]
> Just a bit unsure about the ????? method name when it's unknown.

Yeah using `unknown` just blended in a bit too much with the rest of the logs and this makes it a little clearer something weird is going on, open to suggestions though :)

**Comment by brendankenny** [comment]
did anyone have any more insight into the cause of this? We don't want to crash in the faces of this, but without error tracking this will start to get lost with this change. The devtools case is more understandable, but feedback commands we didn't send is something we should probably track down

**Comment by patrickhulce** [comment]
> did anyone have any more insight into the cause of this?

Nope :) it seems impossible from the stack trace in the issue since if it fails in the resolve it should have definitely failed the first time when it was sending the message (because it actually gets the method when the callback was set)

> but without error tracking this will start to get lost with this change

Good thing we're approved for sentry now let's get it installed post-branch :D

File: lighthouse-core/gather/connections/connection.js [hunk 1]
```diff
@@ -92,7 +92,7 @@ class Connection {
     const object = JSON.parse(message);
     // Remote debugging protocol is JSON RPC 2.0 compiant. In terms of that transport,
     // responses to the commands carry "id" property, while notifications do not.
-    if (object.id) {
+    if (this._callbacks.has(object.id)) {
```
Comment (brendankenny) [inline lighthouse-core/gather/connections/connection.js]: what do you think about making this more explicit than treating it like an event if no callback (it's not really an event since the message does have an `id`)? Could do a third case with a call to `formatProtocol` with an explicit `?????` (and no emit).

Also with level `error` so it hits `log.error`? Not sure about that one if this is a regular occurrence in devtools land

**Comment by brendankenny** [comment]
> Good thing we're approved for sentry now let's get it installed post-branch :D

file an issue in that case? We don't want to forget that we're silencing this

File: lighthouse-core/gather/connections/connection.js (hunk 1 above)
Comment (patrickhulce) [inline lighthouse-core/gather/connections/connection.js]: sure

**Comment by patrickhulce** [comment]
@brendankenny filed #2364

File: lighthouse-core/gather/connections/connection.js [hunk 2]
```diff
@@ -106,11 +106,15 @@ class Connection {
           {method: callback.method, params: object.result}, 'verbose');
         return object.result;
       }));
+    } else if (object.id) {
+      const error = object.error && object.error.message;
```
Comment (brendankenny) [inline lighthouse-core/gather/connections/connection.js]: add a comment about why this might happen (pavel's old `"while notifications do not"` comment above probably should also be updated as it implies only two states)

File: lighthouse-core/gather/connections/connection.js [hunk 3]
```diff
@@ -106,11 +106,15 @@ class Connection {
...
+      log.formatProtocol(`disowned method <= browser ${error ? 'ERR' : 'OK'}`,
+          {method: object.method, params: error || object.result}, 'verbose');
```
Comment (brendankenny) [inline lighthouse-core/gather/connections/connection.js]: normalize `object.method` here rather than in `formatProtocol`?

Comment (brendankenny) [inline lighthouse-core/gather/connections/connection.js]: if it's an error, `params` probably shouldn't be set to the message?

Comment (brendankenny) [inline lighthouse-core/gather/connections/connection.js]: and should it still throw if there's an error?

File: lighthouse-core/gather/connections/connection.js [hunk 4]
```diff
@@ -106,11 +106,15 @@ class Connection {
           {method: callback.method, params: object.result}, 'verbose');
         return object.result;
       }));
+    } else if (object.id) {
+      const error = object.error && object.error.message;
+      log.formatProtocol(`disowned method <= browser ${error ? 'ERR' : 'OK'}`,
```
Comment (brendankenny) [inline lighthouse-core/gather/connections/connection.js]: `disowned` may not be a good word here (sounds like LH did send the command but doesn't care about it now :), but not sure of a good replacement.

File: lighthouse-core/gather/connections/connection.js (hunk 3 above)
Comment (patrickhulce) [inline lighthouse-core/gather/connections/connection.js]: > normalize object.method here rather than in formatProtocol?

I'd really rather not, that's exactly what got us into this mess of fatally erroring on unexpected input, unless I'm misunderstanding what you mean by "normalize" haha

> if it's an error, params probably shouldn't be set to the message?

where would you like to log the message then?

> and should it still throw if there's an error?

that would make these fatal in the future which seems bad. the point is that we don't care about these "disowned" (better name pending you 😄 ) events

File: lighthouse-core/gather/connections/connection.js (hunk 2 above)
Comment (patrickhulce) [inline lighthouse-core/gather/connections/connection.js]: done

File: lighthouse-core/gather/connections/connection.js (hunk 4 above)
Comment (brendankenny) [inline lighthouse-core/gather/connections/connection.js]: `nonrequested`?

File: lighthouse-core/gather/connections/connection.js (hunk 3 above)
Comment (brendankenny) [inline lighthouse-core/gather/connections/connection.js]: >> normalize object.method here rather than in formatProtocol?

> I'd really rather not, that's exactly what got us into this mess of fatally erroring on unexpected input, unless I'm misunderstanding what you mean by "normalize"

I mean `const method = object.method || '?????';` here instead of in `formatProtocol` *just* for the logging, not for how it's handled.

> where would you like to log the message then?

For better or worse, `formatProtocol` expects a `data.method` and `data.params`, so it's better to be strict in sending that than to just let it support whatever. `formatProtocol`'s existence now is kind of dumb (all it's really doing beyond `log.verbose` is clipping to the end of the line), but rather than eliminating, maybe we can just quickly revise the parameters rather than overload them?

> that would make these fatal in the future which seems bad

yeah, makes sense.
