### PR TITLE
core(lantern): use fixed times for data URLs

### LINKED ISSUE #9833: lantern: data uris include server response time
I  noticed in the simulator that non-network URLs get treated, I believe, as actual network requests that will use a connection, etc.

Clearly there shouldn't be any server response time, though I think a non-zero RTT makes sense.. probably more like 5-10ms ish.

@patrickhulce can you help me think about how we'd fix this?  Looking through the lantern code I'm not sure where we'd handle this case.

image

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
Special cases non-network protocols in simulator similar to how we special case cached responses. Net effect on our checked-in data overall was minimal (moving just 1 URL from OK to Good). 

Funniest effect was a 15 second *increase* to the pessimistic TTFCPUI where the data URL time was *just* over the threshold before but now that we shortened it to a few ms that quiet window closed and now FCPUI comes after the second wave of activity instead 😆 everything else was very small movement.

**Related Issues/PRs**
closes #9833

### CODE REVIEW

File: lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js [hunk 1]
```diff
@@ -260,20 +278,20 @@ describe('DependencyGraph/Simulator', () => {
     describe('on a real trace', () => {
       const trace = require('../../../fixtures/traces/progressive-app-m60.json');
       const devtoolsLog = require('../../../fixtures/traces/progressive-app-m60.devtools.log.json');
-      let result;
 
-      beforeAll(async () => {
+      it('should compute a timeInMs', async () => {
```
Comment (patrickhulce) [inline lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js]: cleaned this up because it made looking at just one test with `.only` impossible during development

File: lighthouse-core/lib/dependency-graph/network-node.js [hunk 2]
```diff
@@ -7,6 +7,7 @@
 
 const BaseNode = require('./base-node.js');
 const NetworkRequest = require('../network-request.js');
+const URL = require('../url-shim.js');
```
Comment (brendankenny) [inline lighthouse-core/lib/dependency-graph/network-node.js]: We've got to rename this thing at some point

File: lighthouse-core/lib/dependency-graph/network-node.js [hunk 3]
```diff
@@ -57,6 +58,21 @@ class NetworkNode extends BaseNode {
     return !!this._record.fromDiskCache;
   }
 
+  /**
+   * @return {boolean}
+   */
+  get isNonNetworkProtocol() {
```
Comment (brendankenny) [inline lighthouse-core/lib/dependency-graph/network-node.js]: What's up with all getters in this file? Kind of weird :)

File: lighthouse-core/lib/dependency-graph/simulator/simulator.js [hunk 4]
```diff
@@ -295,10 +295,17 @@ class Simulator {
...
+      // 8ms per seek + 20ms/MB
       // @see http://norvig.com/21-days.html#answers
       const sizeInMb = (record.resourceSize || 0) / 1024 / 1024;
       timeElapsed = 8 + 20 * sizeInMb - timingData.timeElapsed;
+    } else if (networkNode.isNonNetworkProtocol) {
+      // Estimates for the overhead of a data URL in Chromium and the decoding time for base64-encoded data.
+      // 2ms per request + 10ms/MB
+      // @see traces on https://dopiaza.org/tools/datauri/examples/index.php
+      const sizeInMb = (record.resourceSize || 0) / 1024 / 1024;
+      timeElapsed = 2 + 10 * sizeInMb - timingData.timeElapsed;
```
Comment (brendankenny) [inline lighthouse-core/lib/dependency-graph/simulator/simulator.js]: Is this low compared to @paulirish's 10-15ms suggestion?

File: lighthouse-core/lib/dependency-graph/network-node.js [hunk 5]
```diff
@@ -57,6 +58,21 @@ class NetworkNode extends BaseNode {
...
+    return URL.NON_NETWORK_PROTOCOLS.includes(this._record.protocol);
```
Comment (brendankenny) [inline lighthouse-core/lib/dependency-graph/network-node.js]: Is it useful to reuse this here vs making a new list here? There are some non network protocols we wouldn't include here (presumably eg intent wouldn't end up as a node, but this list might expand in the future)

File: lighthouse-core/lib/dependency-graph/simulator/simulator.js (hunk 4 above)
Comment (patrickhulce) [reply lighthouse-core/lib/dependency-graph/simulator/simulator.js]: yeah but I couldn't find evidence to support that much overhead on some test pages and 10-15 seemed too high compared to our read from disk estimates, @paulirish do you have any docs we could link to to support 10-15ms? 

happy to use whatever we have clear evidence of

File: lighthouse-core/lib/dependency-graph/network-node.js (hunk 5 above)
Comment (patrickhulce) [reply lighthouse-core/lib/dependency-graph/network-node.js]: I'm not sure when this would actually need to diverge from our canonical set, so I'd prefer to reuse. It's true it will include things we don't actually need to test but I doubt the reverse will ever be true

File: lighthouse-core/lib/dependency-graph/network-node.js [hunk 6]
```diff
@@ -57,6 +58,21 @@ class NetworkNode extends BaseNode {
...
+  }
+
+
+  /**
+   * @return {boolean}
```
Comment (brendankenny) [inline lighthouse-core/lib/dependency-graph/network-node.js]: a jsdoc description might help explain the purpose of this

File: lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js [hunk 7]
```diff
@@ -118,6 +118,24 @@ describe('DependencyGraph/Simulator', () => {
...
+      const parsedURL = {scheme: 'data', host: '', securityOrigin: 'null'};
+      const nodeA = new NetworkNode(request({startTime: 0, endTime: 1, url, parsedURL, protocol}));
+      const nodeB = new NetworkNode(request({startTime: 0, endTime: 3, url, parsedURL, protocol,
+        resourceSize: 1024 * 1024}));
+      nodeA.addDependent(nodeB);
+
+      const simulator = new Simulator({serverResponseTimeByOrigin});
+      const result = simulator.simulate(nodeA);
+
+      // should be ~2ms for A, ~12ms for B
```
Comment (brendankenny) [inline lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js]: for clarity for future tinkerers, maybe
```suggestion
      // should be ~2ms for A (resourceSize 0), ~12ms for B (resourceSize 1MB)
```
...or else a comment up on the node creation lines calling out the resourceSize?

File: lighthouse-core/lib/dependency-graph/simulator/simulator.js (hunk 4 above)
Comment (brendankenny) [reply lighthouse-core/lib/dependency-graph/simulator/simulator.js]: > happy to use whatever we have clear evidence of

I'd guess that @paulirish was ballparking, too, so let's call this good and we can revisit later if somehow these end up giving us bizarre lantern graphs or something (seems very unlikely :)

Comment (paulirish) [reply lighthouse-core/lib/dependency-graph/simulator/simulator.js]: yah was just ballparking. I went looking in UMA yesterday but couldnt spot a relevant histogram.

Seems fine for now. 👍
