### PR TITLE
Viewport test: accept initial-scale and allow spaces

### LINKED ISSUE #641: Viewport description isn't clear why it's failing
I'm getting a "No" for "HTML has a viewport <meta>" despite the site containing:
 `<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />`

Only on inspecting the source code do I see that it's [explicitly looking](https://github.com/GoogleChrome/lighthouse/blob/eb5f0f69c0c9f6102b6fda6a8373dd2a5543e7cf/lighthouse-core/audits/viewport.js#L40) for "width="

Could this be made clearer, so users know what they need to fix?

I also don't fully understand the practical purpose of specifying the width in the viewport.  My PWAs usually look fine just using "initial-scale=1.0".

### PR DESCRIPTION
**Pull request by dracos**
Fixes #641. and comments in it; allow a viewport to pass if it has width *or* initial-scale, and tweak the displayed error message to say this. It also allows spaces in the viewport elements, they are explicitly given in an example on e.g. https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193

### CODE REVIEW

**Comment by wardpeet** [comment]
thanks for this one :) can you add a test case for this as well.

**Comment by dracos** [comment]
Done! Whilst I agree with your comment elsewhere it probably wants to check for more (though for accessibility, I don’t think it can just be ‘any valid value’ e.g. if it was just maximum-scale!), I think this would hopefully count as a good incremental change prior to that happening, rather than waiting for it to be fully decided :)

File: lighthouse-core/test/audits/viewport-test.js [hunk 1]
```diff
@@ -38,4 +38,16 @@ describe('Mobile-friendly: viewport audit', () => {
       Viewport: 'width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1'
     }).rawValue, true);
   });
+
+  it('passes when a viewport with spaces is provided', () => {
```
Comment (ebidel) [inline lighthouse-core/test/audits/viewport-test.js]: instead of separate tests, what if we expand the "'passes when a viewport is provided" test with a few permutations. Could just rename it to 'passes when a valid viewport is provided'. WDYT?

Comment (dracos) [inline lighthouse-core/test/audits/viewport-test.js]: I’m happy either way, whichever would better fit your existing tests; I assume a failure would be as verbose either way. Pushed change.

**Comment by paulirish** [comment]
http://andreasbovens.github.io/understanding-viewport/ is a good resource for understanding various viewports and how phones handle them.

it looks like just initial-scale is satisfactory for this test, yup.  Nice!

**Comment by ebidel** [comment]
@dracos There's also a line length issue after my rebase fix. If you can take care of it, that would be splendid :)

**Comment by dracos** [comment]
@paulirish Thanks for that! Merged and squashed.
@ebidel Fixed :)

**Comment by paulirish** [comment]
@ebidel can you take another look?

File: lighthouse-core/audits/viewport.js [hunk 2]
```diff
@@ -38,8 +39,15 @@ class Viewport extends Audit {
    * @return {!AuditResult}
    */
   static audit(artifacts) {
-    const hasMobileViewport = typeof artifacts.Viewport === 'string' &&
-        artifacts.Viewport.includes('width=');
+    if (typeof artifacts.Viewport !== 'string') {
+      return Viewport.generateAuditResult({
+        rawValue: false
```
Comment (ebidel) [inline lighthouse-core/audits/viewport.js]: This should be an error case:

```
debugString: 'Error in determining viewport',
rawValue: -1
```

see https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/dobetterweb/no-datenow.js#L57-L59

File: lighthouse-core/audits/viewport.js [hunk 3]
```diff
@@ -38,8 +39,15 @@ class Viewport extends Audit {
...
+      });
+    }
+
+    const viewportProps = Parser.parseMetaViewPortContent(artifacts.Viewport).validProperties;
+    const hasMobileViewport = viewportProps['width'] || viewportProps['initial-scale'];
```
Comment (ebidel) [inline lighthouse-core/audits/viewport.js]: dot notation where you can: `viewportProps.width`

File: lighthouse-core/test/audits/viewport-test.js [hunk 4]
```diff
@@ -33,9 +33,16 @@ describe('Mobile-friendly: viewport audit', () => {
...
 
-  it('passes when a viewport is provided', () => {
-    return assert.equal(Audit.audit({
-      Viewport: 'width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1'
-    }).rawValue, true);
+  it('passes when a valid viewport is provided', () => {
+    const viewports = [
+      'width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1',
+      'width = device-width, initial-scale = 1',
+      'initial-scale=1',
```
Comment (ebidel) [inline lighthouse-core/test/audits/viewport-test.js]: let's include one with just `width` as well.

**Comment by ebidel** [comment]
Nice changes. A few more things after the change.

File: lighthouse-core/audits/viewport.js [hunk 5]
```diff
@@ -38,8 +39,15 @@ class Viewport extends Audit {
...
   static audit(artifacts) {
-    const hasMobileViewport = typeof artifacts.Viewport === 'string' &&
-        artifacts.Viewport.includes('width=');
+    if (typeof artifacts.Viewport !== 'string') {
+      return Viewport.generateAuditResult({
+        rawValue: false
+      });
+    }
+
+    const viewportProps = Parser.parseMetaViewPortContent(artifacts.Viewport).validProperties;
```
Comment (ebidel) [inline lighthouse-core/audits/viewport.js]: now that we have a parser, it might be nice to also warn if there are `unknownProperties` or `invalidValues` values. If that's the case, add a debugString to the artifact.

```
let debugString = '';
const parsedProps = Parser.parseMetaViewPortContent(artifacts.Viewport);

if (Object.keys(parsedProps.unknownProperties).length) {
  debugString += `Invalid properties found: ${parsedProps.unknownProperties}`;
}
if (Object.keys(parsedProps.invalidValues).length) {
  debugString += `Invalid values found: ${parsedProps.invalidValues}`;
}

const viewportProps = parsedProps.validProperties;
const hasMobileViewport = viewportProps.width || viewportProps['initial-scale'];

Viewport.generateAuditResult({
  rawValue: !!hasMobileViewport
  debugString
});
```

**Comment by dracos** [comment]
All done!

File: lighthouse-core/audits/viewport.js [hunk 6]
```diff
@@ -38,8 +39,38 @@ class Viewport extends Audit {
...
+
+    const viewportProps = parsedProps.validProperties;
+    const hasMobileViewport = viewportProps.width || viewportProps['initial-scale'];
+
+    Viewport.generateAuditResult({
+      rawValue: !!hasMobileViewport,
+      debugString
+    });
+
+    if (typeof artifacts.Viewport !== 'string') {
```
Comment (ebidel) [inline lighthouse-core/audits/viewport.js]: whoops. this is duplicated from the top.

Comment (dracos) [inline lighthouse-core/audits/viewport.js]: Whoops!

File: lighthouse-core/test/audits/viewport-test.js [hunk 7]
```diff
@@ -24,7 +24,7 @@ describe('Mobile-friendly: viewport audit', () => {
   it('fails when no input present', () => {
     return assert.equal(Audit.audit({
       Viewport: -1
-    }).rawValue, false);
+    }).rawValue, -1);
```
Comment (ebidel) [inline lighthouse-core/test/audits/viewport-test.js]: Sorry! One more thing can you add a test that checks that there's a `debugString` present for this case?

Comment (dracos) [inline lighthouse-core/test/audits/viewport-test.js]: Yep :)

Comment (ebidel) [inline lighthouse-core/test/audits/viewport-test.js]: Solid!

File: lighthouse-core/audits/viewport.js [hunk 8]
```diff
@@ -38,10 +39,29 @@ class Viewport extends Audit {
...
+    }
+
+    let debugString = '';
+    const parsedProps = Parser.parseMetaViewPortContent(artifacts.Viewport);
+
+    if (Object.keys(parsedProps.unknownProperties).length) {
+      debugString += `Invalid properties found: ${parsedProps.unknownProperties}`;
+    }
+    if (Object.keys(parsedProps.invalidValues).length) {
+      debugString += `Invalid values found: ${parsedProps.invalidValues}`;
```
Comment (brendankenny) [inline lighthouse-core/audits/viewport.js]: this debugString probably needs some separator between the two parts in case there are invalid properties and invalid values

File: lighthouse-core/test/audits/viewport-test.js [hunk 9]
```diff
@@ -33,9 +35,17 @@ describe('Mobile-friendly: viewport audit', () => {
     }).rawValue, false);
   });
```
Comment (brendankenny) [inline lighthouse-core/test/audits/viewport-test.js]: maybe add a better failure case than just not having a viewport meta tag? e.g. a non-mobile friendly but valid viewport

Also is it worth adding a test for an invalid property and/or value and test to make sure it's in the `debugString`?

Comment (dracos) [inline lighthouse-core/test/audits/viewport-test.js]: Added some more tests for this.
Used JSON.stringify to print out the invalid property/values, sorry if there's a better way of doing this that I missed!

File: lighthouse-core/audits/viewport.js [hunk 10]
```diff
@@ -38,10 +39,30 @@ class Viewport extends Audit {
...
+    let debugString = '';
+    const parsedProps = Parser.parseMetaViewPortContent(artifacts.Viewport);
+
+    if (Object.keys(parsedProps.unknownProperties).length) {
+      debugString += `Invalid properties found: ${JSON.stringify(parsedProps.unknownProperties)}. `;
+    }
+    if (Object.keys(parsedProps.invalidValues).length) {
+      debugString += `Invalid values found: ${JSON.stringify(parsedProps.invalidValues)}. `;
+    }
+    debugString = debugString.trim();
```
Comment (brendankenny) [inline lighthouse-core/audits/viewport.js]: nice solution :)
