### PR TITLE
Fix bug when short_name is not present name is not used for audit

### LINKED ISSUE #348: manifest's "short_name" isn't required if "name" is short enough
See this thread for details: https://twitter.com/nekrtemplar/status/734483891071922182

Not sure about what is exactly "short enough", but 4 symbols seems to be.

### PR DESCRIPTION
**Pull request by wardpeet**
Fixes #348

### CODE REVIEW

**Comment by wardpeet** [comment]
I signed it!

File: src/audits/manifest/short-name-length.js [hunk 1]
```diff
@@ -50,14 +50,17 @@ class ManifestShortNameLength extends Audit {
     let debugString;
     const manifest = artifacts.manifest.value;
     const suggestedLength = 12;
+    const shortNameValue = manifest && manifest.short_name && manifest.short_name.value;
```
Comment (samccone) [inline src/audits/manifest/short-name-length.js]: can we add helper fns here instead of depending on the && last value behavior in JS

File: src/audits/manifest/short-name.js [hunk 2]
```diff
@@ -49,8 +49,10 @@ class ManifestShortName extends Audit {
     let hasShortName = false;
     const manifest = artifacts.manifest.value;
 
-    if (manifest && manifest.short_name) {
-      hasShortName = (!!manifest.short_name.value);
+    if (manifest) {
+      const manifestValue = manifest.short_name && manifest.short_name.value ||
```
Comment (samccone) [inline src/audits/manifest/short-name.js]: ditto above comment

**Comment by samccone** [comment]
I like what is going on here, thanks @wardpeet :) Just a few comments ... Thanks!

File: src/audits/manifest/short-name-length.js (hunk 1 above)
Comment (wardpeet) [inline src/audits/manifest/short-name-length.js]: would it be ok to use Conditional (ternary) Operator?

Comment (samccone) [inline src/audits/manifest/short-name-length.js]: yep :) I still like just a function or something but a ternary is nicer than an && chain

Comment (wardpeet) [inline src/audits/manifest/short-name-length.js]: will make functions :) will be more readable indeed

File: src/audits/manifest/short-name-length.js [hunk 3]
```diff
@@ -50,14 +50,17 @@ class ManifestShortNameLength extends Audit {
...
+    const nameValue = manifest && manifest.name && manifest.name.value;
+    const manifestValue = shortNameValue || nameValue;
 
-    if (manifest && manifest.short_name && manifest.short_name.value) {
+    if (manifestValue) {
       // Historically, Chrome recommended 12 chars as the maximum length to prevent truncation.
```
Comment (paulirish) [inline src/audits/manifest/short-name-length.js]: Can you add a comment here that explains that name is used if short_name not present (hopefully with a link to the docs/source on that?)

Comment (wardpeet) [inline src/audits/manifest/short-name-length.js]: Will do :)

**Comment by wardpeet** [comment]
Will have an updated pr later today :)

**Comment by wardpeet** [comment]
As promised :)
1 thing i don't like is that I duplicate _getManifestShortName & _getManifestName. I rather put them in src/lib/util/manifest-helpers.js (or something) and just export those functions.

Another option is appending a getter function to the manifest object manifest.getValue('short_name')

**Comment by paulirish** [comment]
It definitely gets pretty low signal:noise with this breakout.

I have a PR against ward's fork that tries out lodash.get. 
It gives some nice brevity and i'm looking forward to using it elsewhere in the project.

https://github.com/wardpeet/lighthouse/pull/1

**Comment by wardpeet** [comment]
Looks better, didn't knew i could use this `resolvedName = shortNameValue || nameValue;` because of @samccone comment on &&. Merging as we speak

**Comment by wardpeet** [comment]
mmh somehow i get rejected but when i run it locally i have no issues.

**Comment by samccone** [comment]
Fixes #350 also

File: package.json [hunk 4]
```diff
@@ -38,6 +38,7 @@
     "gl-matrix": "2.3.2",
     "handlebars": "^4.0.5",
     "jszip": "2.6.0",
+    "lodash.get": "^4.3.0",
```
Comment (samccone) [inline package.json]: I would prefer not adding a new dep and just using the previous approach for now. We can tackle this cleanup after

File: src/audits/manifest/short-name-length.js [hunk 5]
```diff
@@ -48,16 +49,26 @@ class ManifestShortNameLength extends Audit {
...
     const suggestedLength = 12;
 
-    if (manifest && manifest.short_name && manifest.short_name.value) {
+    if (manifest) {
+      const shortNameValue = _get(manifest, 'short_name.value');
+      const nameValue = _get(manifest, 'name.value');
+
+      // When no shortname can be found we look for a name
+      // https://developer.chrome.com/apps/manifest/name#short_name
+      resolvedName = shortNameValue || nameValue;
```
Comment (samccone) [inline src/audits/manifest/short-name-length.js]: let's be explicit here and check for !== undefined instead of depending on the type coercion

**Comment by samccone** [comment]
Hey @wardpeet thanks for the PR!!! 🍝 

The failure is due to the closure compiler not knowing what _get is. For now as I said in the codereview let's just drop the new dependency (we can tackle that cleanup after we land this)

Thanks again for the PR, looking forward to landing this one!

File: package.json (hunk 4 above)
Comment (paulirish) [inline package.json]: > I would prefer not adding a new dep and just using the previous approach for now.

This was my doing. The fix was grossly verbose without it. :/

File: src/audits/manifest/short-name.js [hunk 6]
```diff
@@ -49,8 +50,11 @@ class ManifestShortName extends Audit {
     let hasShortName = false;
     const manifest = artifacts.manifest.value;
 
-    if (manifest && manifest.short_name) {
-      hasShortName = (!!manifest.short_name.value);
+    // putting a comment to test travis again
```
Comment (brendankenny) [inline src/audits/manifest/short-name.js]: :)

File: src/audits/manifest/short-name-length.js [hunk 7]
```diff
@@ -48,16 +49,26 @@ class ManifestShortNameLength extends Audit {
   static audit(artifacts) {
     let isShortNameShortEnough = false;
     let debugString;
+    let resolvedName;
     const manifest = artifacts.manifest.value;
     const suggestedLength = 12;
 
-    if (manifest && manifest.short_name && manifest.short_name.value) {
+    if (manifest) {
+      const shortNameValue = _get(manifest, 'short_name.value');
```
Comment (brendankenny) [inline src/audits/manifest/short-name-length.js]: even with `_get` this is more complicated than it needs to be. [`short_name` and `name` are always defined on the manifest](https://github.com/GoogleChrome/lighthouse/blob/500ba29394133706579d0002443ee686aef26f21/src/lib/manifest-parser.js#L280-L281); it's their `value` properties that may be `undefined`. Since `manifest` is already checked above, this whole block can be as simple as `resolvedName = manifest.short_name.value || manifest.name.value;`

File: src/audits/manifest/short-name.js [hunk 8]
```diff
@@ -49,8 +50,11 @@ class ManifestShortName extends Audit {
...
+    if (manifest) {
+      const manifestShortName = _get(manifest, 'short_name.value');
+      const manifestName = _get(manifest, 'name.value');
+      hasShortName = !!(manifestShortName || manifestName);
```
Comment (brendankenny) [inline src/audits/manifest/short-name.js]: `hasShortName = !!(manifest.short_name.value || manifest.name.value);`

File: src/audits/manifest/short-name-length.js (hunk 5 above)
Comment (brendankenny) [inline src/audits/manifest/short-name-length.js]: Technically, an empty string for a `name` or a `short_name` (or a string of only whitespace, which is `trim`med down to the empty string) *is* a valid `name` or `short_name`, AFAICT [from the spec](https://www.w3.org/TR/appmanifest/#name-member). The current PR will fail a `resolvedName` of an empty string, so with that in mind should check against `undefined`.

*But*, I believe Chrome, at least, rejects empty strings for names, so it's worth still rejecting those. Testing for truthiness is an equivalent shorthand for `resolvedName !== undefined && resolvedName !== ''` since we know they're of type `string|undefined`. Probably still be worth making a comment that we're specifically rejecting the empty sting even though the web app manifest spec is cool with it, though.

File: src/audits/manifest/short-name.js (hunk 8 above)
Comment (samccone) [inline src/audits/manifest/short-name.js]: yep once _get is dropped this will be what we want.. right now it is working due to _get

**Comment by wardpeet** [comment]
ok i got lost :p so should i go back to the helpers i created or just do the `hasShortName = !!(manifest.short_name.value || manifest.name.value);`

**Comment by brendankenny** [comment]
@wardpeet sorry, nothing like reviewers disagreeing with each other to make everything crystal clear :)

Unless others disagree, I believe my suggestion above is the way to go. It's not verbose, as @paulirish wanted to avoid, and it doesn't introduce a new dependency, as @samccone wanted to avoid. It's also correct for handling all the possible types the manifest parser could hand back, so you'll have covered all your bases there as well.

**Comment by samccone** [comment]
:+1: sounds good @brendankenny

**Comment by paulirish** [comment]
> Unless others disagree, I believe my suggestion above is the way to go

👍

**Comment by wardpeet** [comment]
I used @brendankenny suggestion and it looks like it works now. I removed 2 tests from the length check because they are begin checked in another test

**Comment by paulirish** [comment]
lgtm. thanks for being a trooper on this, @wardpeet. we feel really bad we jerked you around. :/

File: src/audits/manifest/short-name-length.js [hunk 9]
```diff
@@ -42,13 +42,17 @@ class ManifestShortNameLength extends Audit {
...
 
-    if (manifest && manifest.short_name && manifest.short_name.value) {
+    if (manifest) {
+      // When no shortname can be found we look for a name
       // Historically, Chrome recommended 12 chars as the maximum length to prevent truncation.
       // See #69 for more discussion.
-      isShortNameShortEnough = (manifest.short_name.value.length <= suggestedLength);
+      // https://developer.chrome.com/apps/manifest/name#short_name
+      let manifestValue = manifest.short_name.value || manifest.name.value || '';
+      isShortNameShortEnough = manifestValue && manifestValue.length <= suggestedLength;
```
Comment (brendankenny) [inline src/audits/manifest/short-name-length.js]: 👍

Comment (wardpeet) [inline src/audits/manifest/short-name-length.js]: @paulirish  no problem :) Glad I could be a part of the discussion :p

File: test/src/audits/manifest/short-name.js [hunk 10]
```diff
@@ -34,15 +34,26 @@ describe('Manifest: short_name audit', () => {
 
   // Need to disable camelcase check for dealing with short_name.
   /* eslint-disable camelcase */
-  it('fails when a manifest contains no short_name', () => {
+  it('fails when a manifest contains no short_name and no name', () => {
```
Comment (brendankenny) [inline test/src/audits/manifest/short-name.js]: this test isn't doing what it says it's doing. Would you mind fixing it as one last thing while you're in here? :)

This is testing the actual manifest format, not the parsed manifest object. It just fails the `if (manifest)` test (since `manifest` there is actually `manifest.value`, which is undefined on the `inputs` object below) and so returns `hasShortName ` as false immediately instead of checking the values of `name` and `short_name` as it should be.

This test needs to be like the others, parsing the manifest first, then passing that in:
```
const inputs = JSON.stringify({
  name: null,
  short_name: null
});
const manifest = manifestParser(inputs);

return assert.equal(Audit.audit({manifest}).value, false);
```

**Comment by brendankenny** [comment]
one last thing and then LGTM too

File: test/src/audits/manifest/short-name.js (hunk 10 above)
Comment (wardpeet) [inline test/src/audits/manifest/short-name.js]: I think that piece was already there but no problem :)

**Comment by wardpeet** [comment]
And it's added 👍

File: test/src/audits/manifest/short-name.js (hunk 10 above)
Comment (brendankenny) [inline test/src/audits/manifest/short-name.js]: hmm, I don't see it here?

Comment (brendankenny) [inline test/src/audits/manifest/short-name.js]: oh, it's up in `short-name-length.js`. I meant to replace this test here in this file

File: test/src/audits/manifest/short-name-length.js [hunk 11]
```diff
@@ -27,15 +27,29 @@ describe('Manifest: short_name_length audit', () => {
 
   // Need to disable camelcase check for dealing with short_name.
   /* eslint-disable camelcase */
-  it('fails when a manifest contains no short_name', () => {
+  it('fails when a manifest contains no short_name and no name', () => {
+    const inputs = JSON.stringify({
+      name: null,
+      short_name: null
```
Comment (brendankenny) [inline test/src/audits/manifest/short-name-length.js]: should live in the `short-name.js` test since this isn't really testing name length

**Comment by brendankenny** [comment]
LGTM! Thanks for your patience

**Comment by paullewis** [comment]
Thanks from me, too... This was one lengthy PR tennis match!

**Comment by wardpeet** [comment]
No worries ;) glad I could help. And hey now I can say I got a PR from @paulirish :p
