### PR TITLE
core(gather): handle crash if CDP target crashes

### LINKED ISSUE #11827: Handle Inspector.targetCrashed event
If the CDP target we're inspecting crashes, we have to quit with a FATAL error.

### PR DESCRIPTION
**Pull request by paulirish**
fixes #11827 

page could crash (what we saw there).  we can't recover from that, and we should quit.

the CDP connection could also detach.. this happens if you manually close the tab while lighthouse is gathering.  Update: our pptr layer handles this part just fine. we die fatally very quickly when this happens already.

### CODE REVIEW

File: lighthouse-core/gather/gather-runner.js [hunk 1]
```diff
@@ -115,6 +115,24 @@ class GatherRunner {
...
+   * @return {Promise<void>}
+   */
+  static async getGatherTerminatedPromise(driver) {
+    return new Promise((_, reject) => {
+      driver.on('Inspector.targetCrashed', _ => {
+        reject(new LHError(LHError.errors.TARGET_CRASHED));
+      });
+      // In case of crash, detached fires after targetCrashed, so we'll exit with the crash code
+      // Detachment happens (in non-crash cases) when the browser tab is closed or unexpected connection failure.
+      driver.on('Inspector.detached', _ => {
```
Comment (patrickhulce) [inline lighthouse-core/gather/gather-runner.js:130]: Do we need to filter these to particular targets? i.e. I could see a frame detaching if it's removed or something, but I'm not sure

File: lighthouse-core/gather/gather-runner.js [hunk 2]
```diff
@@ -115,6 +115,24 @@ class GatherRunner {
...
   }
 
+  /**
+   * Reject if the gathering terminates due to the CDP target crashing, etc
+   * @param {Driver} driver
+   * @return {Promise<void>}
+   */
+  static async getGatherTerminatedPromise(driver) {
+    return new Promise((_, reject) => {
+      driver.on('Inspector.targetCrashed', _ => {
```
Comment (patrickhulce) [inline lighthouse-core/gather/gather-runner.js:125]: if iframes crash should we still consider it fatal?

File: lighthouse-core/runner.js [hunk 3]
```diff
@@ -230,8 +230,13 @@ class Runner {
       requestedUrl,
       settings: runnerOpts.config.settings,
     };
-    const artifacts = await GatherRunner.run(runnerOpts.config.passes, gatherOpts);
-    return artifacts;
+    const gatherPromise = GatherRunner.run(runnerOpts.config.passes, gatherOpts);
+    await Promise.race([
+      gatherPromise,
+      GatherRunner.getGatherTerminatedPromise(driver),
```
Comment (patrickhulce) [inline lighthouse-core/runner.js:236]: Congratulations this is one of the only forked areas where we need to worry about duplication for FR 🎉  lucky you! 😃 

would you be able to add this to the snapshot runner and use the shared `FRTransitionalDriver` type instead? :)

living in gather-runner feels a little weird at that point, but I don't have a clean new place or suggestion for it. ideas?

File: lighthouse-core/test/runner-test.js [hunk 4]
```diff
@@ -789,6 +793,25 @@ describe('Runner', () => {
       expect(lhr.runtimeError.message).toBeDisplayString(/did not paint any content.*\(NO_FCP\)/);
     });
 
+
+    it('includes a crash runtimeError when there\'s a crash during gathering', async () => {
```
Comment (patrickhulce) [inline lighthouse-core/test/runner-test.js:797]: I'd love to get a smoketest of this, but it's too hard without puppeteer. Maybe with FR support one can be added to the pptr test suite there? :D

File: lighthouse-core/gather/gather-runner.js [hunk 5]
```diff
@@ -115,6 +115,24 @@ class GatherRunner {
     return {};
   }
 
+  /**
+   * Reject if the gathering terminates due to the CDP target crashing, etc
```
Comment (patrickhulce) [inline lighthouse-core/gather/gather-runner.js:119]: non-review comment below

Worth noting here for lurkers that this is a good example our long-standing tradition of memory leak listeners that are never removed and promises that never die. We have a ton of these, so shouldn't need to do anything differently here, but a few folks have asked recently about why we recommend child processes and disposable contexts, this is why :)

**Review by patrickhulce — COMMENTED** [review]
impl sounds right to me! but we also discussed the impl a bit haha

if anyone else wants to weigh in on the fact that it's a race at the highest gather level, feel free :)

File: lighthouse-core/gather/gather-runner.js (hunk 1 above)
Comment (paulirish) [reply lighthouse-core/gather/gather-runner.js:130]: so `Target.detachedFromTarget` is fired if an iframe/SW is removed.

but `Inspector.detached` is the special event that announces unexpected CDP detachments. it's what was introduced to improve the UX before multiclient CDP was available.

so nah we don't need to filter this one.

File: lighthouse-core/gather/gather-runner.js (hunk 2 above)
Comment (paulirish) [reply lighthouse-core/gather/gather-runner.js:125]: good question.. if an iframe shares a process with its parent.. it takes down both. (naturally)

but here's a iframe page crash when that iframe is isolated (oopif):

image

and.......... 

if we didn't explicitly attach to that iframe target.. we'd just see a `Target.targetCrashed` event, but not a `Inspector.targetCrashed` one.

but we DO  autoattach to iframe targets. so we're attached. and thus we'll get the full fledged `Inspector.targetCrashed`.  :)



i don't think there's an easy call here, but ... probably yes.

Comment (patrickhulce) [reply lighthouse-core/gather/gather-runner.js:125]: nice sleuthing thanks :) 

I suppose if we ever have a single gatherer that tries to evaluate something in subtarget contexts we will need to support this (framehole maybe?), so SGTM 👍

File: lighthouse-core/test/runner-test.js (hunk 4 above)
Comment (paulirish) [reply lighthouse-core/test/runner-test.js:797]: maybe doable. looks like it requires a 

```js
driver.gotoURL('chrome://crash');
```

you can't navigate to that URL clientside, so i think it's gotta come via protocol.

**Comment by connorjclark** [comment]
@paulirish we still want this?

File: lighthouse-core/test/runner-test.js (hunk 4 above)
Comment (connorjclark) [reply lighthouse-core/test/runner-test.js:804]: yea this really could use a smoke test

**Comment by connorjclark** [comment]
Can you update the branch?

**Comment by connorjclark** [comment]
image

File: lighthouse-core/gather/driver.js [hunk 6]
```diff
@@ -122,6 +122,28 @@ class Driver {
...
+
+    return new Promise((_, reject) => {
+      this.on('Inspector.targetCrashed', async _ => {
+        await wait(1000);
+        reject(new LHError(LHError.errors.TARGET_CRASHED));
+      });
+      // In case of crash, detached fires after targetCrashed, so we'll exit with the crash code
+      // Detachment happens (in non-crash cases) when the browser tab is closed or unexpected connection failure.
+      this.on('Inspector.detached', async _ => {
+        await wait(1000);
```
Comment (connorjclark) [inline lighthouse-core/gather/driver.js:141]: Is the second because there is time between proper driver disposal and when GatherRunner.run resolves?

ie https://github.com/GoogleChrome/lighthouse/blob/de1fd107c42e12be977ccbc4c19c2ea7e1da2a2f/lighthouse-core/gather/gather-runner.js#L539-L540 just finalizeArtifacts runs between dispose and resolve, and if you look at that function it is not doing anything heavy. so a second will certainly cover that.

**Comment by paulirish** [comment]
Also, let's ensure that we handle detachment of cdp targets (like oopifs) reasonably.

**Comment by paulirish** [comment]
How about another attempt! :)

Thoughts on this setup?

The runners' diffs look big but its mostly because I wanted to assign their enormous anon fn to `gatherFn`.  That could be in its own PR. 

I spent a while trying to get a test for this but it's wildly hard. This impl needs a non-mock x-runner, driver and session. And... we don't have any tests that are that free of mocks. I managed to almost create one, but it failed.

Perhaps folks will have impl ideas that might also improve testability?  (Moving from session to driver could help, probably).

File: core/gather/timespan-runner.js [hunk 7]
```diff
@@ -33,8 +34,10 @@ async function startTimespanGather(page, options = {}) {
   log.setLevel(flags.logLevel || 'error');
 
   const {resolvedConfig} = await initializeConfig('timespan', config, flags);
+  const {promise: crashP, rej: crashRej} = getRejectionCallback();
+
   const driver = new Driver(page);
-  await driver.connect();
+  await driver.connect(crashRej);
```
[the remark this answers is not in the document]
Comment (paulirish) [reply core/gather/timespan-runner.js]: Thanks so much. I had similar thoughts.. 

I've pushed an update that should look a bit cleaner.  Nav-runner is a tad more awkward than the other too, but hopefully it should be clear what's going on.

general vibe sgty? if so, i'll get the unittests updated and a smoketest written.

File: core/runner.js [hunk 8]
```diff
@@ -199,32 +199,33 @@ class Runner {
...
+      }
+
+      const runnerStatus = {msg: 'Gather phase', id: 'lh:runner:gather'};
+      log.time(runnerStatus, 'verbose');
+
+      const gatherFnPromise = gatherFn({resolvedConfig: options.resolvedConfig});
+      // If the fatalGatherPromise rejects, we'll end up in the catch below.
+      // Therefore, `theArtifacts` will reliably be artifacts, despite the type inference.
+      const theArtifacts = await Promise.race([gatherFnPromise, options.fatalGatherPromise]);
+      const artifacts = /** @type {LH.Artifacts} */ (theArtifacts);
```
[the remark this answers is not in the document]
Comment (paulirish) [reply core/runner.js:217]: yes

File: core/gather/driver.js [hunk 9]
```diff
@@ -46,6 +47,7 @@ class Driver {
     this._fetcher = undefined;
 
     this.defaultSession = throwingSession;
+    this.fatalRejection = Driver.getRejectionCallback();
   }
```
[the remark this answers is not in the document]
Comment (paulirish) [reply core/gather/driver.js:56]: it was kinda dumb for me to have a utility method living on driver so i could use it twice.

latest commit: i inlined it into the constructor and in nav-runner.  i think the lifecycles are more clear now.

File: core/runner.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (paulirish) [reply core/runner.js]: hell yeah it does!  :)  i was looking for such a trick. nice!

**Comment by paulirish** [comment]
>> I spent a while trying to get a test for this but it's wildly hard. This impl needs a non-mock x-runner, driver and session. And... we don't have any tests that are that free of mocks. I managed to almost create one, but it failed.

> Auditing `chrome://crash` was enough to get TARGET_CRASHED instantly, whereas before LH would hang then finally PROTOCOL_TIMEOUT.
> A smoke test could be possible, but we need to rework how we handle no output being generated (we currently throw `throw new ChildProcessError`). Another option is to add a test in `cli/index-test.js`.

This got me thinking about it a little differently. 

I had this rejecting out of LH extremely quickly. No LHR, nothing. But I also now remember taking the stance that we should ALWAYS create an LHR.   The fact that we don't is why we (and probably others) have to do [stuff like this](https://github.com/GoogleChrome/lighthouse/blob/458ded802cc48c2b92f07433ef8aa29eb5fbb53d/clients/lightrider/lightrider-entry.js#L129-L143).

I moved the rejection race elsewhere and now it gets an LHR built for free. (And our smoketest runtimeError assertions are also fine. yay we have a test)

**Review by penguin733 — COMMENTED** [review]
_ put the wrong email. I cant get in that email. 
_

File: core/runner.js [hunk 10]
```diff
@@ -199,32 +199,27 @@ class Runner {
...
+      // If `gather` is run multiple times before `audit`, the timing entries for each `gather` can pollute one another.
+      // We need to clear the timing entries at the end of gathering.
+      // Set artifacts.Timing again to ensure lh:runner:gather is included.
+      artifacts.Timing = log.takeTimeEntries();
+
+      // -G means save these to disk (e.g. ./latest-run).
+      if (settings.gatherMode) {
+        const path = this._getDataSavePath(settings);
+        await assetSaver.saveArtifacts(artifacts, path);
       }
```
[the remark this answers is not in the document]
Comment (paulirish) [reply core/runner.js:228]: an earlier version of this branch definitely made changes here, but.. no longer.
so yeah i split it out: https://github.com/GoogleChrome/lighthouse/pull/15914

**Comment by paulirish** [comment]
@connorjclark this is ready for another review. (sorry i forget our workflow conventions :)
