### PR TITLE
core(redirects): update to modern opportunity details type

### LINKED ISSUE #5778: Redirects opportunity squished in report
noticed this recently: 
image

Not sure if it's a recent regression... will look into it.

### PR DESCRIPTION
**Pull request by paulirish**
fixes #5778
seems like this was accidentally left out of #5296 and we didn't catch it.

but the real question is: where should this test go?

### CODE REVIEW

**Comment by brendankenny** [comment]
> but the real question is: where should this test go?

we're going to make a `default-config-test.js` :)

**Comment by brendankenny** [comment]
@paulirish updated, LMKWYT

File: lighthouse-core/index.js [hunk 1]
```diff
@@ -26,9 +26,9 @@ const Config = require('./config/config');
  */
 
 /**
- * @param {string} url
+ * @param {string=} url
  * @param {LH.Flags=} flags
- * @param {LH.Config.Json|undefined} configJSON
+ * @param {LH.Config.Json=} configJSON
```
Comment (brendankenny) [inline lighthouse-core/index.js]: these (and below in runner) were some drive by fixes I noticed since the test is calling `index.js` directly, and the URL is now optional after #5495

File: lighthouse-core/test/config/default-config-test.js [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+ */
+'use strict';
+
+const assert = require('assert');
+const lighthouse = require('../../index.js');
+const defaultConfig = require('../../config/default-config.js');
+
+/* eslint-env jest */
+
+describe.only('Default Config', () => {
```
Comment (paulirish) [inline lighthouse-core/test/config/default-config-test.js]: only

**Comment by paulirish** [comment]
LGTM
