### PR TITLE
Fixes Speedline for extension

### LINKED ISSUE #269: Extension shows -1 for Speed Index
Bit of digging suggests it's to do with the DevTools model stuff:

screen shot 2016-05-04 at 12 30 38 pm

### PR DESCRIPTION
**Pull request by paullewis**
Fixes #269 by adding a browserify transform that intercepts the require for devtools-timeline-model and sets it to use the local version. Means we don't have to maintain a fork of Speedline, and when dtm has upstreamed its changes that make it friendlier to Lighthouse we can drop this transform altogether.

/cc @paulirish

### CODE REVIEW

File: extension/dtm-transform.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+'use strict';
+
```
Comment (samthor) [inline extension/dtm-transform.js]: can you add a comment to this file explaining why we're doing this?

File: extension/gulpfile.js [hunk 2]
```diff
@@ -80,6 +80,9 @@ gulp.task('browserify', () => {
       file.contents = browserify(file.path, {
         transform: ['brfs']
       })
+      .transform('./dtm-transform.js', {
```
Comment (samthor) [inline extension/gulpfile.js]: one-liner comment would be great since this is so hacky.

**Comment by brendankenny** [comment]
looks good. Hacky but maintainable. Agree with @samthor a comment in the gulpfile and in the transform would be helpful for our future selves.
