### PR TITLE
fix(driver): wait for CPU idle

### LINKED ISSUE #2475: Persistent 'Audit error: The main thread was busy for the entire trace recording.' when running via webpagetest
As mentioned in #2434 I'm seeing an issue in Lighthouse when running via webpagetest that I'm hoping someone can help investigate.

Here's what I'm seeing https://www.webpagetest.org/result/170608_KH_4a8be412cf0ef89d56e3cb13a8eed676/ (this is running as Mobile - Faster 3G from https://www.webpagetest.org/easy)

Here's a similar test but using Mobile - Emerging Markets where the waterfall looks pretty similar but the Lighthouse results don't fail as much https://www.webpagetest.org/result/170607_PW_1d454612c736a65ddff058cf16b8842e/

The website is https://nextjs-hn.chrisdwheatley.com/, when running Lighthouse via the Chrome extension or in the devtools in Chrome Canary I'm unable to replicate the issue.

If you have any thoughts as to what's causing this issue it'd be much appreciated.

### PR DESCRIPTION
**Pull request by patrickhulce**
should fix #2475 (the issue raised in https://github.com/tastejs/hacker-news-pwas/pull/63), the large class of remaining sites in https://github.com/GoogleChrome/lighthouse/issues/2293, and the last 10% that were left after #2347 

🎉 🎉 🎉 🎉 🎉 

Best explained by the comment:
```
/**
 * Installs a PerformanceObserver in the page to monitor for longtasks and resolves when there have
 * been no long tasks for at least waitForCPUQuiet ms. The promise will not resolve until the
 * `markAsResolvable` function on the return object has been called. This is to prevent promise resolution
 * before some important point in time such as network quiet or document load.
 * @param {number} waitForCPUQuiet
 * @return {{promise: !Promise, cancel: function(), markAsResolvable: function()}}
 */
_waitForCPUIdle(waitForCPUQuiet) {
```

This change also makes the `pauseAfterNetworkQuiet` heuristic no longer necessary, so it's been removed as well to keep our number of config flags the same.

### CODE REVIEW

File: lighthouse-core/gather/driver.js [hunk 1]
```diff
@@ -460,27 +520,27 @@ class Driver {
...
       maxWaitForLoadedMs) {
     let maxTimeoutHandle;
 
     // Listener for onload. Resolves pauseAfterLoadMs ms after load.
     const waitForLoadEvent = this._waitForLoadEvent(pauseAfterLoadMs);
-    // Network listener. Resolves pauseAfterNetworkQuietMs after when the network has been idle for
-    // networkQuietThresholdMs.
-    const waitForNetworkIdle = this._waitForNetworkIdle(networkQuietThresholdMs,
-        pauseAfterNetworkQuietMs);
+    // Network listener. Resolves when the network has been idle for networkQuietThresholdMs.
```
Comment (addyosmani) [inline lighthouse-core/gather/driver.js]: Might be worth expanding comment to Network and CPU listeners or adding a similar line above `...const waitForCPUIdle` for consistency.

File: lighthouse-core/config/default.js [hunk 2]
```diff
@@ -13,8 +13,8 @@ module.exports = {
     passName: 'defaultPass',
     recordTrace: true,
     pauseAfterLoadMs: 5250,
-    networkQuietThresholdMs: 5000,
-    pauseAfterNetworkQuietMs: 2500,
+    networkQuietThresholdMs: 5250,
```
Comment (addyosmani) [inline lighthouse-core/config/default.js]: Is the idea here to realign `networkQuietThresholdMs` and the new `cpuQuietThresholdMs` with the `pauseAfterLoadMs` delay instead of the lower pause thresholds previously being used?

File: lighthouse-core/gather/driver.js [hunk 3]
```diff
@@ -425,6 +425,66 @@ class Driver {
...
+        .then(timeSinceLongTask => {
+          if (typeof timeSinceLongTask === 'number' && timeSinceLongTask >= waitForCPUQuiet) {
+            log.verbose('Driver', `CPU has been idle for ${timeSinceLongTask} ms`);
+            resolve();
+          } else {
+            log.verbose('Driver', `CPU has been idle for ${timeSinceLongTask} ms`);
+            tryLater();
+          }
+        });
+    }
```
Comment (addyosmani) [inline lighthouse-core/gather/driver.js]: I'm not quite as close to this code as @brendankenny or @paulirish might be, but the general approach to using long-tasks here sgtm.

File: lighthouse-core/config/default.js (hunk 2 above)
Comment (patrickhulce) [inline lighthouse-core/config/default.js]: the historical background to `pauseAfterNetworkQuiet` was that we needed a way to account for CPU work after scripts have finished downloading, so it became the number for "what's the longest after network quiet we might reasonably expect a long task to occur"

now that this role has been subsumed by a bona fide CPU idle check, we don't need it anymore, however, we still want a little bit of slack in our cutoff thus `5250` instead of straight `5000`

`pauseAfterLoad` is probably still worth keeping around for now as there are cases like the ember + fastboot where "quiet" can be reached too quickly without really reaching the load state, and it's good to see the full timeline as we try to improve the other heuristics

File: lighthouse-core/gather/driver.js (hunk 1 above)
Comment (patrickhulce) [inline lighthouse-core/gather/driver.js]: oops, meant to do that thanks!

**Comment by patrickhulce** [comment]
> what about just adding it once in gatherRunner.setupDriver in the style of driver.cacheNatives

Getting rid of markAsResolvable would be nice, but I'm not sure the trade-off of moving this specific functionality that's only for waitForCPUIdle into setupDriver is that much better?

**Comment by patrickhulce** [comment]
bump :)

**Comment by wardpeet** [comment]
does it make sense to cache the native peformanceObserver as we do with Promise and Error?

**Comment by patrickhulce** [comment]
@wardpeet I think it's much less of a problem here since for Promise and Error we relied on them being the actual original classes for instanceof and protocol promise support. Here we just want the PerformanceObserver functionality without caring about the specific object it references. Much like we do with all the other browser APIs we use (Image, DOM APIs, setTimeout, etc)

**Comment by wardpeet** [comment]
@patrickhulce 👍  sounds reasonable 😄 

Can't wait to have this landed!

**Comment by patrickhulce** [comment]
🏏 🏏

**Comment by patrickhulce** [comment]
🏏 🏏

File: lighthouse-core/gather/driver.js [hunk 4]
```diff
@@ -460,27 +520,28 @@ class Driver {
    * See https://github.com/GoogleChrome/lighthouse/issues/627 for more.
```
Comment (paulirish) [inline lighthouse-core/gather/driver.js]: this method description need an update. Can you flesh it out a bit so we won't have to look back up the PR when trying to read the code?

Comment (patrickhulce) [inline lighthouse-core/gather/driver.js]: done

File: lighthouse-cli/test/smokehouse/tricky-ttci/expectations.js [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+
+/**
+ * Expected Lighthouse audit values for --perf tests
+ */
+module.exports = [
+  {
+    initialUrl: 'http://localhost:10200/tricky-ttci.html',
+    url: 'http://localhost:10200/tricky-ttci.html',
+    audits: {
+      'first-interactive': {
```
Comment (patrickhulce) [inline lighthouse-cli/test/smokehouse/tricky-ttci/expectations.js]: love it, gotta check those power levels
