### PR TITLE
core(manifest-parser): handle blob manifests

### LINKED ISSUE #9087: Failed to Construct: Invalid URL
#### Provide the steps to reproduce
1. Run LH on https://www.sce.com

#### What is the current behavior?
I instantly get an error message: 
**Lighthouse Version**: 5.0.0
**Lighthouse Commit**: 77e57c91b416913854f542abfcb1b8c24dc61f4c
**Chrome Version**: 74.0.3729.108
**Initial URL**: https://www.sce.com/
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
```
TypeError: Failed to construct 'URL': Invalid URL
    at new URLShim (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:64148:1)
    at parseIcon (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:29281:11)
    at chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:29358:11
    at Array.map (<anonymous>)
    at parseIcons (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:29358:1)
    at parse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:29503:7)
    at Function.getWebAppManifest (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:23781:8)
    at async Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:23828:30)
    at async Function._gatherArtifactsFromBrowser (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:33114:17)
    at async Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:32983:11)
```
    
#### What is the expected behavior?
LH to run.

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.0.0
* Node.js version:
* Operating System: Chrome

**Related issues**

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
A manifest can be fetched over a `blob:` URL but all of its URLs will be invalid. Handle the case where we have invalid URLs and add a toplevel manifest warning when it's bloby

**Related Issues/PRs**
closes #9087

### CODE REVIEW

File: lighthouse-core/lib/manifest-parser.js [hunk 1]
```diff
@@ -151,7 +151,7 @@ function parseStartUrl(jsonInput, manifestUrl, documentUrl) {
     return {
       raw,
       value: documentUrl,
-      warning: 'ERROR: invalid start_url relative to ${manifestUrl}',
+      warning: `ERROR: invalid start_url relative to ${manifestUrl}`,
```
Comment (brendankenny) [inline lighthouse-core/lib/manifest-parser.js]: lol, that's certainly one big problem with testing via `assert.ok(parsedUrl.warning)`...

File: lighthouse-core/lib/manifest-parser.js [hunk 2]
```diff
@@ -229,8 +229,14 @@ function parseIcon(raw, manifestUrl) {
     src.value = undefined;
   }
   if (src.value) {
-    // 9.4(4) - construct URL with manifest URL as the base
-    src.value = new URL(src.value, manifestUrl).href;
+    try {
+      // 9.4(4) - construct URL with manifest URL as the base
+      src.value = new URL(src.value, manifestUrl).href;
+    } catch (_) {
+      // 9.6 "This algorithm will return a URL or undefined."
```
Comment (brendankenny) [inline lighthouse-core/lib/manifest-parser.js]: unfortunately the numbering has changed since https://www.w3.org/TR/2016/WD-appmanifest-20160825/ or whatever was the current draft when the other numbers are written. We probably should have included a base version for that

File: lighthouse-core/lib/manifest-parser.js [hunk 3]
```diff
@@ -229,8 +229,14 @@ function parseIcon(raw, manifestUrl) {
...
+      src.warning = `ERROR: invalid icon url will be ignored ${raw.src}`;
```
Comment (brendankenny) [inline lighthouse-core/lib/manifest-parser.js]:
```suggestion
      src.warning = `ERROR: invalid icon url will be ignored: '${raw.src}'`;
```
maybe

File: lighthouse-core/lib/manifest-parser.js [hunk 4]
```diff
@@ -460,10 +466,21 @@ function parse(string, manifestUrl, documentUrl) {
...
 
+  /** @type {string|undefined} */
+  let manifestUrlWarning;
+  try {
+    const manifestUrlParsed = new URL(manifestUrl);
+    if (!manifestUrlParsed.protocol.startsWith('http')) {
+      manifestUrlWarning = `WARNING: manifest URL not available over a valid network protocol`;
+    }
+  } catch (_) {
+    manifestUrlWarning = `ERROR: invalid manifest URL ${manifestUrl}`;
```
Comment (brendankenny) [inline lighthouse-core/lib/manifest-parser.js]: if the url was completely invalid, it seems like this should be throwing, a la the undefined check at the top?

(in theory it really should never happen since *something* was fetched in order to get here)

File: lighthouse-core/test/lib/manifest-parser-test.js [hunk 5]
```diff
@@ -47,6 +48,16 @@ describe('Manifest Parser', function() {
...
   });
 
+  it('should warn on invalid manifest parser URL', function() {
+    const parsedManifest = manifestParser('{}', 'not a URL', EXAMPLE_DOC_URL);
+    assert.ok(parsedManifest.warning);
+  });
+
+  it('should warn on valid but non-HTTPS manifest parser URL', function() {
+    const parsedManifest = manifestParser('{}', EXAMPLE_MANIFEST_BLOB_URL, EXAMPLE_DOC_URL);
+    assert.ok(parsedManifest.warning);
```
Comment (brendankenny) [inline lighthouse-core/test/lib/manifest-parser-test.js]: we should probably learn our lesson and do some kind of real assertion :)

File: lighthouse-core/test/lib/manifest-parser-test.js [hunk 6]
```diff
@@ -110,6 +121,18 @@ describe('Manifest Parser', function() {
...
+    it('parses icons and discards any with invalid base URL values', () => {
+      const manifestSrc = JSON.stringify({
+        icons: [{
+          src: '/valid/path',
+        }],
+      });
+      const parsedManifest = manifestParser(manifestSrc, EXAMPLE_MANIFEST_BLOB_URL,
+        EXAMPLE_DOC_URL);
+      const icons = parsedManifest.value.icons;
+      assert.equal(icons.value.length, 0);
```
Comment (brendankenny) [inline lighthouse-core/test/lib/manifest-parser-test.js]: check the warning?

File: lighthouse-core/lib/manifest-parser.js (hunk 2 above)
Comment (patrickhulce) [reply lighthouse-core/lib/manifest-parser.js]: yeah I noticed that, updated the link to point to that version 👍

File: lighthouse-core/lib/manifest-parser.js (hunk 4 above)
Comment (patrickhulce) [reply lighthouse-core/lib/manifest-parser.js]: hm, yeah I agree in principle and it *should* never happen but seeing as it tanks the entire LH run, that seems like a bad outcome and it was reasonable to warn when the rest of the manifest can still be parsed?

File: lighthouse-core/test/lib/manifest-parser-test.js (hunk 5 above)
Comment (patrickhulce) [reply lighthouse-core/test/lib/manifest-parser-test.js]: heh, alright alright

File: lighthouse-core/lib/manifest-parser.js (hunk 4 above)
Comment (brendankenny) [reply lighthouse-core/lib/manifest-parser.js]: > hm, yeah I agree in principle and it should never happen but seeing as it tanks the entire LH run, that seems like a bad outcome and it was reasonable to warn when the rest of the manifest can still be parsed?

arg, very good point. I forgot it's not in a gatherer anymore.

I can't find anywhere that we surface the `warning` if `value` is defined, but we can think about that with the other manifest error stuff.

File: lighthouse-core/lib/manifest-parser.js [hunk 7]
```diff
@@ -301,20 +308,31 @@ function parseIcons(jsonInput, manifestUrl) {
...
+  const value = parsedIcons
     // 9.6(3)(2)(2)
     .filter(parsedIcon => parsedIcon.value.src.value !== undefined);
 
   return {
     raw,
     value,
-    warning: undefined,
+    warning: ignoredIconsWithWarnings.length ?
+      'WARNING: Some icons were ignored due to warnings.' : '',
```
Comment (brendankenny) [inline lighthouse-core/lib/manifest-parser.js]: should it not be
```suggestion
      'WARNING: Some icons were ignored due to warnings.' : undefined,
```
?

File: lighthouse-core/test/lib/manifest-parser-test.js [hunk 8]
```diff
@@ -27,52 +28,70 @@ function noUrlManifestParser(manifestSrc) {
...
     // prefer_related_applications
   });
 
+  it('should warn on invalid manifest parser URL', function() {
+    const parsedManifest = manifestParser('{}', 'not a URL', EXAMPLE_DOC_URL);
+    expect(parsedManifest.warning)
+      .toEqual('ERROR: invalid manifest URL: \'not a URL\'');
+  });
+
+  it('should warn on valid but non-HTTPS manifest parser URL', function() {
```
Comment (brendankenny) [inline lighthouse-core/test/lib/manifest-parser-test.js]: nit:
```suggestion
  it('should warn on valid but non-(HTTP|HTTPS) manifest parser URL', function() {
```
or whatever :)
