### PR TITLE
gatherers: use isolation for fetch

### LINKED ISSUE #10065: pages the modify fetch mess with gathering
#### **Provide the steps to reproduce**
1. Run LH on <affected url>
- Go to https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.tiffany.com and the page speed score does not load. 
  

#### **What is the current behavior**?
I'm trying to pull lighthouse scores for www.tiffany.com but every time i do i receive a "backend error" message. This issue started around Sep 4th, prior to that date, i was able to pull lighthouse KPI's however the SEO score has never been able to populate.

**Today i get the following message:** Lighthouse returned error: generic::internal: Extension result empty. Lighthouse calling Page.navigate with https://www.tiffany.com/ Uncaught (in promise) Error: Extension timed out. No call to exit() before render timeout. at wrs.Extension.onTimeout_ (http://ghost-rider/devtools_script_api.js:5525:13) at http://ghost-rider/devtools_script_api.js:708:9 at Map.forEach (<anonymous>) at chromium.DevTools.Connection.dispatchMessage (http://ghost-rider/devtools_script_api.js:707:76) at chromium.DevTools.Connection.onJsonMessage_ (http://ghost-rider/devtools_script_api.js:689:65) at <anonymous>:1:40 Dismiss

#### **What is the expected behavior?**
I expect to see a desktop and mobile speed scores pulled i from lighthouse. 

#### **Environment Information**
* Affected Channels:  All channels
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System: windows & mac

**Related issues**

### PR DESCRIPTION
**Pull request by connorjclark**
~~(maybe)~~ fixes #10065

### CODE REVIEW

**Comment by patrickhulce** [comment]
WDYT about https://github.com/GoogleChrome/lighthouse/issues/10065#issuecomment-567720322 instead?

**Comment by exterkamp** [comment]
Found another one that is killing the run in #10065 

`lighthouse/lighthouse-core/lib/stack-collector.js`
```javascript
  /** @type {JSLibrary[]} */
  const jsLibraries = await passContext.driver.evaluateAsync(expression, {useIsolation: true});
```

File: lighthouse-core/lib/stack-collector.js [hunk 1]
```diff
@@ -77,7 +77,7 @@ async function collectStacks(passContext) {
   })()`;
 
   /** @type {JSLibrary[]} */
-  const jsLibraries = await passContext.driver.evaluateAsync(expression);
+  const jsLibraries = await passContext.driver.evaluateAsync(expression, {useIsolation: true});
```
Comment (patrickhulce) [inline lighthouse-core/lib/stack-collector.js]: we can't move this one to isolation unfortunately, the detector requires the same global scope to detect some of its libraries :/

Comment (patrickhulce) [reply lighthouse-core/lib/stack-collector.js]: should probably get a smoketest to catch this if there isn't one already

Comment (exterkamp) [reply lighthouse-core/lib/stack-collector.js]: Hm. Well that's unfortunate.

tbh I don't know, is it just bad practice to intercept `fetch()` and error it, like what was happening in #10065? Bad enough that we could audit for it and bail fatally instead of isolate?

**Comment by patrickhulce** [comment]
https://github.com/johnmichel/Library-Detector-for-Chrome/blob/800f925b4f1155edfdc21f7da296711f5866b660/library/libraries.js#L1635-L1655

Wow yeah that really stinks :(

I guess we need to do the __nativeFetch hack and do a local `const fetch = __nativeFetch` when we run the library detector so that it uses the real one too?

File: lighthouse-core/lib/stack-collector.js (hunk 1 above)
Comment (connorjclark) [reply lighthouse-core/lib/stack-collector.js]: > should probably get a smoketest to catch this if there isn't one already

 there is one

**Comment by connorjclark** [comment]
> I guess we need to do the __nativeFetch hack and do a local const fetch = __nativeFetch when we run the library detector so that it uses the real one too?

Do we want to bother with this? Either way, better to split this work up, so let's merge what we got here.

**Comment by patrickhulce** [comment]
> Do we want to bother with this? 

I think @exterkamp indicated we need to to resolve the root issue?

> Either way, better to split this work up, so let's merge what we got here.

Agreed.
