### PR TITLE
tests: fix mocha test runner and mocks on windows

### LINKED ISSUE #14171: Re-enable `yarn unit-cli` in CI on windows
Disabled until I can get to a windows machine.

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #14171

I'm using my fork from my PR to quibble: https://github.com/testdouble/quibble/pull/71

Also fix a couple things ~related to windows paths~ (done in #14464).

### CODE REVIEW

**Comment by connorjclark** [comment]
Note: the quibble PR fixes things related to mocking ES modules. We only do a handful of mocks for ES modules in master right now, so this isn't a great test of the quibble PR. I merged this PR (14202) into the core ESM PR (#14182) and get a handful of test failures related to ESM mocks, so there's still more to do there. But it seems at least the basic usage we do atm in master is working.

Mostly writing this as a reminder to myself to look into this Monday.

File: lighthouse-core/test/scripts/run-mocha-tests.js [hunk 1]
```diff
@@ -288,6 +292,17 @@ function runMochaCLI(tests) {
...
+  // for simply. Instead, use a limit of 8000.
+  if (process.platform === 'win32' && [file, ...args].join(' ').length > 8000) {
+    const halfPoint = Math.floor(tests.length / 2);
+    runMochaCLI(tests.slice(0, halfPoint));
+    runMochaCLI(tests.slice(halfPoint));
+    return;
+  }
+
   console.log(
     `Running command: ${argv.update ? 'SNAPSHOT_UPDATE=1 ' : ''}${file} ${args.join(' ')}`);
```
Comment (paulirish) [inline lighthouse-core/test/scripts/run-mocha-tests.js:307]: if we invoke mocha through its JS api instead of a child-process to use its CLI.... would it fix this ? (node --inspect support would also come back )

Comment (connorjclark) [reply lighthouse-core/test/scripts/run-mocha-tests.js:307]: yup, but it's something that must be done after all the isolation stuff is ripped out. on the todo list

File: core/test/gather/mock-driver.js [hunk 2]
```diff
@@ -187,7 +186,7 @@ const runnerMock = {
   },
 };
 async function mockRunnerModule() {
-  await td.replaceEsm(`${LH_ROOT}/core/runner.js`, {Runner: runnerMock});
+  await td.replaceEsm('../../../runner.js', {Runner: runnerMock});
```
Comment (adamraine) [inline core/test/gather/mock-driver.js:189]:
```suggestion
  await td.replaceEsm('../../runner.js', {Runner: runnerMock});
```

**Comment by connorjclark** [comment]
Passing in CI, and confirmed to work locally. At least, `unit-cli` does.

Some core tests (like pptr scenarios) hang on the after hook. Something to look into one day, but not high priority.

**Review by adamraine — APPROVED** [review]
