### PR TITLE
fix: recover if protocol does not support CSS rule usage

### LINKED ISSUE #1473: Error: Protocol error (CSS.startRuleUsageTracking): 'CSS.startRuleUsageTracking' wasn't found
When doing a lighthouse run (latest master) on current stable chrome I get the error that startRuleUsageTracking is not found. (luckily it's not an issue in latest npm version)

Command rule `lighthouse --disable-device-emulation --disable-cpu-throttling https://airhorner.com --output=json --select-chrome`

```
status Retrieving: HTMLWithoutJavaScript +2ms
  method <= browser ERR:error CSS.startRuleUsageTracking +345ms
  status Disconnecting from browser... +1ms
  ChromeLauncher Killing all Chrome Instances +1ms
Runtime error encountered: Error: Protocol error (CSS.startRuleUsageTracking): 'CSS.startRuleUsageTracking' wasn't found
    at CriConnection.handleRawError (/Volumes/MAC_EXTRA/Projects/tmp/lighthouse/lighthouse-core/gather/connections/connection.js:134:11)
    at callback.resolve.Promise.resolve.then._ (/Volumes/MAC_EXTRA/Projects/tmp/lighthouse/lighthouse-core/gather/connections/connection.js:103:23)
Error: Protocol error (CSS.startRuleUsageTracking): 'CSS.startRuleUsageTracking' wasn't found
    at CriConnection.handleRawError (/Volumes/MAC_EXTRA/Projects/tmp/lighthouse/lighthouse-core/gather/connections/connection.js:134:11)
    at callback.resolve.Promise.resolve.then._ (/Volumes/MAC_EXTRA/Projects/tmp/lighthouse/lighthouse-core/gather/connections/connection.js:103:23)
```

@patrickhulce can you look at this? It's probably not supported in chrome 55 yet

### PR DESCRIPTION
**Pull request by patrickhulce**
R: @wardpeet all

fixes #1473

### CODE REVIEW

**Comment by ebidel** [comment]
https://github.com/GoogleChrome/lighthouse/issues/1482 :)

File: lighthouse-core/gather/gatherers/css-usage.js [hunk 1]
```diff
@@ -25,7 +25,8 @@ class CSSUsage extends Gatherer {
   beforePass(options) {
     return options.driver.sendCommand('DOM.enable')
       .then(_ => options.driver.sendCommand('CSS.enable'))
-      .then(_ => options.driver.sendCommand('CSS.startRuleUsageTracking'));
+      .then(_ => options.driver.sendCommand('CSS.startRuleUsageTracking'))
+      .catch(_ => this.failure = 'CSS Usage tracking requires Chrome \u2265 56');
```
Comment (brendankenny) [inline lighthouse-core/gather/gatherers/css-usage.js]: maybe add a `TODO` to remove this once m56 is released as stable?

Comment (brendankenny) [inline lighthouse-core/gather/gatherers/css-usage.js]: also this marks all errors from `beforePass` as this error. To be fair, the previous code was anticipating no errors :) but probably better to check that it's `'CSS.startRuleUsageTracking' wasn't found` or whatever so that other possible errors aren't muted

**Comment by brendankenny** [comment]
recoverable errors will work, they're just a manual replacement for -1 right now since the last step of #941 isn't in place yet, so probably fine just to use -1 for now

**Comment by brendankenny** [comment]
one interesting thing that this brings up that we didn't anticipate with a recoverable error is if `beforePass` throws a recoverable error `afterPass` is still called. The recoverable error will win and be the value of that artifact in that case, but I guess that means all audits where that's a danger will have to deal with it like this and have to keep internal state tracking that it failed, and not to do more stuff in `afterPass`? OTOH if we *didn't* call `afterPass`, the gatherer has no chance to clean up after itself, close domains, etc. Hopefully this isn't leading us to a `finally` callback or something...

**Comment by patrickhulce** [comment]
Interesting what's wrong with `finally`? I'm not opposed to a `finally` style pass since that would have simplified the domain disabling quite a bit IMO

**Comment by wardpeet** [comment]
i'm ok with finally as well :) Seems a good idea to clean up all the things!
image

Is it an option for the future to change the output of the formatter? (if < chrome 56 show coming soon icon, ...) so it doesn't look like a failure.

**Comment by brendankenny** [comment]
> what's wrong with `finally`?

in theory nothing, but we'd really have to nail down when it runs, its relation to the artifact produced, etc. e.g. will it always make sense to clean up after `afterPass`? What happens to errors in `finally`, do they replace the artifact with an error (like if there was an error in `afterPass` or do we rely on error reporting or whatever to catch those? etc
