### PR TITLE
core(installable-manifest): check for fetchable icon

### LINKED ISSUE #789: Ligthouse checks for an icon in the manifest but does not try to load it
While collection few PWA examples I have found that many manifest have icon URLs but they are actually broken, 404 or errors in the relative path.

I think that "Manifest contains icons at least 144px" should not be true if the URL is broken, or at least have another way to point it out in the report.

### PR DESCRIPTION
**Pull request by connorjclark**
I think how Lighthouse deals with manifests could be improved, but that's a pretty big project for small gain. This PR does the minimal necessary to fix #789.

### CODE REVIEW

File: lighthouse-core/gather/gather-runner.js [hunk 1]
```diff
@@ -536,7 +537,24 @@ class GatherRunner {
   static async getWebAppManifest(passContext) {
     const response = await passContext.driver.getAppManifest();
     if (!response) return null;
-    return manifestParser(response.data, response.url, passContext.url);
+    const manifest = manifestParser(response.data, response.url, passContext.url);
+
+    // Add a warning for icons that aren't fetchable.
+    if (manifest.value && Array.isArray(manifest.value.icons.value)) {
+      const iconsToFetch = manifest.value.icons.value
+        .filter(icon => icon.value.src && icon.value.src.value);
```
Comment (patrickhulce) [inline lighthouse-core/gather/gather-runner.js]: were empty string icons treated as acceptable before but now they won't be? or I suppose they will be valid because we won't try to fetch and put any warning on them?

File: lighthouse-core/gather/gather-runner.js [hunk 2]
```diff
@@ -536,7 +537,24 @@ class GatherRunner {
...
+      const fetchPromises = iconsToFetch.map(async icon => {
+        const expression = `(${pageFunctions.fetchIsOkString})(
+          ${JSON.stringify(icon.value.src.value)}
+        )`;
+        if (!await passContext.driver.evaluateAsync(expression, {useIsolation: true})) {
+          icon.warning = 'Error fetching icon';
```
Comment (patrickhulce) [inline lighthouse-core/gather/gather-runner.js]: don't *love* the Promise.all mutating an object, can we make this a map of the icon results?

File: lighthouse-core/gather/gather-runner.js [hunk 3]
```diff
@@ -536,7 +537,24 @@ class GatherRunner {
...
+
+    // Add a warning for icons that aren't fetchable.
+    if (manifest.value && Array.isArray(manifest.value.icons.value)) {
+      const iconsToFetch = manifest.value.icons.value
+        .filter(icon => icon.value.src && icon.value.src.value);
+      const fetchPromises = iconsToFetch.map(async icon => {
+        const expression = `(${pageFunctions.fetchIsOkString})(
+          ${JSON.stringify(icon.value.src.value)}
+        )`;
+        if (!await passContext.driver.evaluateAsync(expression, {useIsolation: true})) {
```
Comment (patrickhulce) [inline lighthouse-core/gather/gather-runner.js]: Feels like we should make this timeout very short and `.catch` them to not be a fatal protocol timeout

File: lighthouse-core/test/lib/icons-test.js [hunk 4]
```diff
@@ -36,6 +36,17 @@ describe('Icons helper', () => {
       assert.equal(icons.doExist(manifest.value), false);
     });
 
+    it('fails when a manifest contains no fetchable icons', () => {
```
Comment (patrickhulce) [inline lighthouse-core/test/lib/icons-test.js]: ooo ooo can we get an empty string test in here before we forget about it again :D

File: lighthouse-core/gather/gather-runner.js (hunk 1 above)
Comment (connorjclark) [reply lighthouse-core/gather/gather-runner.js]: at this point empty strings were converted to `undefined` (see parser). later, the icons check will ignore icons whose `src` does not end in `.png`.

... however I've just noticed there's a bug if `typeHint === 'image/png'` and `src` is undefined. this is so dirty. Can fix by tweaking `getFetchableIcons` to also check for a nonempty string.

**Comment by connorjclark** [comment]
> what are thoughts on just fetching the largest icon to check and/or whatever one chrome is most likely to actually use?

Only attempt the largest, or attempt all above `512px` until one passes?

**Comment by patrickhulce** [comment]
> Only attempt the largest, or attempt all above 512px until one passes?

Ideally, we'd do whatever browsers are most likely to do across all users. i.e. if Chrome will try the 512 icon first and use it if it works we do the same, try to fetch 512 and stop if it worked

File: lighthouse-core/gather/gather-runner.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-core/gather/gather-runner.js]: aight sgtm

**Comment by connorjclark** [comment]
[Here](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/installable/installable_manager.cc;l=139;drc=19cdf35bf33d348cfb20911b9be2f16471e0ca87?originalUrl=https:%2F%2Fcs.chromium.org%2F) is the installation check. Just looks for any icon >= 144px (with a caveat for maskable icons that #10197 will no doubt need to consider). No fetch here.

More complicated logic is done to [determine the best fitting icon](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/installable/installable_manager.cc;l=694;drc=19cdf35bf33d348cfb20911b9be2f16471e0ca87?originalUrl=https:%2F%2Fcs.chromium.org%2F). Rather than replicating that, we should just let Chrome do the fetching and sniff for the error it may create. `Page.getAppManifest` responses's `.errors` should have that signal. (speaking of which .... why do we replicate all of these checks when this errors object exists?)

**Comment by connorjclark** [comment]
oh right, I forgot about this https://github.com/GoogleChrome/lighthouse/pull/8995

should be fine to use this protocol for just the signal for failure to fetch an icon.

**Comment by connorjclark** [comment]
image

unfortunately we just can't tie it back to a specific icon :(

**Comment by connorjclark** [comment]
This is ready for review.

File: lighthouse-core/lib/manifest-parser.js [hunk 5]
```diff
@@ -281,6 +281,10 @@ function parseIcon(raw, manifestUrl) {
     },
     warning: undefined,
   };
+  // Hack to make warning be `string|undefined`, even though this function will always
+  // return undefined. Can be removed if Manifest is explicitly typed (see artifacts.d.ts).
+  const warning = /** @type {string=} */(undefined);
```
Comment (patrickhulce) [inline lighthouse-core/lib/manifest-parser.js]:
```suggestion
  const warning = /** @type {string=} */ (undefined);
```

File: lighthouse-core/test/computed/manifest-values-test.js [hunk 6]
```diff
@@ -141,6 +141,18 @@ describe('ManifestValues computed artifact', () => {
         const iconResults = results.allChecks.filter(i => i.id.includes('Icons'));
         assert.equal(iconResults.every(i => i.passing === false), true);
       });
+
+      it('fails when a manifest icon fails to fetch icon', async () => {
```
Comment (patrickhulce) [inline lighthouse-core/test/computed/manifest-values-test.js]: I would've expected to see a test like this in installable-manifest.js since that audit failing is what we actually care about. move and/or copy something like it over there?

File: lighthouse-core/test/gather/gather-runner-test.js [hunk 7]
```diff
@@ -1654,13 +1654,20 @@ describe('GatherRunner', function() {
     });
 
     it('should parse the manifest when found', async () => {
+      // https://github.com/GoogleChrome/lighthouse/pull/10136 will allow
```
Comment (patrickhulce) [inline lighthouse-core/test/gather/gather-runner-test.js]:
```suggestion
      // TODO: https://github.com/GoogleChrome/lighthouse/pull/10136 will allow
```

?
otherwise it feels like we'll never find this when searching for things to fix :)

Comment (connorjclark) [reply lighthouse-core/test/gather/gather-runner-test.js]: this is merged now

File: lighthouse-core/test/computed/manifest-values-test.js (hunk 6 above)
Comment (connorjclark) [reply lighthouse-core/test/computed/manifest-values-test.js]: done

**Comment by paulirish** [comment]
this CL (which just landed) will likely affect your PR :/ 

DevTools: Modify Page.getInstallabilityErrors to use structured data | https://chromium-review.googlesource.com/c/chromium/src/+/2008430

**Comment by connorjclark** [comment]
My understanding from reading the doc for that feature was they are maintaining the existing, english strings where they are. CL confirms that: `They'll remain in place so we are backwards
compatible.`

**Comment by patrickhulce** [comment]
@connorjclark you've requested another review but I can't find the response to the major concerns from my last review.

https://github.com/GoogleChrome/lighthouse/pull/10168#pullrequestreview-346287417

Maybe you could help point me if I just missed it? :)

**Comment by connorjclark** [comment]
Sorry, I missed that comment.

> What were your plans for improving manifests and do they include more breaking changes that should be paired?

I don't have anything fleshed out. I mostly mean that the manual checks we have are not great (we may be missing full coverage). The new protocol work on Page.getInstallabilityErrors will help us here in due time. Ideally we'll be able to lean on that 100% and replace the WebappManaifest artifact with just the literal manifest, not all this parsing junk.

> What is the primary motivation for merging the artifacts as opposed to adding an InstallabilityErrors artifact of some sort? I get that they're related but they do come from different places and have somewhat different purposes. If they didn't it feels like we could just inject installabilityErrors into an errors property of the existing manifest artifact like CDP result has (but it doesn't, hence why do we not separate when they do :))

your way is better, changed.

File: lighthouse-core/audits/installable-manifest.js [hunk 8]
```diff
@@ -46,7 +46,7 @@ class InstallableManifest extends MultiCheckAudit {
       title: str_(UIStrings.title),
       failureTitle: str_(UIStrings.failureTitle),
       description: str_(UIStrings.description),
-      requiredArtifacts: ['URL', 'WebAppManifest'],
+      requiredArtifacts: ['URL', 'WebAppManifest', 'InstallabilityErrors'],
```
Comment (connorjclark) [inline lighthouse-core/audits/installable-manifest.js]: just got bit by forgetting to add this. #9946 would have saved me time.

File: lighthouse-core/audits/service-worker.js [hunk 9]
```diff
@@ -95,19 +95,19 @@ class ServiceWorker extends Audit {
   /**
    * Returns a failure message if there is no start_url or if the start_url isn't
    * contolled by the scopeUrl.
-   * @param {LH.Artifacts['WebAppManifest']} manifest
+   * @param {LH.Artifacts['WebAppManifest']} WebAppManifest
```
Comment (connorjclark) [inline lighthouse-core/audits/service-worker.js]: not changing anything else here now, but this naming convention is better imo.

File: lighthouse-core/test/gather/gather-runner-test.js [hunk 10]
```diff
@@ -1642,24 +1642,26 @@ describe('GatherRunner', function() {
...
-      const getAppManifest = jest.spyOn(fakeDriver, 'getAppManifest');
-      // @ts-ignore: Some terrible @types/jest bug lies here.
-      getAppManifest.mockResolvedValueOnce({data: JSON.stringify(manifest), url: MANIFEST_URL});
+      connectionStub.sendCommand
+        .mockResponse('Page.getAppManifest', {data: JSON.stringify(manifest), url: MANIFEST_URL})
+        .mockResponse('Page.getInstallabilityErrors', {errors: []});
+
       const result = await GatherRunner.getWebAppManifest(passContext);
-      expect(result).toHaveProperty('raw', JSON.stringify(manifest));
+      expect(result && result).toHaveProperty('raw', JSON.stringify(manifest));
```
Comment (patrickhulce) [inline lighthouse-core/test/gather/gather-runner-test.js]:
```suggestion
      expect(result).toHaveProperty('raw', JSON.stringify(manifest));
```

**Comment by patrickhulce** [comment]
test failure to deal with though :)

**Comment by paulirish** [comment]
fyi: part 2 of the getInstallabilityErrors -- tweaks to frontend: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2016235

**Comment by brendankenny** [comment]
> I don't have anything fleshed out. I mostly mean that the manual checks we have are not great (we may be missing full coverage). The new protocol work on Page.getInstallabilityErrors will help us here in due time. Ideally we'll be able to lean on that 100% and replace the WebappManifest artifact with just the literal manifest, not all this parsing junk.

The parser code style is different because we forked it from an existing library, and at the time we didn't know what we'd actually need out of it, so the output is just the direct tree instead of linearized errors or whatever. If there are actual bugs to report we should fix them, we should rely on the protocol when we can do so, but in the meantime let's not unnecessarily antagonize those of us that had to do the library forking :)

File: lighthouse-core/test/report/html/renderer/report-renderer-test.js [hunk 11]
```diff
@@ -115,15 +115,18 @@ describe('ReportRenderer', () => {
       const container = renderer._dom._document.body;
       const output = renderer.renderReport(sampleResultsCopy, container);
 
+      function isPWAGauge(el) {
```
Comment (connorjclark) [inline lighthouse-core/test/report/html/renderer/report-renderer-test.js]: pwa category is failing for the sample report json now, which means the pwa__wrapper class isn't set. Changed the test to look at text content instead.

Comment (connorjclark) [reply lighthouse-core/test/report/html/renderer/report-renderer-test.js]: ah well I had to update the sample artifacts anyways, but I'm gonna keep this test change.

File: proto/sample_v2_round_trip.json [hunk 12]
```diff
@@ -2028,7 +2028,7 @@
                         "vulnCount": 2.0
                     }
                 ],
-                "summary": {},
```
Comment (patrickhulce) [inline proto/sample_v2_round_trip.json]: why have these changed?

**Comment by patrickhulce** [comment]
@connorjclark the assignment was just to reflect our new policy right, you're not waiting on me? I don't see anything objectionable that's new so my approval still stands

File: proto/sample_v2_round_trip.json (hunk 12 above)
Comment (connorjclark) [reply proto/sample_v2_round_trip.json]: because i forgot to edit them back

Comment (connorjclark) [reply proto/sample_v2_round_trip.json]: i havent update proto ..
