### PR TITLE
core(errors-in-console): If exception info is not present use exception text

### LINKED ISSUE #4188: TypeError: Cannot read property 'description' of undefined
from sentry: https://sentry.io/google-lighthouse/lighthouse/issues/408418142/

on URL http://www.efaxcorporate.com/

```
TypeError: Cannot read property 'description' of undefined
  File "/usr/lib/node_modules/lighthouse/lighthouse-core/audits/errors-in-console.js", line 52, col 56, in runtimeExceptions.filter.map.entry
    description: entry.exceptionDetails.exception.description,
  ?, in Array.map
  File "/usr/lib/node_modules/lighthouse/lighthouse-core/audits/errors-in-console.js", line 49, col 8, in Function.audit
    .map(entry => {
  File "/usr/lib/node_modules/lighthouse/lighthouse-core/runner.js", line 227, col 20, in Promise.resolve.then._
    return audit.audit(artifacts);
  File "internal/process/next_tick.js", line 135, col 7, in process._tickDomainCallback
```

### PR DESCRIPTION
**Pull request by wardpeet**
Fixes #4188 

when looking at the [devtools protocol](https://chromedevtools.github.io/devtools-protocol/v8/Runtime/#type-ExceptionDetails). Exeption is an optional property, when not present we should use text.

I also added an extra test to cover this case.

### CODE REVIEW

File: lighthouse-core/test/audits/errors-in-console-test.js [hunk 1]
```diff
@@ -121,4 +121,36 @@ describe('Console error logs audit', () => {
...
+          'executionContextId': 3,
+        },
+      }],
+    });
+    assert.equal(auditResult.rawValue, 1);
+    assert.equal(auditResult.score, false);
+    assert.equal(auditResult.details.items.length, 1);
+    // url is undefined
+    assert.strictEqual(auditResult.details.items[0][0].text, 'http://example.com/fancybox.js');
+    // text is undefined
```
Comment (patrickhulce) [inline lighthouse-core/test/audits/errors-in-console-test.js]: not sure what these two comments are, isn't `text` defined here?

Comment (wardpeet) [reply lighthouse-core/test/audits/errors-in-console-test.js]: yes I did, it happens when a syntax error occurred on the page.

```
{
   "timestamp":1515451440948.461,
   "exceptionDetails":{
      "exceptionId":1,
      "text":"Uncaught SyntaxError: Unexpected token ,",
      "lineNumber":3180,
      "columnNumber":302,
      "scriptId":"56",
      "url":"https://enterprise.efax.com/",
      "stackTrace":{
         "callFrames":[
            {
               "functionName":"prop",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":8,
               "columnNumber":22254
            },
            {
               "functionName":"access",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":8,
               "columnNumber":6743
            },
            {
               "functionName":"prop",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":8,
               "columnNumber":18120
            },
            {
               "functionName":"",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":88,
               "columnNumber":274
            },
            {
               "functionName":"each",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":8,
               "columnNumber":5254
            },
            {
               "functionName":"each",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":8,
               "columnNumber":2010
            },
            {
               "functionName":"b",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":88,
               "columnNumber":190
            },
            {
               "functionName":"",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":89,
               "columnNumber":472
            },
            {
               "functionName":"c",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":8,
               "columnNumber":7854
            },
            {
               "functionName":"fireWith",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":8,
               "columnNumber":8655
            },
            {
               "functionName":"ready",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":8,
               "columnNumber":3263
            },
            {
               "functionName":"H",
               "scriptId":"32",
               "url":"https://d9jmv9u00p0mv.cloudfront.net/js/10015692-10015098.js",
               "lineNumber":8,
               "columnNumber":692
            }
         ]
      }
   }
}
```
