### PR TITLE
core(screenshots): fix getParsedImage of null

### LINKED ISSUE #3884: TypeError: Cannot read property 'getParsedImage' of null
```
TypeError: Cannot read property 'getParsedImage' of null
  File "/usr/lib/node_modules/lighthouse/lighthouse-core/audits/screenshot-thumbnails.js", line 99, col 44, in Promise.all.then
    const imageData = frameForTimestamp.getParsedImage();
  File "internal/process/next_tick.js", line 135, col 7, in process._tickDomainCallback
```

https://sentry.io/google-lighthouse/lighthouse/issues/407185967/

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #3884 
fixes https://sentry.io/google-lighthouse/lighthouse/issues/408391251/events/11708246287/

http://side.co is a site that triggers both errors

### CODE REVIEW

File: lighthouse-core/audits/screenshot-thumbnails.js [hunk 1]
```diff
@@ -78,9 +78,12 @@ class ScreenshotThumbnails extends Audit {
     ]).then(([speedline, ttfi, ttci]) => {
       const thumbnails = [];
       const analyzedFrames = speedline.frames.filter(frame => !frame.isProgressInterpolated());
+      const maxFrameTime =
+        speedline.complete ||
```
Comment (paulirish) [inline lighthouse-core/audits/screenshot-thumbnails.js]: seems like we could just ALSO put speedline.complete in the L86 math.max(), yeah? 
 
semantically maxFrameTime is the second half of this, but not realllly .complete.
