### PR TITLE
core(font-size): don't allow a deleted node to fail gatherer

### LINKED ISSUE #9255: FontSize Gatherer fails with "Could not find node with given id"
#### Provide the steps to reproduce
1. Run LH on https://www.custislawpc.com/
  

#### What is the current behavior?
FontSize Gatherer fails with "Required FontSize gatherer encountered an error: Protocol error (CSS.getMatchedStylesForNode): Could not find node with given id"

Google displays '?' most of the time when running report.
image
image

#### What is the expected behavior?
SEO category score is given, FontSize gatherer does not fail.

#### Environment Information
* Affected Channels: Extension, Devtools
* Lighthouse version: 5.1.0.1
* Node.js version:
* Operating System: WIndows 10, Apple Laptop

**Related issues**

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #9255

### CODE REVIEW

File: lighthouse-core/gather/gatherers/seo/font-size.js [hunk 1]
```diff
@@ -192,24 +192,29 @@ function getNodeTextLength(node) {
...
+      type: sourceRule.type,
+      range: sourceRule.range,
+      styleSheetId: sourceRule.styleSheetId,
+      parentRule: sourceRule.parentRule && {
+        origin: sourceRule.parentRule.origin,
+        selectors: sourceRule.parentRule.selectors,
+      },
+    };
+  } catch (err) {
+    Sentry.captureException(err, {tags: {gatherer: 'FontSize'}});
```
Comment (connorjclark) [inline lighthouse-core/gather/gatherers/seo/font-size.js]: Do we want to sentry this?

Comment (patrickhulce) [reply lighthouse-core/gather/gatherers/seo/font-size.js]: I'm not sure there's any value here. We know nodes can disappear it's not really helping us to understand the volume.

File: lighthouse-core/gather/gatherers/seo/font-size.js [hunk 2]
```diff
@@ -294,11 +299,17 @@ class FontSize extends Gatherer {
       .sort((a, b) => b.textLength - a.textLength)
       .slice(0, MAX_NODES_SOURCE_RULE_FETCHED)
       .map(async failingNode => {
-        failingNode.cssRule = await fetchSourceRule(driver, failingNode.node);
+        const cssRule = await fetchSourceRule(driver, failingNode.node);
+        // If cssRule is null, then the node was deleted. Don't set `cssRule` in that case.
```
Comment (patrickhulce) [inline lighthouse-core/gather/gatherers/seo/font-size.js]: how about we just have the try/catch out here so it's a little more self-explanatory and no indentation churn in the function? :)

File: lighthouse-core/gather/gatherers/seo/font-size.js [hunk 3]
```diff
@@ -294,11 +295,19 @@ class FontSize extends Gatherer {
       .sort((a, b) => b.textLength - a.textLength)
       .slice(0, MAX_NODES_SOURCE_RULE_FETCHED)
       .map(async failingNode => {
-        failingNode.cssRule = await fetchSourceRule(driver, failingNode.node);
+        try {
+          const cssRule = await fetchSourceRule(driver, failingNode.node);
+          failingNode.cssRule = cssRule;
+        } catch (err) {
+          // The node was deleted. Don't set `cssRule` in that case.
+          log.error('font-size', err.message);
```
Comment (brendankenny) [inline lighthouse-core/gather/gatherers/seo/font-size.js]: This seems like this could lead to error fatigue, and is it anyone's error? `fetchSourceRule` already returns `undefined` if we can't find a font rule for the failing element, and we just silently drop that case. This seems basically equivalent in importance for logging


There's nothing to do in this case (and the element's not even around anymore). I could see maybe log.verbose, but there doesn't seem to be a good motivation for that (e.g.

File: lighthouse-core/gather/gatherers/seo/font-size.js [hunk 4]
```diff
@@ -294,11 +295,19 @@ class FontSize extends Gatherer {
...
+        }
         return failingNode;
       });
 
-    const analyzedFailingNodesData = await Promise.all(analysisPromises);
+    const analyzedFailingNodesData = (await Promise.all(analysisPromises))
+      // Throw out the nodes that got deleted.
```
Comment (brendankenny) [inline lighthouse-core/gather/gatherers/seo/font-size.js]: (also when `fetchSourceRule` returns undefined)

File: lighthouse-core/gather/gatherers/seo/font-size.js [hunk 5]
```diff
@@ -294,11 +295,19 @@ class FontSize extends Gatherer {
...
+      .filter(data => 'cssRule' in data);
```
Comment (brendankenny) [inline lighthouse-core/gather/gatherers/seo/font-size.js]: any reason not to do `.filter(data => data.cssRule);`? Usually we reserve `in` for making tsc happy on poorly discriminated unions

Comment (brendankenny) [reply lighthouse-core/gather/gatherers/seo/font-size.js]: this is also filtered down on `https://github.com/GoogleChrome/lighthouse/pull/9928/files#diff-aed43c42d5d8fb3c5d70f6775865c8deR351`, so could remove one of them

File: lighthouse-core/gather/gatherers/seo/font-size.js (hunk 4 above)
Comment (connorjclark) [reply lighthouse-core/gather/gatherers/seo/font-size.js]: does it?

image

File: lighthouse-core/gather/gatherers/seo/font-size.js (hunk 5 above)
Comment (connorjclark) [reply lighthouse-core/gather/gatherers/seo/font-size.js]: hmm, i think the former check (the one here) needs to keep `undefined` b/c it still counts towards the total text length

File: lighthouse-core/gather/gatherers/seo/font-size.js (hunk 4 above)
Comment (brendankenny) [reply lighthouse-core/gather/gatherers/seo/font-size.js]: Oh I see. Good catch, but this distinction is definitely going to be overlooked like I just did the next time someone is doing something in here (at least without a test for it, which is going to be annoying/hard).

Should we just treat these two failures the same to keep it simpler (e.g. count them both in the total length since the elements were at least in the DOM at some point)? Or rearrange the mapping/filtering to make it clearer.

Comment (connorjclark) [reply lighthouse-core/gather/gatherers/seo/font-size.js]: I think we shouldn't keep the nodes we know were _deleted_, because in the case of a timer (that can be modified many many many times) the percentages will be thrown off what is visible at any one point.

I added some comments to make it more clear. Importantly, that second filter isn't filtering result _out_ of the artifact, it is just assigning the stylesheet object to the nodes that we could attribute a stylesheet to.

Comment (brendankenny) [reply lighthouse-core/gather/gatherers/seo/font-size.js]: > I think we shouldn't keep the nodes we know were deleted, because in the case of a timer (that can be modified many many many times) the percentages will be thrown off what is visible at any one point.

Wouldn't it be more correct to include it, though? The gatherer is using `DOM.getFlattenedDocument` to get a snapshot of the DOM at a single point in time, so the percentage including it would be accurate for that moment (which is when all the text lengths come from, not from when we finally get to calling `CSS.getMatchedStylesForNode`)

e.g. if the timer is the only too-small text on screen, dropping it would give an `analyzedFailingTextLength` of 0 and no node listing when we do know the node that was failing, and in theory have a decent selector to that would indicate the issue was the timer element.

Comment (connorjclark) [reply lighthouse-core/gather/gatherers/seo/font-size.js]: hmmm this sounds compelling. I was thinking we'd somehow have many copies of the "same" node, but that doesn't make sense b/c we just take a snapshot.
