### PR TITLE
core: score of 1 for informative audits

### LINKED ISSUE #15686: Improve informative audit scoring
From https://github.com/GoogleChrome/lighthouse/discussions/15673. Some audits can dynamically change their score display mode which can lead to confusion.

Couple options discussed on GVC:

- Go back to pass/fail and remove dynamic display mode changes. If we go down this path I think we still need some other system to visually elevate audits that passed but still have valuable information.
- Make score 1 for all informative audits but still not hidden in report
- Make score 0.9 for all informative audits (passing but not 100%)

### PR DESCRIPTION
**Pull request by adamraine**
Closes #15686

Nothing should change from the report perspective. This is for the benefit of JSON consumers that expect the score to change from 0 to 1 under passing conditions rather than 0 to null.

### CODE REVIEW

File: report/renderer/performance-category-renderer.js [hunk 1]
```diff
@@ -237,12 +237,8 @@ export class PerformanceCategoryRenderer extends CategoryRenderer {
...
       // If the score display mode is "metricSavings", the `score` will be a coarse approximation of the overall impact.
       // Therefore, it makes sense to sort audits by score first to ensure visual clarity with the score icons.
-      const scoreA = a.auditRef.result.scoreDisplayMode === 'informative'
-        ? 100
-        : Number(a.auditRef.result.score);
-      const scoreB = b.auditRef.result.scoreDisplayMode === 'informative'
-        ? 100
-        : Number(b.auditRef.result.score);
+      const scoreA = a.auditRef.result.score || 0;
+      const scoreB = b.auditRef.result.score || 0;
```
Comment (adamraine) [inline report/renderer/performance-category-renderer.js:241]: I kinda like this solution because it means the informative audit score accurately communicates where in the sort order informative audits should be. Without this change we need a special exception for informative audits.
