### PR TITLE
core(uses-rel-preconnect): warn on 3+ preconnects

### LINKED ISSUE #9894: Preconnect to required origins suggestion keeps coming even after adding the origins
#### Provide the steps to reproduce
1. Run LH on https://qwww.americanexpress.com
  

#### What is the current behavior?

Running the report earlier was showing these urls under "Preconnect to required origins":
 
  | <link rel="preconnect" href="https://nexus.ensighten.com" crossorigin>
  | <link rel="preconnect" href="https://www.aexp-static.com">
  | <link rel="preconnect" href="https://cdaas.americanexpress.com">
  | <link rel="preconnect" href="https://aug.americanexpress.com">
  | <link rel="preconnect" href="https://aexp.demdex.net" crossorigin>
 
We added these and ran the report again and now we are being shown 6 more origins. We are trying to understand how does this work? How do we know which are the "important third-party origins." and good candidate for adding preconnects? We read somewhere we can only add up to 6 preconnects. Is that correct? If yes, why does Lighthouse keeps suggesting these even after we have added them?

Screen Shot 2019-10-28 at 10 53 16 AM

#### What is the expected behavior?
Shouldn't the report not show this suggestion when the origins have been added?

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

### PR DESCRIPTION
**Pull request by piotrzarycki**
closes #9894

### CODE REVIEW

**Comment by piotrzarycki** [comment]
@googlebot I signed it!

File: lighthouse-core/audits/uses-rel-preconnect.js [hunk 1]
```diff
@@ -35,6 +35,7 @@ const UIStrings = {
    * */
   crossoriginWarning: 'A preconnect <link> was found for "{securityOrigin}" but was not used ' +
     'by the browser. Check that you are using the `crossorigin` attribute properly.',
+  tooManyPreconnectLinksWarning: 'links shouldn\'t be more than 8 and less than 6',
```
Comment (patrickhulce) [inline lighthouse-core/audits/uses-rel-preconnect.js]:
```suggestion
  tooManyPreconnectLinksWarning: 'More than 8 preconnect links were found. Preconnect links should be used sparingly and only to the most important origins.',
```

Comment (patrickhulce) [reply lighthouse-core/audits/uses-rel-preconnect.js]: might need to do a line break in there

File: lighthouse-core/audits/uses-rel-preconnect.js [hunk 2]
```diff
@@ -135,6 +136,12 @@ class UsesRelPreconnectAudit extends Audit {
     const preconnectLinks = artifacts.LinkElements.filter(el => el.rel === 'preconnect');
     const preconnectOrigins = new Set(preconnectLinks.map(link => URL.getOrigin(link.href || '')));
 
+    if (preconnectLinks.length >= 6) {
+      return {
+        score: 1, warnings: preconnectLinks.length >= 8
```
Comment (patrickhulce) [inline lighthouse-core/audits/uses-rel-preconnect.js]: anyone on core team know of docs that could guide these numbers better than gut feel on a random comment? 😆 

```suggestion
        score: 1, warnings: preconnectLinks.length > 8
```

if we're sticking to our "more than 8" comment above :)

Comment (brendankenny) [reply lighthouse-core/audits/uses-rel-preconnect.js]: > anyone on core team know of docs that could guide these numbers better than gut feel on a random comment? 😆

some docs for this (or even a cs.chromium.org reference) would be very appreciated

File: lighthouse-core/audits/uses-rel-preconnect.js [hunk 3]
```diff
@@ -135,6 +140,12 @@ class UsesRelPreconnectAudit extends Audit {
     const preconnectLinks = artifacts.LinkElements.filter(el => el.rel === 'preconnect');
     const preconnectOrigins = new Set(preconnectLinks.map(link => URL.getOrigin(link.href || '')));
 
+    if (preconnectLinks.length >= 6) {
```
[the remark this answers is not in the document]
Comment (patrickhulce) [reply lighthouse-core/audits/uses-rel-preconnect.js]: @brendankenny we explicitly avoided doing this in the original PR for this audit because we don't know which origin is actually the most impactful one for the UX to be preconnecting to so we show the users all the options. 

maybe we need to add something more explicit to state how many of the ones below they should be adding, but I would not want to only show `maxAllowedPreconnects - currentPreconnectCount`

[the remark this answers is not in the document]
Comment (brendankenny) [reply lighthouse-core/audits/uses-rel-preconnect.js]: > we explicitly avoided doing this in the original PR for this audit because we don't know which origin is actually the most impactful one for the UX to be preconnecting to so we show the users all the options.

that's a good point, but it's a bit weird for it to suggest a long list at 5 and then suddenly say nothing at 6 (including if the 6 did nothing to speed things up)

[the remark this answers is not in the document]
Comment (brendankenny) [reply lighthouse-core/audits/uses-rel-preconnect.js]: if we wanted to defer making a change on that, this could also just push a warning if `preconnectLinks.length > 8` and not do the early return on `preconnectLinks.length >= 6)`, instead proceeding as before

[the remark this answers is not in the document]
Comment (patrickhulce) [reply lighthouse-core/audits/uses-rel-preconnect.js]: Very true. I like the idea of throwing a warning and passing it but still including all the origins that would be other options 👍

**Comment by patrickhulce** [comment]
> the audit will currently suggest that you preconnect to all preconnectable origins

We definitely don't want to say this :)

> It seems like a warning that preconnects aren't being used

We do in fact do this already.

**Comment by brendankenny** [comment]
> > It seems like a warning that preconnects aren't being used
> 
> We do in fact do this already.
> 
> https://github.com/GoogleChrome/lighthouse/blame/6e5fc878f8cc69e00620b20092bfad1da6c1e4e2/lighthouse-core/audits/uses-rel-preconnect.js#L168-L172

That's for origins that a resource was loaded from but didn't take advantage of an attempted preconnect. But if I had a preconnect for `random-origin.com` and never loaded anything from it, we wouldn't flag anything in that case, right?

**Comment by patrickhulce** [comment]
> But if I had a preconnect for random-origin.com and never loaded anything from it, we wouldn't flag anything in that case, right?

Oh like you completely stopped making requests to that origin entirely? We wouldn't flag that right now, but we don't wouldn't flag that in preload either and you asked for "like we do in uses-rel-preload" ;) (not sure it's even possible for preload requests?)

**Comment by piotrzarycki** [comment]
@patrickhulce @brendankenny 
Any additional modifications should be done, to finish this PR?

**Comment by patrickhulce** [comment]
@piotrzarycki I think @brendankenny would feel more comfortable with this change if we still returned the `details` items in this case, so basically not an early return but still use the `warnings` and `score` values.

Is this right @brendankenny ?

**Comment by paulirish** [comment]
(there's more recent discussion in #9894 ... )

and from the linked twitter thread, tarun also says

> BTW, even 3 can be too many, especially if the 3 preconnects are themselves not useful. We did an experiment to eliminate the unnecessary preconnects initiated by Chrome (https://crbug.com/962693). The experiment reduced the page aborts (before FCP) by ~5.2% on slow networks.

so yeah I feel good about our warning at 3.

File: lighthouse-core/audits/uses-rel-preconnect.js [hunk 4]
```diff
@@ -35,6 +35,11 @@ const UIStrings = {
    * */
   crossoriginWarning: 'A preconnect <link> was found for "{securityOrigin}" but was not used ' +
     'by the browser. Check that you are using the `crossorigin` attribute properly.',
+  /**
+   * @description A warning message that is shown when found more than 8 preconnected links
+   * */
+  tooManyPreconnectLinksWarning: 'More than 8 preconnect links were found. ' +
```
Comment (paulirish) [inline lighthouse-core/audits/uses-rel-preconnect.js]: 8 -> 3 here and in the description

File: lighthouse-core/audits/uses-rel-preconnect.js [hunk 5]
```diff
@@ -135,6 +140,13 @@ class UsesRelPreconnectAudit extends Audit {
     const preconnectLinks = artifacts.LinkElements.filter(el => el.rel === 'preconnect');
     const preconnectOrigins = new Set(preconnectLinks.map(link => URL.getOrigin(link.href || '')));
 
+    if (preconnectLinks.length >= 3) {
```
Comment (paulirish) [inline lighthouse-core/audits/uses-rel-preconnect.js]:
```suggestion
    // https://twitter.com/_tbansal/status/1197771385172480001
    if (preconnectLinks.length >= 3) {
```

File: lighthouse-core/test/audits/uses-rel-preconnect-test.js [hunk 6]
```diff
@@ -250,4 +250,76 @@ describe('Performance: uses-rel-preconnect audit', () => {
       {url: 'http://cdn.example.com', wastedMs: 150},
     ]);
   });
+
+  it(`should return code 1 if preconnect links equal length 6`, async () => {
```
Comment (paulirish) [inline lighthouse-core/test/audits/uses-rel-preconnect-test.js]: drop this test and just assert warnings.length === 0  in the previous test (like at L252)

File: lighthouse-core/test/audits/uses-rel-preconnect-test.js [hunk 7]
```diff
@@ -250,4 +250,76 @@ describe('Performance: uses-rel-preconnect audit', () => {
...
+      URL: {finalUrl: mainResource.url},
+    };
+
+    const context = {settings: {}, computedCache: new Map()};
+    const result = await UsesRelPreconnect.audit(artifacts, context);
+    assert.equal(result.score, 1);
+    assert.equal(result.warnings.length, 0);
+  });
+
+  it('should return code 1 with warning if links length is equal or more than 8', async () => {
```
Comment (paulirish) [inline lighthouse-core/test/audits/uses-rel-preconnect-test.js]:
```suggestion
  it('should pass with a warning if too many preconnects found', async () => {
```

Comment (piotrzarycki) [reply lighthouse-core/test/audits/uses-rel-preconnect-test.js]: done

File: lighthouse-core/test/audits/uses-rel-preconnect-test.js (hunk 6 above)
Comment (piotrzarycki) [reply lighthouse-core/test/audits/uses-rel-preconnect-test.js]: done

File: lighthouse-core/audits/uses-rel-preconnect.js (hunk 4 above)
Comment (connorjclark) [inline lighthouse-core/audits/uses-rel-preconnect.js]:
```suggestion
  tooManyPreconnectLinksWarning: 'More than 3 preconnect links were found. ' +
```

File: lighthouse-core/audits/uses-rel-preconnect.js [hunk 8]
```diff
@@ -35,6 +35,11 @@ const UIStrings = {
    * */
   crossoriginWarning: 'A preconnect <link> was found for "{securityOrigin}" but was not used ' +
     'by the browser. Check that you are using the `crossorigin` attribute properly.',
+  /**
+   * @description A warning message that is shown when found more than 8 preconnected links
```
Comment (connorjclark) [inline lighthouse-core/audits/uses-rel-preconnect.js]:
```suggestion
   * @description A warning message that is shown when found more than 3 preconnected links
```

File: lighthouse-core/audits/uses-rel-preconnect.js [hunk 9]
```diff
@@ -135,6 +140,14 @@ class UsesRelPreconnectAudit extends Audit {
     const preconnectLinks = artifacts.LinkElements.filter(el => el.rel === 'preconnect');
     const preconnectOrigins = new Set(preconnectLinks.map(link => URL.getOrigin(link.href || '')));
 
+    // https://twitter.com/_tbansal/status/1197771385172480001
+    if (preconnectLinks.length >= 3) {
```
Comment (connorjclark) [inline lighthouse-core/audits/uses-rel-preconnect.js]:
```suggestion
    if (preconnectLinks.length > 3) {
```

File: lighthouse-core/audits/uses-rel-preconnect.js [hunk 10]
```diff
@@ -135,6 +140,14 @@ class UsesRelPreconnectAudit extends Audit {
...
+      return {
+        score: 1,
+        warnings: preconnectLinks.length > 8
```
Comment (connorjclark) [inline lighthouse-core/audits/uses-rel-preconnect.js]: `warnings: [str_(UIStrings.tooManyPreconnectLinksWarning)]`

File: lighthouse-core/test/audits/uses-rel-preconnect-test.js [hunk 11]
```diff
@@ -242,12 +242,55 @@ describe('Performance: uses-rel-preconnect audit', () => {
...
+        },
+      },
+    ];
+    const artifacts = {
+      LinkElements: [
+        {rel: 'preconnect', href: 'https://cdn1.example.com/'},
+        {rel: 'preconnect', href: 'https://cdn2.example.com/'},
+        {rel: 'preconnect', href: 'https://cdn3.example.com/'},
+        {rel: 'preconnect', href: 'https://cdn4.example.com/'},
+        {rel: 'preconnect', href: 'https://cdn5.example.com/'},
```
Comment (connorjclark) [inline lighthouse-core/test/audits/uses-rel-preconnect-test.js]: reduce to 4 elements

File: lighthouse-core/audits/uses-rel-preconnect.js (hunk 4 above)
Comment (connorjclark) [reply lighthouse-core/audits/uses-rel-preconnect.js]: warning at 3 or 4? Please note the sentence structure here - i.e `_more_ than 3`.

From your comment https://github.com/GoogleChrome/lighthouse/pull/9903#issuecomment-564796338, I think you meant to suggest doing `More than 2` (which means we warn at 3).

File: lighthouse-core/audits/uses-rel-preconnect.js [hunk 12]
```diff
@@ -35,6 +35,11 @@ const UIStrings = {
    * */
   crossoriginWarning: 'A preconnect <link> was found for "{securityOrigin}" but was not used ' +
     'by the browser. Check that you are using the `crossorigin` attribute properly.',
+  /**
```
Comment (exterkamp) [inline lighthouse-core/audits/uses-rel-preconnect.js]: Don't need the `@description` tag if it is the only tag.

```suggestion
  /** A warning message that is shown when found more than 3 preconnected links */
```

plus delete l#39 and l#40

File: lighthouse-core/audits/uses-rel-preconnect.js [hunk 13]
```diff
@@ -35,6 +35,9 @@ const UIStrings = {
    * */
   crossoriginWarning: 'A preconnect <link> was found for "{securityOrigin}" but was not used ' +
     'by the browser. Check that you are using the `crossorigin` attribute properly.',
+  /** A warning message that is shown when found more than 3 preconnected links */
```
Comment (connorjclark) [inline lighthouse-core/audits/uses-rel-preconnect.js]:
```suggestion
  /** A warning message that is shown when found more than 2 preconnected links */
```
