### PR TITLE
tests(smoke): print multiple differences

### LINKED ISSUE #14128: Smoke runner should display more than one failed assertion at a time
currently we only show _one_ difference:

image

but that can be annoying when multiple are failing. would be nice to determine/list all of them

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #14128

Brendan mentioned [here](https://github.com/GoogleChrome/lighthouse/pull/14138#issuecomment-1159073385) that presenting all the differences in a smoke test may be noisy. This PR doesn't take any of that into account (I did first try to limit the amount of differences as determined [here](https://github.com/GoogleChrome/lighthouse/issues/14128#issuecomment-1159153096), but that seems to reduce to the same behavior we have today), first I'd like to see exactly what the smoke results might look like when too noisy. @brendankenny can you think of a good way to test this?

### CODE REVIEW

File: lighthouse-cli/test/smokehouse/report-assert.js [hunk 1]
```diff
@@ -427,19 +425,20 @@ function reportAssertion(localConsole, assertion) {
...
-      const msg = `
+    if (assertion.diff?.length) {
+      for (const diff of assertion.diff) {
+        const msg = `
   ${log.redify(log.cross)} difference at ${log.bold}${diff.path}${log.reset}
               expected: ${JSON.stringify(diff.expected)}
-                 found: ${JSON.stringify(diff.actual)}
+                 found: ${JSON.stringify(diff.actual)}\n`;
+        localConsole.log(msg);
+      }
```
Comment (connorjclark) [inline lighthouse-cli/test/smokehouse/report-assert.js:435]: praying for `String.dedent`

File: lighthouse-cli/test/smokehouse/report-assert.js [hunk 2]
```diff
@@ -96,13 +96,14 @@ function findDifference(path, actual, expected) {
...
-    return {
+    return [{
       path,
       actual,
       expected,
-    };
+    }];
   }
 
+  const diff = [];
```
Comment (brendankenny) [inline lighthouse-cli/test/smokehouse/report-assert.js:106]: switch to `diffs` since it's an array of `Difference`s?

File: lighthouse-cli/test/smokehouse/report-assert.js [hunk 3]
```diff
@@ -157,42 +158,39 @@ function findDifference(path, actual, expected) {
         const matchingIndex = arrToCheckAgainst.findIndex(actualEntry =>
             !findDifference(keyPath, actualEntry, expectedExclusion));
         if (matchingIndex !== -1) {
-          return {
+          return [{
```
Comment (brendankenny) [inline lighthouse-cli/test/smokehouse/report-assert.js:161]: why return instead of push?

**Review by brendankenny — COMMENTED** [review]
> first I'd like to see exactly what the smoke results might look like when too noisy

two examples I can think of:
- eliminate an entry in an array, e.g. the [first `LinkElements` entry in dbw](https://github.com/GoogleChrome/lighthouse/blob/16a4ccf6c18e0738ce695a52785966a0365538ab/lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js#L43-L51)
- rename an object, e.g. rename the dbw `LinkElements` entry to `ConsoleMessages`

both are quite noisy.

That said, I tried this PR out a bit and it seems like it will still be worth it. The fact that expectations are usually limited in size and they're what drive the comparisons means that often even excessive errors aren't that bad (`LinkElements` and `ConsoleMessages` also happen to both be arrays, rename `LinkElements` to `URL` (which is an object) instead and the diff list is considerably smaller).

File: lighthouse-cli/test/smokehouse/report-assert.js [hunk 4]
```diff
@@ -427,19 +425,20 @@ function reportAssertion(localConsole, assertion) {
           log.greenify(assertion.actual));
     }
   } else {
-    if (assertion.diff) {
-      const diff = assertion.diff;
-      const fullActual = String(JSON.stringify(assertion.actual, null, 2))
```
Comment (brendankenny) [inline lighthouse-cli/test/smokehouse/report-assert.js:432]: little did you know this was a [load-bearing `String()`](https://github.com/GoogleChrome/lighthouse/pull/9130/files#r290982686) (try renaming `LinkElements` to `LinkElementz` or whatever :)

Though I certainly didn't remember why it was there, so we can change it to something more obvious that does the same thing

Comment (connorjclark) [reply lighthouse-cli/test/smokehouse/report-assert.js:432]: Made it more explicit and added tests.

**Review by adamraine — APPROVED** [review]
