### PR TITLE
core: improve resilience of nodeId-dependent gatherers

### LINKED ISSUE #10893: LCP element and ALLS diagnostics give an Error though working on web.dev/measure
#### Provide the steps to reproduce
1. Run LH on https://web.dev/optimize-cls/ (without any flags, but also with ```--preset perf``` as well as headless)

#### What is the current behavior?

The diagnostics for
* Largest Contentful Paint element
* Avoid large layout shifts

both show "Error!" as can be seen in this screenshot:

lighthouse_lcp-alls_web dev-optimize-cls_error-local-cli_2020-06-01

There are some errors/warnings on stdout that seem to be related:
```  status Gathering: ResponseCompression +42ms
  status Gathering: TagsBlockingFirstPaint +6ms
  status Gathering: TraceElements +4ms
  method <= browser ERR:error DOM.resolveNode  +33ms
  status Disconnecting from browser... +56ms
  status Analyzing and running audits... +13ms
  status Auditing: First Contentful Paint +6ms
  ...
  status Auditing: Minimize third-party usage +1ms
  status Auditing: Largest Contentful Paint element +98ms
  Runner:warn TraceElements gatherer, required by audit largest-contentful-paint-element, encountered an error: Protocol error (DOM.resolveNode): Node with given id does not belong to the document +1ms
  status Auditing: Avoid large layout shifts +0ms
  Runner:warn TraceElements gatherer, required by audit layout-shift-elements, encountered an error: Protocol error (DOM.resolveNode): Node with given id does not belong to the document +1ms
  status Auditing: Uses efficient cache policy on static assets +1ms
  status Auditing: Avoids enormous network payloads +2ms
```

#### What is the expected behavior?
* "Largest Contentful Paint element" should say "1 element found", giving the respective HTML
* "Avoid large layout shifts" should say "No elements found"

As can both be seen in this screenshot taken from a report generated on https://web.dev/optimize-cls/, where this seems to work despite this issue:

lighthouse_lcp-alls_web dev-optimize-cls_ok-on-web dev-measure_2020-06-01

Full web.dev report available here:
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fweb.dev%2Foptimize-cls%2F

#### Environment Information
* Affected Channels: CLI (PowerShell, as well as on WSL1)
* Lighthouse version: 6.0.0
* Chrome version: 83.0.4103.61 (Official Build) (64-bit) (cohort: Stable)
* Node.js version: 12.17.0
* Operating System: Windows 10, Build 1909

**Related issues**
Potentially https://github.com/GoogleChrome/lighthouse/issues/10869

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
There are a few gatherers that fail if the node ID fell out of memory. Adds a smoketest for the trace elements one since the CLS case is more common and reproducible than the LCP or anchor case.

Best repro: run on https://bonusi.soft-press.com/ to see that the category scores aren't `?` anymore

**Related Issues/PRs**
inspired by but does not address #10873 
fixes #10893

### CODE REVIEW

File: lighthouse-cli/test/fixtures/perf/delayed-element.js [hunk 1]
```diff
@@ -6,6 +6,24 @@
...
+function rerender(iterations) {
+  const rerender_ = (i, resolve) => {
+    const filler = `<div>Filler element</div>`.repeat(4000);
+    document.body.innerHTML = `<div id="div-${i}">${i} left</div>${filler}`;
+    if (i === 0) resolve();
+    if (i > 0) requestAnimationFrame(() => rerender_(i - 1, resolve));
+  };
+
+  return new Promise(resolve => rerender_(iterations, resolve));
+}
```
Comment (Beytoven) [inline lighthouse-cli/test/fixtures/perf/delayed-element.js:25]: Took me a minute to understand but this is really good!

File: lighthouse-cli/test/fixtures/perf/delayed-element.js [hunk 2]
```diff
@@ -6,6 +6,24 @@
...
 /* eslint-disable */
 
+/** Create long tasks on the main thread. */
+function stall(ms) {
+  const start = performance.now();
+  while (performance.now() - start < ms) ;
+}
+
+/** Render large number of elements to fill up the backend node cache. */
+function rerender(iterations) {
```
Comment (connorjclark) [inline lighthouse-cli/test/fixtures/perf/delayed-element.js:16]: might this be easier to read as an async function with a for loop, instead of a recursive promise function? the complexity then would just contained to `requestAnimationFrame` being wrapped in a Promise.

File: lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js [hunk 3]
```diff
@@ -199,4 +199,35 @@ module.exports = [
...
     },
   },
+  {
+    lhr: {
+      requestedUrl: 'http://localhost:10200/perf/trace-elements.html?missing',
+      finalUrl: 'http://localhost:10200/perf/trace-elements.html?missing',
+      audits: {
+        'largest-contentful-paint-element': {
+          score: null,
+          displayValue: '1 element found',
```
Comment (connorjclark) [inline lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js:209]: please remove display values, using an array in `details.items` is already asserting the length.

File: lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js [hunk 4]
```diff
@@ -199,4 +199,35 @@ module.exports = [
...
+              },
+            ],
+          },
+        },
+        'layout-shift-elements': {
+          score: null,
+          scoreDisplayMode: 'notApplicable',
+          details: {
+            items: {
+              length: 0,
```
Comment (connorjclark) [inline lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js:226]: an empty array does the same.

File: lighthouse-core/gather/gatherers/trace-elements.js [hunk 5]
```diff
@@ -109,6 +109,21 @@ class TraceElements extends Gatherer {
     return topFive;
   }
 
+  /**
+   * @param {LH.Gatherer.PassContext['driver']} driver
+   * @param {number} backendNodeId
+   * @return {Promise<string|undefined>}
+   */
+  async resolveNodeId(driver, backendNodeId) {
```
Comment (connorjclark) [inline lighthouse-core/gather/gatherers/trace-elements.js:117]: can this move to the Driver class?

Comment (patrickhulce) [reply lighthouse-core/gather/gatherers/trace-elements.js]: it certainly can although nothing else will use it in this way, is your concern mostly forward looking in making the same mistake?

File: lighthouse-cli/test/fixtures/perf/delayed-element.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-cli/test/fixtures/perf/delayed-element.js]: thanks @Beytoven! @connorjclark is right though, it was mean of me to expect others to parse a recursive version of something trivially iterative in nature, sorry you had to do that :) hopefully the new version is clearer 👍

File: lighthouse-core/gather/gatherers/trace-elements.js (hunk 5 above)
Comment (patrickhulce) [reply lighthouse-core/gather/gatherers/trace-elements.js]: either way, I think this was worth the cleanliness, so done :)

File: lighthouse-core/gather/driver.js [hunk 6]
```diff
@@ -1217,6 +1217,41 @@ class Driver {
     return flattenedDocument.nodes ? flattenedDocument.nodes : [];
   }
 
+  /**
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js:1220]: probably worth a comment description for these since the parameters/return values are only primitive types? And maybe a word on what `undefined` indicates

File: lighthouse-core/gather/driver.js [hunk 7]
```diff
@@ -1217,6 +1217,41 @@ class Driver {
...
+   * @param {number} backendNodeId
+   * @return {Promise<string|undefined>}
+   */
+  async resolveNodeIdToObjectId(backendNodeId) {
+    try {
+      const resolveNodeResponse = await this.sendCommand('DOM.resolveNode', {backendNodeId});
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js:1226]: are there any "call `DOM.getDocument` before running this" restrictions for these two new methods?

File: lighthouse-core/gather/driver.js (hunk 6 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js:1220]: done

File: lighthouse-core/gather/driver.js (hunk 7 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js:1229]: on the push to frontend one yes, added a note

Comment (paulirish) [reply lighthouse-core/gather/driver.js:1229]: hmmm is this true?

a comment @Beytoven had previously written: `// DOM.getDocument is necessary for pushNodesByBackendIdsToFrontend to properly retrieve nodeIds.`

I am pretty sure we found that while it was necessary for getting valid nodeIds, it's not necessary if you're getting these objectIds

also our codebase only has 1 remaining call to getDocument and it's unrelated.

all that said, i wouldn't mind keeping a comment around to remind us of this fact if we ever try to get nodeIds again

Comment (patrickhulce) [reply lighthouse-core/gather/driver.js:1229]: I can't tell if we're saying the same thing or not :)

> a comment @Beytoven had previously written: // DOM.getDocument is necessary for pushNodesByBackendIdsToFrontend to properly retrieve nodeIds.

I'm not sure where that one is, but I see @umaar 's comment in anchor elements that's probably a typo since it uses `pushNodeByPathToFrontend`, which is where I added the note in driver already.

Are you saying that `DOM.resolveNode` also requires `DOM.getDocument`? That would be surprising to me because trace-elements doesn't use it but seems to work. Happy to update the jsdoc on this function if that's wrong though.
