### PR TITLE
Fixup service worker detection test

### LINKED ISSUE #158: SW registration audit fails consistently
is registered fails in extension

### PR DESCRIPTION
**Pull request by samccone**
Fixes #158

### CODE REVIEW

File: gatherers/gather.js [hunk 1]
```diff
@@ -16,9 +16,24 @@
  */
 'use strict';
 
+function pendingPromiseFactory() {
+  let ret = {};
+
+  let p = new Promise((res, rej) => {
```
Comment (paullewis) [inline gatherers/gather.js]: Can be const I think

File: gatherers/gather.js [hunk 2]
```diff
@@ -16,9 +16,24 @@
  */
 'use strict';
 
+function pendingPromiseFactory() {
```
Comment (paullewis) [inline gatherers/gather.js]: What does the factory do? Feels side effecty

Comment (paullewis) [inline gatherers/gather.js]: Oh I get it. It's to set up a Promise that can be resolved when the SW data arrives

**Comment by paullewis** [comment]
Nit on the const. Otherwise LGTM

File: gatherers/service-worker.js [hunk 3]
```diff
@@ -19,19 +19,25 @@
 const Gather = require('./gather');
 
 class ServiceWorker extends Gather {
+  setup(options) {
```
Comment (brendankenny) [inline gatherers/service-worker.js]: Why not just create the promise here and save it on this object, return it in beforePageLoad?

File: gatherers/gather.js (hunk 2 above)
Comment (samccone) [inline gatherers/gather.js]: yep

File: gatherers/gather.js (hunk 1 above)
Comment (samccone) [inline gatherers/gather.js]: :+1:

File: gatherers/service-worker.js (hunk 3 above)
Comment (samccone) [inline gatherers/service-worker.js]: hmm I will move it into here for now, I had it in the super class because I wanted to extract it for reuse, but the argument is invalid until someone else needs it.

Comment (samccone) [inline gatherers/service-worker.js]: :+1: moved

File: gatherers/service-worker.js [hunk 4]
```diff
@@ -18,20 +18,42 @@
...
+
+  p.resolve = ret.resolve;
+  p.reject = ret.reject;
+
+  return p;
+}
+
 class ServiceWorker extends Gather {
+  setup(options) {
+    this.artifactsResolved = pendingPromiseFactory();
```
Comment (brendankenny) [inline gatherers/service-worker.js]: oh, I meant 
```
this.artifactsPromise = new Promise((res, rej) => {
  options.driver.on(
    'ServiceWorker.workerVersionUpdated', data => {
      if (ServiceWorker.getActivatedServiceWorker(data.versions) !== undefined) {
        this.artifact = {serviceWorkers: data};
        res();
     }
   });
});
```

and then `return this.artifactsPromise` in beforePageLoad.

Comment (samccone) [inline gatherers/service-worker.js]: +1
