### PR TITLE
extension: close the popup once the report has opened

### LINKED ISSUE #5340: extension: "Generating results" hangs around after report opns
to be fair this is the same session as #5339, but I've seen it before in the 3.0 era.

#### Provide the steps to reproduce
1. Run LH extension on paulirish.com
2. dont switch to another window while it's doing stuff.
3. it opens new window with the report, but the popup stays open on 'generating results...'

image

### PR DESCRIPTION
**Pull request by paulirish**
fixes #5340 

thanks https://stackoverflow.com/questions/4924615/chrome-extension-force-popup-html-to-close <3

Tested error -> reporting flow and it lg, too.

### CODE REVIEW

File: lighthouse-extension/app/src/popup.js [hunk 1]
```diff
@@ -117,18 +117,27 @@ function createOptionItem(text, id, isChecked) {
...
+      flags: {throttlingMethod: useDevTools ? 'devtools' : 'simulate'},
+    }, selectedCategories);
+
+    // Close popup once report is opened in a new tab
+    window.close();
+  } catch (err) {
+    handleError(err);
+  }
+
+  function handleError(err) {
```
Comment (brendankenny) [inline lighthouse-extension/app/src/popup.js]: any reason to make this a function? I'd say either spin off as it's own function or just nest in the catch{}
