### PR TITLE
core: alias element.currentSrc to element.src in node snippet

### LINKED ISSUE #11895: Bad evaluation LCP and Best Practices on picture tag
On this page (https://www.kortic.com/photographie/skateboard-volant.html) , Lighthouse matches only the src tag and ignores the source tags. So LCP is wrong. It says : 
```
Largest Contentful Paint element 1 element found

Skateboard (volant) <img decoding="async" loading="lazy" src="/images/card/950/643c16e4/skateboard-volant-2.jpg" alt="Skateboard (volant)" aria-labelledby="imgContentInfo" itemprop="contentUrl">
```
Additionnaly, the evaluation of best practice "Serves images with low resolution" is wrong too on the same element : 
Displayed size | Actual size | Expected size
360 x 360 | 420 x 420 | 945 x 945

However, only the "/images/card/420/643c16e4/skateboard-volant-2.jpg" is loaded on mobile.

The original source is : 
```
<picture>
<source media="(max-width: 29.9375rem)" srcset="/images/card/420/643c16e4/skateboard-volant-2.jpg">
<source media="(min-width: 30rem) and (max-width: 63.9375rem)" srcset="/images/card/500/643c16e4/skateboard-volant-2.jpg">
<img decoding="async" loading="lazy" src="/images/card/950/643c16e4/skateboard-volant-2.jpg" alt="Skateboard (volant)" aria-labelledby="imgContentInfo" itemprop="contentUrl">
</picture>
```

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #11895

### CODE REVIEW

**Comment by connorjclark** [comment]
image

ooooh interesting.

we could skip overriding the `src` if `new URL(img.getAttribute('src'), location.href).toString() === img.src`

File: lighthouse-core/lib/page-functions.js [hunk 1]
```diff
@@ -155,15 +155,33 @@ function getOuterHTMLSnippet(element, ignoreAttrs = [], snippetCharacterLimit =
...
+        if (new URL(attributeValue, documentHref).toString() !== currentSrc) {
+          attributeValue = currentSrc;
+          dirty = true;
         }
-        charCount += attributeName.length + attributeValue.length;
       }
+
+      // Elide attribute value if too long.
+      if (attributeValue.length > ATTRIBUTE_CHAR_LIMIT) {
+        attributeValue = attributeValue.slice(0, ATTRIBUTE_CHAR_LIMIT - 1) + '…';
```
Comment (connorjclark) [inline lighthouse-core/lib/page-functions.js:179]: possible future change: I'm thinking eliding is more useful if done m[i](https://www.youtube.com/watch?v=0rhdOt9bOHE)ddle-out. @Beytoven wdyt?

Comment (Beytoven) [reply lighthouse-core/lib/page-functions.js:179]: By middle-out do you mean having the '...' in the middle with `ATTRIBUTE_CHAR_LIMIT/2` characters on each side? If so, that could be more useful although, just like the current implementation, the usefulness will be dependent on the element and the way it's attributes are set up.

Comment (connorjclark) [reply lighthouse-core/lib/page-functions.js:179]: the argument is straightforward for url values (the last bit has the filename, so that's pretty important). but pretty much agree it's 50/50 on which is better for arbitrary values.

there's also the super complex `Util.getURLDisplayName` that does a url-specific eliding

Comment (patrickhulce) [reply lighthouse-core/lib/page-functions.js:179]: additional eliding thought, always elide the origin if it matches the ownerDocument's

File: lighthouse-core/lib/page-functions.js [hunk 2]
```diff
@@ -155,15 +155,33 @@ function getOuterHTMLSnippet(element, ignoreAttrs = [], snippetCharacterLimit =
...
+      if (attributeValue === null) continue; // Can't happen.
+
+      let dirty = false;
+
+      // Replace img.src with img.currentSrc.
+      if (attributeName === 'src' && element.tagName === 'IMG') {
+        const currentSrc = /** @type {HTMLImageElement} */ (element).currentSrc;
+        // Only replace if the two URLs do not resolve to the same location.
+        const documentHref = element.ownerDocument.location.href;
+        if (new URL(attributeValue, documentHref).toString() !== currentSrc) {
```
Comment (patrickhulce) [inline lighthouse-core/lib/page-functions.js:171]: my initial instinct was that this will throw for invalid values, but I recently learned ( #12008) that Chrome's URL is waaaaay more lenient than node's. Worth a test/catch anyway?

The failure mode for `getOuterHTMLSnippet` is quite painful in that it will typically fail the entire gatherer

**Review by patrickhulce — APPROVED** [review]
LGTM, ~~though I'd definitely feel better with a catch in our snippet creation logic the more we do with it~~ we're already covered :)

File: lighthouse-core/lib/page-functions.js (hunk 2 above)
Comment (connorjclark) [reply lighthouse-core/lib/page-functions.js:171]: This entire block is wrapped in a try catch, so the failure mode is just that the snippet is `<tagName>`.

Want me to pull this out to another function w/ another try/catch?

Comment (patrickhulce) [reply lighthouse-core/lib/page-functions.js:171]: oh I totally missed that I was chasing the chain upwards but it was right here elided 😆 

sorry for the noise!

File: lighthouse-core/lib/page-functions.js [hunk 3]
```diff
@@ -155,15 +155,33 @@ function getOuterHTMLSnippet(element, ignoreAttrs = [], snippetCharacterLimit =
...
+        continue;
+      }
+
+      let attributeValue = clone.getAttribute(attributeName);
+      if (attributeValue === null) continue; // Can't happen.
+
+      let dirty = false;
+
+      // Replace img.src with img.currentSrc.
+      if (attributeName === 'src' && element.tagName === 'IMG') {
```
Comment (paulirish) [inline lighthouse-core/lib/page-functions.js:167]:
```suggestion
      if (attributeName === 'src' && 'currentSrc' in element) {
```

bonus.. also get this behavior for `<audio>` and `<video>` elems.
