### PR TITLE
core(stacks): timeout stack detection

### LINKED ISSUE #11124: Chrome crashes when running stacks gatherer sometimes
Filed from https://github.com/GoogleChrome/lighthouse-ci/issues/381#issuecomment-660430414

image

#### Provide the steps to reproduce
1. Lots of complicated infrastructure setup described in https://github.com/GoogleChrome/lighthouse-ci/issues/381#issuecomment-660430414 :(

> AWS Lightsail Node-js server(v12.6.1) at 4 GB RAM, 2 vCPUs, 80 GB SSD.
The folllowing exact commands were run:
1 mkdir node-apps
2 cd node-apps
3 touch apps.js
4 edit apps.js to initiate a server on port 3000
const http = require('http') ;
const server = http.createServer((req,res) => {
res.end("Server Running!") ;
})cd
server.listen(3000) ;
5 npm init - complete the wizard
6 sudo npm install -g lighthouse
6 sudo npm install -g chromium-launcher
7 sudo apt install chromium-browser
8 chromium-browser --product-version
9 sudo npm install -g tcp-port-used
the following lighthouse cli was run
lighthouse https://www.etihad.com/ --chrome-flags="--headless" --output json --output ht
ml --output-path ./myfile.json --collect.settings.disableStorageReset --verbose

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: v6.1.1
* Chrome version: ?
* Node.js version: ?
* Operating System: ?

**Related issues**
ref https://github.com/GoogleChrome/lighthouse/issues/6512

I have been unable to reproduce this error so far, but Chrome crashing in the middle probably should result in a more specific error message with Chrome log output rather than the dreaded protocol message.

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
The stacks gatherer has a few async detections that can never resolve when the page overrides fetch or does other weird things. When this happens the entire run becomes fatal 😢 

This adds a strict 1s timeout to each async detection to avoid PROTOCOL_TIMEOUT.

Real-world site that had this problem: https://www.tiffany.com/ 

**Related Issues/PRs**
fixes #11124 
upstream fix https://github.com/johnmichel/Library-Detector-for-Chrome/pull/175

### CODE REVIEW

File: lighthouse-core/lib/stack-collector.js [hunk 1]
```diff
@@ -51,7 +51,12 @@ async function detectLibraries() {
 
   for (const [name, lib] of Object.entries(libraryDetectorTests)) {
     try {
-      const result = await lib.test(window);
+      /** @type {NodeJS.Timeout|undefined} */
+      let timeout;
+      const timeoutPromise = new Promise(r => timeout = setTimeout(() => r(false), 1000));
```
Comment (paulirish) [inline lighthouse-core/lib/stack-collector.js:56]: add a comment?  also can it point to https://github.com/GoogleChrome/lighthouse/pull/11172
