### PR TITLE
extension: better error message if user attempts to audit the Chrome Web Store

### LINKED ISSUE #1023: Extension Error: The extensions gallery cannot be scripted
**Lighthouse Version**: 1.2.0
**Chrome Version**: 54.0.2840.99
**Error Message**: The extensions gallery cannot be scripted.
**Stack Trace**:
 ```undefined```

### PR DESCRIPTION
**Pull request by brendankenny**
fixes #1023

### CODE REVIEW

**Comment by brendankenny** [comment]
As mentioned in that bug, the Chrome extension debugger API [isn't allowed to attach to the Chrome Web Store](https://chromium.googlesource.com/chromium/src/+/5d1f214db0f7996f3c17cd87093d439ce4c7f8f1/chrome/common/extensions/chrome_extensions_client.cc#232). This gives a hardcoded message to explain that and removes the "Report Error" link since it isn't an error.

This PR also wraps `chrome.debugger.attach` and `detach` errors in an `Error` so we'll get stack traces for future errors at those points.

Happy to bikeshed on variable names. Best I could do right now :)

File: lighthouse-extension/app/src/popup.js [hunk 1]
```diff
@@ -37,6 +37,20 @@ document.addEventListener('DOMContentLoaded', _ => {
 
   const MAX_ISSUE_ERROR_LENGTH = 60;
 
+  /**
+   * Error strings that indicate a problem in how Lighthouse was run, not in
+   * Lighthouse itself, mapped to more useful strings to report to the user.
+   */
+  const NON_BUG_ERROR_MESSAGES = {
+    'Another debugger': 'You probably have DevTools open. Close DevTools to use lighthouse',
```
Comment (addyosmani) [inline lighthouse-extension/app/src/popup.js]: s/lighthouse/Lighthouse?

Comment (brendankenny) [inline lighthouse-extension/app/src/popup.js]: done
