### PR TITLE
FMP metrics: Don't require tracingStartedInPage to precede navStart 

### LINKED ISSUE #753: extension trace issues (occasional -1 on TTI)
I spent a little while looking into the latest trace issues, which seem to be only occurring in the extension. Usual manifestation is a -1 on TTI due to an error inside it while calculating FMP, even though the exact same calculation of FMP on the same trace was successful in an earlier audit. news.google.com is a site that can often produce this. Information dump in case this takes me a little while to get back to or someone else wants to take over.

tl;dr, I'm currently thinking:
- [x] Sort in `ts` order for FMP calculation. This would make us more correct but also unable to calculate FMP in more cases in the extension, at least.
- [ ] Fix anywhere else we're dependent on ordering of entries in `traceEvents` array
- [x] Fix #618 when m54 comes out (~end of October)
- [ ] Find out why ordering of events from the same thread can be different when looking at `ts` vs `tts` and (if expected) which timestamp should win in those cases
- [ ] Better surface `debugString`s in the extension so it's clearer why -1s are popping up. They're in the pretty print version of the report for the CLI, so it would be nice to at least `log.warn` them somewhere (in `lighthouse-background.js` before populating the report, maybe?) so you don't have to set breakpoints just to see them on the extension side.

---

What I've found so far:
The proximate cause is weird trace event ordering. When we're trying to find what we consider to be navigation start in a trace, [we look for the first `navigationStart` event after the `TracingStartedInPage` event](https://github.com/GoogleChrome/lighthouse/blob/3dd1caca56f2edc74ab638378920a0f36b5ccc17/lighthouse-core/audits/first-meaningful-paint.js#L170-L178). A typical example problem trace, highlighting the `TracingStartedInPage` and `navigationStart` events:

screen shot 2016-10-06 at 12 33 07
- If we look at `event.ts` ("the tracing clock timestamp") in this example, _both_ `navigationStart` events occur before the `TracingStartedInPage` event, so according to `ts`, there is no nav start event after tracing started.
- If we look at `event.tts` ("the thread clock timestamp of the event"), there _is_ a `navigationStart` event after the tracing started.

All three events are in the same thread, so I don't see how they could have a different ordering based on the clock used. Interestingly, after many many runs I haven't been able to recreate this situation in the CLI, so I'm wondering if this is a weird timestamp bug somehow due to tracing from an extension.

I've uploaded an example trace to [a gist](https://gist.github.com/brendankenny/1ecd3d076bc016360a36afe30ce78cec), which you can look at [in timeline viewer](https://www.google.com/url?q=https%3A%2F%2Fchromedevtools.github.io%2Ftimeline-viewer%2F%3FloadTimelineFromURL%3Dhttps%3A%2F%2Fgist.github.com%2Fbrendankenny%2F1ecd3d076bc016360a36afe30ce78cec%2Fraw%2Ff9d1db5cf06421e029ef3c2febfae5e9ba92e2cd%2Fbad_ts_ordering.json&sa=D&sntz=1&usg=AFQjCNHpBuN2VLIj4qj-d18Ni5d4Rvq0aQ).

Other issues at work here:
- The reason that one FMP calculation is successful while the next fails is that catapult/traceviewer is changing the array order of the trace events out from under us when we pass the trace into it between the two FMP calls. Specifically, it appears to sort the events purely by `ts`, which is _not_ the order before we pass it in to traceviewer (it appears to be mostly, but not completely, in `tts` order).
  
  The [calculation code](https://github.com/GoogleChrome/lighthouse/blob/3dd1caca56f2edc74ab638378920a0f36b5ccc17/lighthouse-core/audits/first-meaningful-paint.js#L170-L178) assumes that a `navigationStart` event will be found after `TracingStartedInPage`. As stated above, if in `tts` order, we find the `navigationStart` where we expect it. When traceviewer sorts in `ts` order, no `navigationStart` is after tracing start, so we fail.
  
  We could prevent traceviewer from changing things by only passing a copy of the trace in or we could cache the FMP calculation, but...
- We're sensitive to ordering of events in the trace, which [we shouldn't be](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit#heading=h.f2f0yd51wi15). In this case, if we explicitly order by `tts` before calculating FMP (as we implicitly depend on in the first run through FMP), we can continue to calculate successfully. However, we use `ts` for basically all other calculations, so it feels like we should be explicitly ordering by `ts`, always fail at calculating FMP in this situation, and hope this can be fixed upstream.
- When Chrome 54 hits stable, [we'll have a totally new way of calculating FMP](https://github.com/GoogleChrome/lighthouse/issues/618) which won't be sensitive to this, so some of this will soon (~end of October) be irrelevant. However, we should be more certain on the timestamps we use, be insensitive to trace event ordering, and we'll still need to know which `navigationStart` event we care about for other calculations.

### PR DESCRIPTION
**Pull request by paulirish**
The short version is: sometimes traces have the `tracingStartedInPage` event following after the `navigationStart`. We use the former to find our renderer thread of interest. The navStart is the time origin for all our metrics.

This PR changes the logic to align with [traceviewer's approach](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/system_health/loading_metric.html): look at navStarts that precede events of interest.

This PR also adds two new tests:

1. a trace of chrome://history which was reported by a user as failing to deliver metrics
1. the `bad-nav-start-ts.json` which was asserted to return a -1, but actually should be working. So now we deliver real values.

Fixes #753

#### Some examples:

gmail:
image

chrome://history:
image

devtools.chrome.com
image

### CODE REVIEW

File: lighthouse-core/audits/first-meaningful-paint.js [hunk 1]
```diff
@@ -83,9 +74,14 @@ class FirstMeaningfulPaint extends Audit {
...
 
-  static calculateScore(data) {
-    // First meaningful paint is the last timestamp observed from the candidates
-    const firstMeaningfulPaint = (data.fMP.ts - data.navStart.ts) / 1000;
+  static calculateScore(evts) {
+    const firstMeaningfulPaint = (evts.firstMeaningfulPaint.ts - evts.navigationStart.ts) / 1000;
+    const firstContentfulPaint = (evts.firstContentfulPaint.ts - evts.navigationStart.ts) / 1000;
+
+    const timings = {};
+    timings.navStart = evts.navigationStart.ts / 1000;
```
Comment (paulirish) [inline lighthouse-core/audits/first-meaningful-paint.js]: this is fair. Originally I was thinking of something like:

```js
{ 
  timestamps: {
    navStart: 8923942942.122,
    fCP: 8934942942.246,
    FMP: 8926942942.572
  },
  timings: {
    navStart: 0,
    fCP: 1201.33,
    FMP: 1642.55
  }
}
```

Happy to update it to this format.  And in fact, there are downstream consumers of the timestamps, so I'm happy to keep those around.

Comment (patrickhulce) [inline lighthouse-core/audits/first-meaningful-paint.js]: +1 to moving to that, a lot clearer what the values should look like there

Comment (paulirish) [inline lighthouse-core/audits/first-meaningful-paint.js]: done.

File: lighthouse-core/audits/first-meaningful-paint.js [hunk 2]
```diff
@@ -83,9 +74,23 @@ class FirstMeaningfulPaint extends Audit {
     });
   }
 
-  static calculateScore(data) {
-    // First meaningful paint is the last timestamp observed from the candidates
-    const firstMeaningfulPaint = (data.fMP.ts - data.navStart.ts) / 1000;
+  static calculateScore(evts) {
+    const firstMeaningfulPaint = (evts.firstMeaningfulPaint.ts - evts.navigationStart.ts) / 1000;
+    const firstContentfulPaint = (evts.firstContentfulPaint.ts - evts.navigationStart.ts) / 1000;
```
Comment (ebidel) [inline lighthouse-core/audits/first-meaningful-paint.js]: Just checking...I've seen multiple FCP events in a trace. https://bugs.chromium.org/p/chromium/issues/detail?id=673922. Will this need to be more robust to handle those cases?

File: lighthouse-core/audits/first-meaningful-paint.js [hunk 3]
```diff
@@ -99,59 +104,47 @@ class FirstMeaningfulPaint extends Audit {
...
+      return e.cat.includes('blink.user_timing') || e.name === 'TracingStartedInPage';
+    }).sort((event0, event1) => event0.ts - event1.ts);
+
+    // The first TracingStartedInPage in the trace is definitely our renderer thread of interest
+    // Beware: the tracingStartedInPage event can appear slightly after a navigationStart
+    const startedInPageEvt = eventsAllFrames.find(e => e.name === 'TracingStartedInPage');
+    // Filter to just events matching the frame ID for sanity
+    const events = eventsAllFrames.filter(e => e.args.frame === startedInPageEvt.args.data.page);
+
+    // Find our first FCP. Our navStart will be the latest one before fCP.
```
Comment (ebidel) [inline lighthouse-core/audits/first-meaningful-paint.js]: Move "Our navStart will be the latest one before fCP." comment before its line.

File: lighthouse-core/audits/first-meaningful-paint.js [hunk 4]
```diff
@@ -99,59 +104,47 @@ class FirstMeaningfulPaint extends Audit {
...
+    const firstFCP = events.find(e => e.name === 'firstContentfulPaint');
+    const navigationStart = events.filter(e =>
+        e.name === 'navigationStart' && e.ts < firstFCP.ts).pop();
+    // FMP will follow at/after the FCP
+    const firstMeaningfulPaint = events.find(e =>
```
Comment (ebidel) [inline lighthouse-core/audits/first-meaningful-paint.js]: despite the multiple finds, this is a lot cleaner than before. 👍

File: lighthouse-core/audits/time-to-interactive.js [hunk 5]
```diff
@@ -71,29 +71,29 @@ class TTIMetric extends Audit {
...
 
       // Process the trace
       const tracingProcessor = new TracingProcessor();
       const trace = artifacts.traces[Audit.DEFAULT_PASS];
       const model = tracingProcessor.init(trace);
       const endOfTraceTime = model.bounds.max;
 
-      // TODO: Wait for DOMContentLoadedEndEvent
-      const fMPts = timings.fMP + timings.navStart;
+      const fmpTiming = fmpResult.rawValue;
```
Comment (ebidel) [inline lighthouse-core/audits/time-to-interactive.js]: no more parseFloat?

File: lighthouse-core/audits/time-to-interactive.js [hunk 6]
```diff
@@ -147,6 +147,11 @@ class TTIMetric extends Audit {
           visuallyReady: visuallyReadyTiming.toFixed(1),
           mainThreadAvail: startTime.toFixed(1)
         },
+        timestamps: {
+          fMP: fMPtsInMS * 1000,
+          visuallyReady: (visuallyReadyTiming + navStartTsInMS) * 1000,
+          mainThreadAvail: (timeToInteractive + navStartTsInMS) * 1000
```
Comment (ebidel) [inline lighthouse-core/audits/time-to-interactive.js]: Is there a reason to call this `mainTreadAvail` instead of `timeToInteractive`?

File: lighthouse-core/audits/first-meaningful-paint.js (hunk 2 above)
Comment (paulirish) [inline lighthouse-core/audits/first-meaningful-paint.js]: it should handle that. The audit is only looking at the first fCP that has the same frameID as the first tracingStartedInPage. 

The [traces in fixtures](https://cloud.githubusercontent.com/assets/39191/21165321/7a1452d6-c153-11e6-8822-7ac58fea4c94.png) have multiple fCP's per trace already. :)

File: lighthouse-core/audits/time-to-interactive.js (hunk 5 above)
Comment (paulirish) [inline lighthouse-core/audits/time-to-interactive.js]: good question. I'm gonna normalize all the exported rawValues to be `parseFloat(num.toFixed(1))` so we never have to parseFloat randomly.

File: lighthouse-core/audits/time-to-interactive.js (hunk 6 above)
Comment (paulirish) [inline lighthouse-core/audits/time-to-interactive.js]: renamed.

File: lighthouse-core/test/audits/time-to-interactive-test.js [hunk 7]
```diff
@@ -53,8 +53,8 @@ describe('Performance: time-to-interactive audit', () => {
       assert.equal(output.rawValue, '1105.8', output.debugString);
       assert.equal(output.extendedInfo.value.expectedLatencyAtTTI, '20.72');
```
Comment (ebidel) [inline lighthouse-core/test/audits/time-to-interactive-test.js]: Shall we just make all of these floats?

Comment (paulirish) [inline lighthouse-core/test/audits/time-to-interactive-test.js]: k done
