### PR TITLE
fix: always ensure tracing is off before starting

### LINKED ISSUE #2272: Fix the "tracing already started" bug
Our primary issue for it: #1091 

Current bandaid proposal while we find a reliable repro...   call `Tracing.stop` early and consume any error. 

Caseq agrees this is harmless and worth a try.

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #2272

### CODE REVIEW

File: lighthouse-core/gather/connections/connection.js [hunk 1]
```diff
@@ -46,15 +46,16 @@ class Connection {
    * Call protocol methods
    * @param {!string} method
    * @param {!Object} params
+   * @param {boolean=} silent
```
Comment (patrickhulce) [inline lighthouse-core/gather/connections/connection.js]: open to much better names, `silenceError` felt like it would supress the error itself, `silenceErrorLogging` too verbose?

File: lighthouse-core/gather/driver.js [hunk 2]
```diff
@@ -710,9 +711,23 @@ class Driver {
...
+      // ensure tracing is stopped before we can start
+      // see https://github.com/GoogleChrome/lighthouse/issues/1091
+      .then(_ => this.endTraceIfStarted())
       .then(_ => this.sendCommand('Tracing.start', tracingOpts));
   }
 
+  endTraceIfStarted() {
+    return new Promise((resolve) => {
+      const traceCallback = () => resolve();
+      this.once('Tracing.tracingComplete', traceCallback);
```
Comment (paulirish) [inline lighthouse-core/gather/driver.js]: why listen here? what about

```js
this.sendCommand('Tracing.end').then(resolve, resolve);
```

File: lighthouse-core/gather/driver.js [hunk 3]
```diff
@@ -187,9 +187,10 @@ class Driver {
    * Call protocol methods
    * @param {!string} method
    * @param {!Object} params
+   * @param {boolean=} silent
    * @return {!Promise}
    */
-  sendCommand(method, params) {
+  sendCommand(method, params, silent) {
```
Comment (paulirish) [inline lighthouse-core/gather/driver.js]: im not crazy about the boolean trap here.  do we need this at all if we follow my idea below?

File: lighthouse-core/gather/driver.js (hunk 2 above)
Comment (patrickhulce) [inline lighthouse-core/gather/driver.js]: nah it moves on too quickly and still fails fatally with `tracing already started`, this seemed preferable to an arbitrary timeout

File: lighthouse-core/gather/driver.js (hunk 3 above)
Comment (patrickhulce) [inline lighthouse-core/gather/driver.js]: yeah regardless of that change the connection is currently hard coded for all messages with an error property to log them even if you don't care about the promise resolution

Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: the boolean trap is pretty gnarly. Before we hardcoded some error message to ignore it...we could do the same again. There could also be some kind of `log` trickery so that this call to `sendCommand` could silence an error it was expecting then turn the silencing off again. Pretty hacky ideas, though...

**Comment by patrickhulce** [comment]
@paulirish @brendankenny switched away from bool PTAL :)

File: lighthouse-core/gather/connections/connection.js [hunk 4]
```diff
@@ -46,15 +46,16 @@ class Connection {
    * Call protocol methods
    * @param {!string} method
    * @param {!Object} params
+   * @param {Object=} options
    * @return {!Promise}
    */
-  sendCommand(method, params = {}) {
+  sendCommand(method, params = {}, options = {}) {
```
Comment (paulirish) [inline lighthouse-core/gather/connections/connection.js]: sg, but can rename to `cmdOpts` or something? so it's clear this is different from our beloved `options` friend?

Comment (brendankenny) [inline lighthouse-core/gather/connections/connection.js]: Should also document it, not just it takes some options :) 

Wonder if it should be something like a regex so it's not just unconditionally ignoring errors. That would resemble the temporary fix we had for silencing domain enable/disable errors, which seemed like a good idea at the time

**Comment by brendankenny** [comment]
wdyt about `ignoreErrorPattern` or something instead of `silent`?

**Comment by patrickhulce** [comment]
> wdyt about ignoreErrorPattern or something instead of silent?

I think it's a slightly better bandaid for the situation at hand but introduces unnecessary complexity for something we want to get rid of in forthcoming catharsis :)

**Comment by brendankenny** [comment]
Wait, what are we removing that would fix the underlying problem? Or are you saying this is a temporary fix for something we want to actually fix?

**Comment by patrickhulce** [comment]
> Wait, what are we removing that would fix the underlying problem?

Oh that the connection class tries to do anything more than verbose logging to begin with! Isn't that what you were proposing anyway?

**Comment by paulirish** [comment]
let's wrap this guy up. i'm OK with merging and giving it a go.. see what happens.

to you, @brendankenny
