### PR TITLE
fix(report): prevents unicode newline from breaking the report

### LINKED ISSUE #3093: Report page is blank
Running from both the command line and as a browser extension, everything is seemingly successful, but the results page is blank.

screen shot 2017-08-23 at 12 32 13

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #3093

### CODE REVIEW

File: lighthouse-core/report/v2/report-generator.js [hunk 1]
```diff
@@ -116,7 +116,9 @@ class ReportGeneratorV2 {
    * @return {string}
    */
   generateReportHtml(reportAsJson) {
-    const sanitizedJson = JSON.stringify(reportAsJson).replace(/</g, '\\u003c');
+    const sanitizedJson = JSON.stringify(reportAsJson)
+      .replace(/</g, '\\u003c') // replaces opening script tags
+      .replace(/\u2028/g, '\\n'); // replaces line separators
```
Comment (brendankenny) [inline lighthouse-core/report/v2/report-generator.js]: we also need `\u2029` (see http://timelessrepo.com/json-isnt-a-javascript-subset)

File: lighthouse-core/test/report/v2/report-generator-test.js [hunk 2]
```diff
@@ -129,9 +129,9 @@ describe('ReportGeneratorV2', () => {
     });
 
     it('should inject the report JSON', () => {
-      const code = 'hax</script><script>console.log("pwned");%%LIGHTHOUSE_JAVASCRIPT%%';
+      const code = 'hax\u2028</script><script>console.log("pwned");%%LIGHTHOUSE_JAVASCRIPT%%';
       const result = new ReportGeneratorV2().generateReportHtml({code});
-      assert.ok(result.includes('"code":"hax'), 'injects the json');
+      assert.ok(result.includes('"code":"hax\\n'), 'injects the json');
       assert.ok(result.includes('\\u003c/script'), 'escapes HTML tags');
```
Comment (brendankenny) [inline lighthouse-core/test/report/v2/report-generator-test.js]: I noticed this line was passing regardless of having a `<` escape on the JSON because we also escape `<` elsewhere in the parts of the full HTML. e.g. `REPORT_JAVASCRIPT` is escaped too, so `Dummy text for ensuring report robustness: </script>` ends up passing this assertion even if the JSON isn't escaped.

Switching it to verifying more of the string at once could work around this

File: lighthouse-core/report/v2/report-generator.js (hunk 1 above)
Comment (brendankenny) [reply lighthouse-core/report/v2/report-generator.js]: and do we want to replace with new lines or with `\\u2028` and `\\u2029` to preserve the characters?

Comment (patrickhulce) [reply lighthouse-core/report/v2/report-generator.js]: yeah sure sg

File: lighthouse-core/test/report/v2/report-generator-test.js (hunk 2 above)
Comment (patrickhulce) [reply lighthouse-core/test/report/v2/report-generator-test.js]: ah I gotcha, yeah I added distinct assertions for the json and the javascript 👍
