### PR TITLE
core: increase Page.navigate timeout

### LINKED ISSUE #6407: core: Increase timeout for Page.navigate
```
cjamcl@cjamcl-macbookpro  ~/src/lighthouse   issue-6386-speed-up-font-size-gatherer ? ⍟1  node lighthouse-cli https://www.flynashville.com/Pages/default.aspx --view                  ✔  1637  11:59:01
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +518ms
  ChromeLauncher Waiting for browser.....✓ +1ms
  status Connecting to browser +138ms
  status Resetting state with about:blank +165ms
  status Benchmarking machine +327ms
  status Initializing… +511ms
  status Loading page & waiting for onload Scripts, CSSUsage, Viewport, ViewportDimensions, ThemeColor, Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage, Accessibility, AnchorsWithNoRelNoopener, AppCacheManifest, Doctype, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, MetaDescription, FontSize, CrawlableLinks, MetaRobots, Hreflang, EmbeddedContent, Canonical, RobotsTxt +15ms
(node:33528) UnhandledPromiseRejectionWarning: LHError: PROTOCOL_TIMEOUT Method: Page.navigate
    at Timeout._ [as _onTimeout] (/Users/cjamcl/src/lighthouse/lighthouse-core/gather/driver.js:290:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

`Page.navigate` times out occasionally for `https://www.flynashville.com/Pages/default.aspx`.

### PR DESCRIPTION
**Pull request by Hoten**
Fixes #6407

### CODE REVIEW

File: lighthouse-core/gather/driver.js [hunk 1]
```diff
@@ -840,6 +840,7 @@ class Driver {
     // happen _after_ onload: https://crbug.com/768961
     this.sendCommand('Page.enable');
     this.sendCommand('Emulation.setScriptExecutionDisabled', {value: disableJS});
+    this.setNextProtocolTimeout(30 * 1000);
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: > These can 'race' and that's OK.

apparently not :)

Feels like we should `await` `Page.enable` and `Emulation.setScriptExecutionDisabled` (either they're short and it's no big deal or they're long and we need to account for them) but we can save that for another day.
