### PR TITLE
core(webfonts): Patches fonts gatherer so it doesn't throw an exception

### LINKED ISSUE #4464: TypeError: Cannot read property 'src' of undefined
https://sentry.io/google-lighthouse/lighthouse/issues/454184109/

```
TypeError: Cannot read property 'src' of undefined
  File "/usr/lib/node_modules/lighthouse/lighthouse-core/gather/gatherers/fonts.js", line 149, in loadedFonts.map.fontFace
    fontFace.src = fontFaceItem.src || [];
  ?, in Array.map
  File "/usr/lib/node_modules/lighthouse/lighthouse-core/gather/gatherers/fonts.js", line 147, in Promise.all.then
    return loadedFonts.map(fontFace => {
  File "internal/process/next_tick.js", line 135, in process._tickDomainCallback

TypeError: Cannot read property 'src' of undefined
```

### PR DESCRIPTION
**Pull request by wardpeet**
fixes #4464

### CODE REVIEW

File: lighthouse-core/gather/gatherers/fonts.js [hunk 1]
```diff
@@ -146,7 +146,10 @@ class Fonts extends Gatherer {
     ).then(([loadedFonts, fontFaces]) => {
       return loadedFonts.map(fontFace => {
         const fontFaceItem = this._findSameFontFamily(fontFace, fontFaces);
-        fontFace.src = fontFaceItem.src || [];
+        fontFace.src = [];
```
Comment (patrickhulce) [inline lighthouse-core/gather/gatherers/fonts.js]: seems like we lost the case where `.src` is not an array but not sure if that's possible?

how abouts `fontFace.src = (fontFaceItem && fontFaceItem.src) || []`?

Comment (wardpeet) [reply lighthouse-core/gather/gatherers/fonts.js]: your wish is my command!
