### PR TITLE
report(devtools): fix wrong emulation string in meta block

### LINKED ISSUE #14671: Devtools incorrectly shows "no emulation" for mobile runs
image

#14515 changed `getEmulationDescriptions` to return "no emulation" when screenEmulation.disabled is true, which we do for devtools in `devtools-entry.js`.

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #14671

### CODE REVIEW

File: report/test/renderer/util-test.js [hunk 1]
```diff
@@ -37,8 +37,10 @@ describe('util helpers', () => {
     /* eslint-disable max-len */
     assert.equal(get({formFactor: 'mobile', screenEmulation: {disabled: false, mobile: true}}), 'Emulated Moto G4');
     assert.equal(get({formFactor: 'mobile', screenEmulation: {disabled: true, mobile: true}}), 'No emulation');
+    assert.equal(get({formFactor: 'mobile', screenEmulation: {disabled: true, mobile: true}, channel: 'devtools'}), 'Emulated Moto G4');
     assert.equal(get({formFactor: 'desktop', screenEmulation: {disabled: false, mobile: false}}), 'Emulated Desktop');
     assert.equal(get({formFactor: 'desktop', screenEmulation: {disabled: true, mobile: false}}), 'No emulation');
+    assert.equal(get({formFactor: 'mobile', screenEmulation: {disabled: true, mobile: false}, channel: 'devtools'}), 'Emulated Desktop');
```
Comment (adamraine) [inline report/test/renderer/util-test.js:43]: I thought this would defer to `formFactor`. This situation with `screenEmulation: {disabled: true, mobile: true}` would never happen in devtools:

https://github.com/GoogleChrome/lighthouse/blob/3055496570b7f18378718b2ddcaaa62edde563d7/clients/devtools/devtools-entry.js#L43

Comment (connorjclark) [reply report/test/renderer/util-test.js:43]: That's being set on a config extending the default. It gets fully resolved by the time LH runs.

Comment (adamraine) [reply report/test/renderer/util-test.js:43]: Sorry I meant `screenEmulation: {disabled: true, mobile: false}` could never happen. If the config extends the default then `mobile` will always be true.

When I look at a desktop report from DT, `mobile` is still set to `true`.

`devtools-entry.js` does change the `formFactor` property.

Comment (connorjclark) [reply report/test/renderer/util-test.js:43]: ah, good catch

**Review by adamraine — APPROVED** [review]
