### PR TITLE
Fixes #808

### LINKED ISSUE #808: DBW: broken due to https://github.com/GoogleChrome/lighthouse/commit/80ca262ac2626d6944bd9811b62ebce1a3f86d7f changes

### PR DESCRIPTION
**Pull request by ebidel**
R: @paulirish @samccone @pavelfeldman

### CODE REVIEW

File: lighthouse-core/gather/drivers/driver.js [hunk 1]
```diff
@@ -539,7 +539,7 @@ class Driver {
     const globalVarToPopulate = `window['__${funcName}StackTraces']`;
     const collectUsage = () => {
       return this.evaluateAsync(
-          `__returnResults(Array.from(${globalVarToPopulate}).map(item => JSON.parse(item)))`);
+          `Promise.resolve(Array.from(${globalVarToPopulate}).map(item => JSON.parse(item)))`);
```
Comment (pavelfeldman) [inline lighthouse-core/gather/drivers/driver.js]: LGTM, thanks.

**Comment by brendankenny** [comment]
We should consider adding the DBW audits to the smoke tests so this kind of thing would be caught
