### PR TITLE
Extension: add report error button

### LINKED ISSUE #919: Report bug from extension popup
In cases where we error and immediately quit, we show the exception message, but users don't know how to report this bug

image

Let's add a "file bug" link after the exception message?

### PR DESCRIPTION
**Pull request by olingern**
fixes #919

### CODE REVIEW

**Comment by brendankenny** [comment]
Thanks for the PR!

I'll take a closer look at it shortly, but just as a quick drive by comment on the screenshot in #919, we'll definitely want the plugin and Chrome versions included in the bug report body.

Looks like you may have to [parse the UA string](http://stackoverflow.com/a/19295499) to get the Chrome version (unless there's an extension API I'm missing), and you may need to pipe in the extension version through the background page.

File: lighthouse-extension/app/src/popup.js [hunk 1]
```diff
@@ -141,7 +141,20 @@ document.addEventListener('DOMContentLoaded', _ => {
           ' Close the other tabs to use lighthouse.';
       }
 
+      const reportErrorEl = document.createElement('a');
+      reportErrorEl.className = 'button button--report-error';
+
+      const base = 'https://github.com/googlechrome/lighthouse/issues/new?';
+      const title = 'title=Lighthouse%20Extension%20Error';
+      const body = '&body=Error:%20' + message;
```
Comment (brendankenny) [inline lighthouse-extension/app/src/popup.js]: the two cases handled by `if` statements above (devtools open and multiple tabs) should not trigger the report error button, since they're local things the user needs to fix

File: lighthouse-extension/app/src/popup.js [hunk 2]
```diff
@@ -141,7 +141,20 @@ document.addEventListener('DOMContentLoaded', _ => {
...
+
+      reportErrorEl.href = base + title + body;
+      reportErrorEl.text = 'Report Error';
```
Comment (ebidel) [inline lighthouse-extension/app/src/popup.js]: .text -> .textContent incase we use something other than HTMLAnchorElement in the future.

File: lighthouse-extension/app/src/popup.js (hunk 1 above)
Comment (olingern) [inline lighthouse-extension/app/src/popup.js]: Good catch, thank ya!

**Comment by olingern** [comment]
@ebidel @brendankenny 
Thanks for the comments! I think everything should be there now. You can see how this looks below.
- [x]  Plugin version ( found [here](https://developer.chrome.com/extensions/runtime#method-getManifest) )
- [x]  Chrome version (thanks @brendankenny !)
- [x]  Update link text property to be textContent

screen shot 2016-11-16 at 12 53 13 am

Also, I poked around and seem to have found the version in here, in [chrome.runtime]():
`chrome.runtime.getManifest().version`

File: lighthouse-extension/app/src/popup.js [hunk 3]
```diff
@@ -37,6 +37,32 @@ document.addEventListener('DOMContentLoaded', _ => {
   const optionsList = document.body.querySelector('.options__list');
   const okButton = document.getElementById('ok');
 
+  function getLightHouseVersion() {
```
Comment (brendankenny) [inline lighthouse-extension/app/src/popup.js]: nit: we aren't always consistent with this, but lighthouse is one word, so should be `getLighthouseVersion()`

File: lighthouse-extension/app/src/popup.js [hunk 4]
```diff
@@ -37,6 +37,32 @@ document.addEventListener('DOMContentLoaded', _ => {
...
+    return chrome.runtime.getManifest().version;
```
Comment (brendankenny) [inline lighthouse-extension/app/src/popup.js]: nice find!

File: lighthouse-extension/app/src/popup.js [hunk 5]
```diff
@@ -37,6 +37,32 @@ document.addEventListener('DOMContentLoaded', _ => {
...
+  }
+
+  function getChromeVersion() {
+    return /Chrome\/([0-9.]+)/.exec(navigator.userAgent)[1];
+  }
+
+  function buildReportErrorLink(err) {
+    const reportErrorEl = document.createElement('a');
+    reportErrorEl.className = 'button button--report-error';
```
Comment (brendankenny) [inline lighthouse-extension/app/src/popup.js]: I have @robdodson in my head saying "just use a button" here. Should this be just a button? Alternatively we could make the link more link-like.

I don't want to bikeshed here too much, we can always change it up later if we don't get it exactly right at first. @ebidel for a quick opinion.

File: lighthouse-extension/app/src/popup.js [hunk 6]
```diff
@@ -37,6 +37,32 @@ document.addEventListener('DOMContentLoaded', _ => {
...
+
+    let qsBody = '**Lighthouse Version**: ' + getLightHouseVersion() + '\n';
+    qsBody += '**Chrome Version**: ' + getChromeVersion() + '\n';
+    qsBody += '**Stack Trace**:\n' + err.stack;
```
Comment (brendankenny) [inline lighthouse-extension/app/src/popup.js]: nit: possible to surround the stack with ```` ``` ````s to turn it into a code block?

Comment (olingern) [inline lighthouse-extension/app/src/popup.js]: Good call and done. After placing it in a code block, I noticed the original error wasn't in the stack trace, so I also added that.

File: lighthouse-extension/app/src/popup.js (hunk 5 above)
Comment (olingern) [inline lighthouse-extension/app/src/popup.js]: A button would be consistent with the existing HTML buttons, but would have a few small hoops to jump through, i.e. storing the link on a `data-issue-link` attribute and binding an onclick function to the button. Nothing too crazy, but a link was easiest 😄

**Comment by ebidel** [comment]
Think a link is fine because it's action is a URL taking you to a webpage.

File: lighthouse-extension/app/src/popup.js [hunk 7]
```diff
@@ -51,7 +51,8 @@ document.addEventListener('DOMContentLoaded', _ => {
 
     let qsBody = '**Lighthouse Version**: ' + getLightHouseVersion() + '\n';
     qsBody += '**Chrome Version**: ' + getChromeVersion() + '\n';
-    qsBody += '**Stack Trace**:\n' + err.stack;
+    qsBody += '**Error Message**: ' + err.message + '\n';
+    qsBody += '**Stack Trace**:\n ```' + err.stack + '```';
```
Comment (ebidel) [inline lighthouse-extension/app/src/popup.js]: The URL the user was running LH against would also be helpful to add to the bug report.

Comment (olingern) [inline lighthouse-extension/app/src/popup.js]: I thought about that, but is thought it could be considered invasive. Thoughts?

File: lighthouse-extension/app/src/popup.js (hunk 5 above)
Comment (robdodson) [inline lighthouse-extension/app/src/popup.js]: in general buttons are for actions and links are for navigation. Not sure what the intent of this control is but happy to take a look in-person if that's any help

File: lighthouse-extension/app/src/popup.js (hunk 7 above)
Comment (brendankenny) [inline lighthouse-extension/app/src/popup.js]: yeah, it could be invasive. Most of the extension issues we've seen with an actual caught error (as opposed to something more subtle, like -1 in FMP) have been tracked down without the URL. We can add the optional prompt for it later if we find ourselves asking for it more often than not

File: lighthouse-extension/app/src/popup.js (hunk 5 above)
Comment (brendankenny) [inline lighthouse-extension/app/src/popup.js]: yeah, my point was more styling. It's a link acting like a link, but somewhat styled like a button :)

However, it works and we've talked about reworking the popup as it keeps getting more crowded anyways, so we can address this at that point if need be. I'd like to get this landed now to help users out.

**Comment by paulirish** [comment]
just came across this. Awesome work here @olingern!

**Comment by olingern** [comment]
Thanks, @paulirish. You guys have an awesome initiative and it's a fun project to contribute to!
