### PR TITLE
core(user-timings): add back startTime

### LINKED ISSUE #5418: lighthouse 3 regression in user-timings details
## Bug report

Lighthouse v3 does not provide `startTime` value for user timing measures. This info is the part of `extendedInfo` but it was removed.

#### Provide the steps to reproduce
1. `lighthouse https://treo.sh`
2. Check JSON report:

```json
  "user-timings": {
      "id": "user-timings",
      "title": "User Timing marks and measures",
      "description": "Consider instrumenting your app with the User Timing API to create custom, real-world measurements of key user experiences. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/user-timing).",
      "score": null,
      "scoreDisplayMode": "informative",
      "rawValue": false,
      "displayValue": "2",
      "details": {
        "type": "table",
        "headings": [{
          "key": "name",
          "itemType": "text",
          "text": "Name"
        }, {
          "key": "timingType",
          "itemType": "text",
          "text": "Type"
        }, {
          "key": "time",
          "itemType": "ms",
          "granularity": 0.01,
          "text": "Time"
        }],
        "items": [{
          "name": "home did mount",
          "timingType": "Measure",
          "time": 49
        }, {
          "name": "boot",
          "timingType": "Mark",
          "time": 716.685
        }]
      }
    }
```

#### What is the current behavior?

The report contains only `time` value.

#### What is the expected behavior?

The report should contain `startTime` value for measures.

#### Environment Information
* Affected Channels: All (report)
* Lighthouse version: 3.0.0-beta.0

**Related issues**

#5402

### PR DESCRIPTION
**Pull request by patrickhulce**
**Related Issues/PRs**
closes #5418

### CODE REVIEW

File: lighthouse-core/audits/user-timings.js [hunk 1]
```diff
@@ -118,6 +118,7 @@ class UserTimings extends Audit {
         const time = item.isMark ? item.startTime : item.duration;
         return {
           name: item.name,
+          startTime: item.startTime,
```
Comment (paulirish) [inline lighthouse-core/audits/user-timings.js]: can you assert this in user-timing-test?

File: lighthouse-core/audits/user-timings.js [hunk 2]
```diff
@@ -118,6 +118,7 @@ class UserTimings extends Audit {
...
           timingType: item.isMark ? 'Mark' : 'Measure',
           time,
```
Comment (paulirish) [inline lighthouse-core/audits/user-timings.js]: just noticed.. this name seems pretty weak. duration? timeInMs?

File: lighthouse-core/audits/user-timings.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-core/audits/user-timings.js]: done

File: lighthouse-core/audits/user-timings.js (hunk 2 above)
Comment (patrickhulce) [reply lighthouse-core/audits/user-timings.js]: well that name is weak because it's either or and just for display, I added duration separately, but programmatic folks should probably just ignore `time`

maybe update to `timeToDisplay`?

Comment (paulirish) [reply lighthouse-core/audits/user-timings.js]: it's always been a bit odd that we share a column for two diff types of values

how about we add a second column, then we can be really clear with `Start time` and `Duration`. wdyt?

**Comment by patrickhulce** [comment]
> add additional column? does it mess too much with our types to have undefined/null durations?

done
