### PR TITLE
launch-chrome: inform user about Chrome launch. refactor & cleanup.

### LINKED ISSUE #625: Lighthouse stuck using Chrome from incorrect location
I'm running lighthouse in Node 6.0 and 6.5. When I try to run 

`npm explore -g lighthouse -- npm run chrome`

I get the following error:

```
Using Chrome Canary from path /Users/caraya/.Trash/Google Chrome Canary.app
You must install Google Chrome Canary to use lighthouse
You can download it from https://www.google.com/chrome/browser/canary.html
```

I've tried multiple solutions:

Remove the Trash folder
Uninstall and reinstall Chrome

Neither of them fix the problem. 

Is there any way to reset the location of Chrome for Lighthouse?

### PR DESCRIPTION
**Pull request by paulirish**
image

fixes #625, #626

### CODE REVIEW

File: lighthouse-core/scripts/launch-chrome.sh [hunk 1]
```diff
@@ -1,25 +1,44 @@
...
+#     npm run chrome
+# or
+#     npm explore -g lighthouse -- npm run chrome
+
+# You can also add custom cmd line flags for Chrome:
+#     npm run chrome -- --show-paint-rects
+
 CHROME_ARGS=$@
 
+URL_TO_LOAD="about:blank"
```
Comment (brendankenny) [inline lighthouse-core/scripts/launch-chrome.sh]: maybe `INITIAL_URL` or something like that so it doesn't look like something you need to update to run lighthouse?

**Comment by brendankenny** [comment]
LGTM if smoketests are cool with it

File: lighthouse-core/scripts/launch-chrome.sh (hunk 1 above)
Comment (paulirish) [inline lighthouse-core/scripts/launch-chrome.sh]: done
