### PR TITLE
v6.3.0

### LINKED ISSUE #11231: error running release/test.sh–Cannot find module 'lodash.clonedeep'
```
+ npm install /Users/cjamcl/src/lighthouse/lighthouse-core/scripts/release/../../../../lighthouse-pristine/lighthouse-6.1.0.tgz
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN lighthouse-local-test@1.0.0 No description
npm WARN lighthouse-local-test@1.0.0 No repository field.

+ lighthouse@6.1.0
added 266 packages from 207 contributors in 8.562s
found 0 vulnerabilities

+ npm explore lighthouse -- npm run smoke -- --retries=3

> lighthouse@6.1.0 smoke /private/tmp/lighthouse-local-test/node_modules/lighthouse
> node lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js "--retries=3"

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'lodash.clonedeep'
Require stack:
- /private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/report-assert.js
- /private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/smokehouse.js
- /private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/report-assert.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/report-assert.js',
    '/private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/smokehouse.js',
    '/private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lighthouse@6.1.0 smoke: `node lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js "--retries=3"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lighthouse@6.1.0 smoke script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cjamcl/.npm/_logs/2020-08-06T19_53_07_244Z-debug.log
npm ERR! weird error 1
```

lol `weird error`

### PR DESCRIPTION
**Pull request by connorjclark**
Also fixes #11231

### CODE REVIEW

File: lighthouse-core/scripts/roll-to-devtools.sh [hunk 1]
```diff
@@ -6,25 +6,23 @@
 # Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 ##
 
-# You will need a Chromium checkout: https://chromium.googlesource.com/devtools/devtools-frontend/+/HEAD/docs/workflows.md#integrated-checkout
-# You could use the standalone DevTools workflow, but you won't be able to run layout tests, so
-# if you are the release manager you'll need the full Chromium checkout.
+# You will need a DevTools Frontend checkout
```
Comment (connorjclark) [inline lighthouse-core/scripts/roll-to-devtools.sh:9]: bye-bye full checkout!

File: third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt [hunk 2]
```diff
@@ -2,11 +2,11 @@ Tests that exporting works.
 
 ++++++++ testExportHtml
 
-# of .lh-audit divs (original): 136
+# of .lh-audit divs (original): 135
```
Comment (connorjclark) [inline third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt:5]: @patrickhulce idk how this was missed from #11328 ...

Comment (patrickhulce) [reply third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt:5]: hm that's weird that PR passed and the last two master ones have passed https://github.com/GoogleChrome/lighthouse/runs/1033591612

I would've expected this change to fail...

does this get run with just `yarn build-devtools && yarn test-devtools` locally?

File: changelog.md [hunk 3]
```diff
@@ -1,3 +1,85 @@
...
+* Pete Nykänen @petetnt
+* Radu Micu @radum
+* ryo @ryoAccount
+* Saavan Nanavati @saavannanavati
+* Stanislav Popov @popstas
+* Wicked @Wicked7000
+
+## Notable Changes
+
+* revert: move unsized-images to experimental due to perf impact ([#11317](https://github.com/GoogleChrome/lighthouse/pull/11317))
```
Comment (patrickhulce) [inline changelog.md:24]: I'm not sure this should be in notable since it wasn't shipped in 6.2.0 to begin with, maybe hide in core?

File: changelog.md [hunk 4]
```diff
@@ -1,3 +1,85 @@
...
+* readme: add related projects: site-audit-seo ([#11305](https://github.com/GoogleChrome/lighthouse/pull/11305), [#11250](https://github.com/GoogleChrome/lighthouse/pull/11250))
+* readme: align headings with table of contents ([#11288](https://github.com/GoogleChrome/lighthouse/pull/11288))
+
+## Tests
+
+* run chromium webtests for devtools integration ([#11176](https://github.com/GoogleChrome/lighthouse/pull/11176), [#11328](https://github.com/GoogleChrome/lighthouse/pull/11328))
+
+## Misc
+
+* benchmark: update BenchmarkIndex for m86 changes ([#11304](https://github.com/GoogleChrome/lighthouse/pull/11304), [#11247](https://github.com/GoogleChrome/lighthouse/pull/11247))
```
Comment (patrickhulce) [inline changelog.md:76]: honestly this might be a notable change 😆 the scale is different now for anyone that was paying attention to it

**Comment by patrickhulce** [comment]
heh, need to update the devtools fixtures for 6.3.0 😎

File: changelog.md (hunk 3 above)
Comment (connorjclark) [reply changelog.md:24]: Yes it was?

File: third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt (hunk 2 above)
Comment (connorjclark) [reply third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt:5]: yea (and `yarn update:test-devtools` to rebaseline)

Comment (connorjclark) [reply third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt:5]: image
 hm.... (the one you linked)

Comment (connorjclark) [reply third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt:5]: `run_web_tests.py` didnt exit 1 ...

File: changelog.md (hunk 3 above)
Comment (patrickhulce) [reply changelog.md:24]: wait so we had already shipped that regression to LR weeks ago? I completely misunderstood that situation then 😅 

nevermind carry on 👍

File: third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt (hunk 2 above)
Comment (connorjclark) [reply third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt:5]: image

https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/test/webtests/TestExpectations

I'll look into re-enabling it.
