### PR TITLE
tests(dom): fix node 16 createObjectURL bug

### LINKED ISSUE #12934: flaky test `safelySetBlobHref`
```
FAIL report/test/renderer/dom-test.js
  ● DOM › safelySetBlobHref › sets href for safe blob types

    TypeError: The "obj" argument must be an instance of Blob. Received an instance of Blob

      178 |       throw new Error('Unsupported blob type');
      179 |     }
    > 180 |     const href = URL.createObjectURL(blob);
          |                      ^
      181 |     elem.href = href;
      182 |   }
      183 |

      at DOM.safelySetBlobHref (report/renderer/dom.js:180:22)
      at report/test/renderer/dom-test.js:213:13
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (report/test/renderer/dom-test.js:211:9)
```

https://github.com/GoogleChrome/lighthouse/pull/12930/checks?check_run_id=3364452167#step:12:338

Saw this in two different PRs, both for node 16

### PR DESCRIPTION
**Pull request by connorjclark**
fixes #12934

### CODE REVIEW

File: report/test/renderer/dom-test.js [hunk 1]
```diff
@@ -19,23 +19,22 @@ describe('DOM', () => {
...
   beforeAll(() => {
     Util.i18n = new I18n('en', {...Util.UIStrings});
     window = new jsdom.JSDOM().window;
 
-    // Make a lame "polyfill" since JSDOM doesn't have createObjectURL: https://github.com/jsdom/jsdom/issues/1721
-    const lameCOURL = jest.fn(_ => `https://fake-origin/blahblah-blobid`);
-    if (!URL.createObjectURL) {
-      URL.createObjectURL = lameCOURL;
-    }
+    nativeCreateObjectURL = URL.createObjectURL;
```
Comment (brendankenny) [inline report/test/renderer/dom-test.js:28]: add a comment that we're shimming because the Node version of `URL.createObjectURL` isn't compatible with the jsdom blob type, at least at this time?

**Review by brendankenny — APPROVED** [review]
nice 🕵️ !

**Review by patrickhulce — APPROVED** [review]
nice! thanks @connorjclark :)
