### PR TITLE
core(driver): use execution context isolation when necessary

### LINKED ISSUE #2505: Audit error: Required Accessibility gatherer encountered an error when using almond.js
We are using https://github.com/requirejs/almond in our builds instead of the whole requirejs package and this seems to break lighthouse accessibility tests. I've tried it both via the node package and via the Audit tab in Chrome Developer Tools.

    lighthouse https://bibliotek.jonkoping.se/

The result is a 0 score for accessibility and all tests have failed with the below message:

    Audit error: Required Accessibility gatherer encountered an error: See almond README: incorrect module build, no module name

Almond has 30 000 downloads the last week on npm and is used in lots of places around the web so a solution or at least a workaround that we can use would be great!

### LINKED ISSUE #2511: Move `evaluateAsync` calls to content scripts
A new protocol method `createIsolatedWorld` [landed in 59](https://chromium.googlesource.com/chromium/src/+blame/6ebcb95f8c4fadb29b69d2fbcbf8c964974e76aa/third_party/WebKit/Source/core/inspector/browser_protocol.json#535) that creates an execution sandbox that we can use to isolate ourselves from the page mucking with natives.

This should allow us to remove the `cacheNatives` method in driver and prevent miscellaneous bugs from strange interactions with the page.

### PR DESCRIPTION
**Pull request by patrickhulce**
closes #2511 
fixes #2505

### CODE REVIEW

File: lighthouse-core/gather/driver.js [hunk 1]
```diff
@@ -247,7 +250,13 @@ class Driver {
         includeCommandLineAPI: true,
         awaitPromise: true,
         returnByValue: true,
-      }).then(result => {
+      };
+
+      if (useIsolation && typeof this._isolatedExecutionContextId === 'number') {
```
Comment (paulirish) [inline lighthouse-core/gather/driver.js]: if isolation is requested but there is no contextId... should we throw?

File: lighthouse-cli/test/smokehouse/run-all-tests.sh [hunk 2]
```diff
@@ -0,0 +1,12 @@
+#!/usr/bin/env bash
+
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+for d in "$DIR"/*/ ; do
+  bash "${d}run-tests.sh"
```
Comment (paulirish) [inline lighthouse-cli/test/smokehouse/run-all-tests.sh]: there are a few other ways to do this, but the benefit of this approach is the failures won't be silent. :)

sgtm

File: lighthouse-core/gather/driver.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: I had this originally to check for leaks and it seemed ok, but it's definitely possible and seemed bad to tank the run because it since it won't matter most of the time

perhaps something to add to sentry though when it lands?

File: lighthouse-cli/test/smokehouse/run-all-tests.sh (hunk 2 above)
Comment (brendankenny) [reply lighthouse-cli/test/smokehouse/run-all-tests.sh]: can we just manually list the files in here? If I'm messing with some smoke tests it's a lot easier to comment out lines in one place by name than look up where the individual run-tests file is

also it'd probably be better to just get rid of all the `run-tests.sh` files since they're all exactly the same except for the expectations and config filename strings :)

File: lighthouse-core/gather/driver.js [hunk 3]
```diff
@@ -219,17 +220,19 @@ class Driver {
    * Evaluate an expression in the context of the current page.
    * Returns a promise that resolves on the expression's value.
    * @param {string} expression
+   * @param {{useIsolation: boolean}=} options
    * @return {!Promise<*>}
    */
-  evaluateAsync(expression) {
+  evaluateAsync(expression, options) {
+    const {useIsolation = true} = options || {};
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: the double defaults here is kind of confusing. Maybe move the `{}` default for `options` to the params?

File: lighthouse-core/gather/driver.js (hunk 1 above)
Comment (brendankenny) [reply lighthouse-core/gather/driver.js]: Seems like we should be able to figure out definitively if it's possible to reach here without having created a new context? Then future violations of this can complain loudly by throwing (alternatively, see other comment about lazily calling `_createIsolatedWorld()`)

File: lighthouse-core/gather/driver.js [hunk 4]
```diff
@@ -633,6 +661,7 @@ class Driver {
       })
       .then(_ => waitForLoad && this._waitForFullyLoaded(pauseAfterLoadMs,
           networkQuietThresholdMs, cpuQuietThresholdMs, maxWaitMs))
+      .then(_ => this._createIsolatedWorld())
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: Would there be downsides to clearing on all navigations (as above) but calling `_createIsolatedWorld` lazily on next `evaluateAsync()` when `_isolatedExecutionContextId` isn't defined?

File: lighthouse-core/gather/driver.js (hunk 1 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: going the lazy route 👍

File: lighthouse-core/gather/driver.js (hunk 3 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: done

File: lighthouse-core/gather/driver.js (hunk 4 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: done

File: lighthouse-cli/test/smokehouse/run-all-tests.sh (hunk 2 above)
Comment (patrickhulce) [reply lighthouse-cli/test/smokehouse/run-all-tests.sh]: will nuke 'em all in a follow up PR and improve this file here 👍

**Comment by patrickhulce** [comment]
> Is there anything we can do for these non-isolated ones (js-libraries, function callsites, and check for quiet) to make them isolated? I guess it's just unclear what's isolated and what's not if the axe checks work but js-library-detector does not

discussed offline, decided to switch the default to useIsolation=false and just opt-in a11y for now

**Comment by patrickhulce** [comment]
PTAL :)

File: lighthouse-cli/test/fixtures/a11y/a11y_tester.html [hunk 5]
```diff
@@ -197,5 +197,13 @@
     <section>
       <video id="video-description"></video>
     </section>
+    <script>
+      // axe fails if `define` is present but misbehaves, create a bogus implementation to exercise our
```
Comment (paulirish) [inline lighthouse-cli/test/fixtures/a11y/a11y_tester.html]: I don't totally get this. I'll ask you in person if i'm interpreting it correctly, but it could probably use a slightly more extended comment. :)

File: lighthouse-cli/test/smokehouse/a11y/a11y-config.js [hunk 6]
```diff
@@ -0,0 +1,18 @@
...
+
+/**
+ * Config file for running PWA smokehouse audits for axe.
+ */
+module.exports = {
+  extends: 'lighthouse:default',
+  settings: {
+    onlyCategories: [
+      'accessibility',
+    ],
```
Comment (paulirish) [inline lighthouse-cli/test/smokehouse/a11y/a11y-config.js]: since we were talking about it yesterday... is it possible to reuse an existing smoketest?

File: lighthouse-core/gather/driver.js [hunk 7]
```diff
@@ -216,20 +217,37 @@ class Driver {
...
+   * will be evaluated in a content script that has access to the page's DOM but whose JavaScript state
+   * is completely separate.
    * Returns a promise that resolves on the expression's value.
    * @param {string} expression
+   * @param {{useIsolation: boolean}=} options
    * @return {!Promise<*>}
    */
-  evaluateAsync(expression) {
+  evaluateAsync(expression, options = {}) {
+    const contextIdPromise = options.useIsolation ?
```
Comment (paulirish) [inline lighthouse-core/gather/driver.js]: what about 

```js
    const fn = options.useIsolation ? this._getOrCreateIsolatedContextId : Promise.resolve;
    return fn().then(contextId => this._evaluateInContext(expression, contextId));
```

not a huge deal . w/e

File: lighthouse-core/gather/driver.js [hunk 8]
```diff
@@ -596,6 +619,26 @@ class Driver {
   }
 
   /**
+   * @return {!Promise<number>}
+   */
+  _getOrCreateIsolatedContextId() {
```
Comment (paulirish) [inline lighthouse-core/gather/driver.js]: `_acquireIsolatedContextId()`  ?

File: lighthouse-core/gather/driver.js [hunk 9]
```diff
@@ -596,6 +619,26 @@ class Driver {
...
+    if (typeof this._isolatedExecutionContextId === 'number') {
+      return Promise.resolve(this._isolatedExecutionContextId);
+    }
+
+    return this.sendCommand('Page.getResourceTree')
+      .then(data => {
+        const frameId = data.frameTree.frame.id;
+        return this.sendCommand('Page.createIsolatedWorld', {frameId});
```
Comment (paulirish) [inline lighthouse-core/gather/driver.js]: let's give it a `worldName` while we're at it.

File: lighthouse-core/gather/driver.js [hunk 10]
```diff
@@ -596,6 +619,26 @@ class Driver {
...
+   * @return {!Promise<number>}
+   */
+  _getOrCreateIsolatedContextId() {
+    if (typeof this._isolatedExecutionContextId === 'number') {
+      return Promise.resolve(this._isolatedExecutionContextId);
+    }
+
+    return this.sendCommand('Page.getResourceTree')
+      .then(data => {
+        const frameId = data.frameTree.frame.id;
```
Comment (paulirish) [inline lighthouse-core/gather/driver.js]: frameId => mainFrameId

File: lighthouse-core/gather/driver.js (hunk 7 above)
Comment (paulirish) [reply lighthouse-core/gather/driver.js]: nevermind this one. bad idea.

File: lighthouse-core/gather/driver.js [hunk 11]
```diff
@@ -216,20 +217,37 @@ class Driver {
   }
 
   /**
-   * Evaluate an expression in the context of the current page.
+   * Evaluate an expression in the context of the current page. If useIsolation is true, the expression
+   * will be evaluated in a content script that has access to the page's DOM but whose JavaScript state
+   * is completely separate.
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: 👍 👍

File: lighthouse-core/gather/driver.js [hunk 12]
```diff
@@ -216,20 +217,37 @@ class Driver {
...
+        this._getOrCreateIsolatedContextId() :
+        Promise.resolve(undefined);
+    return contextIdPromise.then(contextId => this._evaluateInContext(expression, contextId));
+  }
+
+  /**
+   * Evaluate an expression in the given execution context; an undefined contextId implies the main
+   * page without isolation.
+   * @param {string} expression
+   * @param {number|undefined} contextId
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: can be `{number=}` FWIW

File: lighthouse-cli/test/smokehouse/a11y/a11y-config.js (hunk 6 above)
Comment (patrickhulce) [reply lighthouse-cli/test/smokehouse/a11y/a11y-config.js]: I know we were literally just talking about not adding more yesterday but of all the testers that should probably get their own one, I think a11y is one of them 😆  

maybe we can start by reducing DBW's 6 passes instead? :)

File: lighthouse-core/gather/driver.js (hunk 8 above)
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: maybe a jsdoc comment here that the contextId won't persist past a page load (so should be cleared and recreated)?

File: lighthouse-cli/test/fixtures/a11y/a11y_tester.html (hunk 5 above)
Comment (patrickhulce) [reply lighthouse-cli/test/fixtures/a11y/a11y_tester.html]:
```
// axe fails if a different UMD loader like almond.js is used on the page, see https://github.com/GoogleChrome/lighthouse/issues/2505
// We can simulate this behavior by defining a similarly misbehaving `define` function.
```

sounds better?

File: lighthouse-core/gather/driver.js (hunk 8 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: discussed offline, Paul's a huge fan of `getOrCreate` now 🚗  🎏  🎉

File: lighthouse-core/gather/driver.js (hunk 10 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: done

File: lighthouse-core/gather/driver.js (hunk 9 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: done

File: lighthouse-core/gather/driver.js (hunk 12 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: yeah just seemed more explicit since something is always passed in but doesn't matter to me

File: lighthouse-core/gather/driver.js (hunk 8 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: good call, done

File: lighthouse-cli/test/fixtures/a11y/a11y_tester.html (hunk 5 above)
Comment (paulirish) [reply lighthouse-cli/test/fixtures/a11y/a11y_tester.html]: YESSS so good

File: lighthouse-core/gather/driver.js (hunk 8 above)
Comment (paulirish) [reply lighthouse-core/gather/driver.js]: lol
