### PR TITLE
core(global-listeners): iterate all execution contexts

### LINKED ISSUE #14980: Extension unload listeners can fail the bfcache audit but be otherwise undetectable
From an issue @rviscomi ran into:

An extension can inject an unload listener into the main frame and the bfcache audit will fail on this reason, but the `no-unload-listeners` audit will pass, and a user looking in the DevTools Elements panel or running `getEventListeners(window)` in the console will similarly find no `'unload'` listeners. This ends up very challenging to debug.

To repro:
- `yarn chrome --port=9222 --enable-extensions`
- install the LastPass extension (`https://chrome.google.com/webstore/detail/hdokiejnpimakedhajhdlcegeplioahd`), ignore the log-in screen
- either
  - visit `https://example.com` and run Lighthouse in DevTools
  - run `node cli/index.js https://example.com --port 9222 --view` on the command line

Failing bfcache audit in Lighthouse due to 'an unload handler in the main frame'

Passing 'no unload event listeners' audit in Lighthouse, with no unload listeners listed

---

This is due to the `'unload'` listener being added inside a content script injected on `document_start`, which runs in an isolated execution context. Unless `no-unload-listeners` starts running `DOMDebugger.getEventListeners` on a `window` reference from the isolated context, those listeners are invisible to the user (similar to how users need to know to pick the other execution context in the DevTools console dropdown for `getEventListeners(window)` to show the injected script's `unload` listeners).

Lighthouse could
- cycle through execution contexts for the queries for this kind of audit (probably good in general)
- add a top-level extension warning to the report if there were any content scripts from extensions (possibly similar to #14651)

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #14980

image

### CODE REVIEW

File: core/legacy/gather/driver.js [hunk 1]
```diff
@@ -101,6 +101,20 @@ class Driver {
       rootSession: () => {
         return this.defaultSession;
       },
+      // For legacy driver, only bother supporting access to the default execution context.
```
Comment (connorjclark) [inline core/legacy/gather/driver.js:104]: This seems like a reasonable time to stop trying for parity wrt legacy driver. So...just giving the default EC here.

File: types/gatherer.d.ts [hunk 2]
```diff
@@ -47,6 +47,8 @@ declare module Gatherer {
     url: () => Promise<string>;
     targetManager: {
       rootSession(): FRProtocolSession;
+      executionContexts(): Array<Crdp.Runtime.ExecutionContextDescription>;
+      mainFrameExecutionContexts(): Array<Crdp.Runtime.ExecutionContextDescription>;
```
Comment (connorjclark) [inline types/gatherer.d.ts:51]: Although we only want to process main frames in global listeners, I don't want that to happen via a method called just `executionContexts` because that locks in the contract that this is only main frames (which could mess with potential plugins). Having the gatherer provide the main frame id is not possible for snapshots, so this logic is kept in target manager. Hence, an explicit `mainFrameExecutionContexts`... and adding `executionContexts` just-cuz.

File: core/gather/driver/target-manager.js [hunk 3]
```diff
@@ -185,8 +235,12 @@ class TargetManager extends ProtocolEventEmitter {
     this._targetIdToTargets = new Map();
 
     this._rootCdpSession.on('Page.frameNavigated', this._onFrameNavigated);
+    this._rootCdpSession.on('Runtime.executionContextCreated', this._onExecutionContextCreated);
+    this._rootCdpSession.on('Runtime.executionContextDestroyed', this._onExecutionContextDestroyed);
+    this._rootCdpSession.on('Runtime.executionContextsCleared', this._onExecutionContextsCleared);
 
     await this._rootCdpSession.send('Page.enable');
+    await this._rootCdpSession.send('Runtime.enable');
```
Comment (adamraine) [inline core/gather/driver/target-manager.js:243]: Will this flush `Runtime.executionContextCreated` events for execution contexts on the page when the run started?

Comment (connorjclark) [reply core/gather/driver/target-manager.js:243]: looking around the [code](https://source.chromium.org/chromium/chromium/src/+/main:v8/src/inspector/v8-inspector-impl.cc;bpv=1;bpt=1?q=executionContextCreated%20f:cc%20-f:out&ss=chromium) ... i don't think so.

Comment (brendankenny) [reply core/gather/driver/target-manager.js:243]: DevTools populates the execution context dropdown though, so it must be possible somehow

Comment (adamraine) [reply core/gather/driver/target-manager.js:243]: That might be a problem for timespan/snapshot mode. Is there some other way to see contexts created before the run?

File: core/gather/driver/target-manager.js [hunk 4]
```diff
@@ -153,6 +171,38 @@ class TargetManager extends ProtocolEventEmitter {
...
+  _onExecutionContextCreated(event) {
+    // This execution context was made via the protocol (e.g. by us or Puppeteer).
+    if (event.context.origin === '://' || event.context.origin === '') return;
+    // Just in case the above changes somehow.
+    if (event.context.name === '__puppeteer_utility_world__') return;
+    if (event.context.name === 'lighthouse_isolated_context') return;
+
+    const index = this._executionContextDescriptions.findIndex(d =>
+      d.uniqueId === event.context.uniqueId);
+    if (index === -1) {
```
Comment (connorjclark) [inline core/gather/driver/target-manager.js:186]: I'm not sure why, but puppeteer is sending a context created event twice for every single one. So I had to do a check on `uniqueId` here.

File: core/gather/driver/target-manager.js [hunk 5]
```diff
@@ -153,6 +171,38 @@ class TargetManager extends ProtocolEventEmitter {
...
+   * @param {LH.Crdp.Runtime.ExecutionContextCreatedEvent} event
+   */
+  _onExecutionContextCreated(event) {
+    // This execution context was made via the protocol (e.g. by us or Puppeteer).
+    if (event.context.origin === '://' || event.context.origin === '') return;
+    // Just in case the above changes somehow.
+    if (event.context.name === '__puppeteer_utility_world__') return;
+    if (event.context.name === 'lighthouse_isolated_context') return;
+
+    const index = this._executionContextDescriptions.findIndex(d =>
```
[the remark this answers is not in the document]
Comment (connorjclark) [reply core/gather/driver/target-manager.js:184]: good call

File: core/gather/driver/target-manager.js [hunk 6]
```diff
@@ -153,6 +171,38 @@ class TargetManager extends ProtocolEventEmitter {
...
 
+  /**
+   * @param {LH.Crdp.Runtime.ExecutionContextCreatedEvent} event
+   */
+  _onExecutionContextCreated(event) {
+    // This execution context was made via the protocol (e.g. by us or Puppeteer).
+    if (event.context.origin === '://' || event.context.origin === '') return;
+    // Just in case the above changes somehow.
+    if (event.context.name === '__puppeteer_utility_world__') return;
+    if (event.context.name === 'lighthouse_isolated_context') return;
```
Comment (brendankenny) [inline core/gather/driver/target-manager.js:182]: Can we drop the general case filtering above if the narrow cases by name here work? For instance, an extension uses the protocol to create an execution context, we'd probably still want to capture unload listeners.

File: core/gather/gatherers/global-listeners.js [hunk 7]
```diff
@@ -61,30 +61,45 @@ class GlobalListeners extends FRGatherer {
...
+          returnByValue: false,
+          uniqueContextId: executionContext.uniqueId,
+        });
+        if (!result.objectId) {
+          throw new Error('Error fetching information about the global object');
+        }
+        objectId = result.objectId;
+      } catch (err) {
+        // Execution context is no longer valid, but don't let that fail the gatherer.
+        console.error(err);
```
Comment (brendankenny) [inline core/gather/gatherers/global-listeners.js:82]: should use logger but if we're going to log (log.warn?), maybe include more detail?

File: core/gather/driver/target-manager.js [hunk 8]
```diff
@@ -40,16 +40,22 @@ class TargetManager extends ProtocolEventEmitter {
...
     this._rootCdpSession = cdpSession;
+    this._mainFrameId = '';
 
     /**
      * A map of target id to target/session information. Used to ensure unique
      * attached targets.
      * @type {Map<string, TargetWithSession>}
      */
     this._targetIdToTargets = new Map();
+    /** @type {Map<LH.Crdp.Runtime.ExecutionContextDescription['uniqueId'], LH.Crdp.Runtime.ExecutionContextDescription>} */
```
Comment (adamraine) [inline core/gather/driver/target-manager.js:51]: nit: does this work?
```suggestion
    /** @type {Map<string, LH.Crdp.Runtime.ExecutionContextDescription>} */
```

File: core/gather/driver/target-manager.js [hunk 9]
```diff
@@ -115,6 +132,7 @@ class TargetManager extends ProtocolEventEmitter {
       const targetId = target.targetInfo.targetId;
       if (this._targetIdToTargets.has(targetId)) return;
 
+      if (isRootSession) this._mainFrameId = targetId;
```
Comment (adamraine) [inline core/gather/driver/target-manager.js:135]: Is `targetId` guaranteed to be the frame id here? I think it would be more correct to get `_mainFrameId` via a call to `Page.getFrameTree` in the enable function.

File: core/gather/driver/target-manager.js [hunk 10]
```diff
@@ -97,10 +103,21 @@ class TargetManager extends ProtocolEventEmitter {
     return this._findSession(rootSessionId);
   }
 
+  executionContexts() {
```
Comment (brendankenny) [inline core/gather/driver/target-manager.js:106]: Explicit `mainFrameExecutionContexts` is a good call, but FWIW I was imagining a completely different interface for general access to all execution contexts (maybe find the target of interest first, then get its execution contexts), so the architecture space seems completely open. Could we drop this for now and then open up discussion when we need it?

**Review by brendankenny — COMMENTED** [review]
exciting!

File: core/gather/driver/target-manager.js (hunk 10 above)
Comment (connorjclark) [reply core/gather/driver/target-manager.js]: Sure.

**Review by adamraine — APPROVED** [review]

File: core/gather/driver/target-manager.js [hunk 11]
```diff
@@ -97,6 +103,12 @@ class TargetManager extends ProtocolEventEmitter {
     return this._findSession(rootSessionId);
   }
 
+  mainFrameExecutionContexts() {
+    return [...this._executionContextIdToDescriptions.values()].filter(executionContext => {
+      return executionContext.auxData.frameId === this._mainFrameId;
```
Comment (brendankenny) [inline core/gather/driver/target-manager.js:108]: do we need this since we only listen on the root session?

Comment (connorjclark) [reply core/gather/driver/target-manager.js:108]: Nope, just adding for later in case that ever changes. Could be easy to overlook.

Comment (connorjclark) [reply core/gather/driver/target-manager.js:108]: er, wait no this is important. It filters out a number of execution contexts for this simple page:

```
Who Framed A11y Tester?!
<iframe src="a11y_tester.html" width="100%" height="100%"></iframe>
```
coming from the iframe. comment out the iframe, and only the first execution context is present

```
{
  id: 7,
  origin: 'http://localhost:10503',
  name: '',
  uniqueId: '5889311435627745206.-699647868331920856',
  auxData: {
    isDefault: true,
    type: 'default',
    frameId: 'E3DEC3BA2977996FAA61E3E4418D4122'
  }
}
{
  id: 9,
  origin: 'http://localhost:10503',
  name: '',
  uniqueId: '-9077244664686306541.-7829375488897728831',
  auxData: {
    isDefault: true,
    type: 'default',
    frameId: '48AA5C7F280A6810D012BAD09CB99732'
  }
}
{
  id: 11,
  origin: 'http://localhost:10503',
  name: '',
  uniqueId: '2049821010959430554.-6542202802565848863',
  auxData: {
    isDefault: true,
    type: 'default',
    frameId: '9548FD706B2909A5E58864CB898DDF7D'
  }
}
{
  id: 13,
  origin: '://',
  name: '',
  uniqueId: '7110504061362463461.-3201941903195113152',
  auxData: {
    isDefault: true,
    type: 'default',
    frameId: 'E1DD688E090D4775B24C805636F001C2'
  }
}
```
