### PR TITLE
Temp disable Shop in smoketests

### LINKED ISSUE #1653: Remove shop from smoketests
Shop has been unreliable the past few weeks and continues to be down. This is causing our smoke tests to consistent fail.

I think we need to remove it until the issues have been ironed out.

cc @tjsavage

### PR DESCRIPTION
**Pull request by ebidel**
R: all

Fixes #1653

I can file a bug to remember to re-enable it.

### CODE REVIEW

File: lighthouse-cli/test/smokehouse/pwa-expectations.js [hunk 1]
```diff
@@ -182,57 +182,57 @@ module.exports = [
     }
   },
```
Comment (brendankenny) [inline lighthouse-cli/test/smokehouse/pwa-expectations.js]: need to remove dangling comma

Comment (ebidel) [inline lighthouse-cli/test/smokehouse/pwa-expectations.js]: done
