### PR TITLE
core(response-time): add time spent to details

### LINKED ISSUE #9671: TTFB Reporting Incorrectly
In this run, the report says TTFB was 0.03s, and that it was too long.  In reality it was too long (~630ms, but certainly not 0.03s)

THE WEIRD RESULT
https://wpt1.speedcurve.com/lighthouse.php?test=190911_C8_a09d5ef039e903e4387bec9754b9c65c&run=1

3 TESTS
https://wpt1.speedcurve.com/result/190911_C8_a09d5ef039e903e4387bec9754b9c65c/

#### Environment Information
* Affected Channels: ?
* Lighthouse version: 5.2.0
* Node.js version: ?
* Operating System: ?

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
Adds a details entry to show how much time was spent fetching the root document.

image

**Related Issues/PRs**
fixes #9671

### CODE REVIEW

File: lighthouse-core/audits/server-response-time.js [hunk 1]
```diff
@@ -22,7 +22,10 @@ const UIStrings = {
 
 const str_ = i18n.createMessageInstanceIdFn(__filename, UIStrings);
 
-const RESPONSE_THRESHOLD = 600;
+// Due to the way that DevTools throttling works we cannot see if server response took less than ~570ms.
+// We set our failure threshold to 600ms to avoid those false positives but we want devs to shoot for 100ms.
```
Comment (Beytoven) [inline lighthouse-core/audits/server-response-time.js:26]: Does this mean that a passing response time will always be between 570 and 600 ms or am I understanding this wrong?

Comment (patrickhulce) [reply lighthouse-core/audits/server-response-time.js:26]: When `throttlingMethod` is `devtools` that's right. The minimum response time we'll observe for all requests is `3.75 * 150 = 562.5ms` so a passing request will be right around there.

Comment (Beytoven) [reply lighthouse-core/audits/server-response-time.js:26]: Gotcha! Thanks for clearing that up for me.
