### PR TITLE
core: bail if encounter insecure ssl cert, to avoid hanging forever

### LINKED ISSUE #6287: Certificate error hangs Lighthouse
repro:

```
lighthouse https://ilkayuyarkaba.av.tr/tag/istifaya-zorlanan-iscinin-kidem-tazminati
```

The site fails to load and shows the NET::ERR_CERT_SYMANTEC_LEGACY error, but Lighthouse doesn't recognize this. After the 45s timeout it just hangs permanently on "Retrieving devtoolsLog and network records".

We should detect the certificate failure early and fail with a new pageLoadError state. Maybe something like `CERT_ERR_DOCUMENT _REQUEST` ?

I _think_ there's something on the protocol which represents this situation.. Something in the `Security` domain? Will require some investigation.   https://badssl.com/ might be useful though they dont have a symantec cert situation. Just other ones.

-----

Issue broken out from #6272

### PR DESCRIPTION
**Pull request by Hoten**
After encountering an SSL error, some commands to the Network/Page domains either took awhile to timeout, or hung forever (only seemed to happen for `ERR_CERT_SYMANTEC_LEGACY`). You can see this at https://ilkayuyarkaba.av.tr/tag/istifaya-zorlanan-iscinin-kidem-tazminati (use canary).

If one of the passes generates an SSL error, just bail. A report is generated with a useful error message at the top.

Fixes #6287.

### CODE REVIEW

File: lighthouse-core/gather/driver.js [hunk 1]
```diff
@@ -849,6 +849,24 @@ class Driver {
     });
   }
 
+  /**
+   * @param {number} [timeout]
+   * @return {Promise<LH.Crdp.Security.SecurityStateChangedEvent>}
+   */
+  getSecurityState(timeout = 1000) {
```
Comment (Hoten) [inline lighthouse-core/gather/driver.js]: this will eventually be replaced by #6296

File: lighthouse-core/gather/driver.js [hunk 2]
```diff
@@ -849,6 +849,24 @@ class Driver {
...
+    return new Promise((resolve, reject) => {
+      const err = new LHError(LHError.errors.SECURITY_STATE_TIMEOUT);
+      const asyncTimeout = setTimeout((_ => reject(err)), timeout);
```
Comment (Hoten) [inline lighthouse-core/gather/driver.js]: this will eventually be replaced by #6296

File: lighthouse-core/gather/gather-runner.js [hunk 3]
```diff
@@ -165,6 +166,20 @@ class GatherRunner {
     } else if (mainRecord.hasErrorStatusCode()) {
       errorDef = {...LHError.errors.ERRORED_DOCUMENT_REQUEST};
       errorDef.message += ` Status code: ${mainRecord.statusCode}.`;
+    } else if (!mainRecord.finished) {
```
Comment (Hoten) [inline lighthouse-core/gather/gather-runner.js]: AFAIK, an insecure security state will always have `.finished` set to false on the network records. I wanted to avoid calling these Security commands if not needed.

File: lighthouse-core/gather/gather-runner.js [hunk 4]
```diff
@@ -313,7 +333,7 @@ class GatherRunner {
     }
 
     // Resolve on tracing data using passName from config.
-    return passData;
+    return [passData, pageLoadError];
```
Comment (Hoten) [inline lighthouse-core/gather/gather-runner.js]: thoughts?

File: lighthouse-core/gather/gather-runner.js [hunk 5]
```diff
@@ -165,6 +166,20 @@ class GatherRunner {
     } else if (mainRecord.hasErrorStatusCode()) {
       errorDef = {...LHError.errors.ERRORED_DOCUMENT_REQUEST};
       errorDef.message += ` Status code: ${mainRecord.statusCode}.`;
+    } else if (!mainRecord.finished) {
+      // could be security error
```
Comment (paulirish) [inline lighthouse-core/gather/gather-runner.js]: I think this may be just certificate errors. Seems like most of the connection errors are `mainRecord.failed === true`.

File: lighthouse-core/gather/gather-runner.js [hunk 6]
```diff
@@ -165,6 +166,20 @@ class GatherRunner {
...
+      const securityState = await driver.getSecurityState();
```
Comment (paulirish) [inline lighthouse-core/gather/gather-runner.js]: Small nit but I think it'd be slightly better to collect this on L288 and pass that into getPageLoadError() rather than all of driver.

File: lighthouse-core/gather/gather-runner.js [hunk 7]
```diff
@@ -165,6 +166,20 @@ class GatherRunner {
...
+      if (securityState.securityState === 'insecure') {
+        errorDef = {...LHError.errors.INSECURE_DOCUMENT_REQUEST};
+        const insecureDescriptions = securityState.explanations
+          .filter(exp => exp.securityState === 'insecure')
+          .map(exp => exp.description)
+          .join(' ');
+        errorDef.message += ` Insecure: ${insecureDescriptions}`;
```
Comment (paulirish) [inline lighthouse-core/gather/gather-runner.js]: Agree the explanation gathering is the best we can do.
For this line i think it could just be 

```suggestion
        errorDef.message += ` ${insecureDescriptions.join(' ')}`;
```

File: lighthouse-core/gather/gather-runner.js [hunk 8]
```diff
@@ -410,7 +430,8 @@ class GatherRunner {
         await driver.setThrottling(options.settings, passConfig);
         await GatherRunner.beforePass(passContext, gathererResults);
         await GatherRunner.pass(passContext, gathererResults);
-        const passData = await GatherRunner.afterPass(passContext, gathererResults);
+        const [passData, pageLoadError] =
```
Comment (paulirish) [inline lighthouse-core/gather/gather-runner.js]: @brendankenny @patrickhulce either of you have an idea on how else to deliver this error?

see also the L462 here

File: lighthouse-core/lib/strings.js [hunk 9]
```diff
@@ -11,7 +11,9 @@ module.exports = {
   badTraceRecording: `Something went wrong with recording the trace over your page load. Please run Lighthouse again.`,
   pageLoadTookTooLong: `Your page took too long to load. Please follow the opportunities in the report to reduce your page load time, and then try re-running Lighthouse.`,
   pageLoadFailed: `Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests.`,
+  pageLoadFailedInsecure: `The URL you have provided does not have a valid security certificate.`,
```
Comment (paulirish) [inline lighthouse-core/lib/strings.js]: hmm technically not just certificate, but admittedly most other security errors fall through the ERRORED_DOC_REQ path right now.  how about

> ... does not have valid security credentials.

File: lighthouse-core/gather/driver.js [hunk 10]
```diff
@@ -849,6 +849,24 @@ class Driver {
...
+
+      this.sendCommand('Security.enable');
+      this.once('Security.securityStateChanged', (e) => {
```
Comment (patrickhulce) [inline lighthouse-core/gather/driver.js]: somewhat tangential... 

@paulirish are we just paranoid for doing all our listeners before enabling or do we actually need to? I seem to remember dgozman scolding me for not trusting in JS microtasks when we had listeners before `.enable` :)

File: lighthouse-core/gather/driver.js [hunk 11]
```diff
@@ -849,6 +849,24 @@ class Driver {
...
+  /**
+   * @param {number} [timeout]
+   * @return {Promise<LH.Crdp.Security.SecurityStateChangedEvent>}
+   */
+  getSecurityState(timeout = 1000) {
+    return new Promise((resolve, reject) => {
+      const err = new LHError(LHError.errors.SECURITY_STATE_TIMEOUT);
+      const asyncTimeout = setTimeout((_ => reject(err)), timeout);
+
+      this.sendCommand('Security.enable');
```
Comment (patrickhulce) [inline lighthouse-core/gather/driver.js]: also, @paulirish is Security domain still broken on Android, is this going to break us on real devices again?

File: lighthouse-core/gather/gather-runner.js (hunk 4 above)
Comment (patrickhulce) [reply lighthouse-core/gather/gather-runner.js]: WDYT about attaching it to `passData` instead? It's a relatively grab-bag object of what a happened during a pass, so it makes some sense :)

File: lighthouse-core/gather/gather-runner.js (hunk 6 above)
Comment (patrickhulce) [inline lighthouse-core/gather/gather-runner.js]: super nit: WDYT about sprinkling some nice destructuring here, `const {securityState, explanations} =`? somethin' about `securityState.securityState` just spoke to me :)

File: lighthouse-core/gather/gather-runner.js (hunk 8 above)
Comment (brendankenny) [reply lighthouse-core/gather/gather-runner.js]: `pageLoadError.fatal = true; throw pageLoadError;` :P

File: lighthouse-core/gather/gather-runner.js (hunk 4 above)
Comment (Hoten) [reply lighthouse-core/gather/gather-runner.js]: Sure. I'll add it as an optional property. I avoided it in the first place b/c I didn't want to modify all usages of this type, but I completely forgot about optional properties :P

File: lighthouse-core/gather/driver.js (hunk 10 above)
Comment (paulirish) [reply lighthouse-core/gather/driver.js]: hmm good call.

This code here would be a problem if there was an `await` on the `.enable` call above. which seems fairly reasonable.

So yeah +1 to defining the once handler before we flip enable() on

File: lighthouse-core/gather/driver.js (hunk 11 above)
Comment (paulirish) [reply lighthouse-core/gather/driver.js]: they fixed android like a year ago! yay

image

Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: well someone's behind the times 😆

File: lighthouse-core/gather/gather-runner.js (hunk 6 above)
Comment (Hoten) [reply lighthouse-core/gather/gather-runner.js]: I didn't even notice that :O

File: lighthouse-core/gather/driver.js (hunk 10 above)
Comment (Hoten) [reply lighthouse-core/gather/driver.js]: good point, fixed.

I don't quite understand the execution model here. It's clear to me why `await`ing the enable would schedule registering the listener much too late, but I don't understand how this original code worked (enable without `await`ing, then register a listener via `.once`). Why does enabling the Security domain still occur after the listener is registered?

File: lighthouse-core/gather/driver.js [hunk 12]
```diff
@@ -849,6 +849,24 @@ class Driver {
...
+  /**
+   * @param {number} [timeout]
+   * @return {Promise<LH.Crdp.Security.SecurityStateChangedEvent>}
+   */
+  getSecurityState(timeout = 1000) {
+    return new Promise((resolve, reject) => {
+      const err = new LHError(LHError.errors.SECURITY_STATE_TIMEOUT);
+      const asyncTimeout = setTimeout((_ => reject(err)), timeout);
+
+      this.once('Security.securityStateChanged', state => {
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: does this check break if someone else has been listening to the `Security` domain? It would be nice to get a non-event based version of this in the protocol

File: lighthouse-core/gather/driver.js [hunk 13]
```diff
@@ -849,6 +849,24 @@ class Driver {
...
+        clearTimeout(asyncTimeout);
+        resolve(state);
+        this.sendCommand('Security.disable');
+      });
+      this.sendCommand('Security.enable');
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: If we want this to be a general utility function, it will need to disable the domain and remove the event listener in the rejection case. Otherwise we'll need to think how to make rejections always lead to a program exit, as the state of things might get weird (we'll have to deal with the same thing in #6296)

File: lighthouse-core/gather/gather-runner.js [hunk 14]
```diff
@@ -271,7 +278,9 @@ class GatherRunner {
     const networkRecords = NetworkRecorder.recordsFromLogs(devtoolsLog);
     log.verbose('statusEnd', status);
 
-    let pageLoadError = GatherRunner.getPageLoadError(passContext.url, networkRecords);
+    const securityState = await driver.getSecurityState();
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: Maybe we're making this harder than it needs to be by trying to unify with with the other page load errors.

`getPageLoadError` is trying really hard to not interrupt normal control flow, inserting the promise rejection into the gather results instead of into the executing chain. Meanwhile, this security check is trying to abandon the gathering altogether.

Maybe this should just be a separate function, `checkPageSecurityState()` or whatever, called here-ish. If the page is insecure, throw in there. It'll bail back to here, which will bail up to the `catch` in `run()`. If we really want to still return something in that case, the check against `LHError.errors.INSECURE_DOCUMENT_REQUEST.code` can happen there (or rethrow if it's something different).

This also gets around extending `passData`, which makes sense, because really there isn't any other useful pass data when there's this kind of error.

WDYT?

File: lighthouse-core/gather/driver.js (hunk 13 above)
Comment (brendankenny) [reply lighthouse-core/gather/driver.js]: > If we want this to be a general utility function, it will need to disable the domain and remove the event listener in the rejection case.

Maybe this is overkill. If it's timing out (unexpectedly), something is pretty wrong and LH probably won't recover. Disabling the domain also might not even work. OTOH, not cleaning up feels wrong :)

File: lighthouse-core/gather/driver.js (hunk 12 above)
Comment (Hoten) [reply lighthouse-core/gather/driver.js]: I enabled just before calling this function, and yes, it does break. It hangs, and eventually rejects with `SECURITY_STATE_TIMEOUT` (which actually kills Lighthouse. oops)

Besides other users enabling the Security domain, could this fail if a developer opens the Security tab (this enables the domain) before running an audit?

File: lighthouse-core/gather/gather-runner.js (hunk 14 above)
Comment (Hoten) [reply lighthouse-core/gather/gather-runner.js]: Can't quite figure out how to still display a LHR in `run`'s `catch`. I marked the security LHError fatal (so it would throw), moved `baseArtifacts` up a bit (so it can be accessed in `catch`), but get this silly error:

```
Error: CSSUsage failed to provide an artifact.
    at Function.collectArtifacts (/Users/cjamcl/src/lighthouse/lighthouse-core/gather/gather-runner.js:366:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by Hoten** [comment]
OK, I believe I resolved all comments. Opened #6330 to discuss how to handle errors being thrown during gather-runner.

File: lighthouse-core/gather/driver.js [hunk 15]
```diff
@@ -849,6 +849,21 @@ class Driver {
...
+    });
+    await this.sendCommand('Security.enable');
+  }
+
+  /**
+   * @return {LH.Crdp.Security.SecurityStateChangedEvent}
+   */
+  getSecurityState() {
+    // @ts-ignore
+    return this.lastSecurityState;
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: should set this in the `Driver` constructor (I guess to null since `SecurityStateChangedEvent` is a relatively large object so it's probably not worth constructing an `unknown` starting value). Won't need to ts-ignore then

File: lighthouse-core/gather/gather-runner.js [hunk 16]
```diff
@@ -112,6 +112,7 @@ class GatherRunner {
     await driver.cacheNatives();
     await driver.registerPerformanceObserver();
     await driver.dismissJavaScriptDialogs();
+    await driver.listenForSecurityStateChanges();
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: doing it this way, I guess we'll find out if there are issues with listening through the whole page load :)

But it does nicely pave the way for bailing earlier if we want to do that.

File: lighthouse-core/gather/gather-runner.js [hunk 17]
```diff
@@ -172,6 +173,22 @@ class GatherRunner {
...
+   * @return {LHError|undefined}
+   */
+  static checkForSecurityIssue({securityState, explanations}) {
+    if (securityState === 'insecure') {
+      const errorDef = {...LHError.errors.INSECURE_DOCUMENT_REQUEST};
+      const insecureDescriptions = explanations
+        .filter(exp => exp.securityState === 'insecure')
+        .map(exp => exp.description);
+      errorDef.message += ` ${insecureDescriptions.join(' ')}`;
+      return new LHError(errorDef, {fatal: true});
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: rather than returning the error and throwing on the return value, I'd say just throw in here

File: lighthouse-core/gather/gather-runner.js [hunk 18]
```diff
@@ -172,6 +173,22 @@ class GatherRunner {
     }
   }
 
+  /**
+   * Returns an error if the original network request failed or wasn't found.
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: need to update string

File: lighthouse-core/gather/gather-runner.js [hunk 19]
```diff
@@ -172,6 +173,22 @@ class GatherRunner {
...
+   * @param {LH.Crdp.Security.SecurityStateChangedEvent} securityState
+   * @return {LHError|undefined}
+   */
+  static checkForSecurityIssue({securityState, explanations}) {
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: bikeshed: if it does throw in here, maybe rename `assertCertificateError` or something? Or does this catch a larger class of issues

File: lighthouse-core/gather/gather-runner.js (hunk 17 above)
Comment (brendankenny) [reply lighthouse-core/gather/gather-runner.js]: `{fatal: true}` shouldn't be necessary anymore

File: lighthouse-core/gather/gather-runner.js [hunk 20]
```diff
@@ -288,7 +310,6 @@ class GatherRunner {
       trace,
     };
 
-    // Disable throttling so the afterPass analysis isn't throttled
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: restore?

File: lighthouse-core/lib/lh-error.js [hunk 21]
```diff
@@ -169,6 +175,12 @@ const ERRORS = {
     message: strings.requestContentTimeout,
   },
 
+  // Protocol timeout failures
+  SECURITY_STATE_TIMEOUT: {
```
Comment (brendankenny) [inline lighthouse-core/lib/lh-error.js]: in the usual case for the security state check, it should just reject on an insecure security state, right? If so, we probably want to make this a more general protocol communication timeout error (anticipating #6296)

File: lighthouse-core/test/gather/gather-runner-test.js [hunk 22]
```diff
@@ -543,9 +545,9 @@ describe('GatherRunner', function() {
       ],
     };
 
-    return GatherRunner.afterPass({url, driver, passConfig}, {TestGatherer: []}).then(vals => {
+    return GatherRunner.afterPass({url, driver, passConfig}, {TestGatherer: []}).then(passData => {
```
Comment (brendankenny) [inline lighthouse-core/test/gather/gather-runner-test.js]: ok to revert these lines now?

File: lighthouse-core/gather/driver.js (hunk 15 above)
Comment (Hoten) [reply lighthouse-core/gather/driver.js]: It's ts-ignored to coerce a non-nullable value, since I believe this should always be set. I could remove it and allow this getter to be nullable, but would also need to handle that in the calling code (a case that I think will never happen). wdyt?

File: lighthouse-core/gather/gather-runner.js (hunk 17 above)
Comment (Hoten) [reply lighthouse-core/gather/gather-runner.js]: OK, I can do that. I was thinking it's nicer to make tests that check return values rather than throwing conditions, but just my preference, I could have it either way.

I'll remove fatal. yay, that means the resolve or throw thing really can still be removed.

File: lighthouse-core/gather/gather-runner.js (hunk 19 above)
Comment (Hoten) [reply lighthouse-core/gather/gather-runner.js]: It catches anytime the latest security state has an insecure property. a certificate error is one example. I don't know if it's just one of, most of them, or all possible scenarios.

File: lighthouse-core/lib/lh-error.js (hunk 21 above)
Comment (Hoten) [reply lighthouse-core/lib/lh-error.js]: My plan was to modify that bit in the referenced issue. but now that we have this concrete proto definition it makes sense to make it good sooner rather than later

File: lighthouse-core/test/gather/gather-runner-test.js (hunk 22 above)
Comment (Hoten) [reply lighthouse-core/test/gather/gather-runner-test.js]: I think `passData` is more clear than `vals`.

File: lighthouse-core/lib/lh-error.js (hunk 21 above)
Comment (Hoten) [reply lighthouse-core/lib/lh-error.js]: Oh, I actually removed the timeout stuff for security checking. I'll remove this too.

File: lighthouse-core/gather/driver.js (hunk 15 above)
Comment (patrickhulce) [reply lighthouse-core/gather/driver.js]: If we believe it's always set but don't know for sure, WDYT about throwing an explicit error if it's not? 

This way it'll be clear to us when something unexpected happens and ts is happy by default :)

File: lighthouse-core/gather/gather-runner.js (hunk 19 above)
Comment (patrickhulce) [reply lighthouse-core/gather/gather-runner.js]: Just triple checking because the protocol name is getting me concerned a bit, but `securityState === 'insecure'` only when the page is HTTPS but actually isn't secure, right? Not just every time the page is served over HTTP without encryption correct? :)

Comment (patrickhulce) [reply lighthouse-core/gather/gather-runner.js]: +1 to the idea of throwing in here with a `assert*` rename too, btw. Seems much easier and removes the cognitive load from the caller

Comment (Hoten) [reply lighthouse-core/gather/gather-runner.js]: Good idea to check HTTP. Tested with `node lighthouse-cli http://www.httpvshttps.com/ --verbose --view` - it still generated a full LHR. I presume "insecure" is only used for HTTPS connection that don't comply with security standards (and I guess they always go hand-in-hand with interstitial security warnings).

**Comment by brendankenny** [comment]
> Just triple checking because the protocol name is getting me concerned a bit, but securityState === 'insecure' only when the page is HTTPS but actually isn't secure, right?

Looking through the chromium source, the values to search for are `blink::kWebSecurityStyleInsecure` and `Security::SecurityStateEnum::Insecure` (that's what ends up setting the field in the event payload in [`security_handler.cc`](https://cs.chromium.org/chromium/src/content/browser/devtools/protocol/security_handler.cc?sq=package:chromium&dr=CSs&g=0&l=186)).

There are two ways it's set. If someone wants to track down which one is actually in our execution path, feel free :)

- The style in [`web_url_loader_impl.cc`](https://cs.chromium.org/chromium/src/content/renderer/loader/web_url_loader_impl.cc?type=cs&q=kWebSecurityStyleInsecure&g=0&l=120-123)
```cc
if (net::IsCertStatusError(cert_status) &&
    !net::IsCertStatusMinorError(cert_status)) {
  return blink::kWebSecurityStyleInsecure;
}
```
This is per-resource, not per-page, so probably not it.
- The check in [`content_utils.cc`](https://cs.chromium.org/chromium/src/components/security_state/content/content_utils.cc?type=cs&q=kWebSecurityStyleInsecure&g=0&l=48-49)
```cc
switch (security_level) {
  // ...
  case security_state::DANGEROUS:
    return blink::kWebSecurityStyleInsecure;
  // ..
}
```

where DANGEROUS is
```
// Attempted HTTPS and failed, page not authenticated, HTTPS with
// insecure active content on the page, malware, phishing, or any other
// serious security issue that could be dangerous.
```

Either way, this assumption seems to be ok. The main extra thing seems to be malware/phishing. Presumably that information will be in the explanation put in the friendly messsage.

**Comment by brendankenny** [comment]
> `HTTPS with insecure active content on the page`

oh, mixed content might be an issue as well? We should check. I'm not sure we want to throw in that case

**Comment by brendankenny** [comment]
yeah, it's flagged as "neutral". Mixed content pages with passwords might trigger this (cf. https://crbug.com/647754), but it seems it will only require a error message tweak in the future if folks run into it

File: lighthouse-core/test/gather/gather-runner-test.js [hunk 23]
```diff
@@ -679,6 +681,43 @@ describe('GatherRunner', function() {
     });
   });
 
+  describe('#checkForSecurityIssue', () => {
```
Comment (brendankenny) [inline lighthouse-core/test/gather/gather-runner-test.js]: `#assertNoSecurityIssues`

File: lighthouse-core/gather/driver.js [hunk 24]
```diff
@@ -849,6 +849,26 @@ class Driver {
     });
   }
 
+  async listenForSecurityStateChanges() {
+    this.on('Security.securityStateChanged', state => {
+      this.lastSecurityState = state;
```
Comment (brendankenny) [inline lighthouse-core/gather/driver.js]: the type checker now allows this (in JS files as of 3.0 or 3.1), but should still declare it in the constructor so there's a clear place to check for what's on Driver, we don't dynamically mutate the object's shape, etc

File: lighthouse-core/gather/gather-runner.js [hunk 25]
```diff
@@ -172,6 +173,22 @@ class GatherRunner {
     }
   }
 
+  /**
+   * Returns an error if the security state is insecure.
```
Comment (brendankenny) [inline lighthouse-core/gather/gather-runner.js]: Throws

File: lighthouse-core/test/gather/gather-runner-test.js [hunk 26]
```diff
@@ -679,6 +681,43 @@ describe('GatherRunner', function() {
...
+            securityState: 'insecure',
+          },
+        ],
+        securityState: 'insecure',
+      };
+      try {
+        GatherRunner.assertNoSecurityIssues(insecureSecurityState);
+        assert.fail('expected INSECURE_DOCUMENT_REQUEST LHError');
+      } catch (err) {
+        assert.equal(err.message, 'INSECURE_DOCUMENT_REQUEST');
```
Comment (brendankenny) [inline lighthouse-core/test/gather/gather-runner-test.js]: maybe check `err.code` as well/instead, since that's what we use for the top level `runtimeError`

File: lighthouse-core/gather/driver.js (hunk 24 above)
Comment (Hoten) [reply lighthouse-core/gather/driver.js]: yeah this really surprised me, how it was able to infer the type. it was able to see that it could be undefined, since the ctor didn't set it.

Makes sense. This is not good:
image

I guess TSC just infers a permissive union type for `this.property`, based on all setters? What new feature of tsc 3.0/3.1 is this?

File: lighthouse-core/test/gather/gather-runner-test.js (hunk 26 above)
Comment (Hoten) [reply lighthouse-core/test/gather/gather-runner-test.js]: Done. Some other tests were just testing `.message`, so I added checks there too. lmk if I should just remove the `.message` assertions.
