### PR TITLE
fix HTTPS audit to actually fail on insecure URLs

### LINKED ISSUE #479: false positive: Site is on HTTPS whilst the website is not.
The Lighthouse report lists a false positive for "Network connection is secure -> Site is on HTTPS" := Yes whilst the website is only on HTTP so it should report := No, right?

You can test it with this mobile website / webapp (I added the manifest today):
    http://m.feestdagen-belgie.be/

### PR DESCRIPTION
**Pull request by brendankenny**
fixes #479 

In #353, the `HTTPS` artifact changed to returning an object with a `value` property, but the audit was still checking if the `HTTPS` artifact was truthy or not. Since an object is always truthy, the audit was always passing.

### CODE REVIEW

**Comment by paulirish** [comment]
Lgtm

File: lighthouse-core/audits/is-on-https.js [hunk 1]
```diff
@@ -37,7 +37,8 @@ class HTTPS extends Audit {
    */
   static audit(artifacts) {
     return HTTPS.generateAuditResult({
-      value: !!artifacts.HTTPS
+      value: !!artifacts.HTTPS.value,
```
Comment (paulirish) [inline lighthouse-core/audits/is-on-https.js]: let's remove this `!!` cast. The gather should hand over the boolean cleanly

Comment (brendankenny) [inline lighthouse-core/audits/is-on-https.js]: done
