### PR TITLE
tests(travis): force use of GCE, remove dSE calls

### LINKED ISSUE #4221: Failing travis builds
Since last night all our travis builds are failing.

The upstream issue is here: https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524

The workaround is setting `sudo: required` to use GCE infrastructure instead.

### PR DESCRIPTION
**Pull request by patrickhulce**
make 💡 🏠  💚  again

closes #4221 due to https://github.com/travis-ci/travis-ci/issues/8836

### CODE REVIEW

**Comment by paulirish** [comment]
looks good so far.  
image

File: lighthouse-core/test/lib/asset-saver-test.js [hunk 1]
```diff
@@ -54,9 +54,12 @@ describe('asset-saver helper', () => {
...
       const traceFilename = 'the_file-0.trace.json';
       const traceFileContents = fs.readFileSync(traceFilename, 'utf8');
-      assert.deepStrictEqual(JSON.parse(traceFileContents), {traceEvents});
+      const traceEventsFromDisk = JSON.parse(traceFileContents).traceEvents;
+      traceEventsFromDisk.forEach((evt, i) => {
+        assert.deepStrictEqual(evt, traceEvents[i]);
+      });
       fs.unlinkSync(traceFilename);
-    });
+    }).timeout(120000);
```
Comment (paulirish) [inline lighthouse-core/test/lib/asset-saver-test.js]: according to https://travis-ci.org/GoogleChrome/lighthouse/jobs/327029200#L1499 the forEach takes just 160ms.

so we can nuke this timeout.

**Comment by patrickhulce** [comment]
huzzah!!
image
