### PR TITLE
clients(devtools): use the same desktop throttling as lightrider

### LINKED ISSUE #10315: Chrome 80 - Desktop throttling profile not using lr-desktop-config
#### Provide the steps to reproduce
1. Run LH on http://www.ideacasaimmobiliare.it/web/ with this options flagged:
- Performance
- Best practices
- Accessibility
- SEO
- Desktop
- Clear storage
- Simulated Throttling 

2. LH runs correctly but loading web site resources take very long time 

#### What is the current behavior?
All the web site weights about 3 Mb but LH takes about 8.4 seconds for FMP and score 10.2s for speed index!

#### What is the expected behavior?
This is a very strange behaviour because in Italy, for desktop sites (DSL home line) a web site loads in about 2 secs!
Removing throttling and leaving clear cache flagged gave me same results.
I can't show my customers a report showing that a 3 Mb site loads in 10 seconds!

Take a look at the report

[IDEACASA.IT summary.pdf](https://github.com/GoogleChrome/lighthouse/files/4180225/IDEACASA.IT.summary.pdf)

#### Environment Information
* Affected Channels: LH
* Lighthouse version: 5.7.0
* Chrome version: 80.0.3987.87 - 64 bit
* Operating System: Win 10 Pro

### PR DESCRIPTION
**Pull request by connorjclark**
fixes #10315

I was going to make a shared desktop config and rely on config inheritance, but it turns out that we only support inheriting from the default config :)

### CODE REVIEW

File: clients/devtools-entry.js [hunk 1]
```diff
@@ -9,23 +9,32 @@ const lighthouse = require('../lighthouse-core/index.js');
...
+ * Returns a config, which runs only certain categories.
+ * Varies the config to use based on device.
+ * If `lighthouse-plugin-publisher-ads` is in the list of
  * `categoryIDs` the plugin will also be run.
  * @param {Array<string>} categoryIDs
+ * @param {string} device
  * @return {LH.Config.Json}
  */
-function getDefaultConfigForCategories(categoryIDs) {
+function createConfig(categoryIDs, device) {
```
Comment (connorjclark) [inline clients/devtools-entry.js]: cc @chruxin breaking change for you

File: lighthouse-core/config/constants.js [hunk 2]
```diff
@@ -38,6 +38,13 @@ const throttling = {
     uploadThroughputKbps: 700 * DEVTOOLS_THROUGHPUT_ADJUSTMENT_FACTOR,
     cpuSlowdownMultiplier: 4,
   },
+  // Using a "broadband" connection type
+  // Corresponds to "Dense 4G 25th percentile" in https://docs.google.com/document/d/1Ft1Bnq9-t4jK5egLSOc28IL4TvR-Tt0se_1faTA4KTY/edit#heading=h.bb7nfy2x9e5v
+  desktopDense4G: {
+    rttMs: 40,
```
Comment (patrickhulce) [inline lighthouse-core/config/constants.js]: should we set `requestLatencyMs: 0, downloadThroughputKbps: 0, uploadThroughputKbps: 0` for no throttling when `--throttling-method=devtools`?

File: clients/devtools-entry.js [hunk 3]
```diff
@@ -9,23 +9,32 @@ const lighthouse = require('../lighthouse-core/index.js');
...
+  /** @type {LH.SharedFlagsSettings} */
+  const settings = {
+    onlyCategories: categoryIDs,
+  };
+  if (device === 'desktop') {
+    settings.throttling = desktopDense4G;
```
Comment (patrickhulce) [inline clients/devtools-entry.js]: feels a little weird to manage half the configuration here and half in devtools. should we either bring all of it into here or just export the throttling object? will it be a bigger pain to make changes to devtools if it's all here?

**Comment by patrickhulce** [comment]
Either way this PR will have a Chromium counterpart correct?

File: clients/devtools-entry.js (hunk 3 above)
Comment (paulirish) [reply clients/devtools-entry.js]: > feels a little weird to manage half the configuration here and half in devtools. 

heh we were discussing this point yesterday. :)

but which half in devtools are you talking about?

Comment (patrickhulce) [reply clients/devtools-entry.js]: all the `setFlags` business

https://cs.chromium.org/chromium/src/third_party/devtools-frontend/src/front_end/audits/AuditsController.js?type=cs&q=f:audits+-f:out&sq=package:chromium&g=0&l=250-282

Comment (connorjclark) [reply clients/devtools-entry.js]: the flags are set based on values from UI controls in DevTools. So it seems unreasonable to have the entry handle the config entirely.

I was an advocate for just having DevTools pass in an entire config (thus, it would have knowledge of Lighthouse configs). Paul preferred the encapsulation this current approach provides. Although, there's the argument that CDT already knows about the flags, which is a subset of the config ...

**Comment by connorjclark** [comment]
> Either way this PR will have a Chromium counterpart correct?

Yeah. Even without this change there is. The last change to this file was post-5.7, and it completely changed the interface.

File: lighthouse-core/config/constants.js (hunk 2 above)
Comment (connorjclark) [reply lighthouse-core/config/constants.js]: would this be done in just the dt entry's `createConfig`?

Comment (connorjclark) [reply lighthouse-core/config/constants.js]: bump :)

Comment (patrickhulce) [reply lighthouse-core/config/constants.js]: I assumed we'd set it on this same object like we do for mobile settings

Comment (connorjclark) [reply lighthouse-core/config/constants.js]: tbh I've lost the thread here and have no idea how to synthesize what your saying :)

Comment (patrickhulce) [reply lighthouse-core/config/constants.js]: I'm saying this object should look like this

```
  desktopDense4G: {
    rttMs: 40,
    throughputKbps: 10 * 1024,
    requestLatencyMs: 0, // 0 means unset
    downloadThroughputKbps: 0,
    uploadThroughputKbps: 0,
    cpuSlowdownMultiplier: 1,
  }
```

assuming that 0 still means unset to devtools

Comment (connorjclark) [reply lighthouse-core/config/constants.js]: but you said `when --throttling-method=devtools`, so what about for when throttling is set to simulated? That's why I thought this might need to be done in createConfig, behind a check for the throttling method


and is this what we want for `lr-desktop-config` too?

Comment (patrickhulce) [reply lighthouse-core/config/constants.js]: Well adding these here is just going to be a noop when `--throttling-method=simulate`, I was distinguishing that this object should cover both throttling cases like the mobile 4g ones do above.

Comment (exterkamp) [reply lighthouse-core/config/constants.js]: +1 to adding `=0`, imo is more explicit and matches the pattern of all of the ones above.

**Comment by connorjclark** [comment]
> Is this ready to go at this point?

I think so?

**Comment by connorjclark** [comment]
@paulirish @patrickhulce I think one of you should sanity check :)

File: clients/devtools-entry.js (hunk 3 above)
Comment (patrickhulce) [reply clients/devtools-entry.js]: yeah I'm a little concerned this approach makes it harder for someone to figure out where things are being set, but it's fine

File: clients/devtools-entry.js [hunk 4]
```diff
@@ -9,23 +9,32 @@ const lighthouse = require('../lighthouse-core/index.js');
...
 
 /** @typedef {import('../lighthouse-core/gather/connections/connection.js')} Connection */
 
 /**
- * Return a version of the default config, filtered to only run the specified
- * categories. If `lighthouse-plugin-publisher-ads` is in the list of
+ * Returns a config, which runs only certain categories.
+ * Varies the config to use based on device.
+ * If `lighthouse-plugin-publisher-ads` is in the list of
  * `categoryIDs` the plugin will also be run.
```
Comment (patrickhulce) [inline clients/devtools-entry.js]:
```suggestion
 * `categoryIDs` the plugin will also be run.
 * Counterpart to the CDT code that sets flags. 
 * @see https://cs.chromium.org/chromium/src/third_party/devtools-frontend/src/front_end/lighthouse/LighthouseController.js?type=cs&q=%22const+RuntimeSettings%22+f:lighthouse+-f:out&g=0&l=250
```

IDK something like that to signal there's something else that also sets devtools config stuff as a compromise to the below?

File: lighthouse-core/config/constants.js (hunk 2 above)
Comment (patrickhulce) [reply lighthouse-core/config/constants.js]: did we decide not to do this? my suggestion seems to have a +1 from shane :)

Comment (connorjclark) [reply lighthouse-core/config/constants.js]: i forgot to push

**Comment by patrickhulce** [comment]
GH comment editor somehow added trailing spaces though sorry 😬
