### PR TITLE
lantern: keep first layout/paint/parse events regardless of duration

### LINKED ISSUE #9627: FCP may impact by the loadEvent fire or not in simulator throttling.
#### Provide the steps to reproduce
1. Run LH on https://st.music.163.com/c/wapm-lighthouse-test/id
 
My test result can download in https://webapm.nos-jd.163yun.com/lighthouse%2F%2Ftmplh3.zip, it contains 6 times test results(JSON HTML trace file).  The first test' FCP is 0.8s, others are larger than 1.6s.

#### What is the current behavior?
We build a page monitor system based on lighthouse-CLI. In this system, we test page in 20min interval, recently we find some page's metrics data is not stable. Some times the FCP' value may double than normal point. 

I choose a very simple page like above to reproduce this behavior, I find some times the FCP is 0.8s some times the FCP is 1.6s. I'm very curious about the reason, so I also saved the trace file. I find when FCP is 1.6s, there are some network requests is not finished in the trace, and the load event is not fired normally.

Because we use the simulator throttling, so the FCP is impacted both by the FCP of trace and the page dependence Node tree. I guess the main reason cause the  FCP varied largely is sometimes network request not completed, so network dependence Node computing varied. 

I also changed the throttling method to 'devtools',  I think this method uses the real FCP, not simulator computing result. I hope this will fine, but when I change to devtools, the page can not be measured in 10s, sometimes will also encounter NO_DCL error.

#### What is the expected behavior?
I'm curious about why some network request will not be completed in 10s, they are CDN static resource, it should complete very quickly. 

And Dose the FCP simular algorithm should be adjusted to reduce the impact of load Event?

I think this problem is mainly caused by we are testing in docker images. We use this [docker environment](https://hub.docker.com/r/justinribeiro/lighthouse) to test. 

Can you give me some advice to let the metric not varied a largely.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 5.2.0
* Node.js version: 11
* Operating System: Docker Linux Image
* Chrome version: 69.0.3497.100

**Related issues**

### PR DESCRIPTION
**Pull request by connorjclark**
Fixes #9627

Lantern

image

master

image

pr

image

### CODE REVIEW

File: lighthouse-core/computed/page-dependency-graph.js [hunk 1]
```diff
@@ -137,6 +136,23 @@ class PageDependencyGraph {
         children.push(traceOfTab.mainThreadEvents[i]);
       }
 
+      // Skip trace events that do not have a sizable duration,
+      // unless the event is the first ParseHTML/Layout/Paint.
```
Comment (patrickhulce) [inline lighthouse-core/computed/page-dependency-graph.js]: add a link to my explanatory comment on that issue?

**Comment by connorjclark** [comment]
Is this still relevant?

File: lighthouse-core/computed/page-dependency-graph.js (hunk 1 above)
Comment (dgnext) [reply lighthouse-core/computed/page-dependency-graph.js]: Yes sir Help Me grow

File: lighthouse-core/test/computed/metrics/__snapshots__/first-contentful-paint-test.js.snap [hunk 2]
```diff
@@ -2,8 +2,8 @@
 
 exports[`Metrics: FCP should compute a simulated value 1`] = `
 Object {
-  "optimistic": 1307,
-  "pessimistic": 1307,
-  "timing": 1307,
+  "optimistic": 1337,
```
Comment (connorjclark) [inline lighthouse-core/test/computed/metrics/__snapshots__/first-contentful-paint-test.js.snap]: nice

**Comment by connorjclark** [comment]
meta note: it'd be nice if we saved a summary of `test-lantern` in a flat json file, and commit it to source. That way we can easily see from a git diff what the change is.

File: lighthouse-core/test/computed/metrics/first-cpu-idle-test.js [hunk 3]
```diff
@@ -66,7 +66,7 @@ describe('FirstInteractive computed artifact:', () => {
       pessimistic: Math.round(result.pessimisticEstimate.timeInMs),
     }).toMatchSnapshot();
     assert.equal(result.optimisticEstimate.nodeTimings.size, 19);
-    assert.equal(result.pessimisticEstimate.nodeTimings.size, 79);
+    assert.equal(result.pessimisticEstimate.nodeTimings.size, 80);
```
Comment (patrickhulce) [inline lighthouse-core/test/computed/metrics/first-cpu-idle-test.js]: curious and very unexpected that the optimistic estimate already included this somehow but the pessimistic didn't...

can we double check this? might point to a bug we're missing

File: lighthouse-core/computed/page-dependency-graph.js [hunk 4]
```diff
@@ -305,11 +305,30 @@ class PageDependencyGraph {
...
+    let foundFirstLayout = false;
+    let foundFirstPaint = false;
+    let foundFirstParse = false;
+
     for (const node of cpuNodes) {
-      if (node.event.dur >= SIGNIFICANT_DUR_THRESHOLD_MS * 1000) {
-        // Don't prune this node. The task is long so it will impact simulation.
+      // Don't prune if event is the first ParseHTML/Layout/Paint.
+      // See https://github.com/GoogleChrome/lighthouse/issues/9627#issuecomment-526699524 for more.
+      let isFirst = false;
```
[the remark this answers is not in the document]
Comment (connorjclark) [reply lighthouse-core/computed/page-dependency-graph.js]: does this really help with understanding? kinda a mouth full (mind full?) to read

File: lighthouse-core/test/computed/metrics/first-cpu-idle-test.js (hunk 3 above)
Comment (connorjclark) [reply lighthouse-core/test/computed/metrics/first-cpu-idle-test.js]: is it b/c cpu idle uses fmp like this?

```
    const fmpTimeInMs = extras.optimistic
      ? extras.fmpResult.optimisticEstimate.timeInMs
      : extras.fmpResult.pessimisticEstimate.timeInMs;
```

Comment (patrickhulce) [reply lighthouse-core/test/computed/metrics/first-cpu-idle-test.js]: That doesn't change the size of the `nodeTimings` map though, so I don't think it could affect this.

File: lighthouse-core/computed/page-dependency-graph.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (patrickhulce) [reply lighthouse-core/computed/page-dependency-graph.js]: helps IMO, but I don't feel strongly can skip if you think it makes things worse

File: lighthouse-core/test/computed/metrics/first-cpu-idle-test.js (hunk 3 above)
Comment (connorjclark) [reply lighthouse-core/test/computed/metrics/first-cpu-idle-test.js]: No idea how to debug this.

Comment (patrickhulce) [reply lighthouse-core/test/computed/metrics/first-cpu-idle-test.js]: I'll take a look

Comment (patrickhulce) [reply lighthouse-core/test/computed/metrics/first-cpu-idle-test.js]: Ah it's not that the optimistic estimate already had it, it's just that it still gets filtered out by the optimistic estimate. 

https://github.com/GoogleChrome/lighthouse/blob/43678454b845b89e0caab2b3ce5f9fdda2492ea2/lighthouse-core/computed/metrics/lantern-interactive.js#L40-L43

This is slightly suboptimal but OKish from the simulation perspective because we're flooring on the first paint metrics if we end up too early and if it's that short it's unlikely to have a large impact to the last long task.

Comment (connorjclark) [reply lighthouse-core/test/computed/metrics/first-cpu-idle-test.js]: cool, thanks for looking!
