### PR TITLE
report: support narrow screens

### LINKED ISSUE #6645: Lighthouse report shows horizontal scrollbar on mobile
#### Provide the steps to reproduce
1. Run LH on mobile for https://www.google.com via https://developers.google.com/web/tools/lighthouse/run
#### What is the current behavior?
Report is generated, however, there is a horizontal scroll bar when viewed on mobile and rendering isn't optimal: https://builder-dot-lighthouse-ci.appspot.com/report.1543118339965.html
#### What is the expected behavior?
No horizontal scrollbar

#### Environment Information
* Affected Channels: 
* Lighthouse version: 3.2.1
* Node.js version:
* Operating System:

**Related issues**

### PR DESCRIPTION
**Pull request by exterkamp**
Transition from full width to >500px
mobile_view
minimum width without horizontal scroll (400px):
screen shot 2018-12-20 at 5 53 04 pm
minimum width without horizontal scroll (1 category):
screen shot 2018-12-20 at 5 53 55 pm

**Related Issues/PRs**
fixes #6645

### CODE REVIEW

File: lighthouse-core/report/html/renderer/report-ui-features.js [hunk 1]
```diff
@@ -118,6 +118,8 @@ class ReportUIFeatures {
   onMediaQueryChange(mql) {
     const root = this._dom.find('.lh-root', this._document);
     root.classList.toggle('lh-narrow', mql.matches);
+    // Reset animations for the narrow view header height change.
```
Comment (patrickhulce) [inline lighthouse-core/report/html/renderer/report-ui-features.js]: 👍

File: lighthouse-core/report/html/renderer/report-ui-features.js [hunk 2]
```diff
@@ -226,8 +228,8 @@ class ReportUIFeatures {
     this.headerSticky.style.transform = `translateY(${heightDiff * scrollPct * -1}px)`;
     this.headerBackground.style.transform = `translateY(${scrollPct * this.headerOverlap}px)`;
     this.lighthouseIcon.style.transform =
-      `translate3d(var(--report-width-half),` +
-      ` calc(-100% - ${scrollPct * this.headerOverlap * -1}px), 0) scale(${1 - scrollPct})`;
+      `translate3d(0,` +
```
Comment (patrickhulce) [inline lighthouse-core/report/html/renderer/report-ui-features.js]: you might have to explain this one to me :)

File: lighthouse-core/report/html/report-styles.css [hunk 3]
```diff
@@ -728,6 +731,7 @@
 
 .lh-report {
   background-color: #fff;
+  min-width: var(--report-min-width);
```
Comment (patrickhulce) [inline lighthouse-core/report/html/report-styles.css]: this used to be only `@media screen` do we still want to keep that or doesn't matter?

File: lighthouse-core/report/html/templates.html [hunk 4]
```diff
@@ -164,11 +164,13 @@
...
     }
+    .lh-narrow .lh-header-bg {
+      height: var(--report-header-height-narrow);
+    }
     .lh-lighthouse {
       position: absolute;
-      top: var(--report-header-height);
-      right: 50%;
-      transform: translate3d(var(--report-width-half), -100%, 0);
+      bottom: -4px;
```
Comment (patrickhulce) [inline lighthouse-core/report/html/templates.html]: bottom -4?

File: lighthouse-core/report/html/templates.html [hunk 5]
```diff
@@ -164,11 +164,13 @@
...
       will-change: transform;
     }
+    .lh-narrow .lh-header-bg {
+      height: var(--report-header-height-narrow);
+    }
     .lh-lighthouse {
       position: absolute;
-      top: var(--report-header-height);
-      right: 50%;
-      transform: translate3d(var(--report-width-half), -100%, 0);
```
Comment (patrickhulce) [inline lighthouse-core/report/html/templates.html]: seems like these all changed because `lh-lighthouse` moved inside the header. what does that get us and do we know if there's a reason it was outside it to begin with? :)

File: lighthouse-core/report/html/renderer/report-ui-features.js (hunk 2 above)
Comment (exterkamp) [reply lighthouse-core/report/html/renderer/report-ui-features.js]: Since the `lh-lighthouse` element is inside the header container now it doesn't need to be translated on the x axis since it is positioned absolutely to the bottom right corner.

File: lighthouse-core/report/html/templates.html (hunk 4 above)
Comment (exterkamp) [reply lighthouse-core/report/html/templates.html]: The lighthouse SVG element is 4px above the bottom of the svg's wrapper div (which in this screenshot is set to 0px bottom) so I moved it 4px down to match the header height exactly.  I tried to fix the SVG but hand editing an SVG proved a bit difficult.  So I moved the whole thing 4 px down.
image

File: lighthouse-core/report/html/templates.html (hunk 5 above)
Comment (exterkamp) [reply lighthouse-core/report/html/templates.html]: Should have included a screenshot of the current UI:
image
Since the lighthouse isn't tied to the bottom right of the header container it doesn't scale correctly on small screens and clips off the edge like so!

File: lighthouse-core/report/html/report-styles.css (hunk 3 above)
Comment (exterkamp) [reply lighthouse-core/report/html/report-styles.css]: Hm, I don't think it really matters. I moved it here because I felt like it was always true for every screen not just `max-width: 964px` but I'm not sure it matters?

File: lighthouse-core/report/html/renderer/report-ui-features.js (hunk 2 above)
Comment (patrickhulce) [reply lighthouse-core/report/html/renderer/report-ui-features.js]: and the `100%` is gone because of the `right: 0` we're apply all the time now?

Comment (exterkamp) [reply lighthouse-core/report/html/renderer/report-ui-features.js]: Yup, it had -100% on in the `.lh-lighthouse` class to position it before, so the new anchoring doesn't need it.

File: lighthouse-core/report/html/templates.html [hunk 6]
```diff
@@ -164,11 +164,13 @@
       width: 100%;
       will-change: transform;
     }
+    .lh-narrow .lh-header-bg {
+      height: var(--report-header-height-narrow);
```
Comment (paulirish) [inline lighthouse-core/report/html/templates.html]: eh. i dont think we need this. the jump is a bit awkward and putting the LH behind the text isn't terrible:
image

but if you wanted to avoid that.. we could do `  max-width: 60%;` on `.lh-config`
image

File: lighthouse-core/report/html/renderer/report-ui-features.js [hunk 7]
```diff
@@ -226,9 +229,10 @@ class ReportUIFeatures {
...
+      ` calc(-${scrollPct * this.headerOverlap * -1}px), 0) scale(${1 - scrollPct})`;
```
Comment (brendankenny) [inline lighthouse-core/report/html/renderer/report-ui-features.js]: calc not needed anymore?

File: lighthouse-core/report/html/renderer/report-ui-features.js [hunk 8]
```diff
@@ -226,9 +229,10 @@ class ReportUIFeatures {
...
     this.lighthouseIcon.style.opacity = (1 - scrollPct).toString();
+    this.headerMetadata.style.opacity = (1 - scrollPct).toString();
```
Comment (brendankenny) [inline lighthouse-core/report/html/renderer/report-ui-features.js]: since `.lh-header` only contains the icon and the metadata, maybe save `this.header` instead and set opacity once on the whole thing?

Comment (exterkamp) [reply lighthouse-core/report/html/renderer/report-ui-features.js]: Good call!
